fabric8io/kubernetes-client

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java
fixes #166 so that rolling upgrades wait for the new pods to be running before scaling down the old RC
> fixes #166 so that rolling upgrades wait for the new pods to be running before scaling down the old RC

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
Adding null check to the NoProxy string array. As it fails when I write client code in the form:
Config config = new Config();
client = new DefaultKubernetesClient(config);
It returns:
java.lang.NullPointerException
at io.fabric8.kubernetes.client.utils.HttpClientUtils.getProxyUrl(HttpClientUtils.java:148)
at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:130)
at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:41)
at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:90)
> Merge fix NPE on getProxyUrl when no NoProxy is null

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
The `withResourceVersion()` signature was added in 049e1077, but was missing an implementation. This is an attempt to add one, since the old `watch(resourceVersion, watcher)` method was marked deprecated in 6e89a5a8.
> Add withResourceVersion() implementation.

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/KubernetesDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ComponentStatusOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/ComponentStatusTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Kindly review this PR which enables querying of:
*  "api/v1/namespaces/test/componentstatuses" and
*  "api/v1/namespaces/test/componentstatuses/scheduler" type of endpoints and returns ComponentStatus objects.
Thanks in advance.
> Adding support for componentstatuses API call

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
Fixes two issues:
1. A NPE would be thrown on failures that did not have a response body (such as the underlying websocket throwing a ProtocolException)
2. For cases when there is a response body, the body is not closed
> Close response body on failure responses

- kubernetes-client/pom.xml
- kubernetes-client/src/main/java-templates/io/fabric8/kubernetes/client/Version.java
@iocanel, @lwander This enables the client version to be compiiled in (no properties files - yay!) available as ``Version.clientVersion()``
that you can use in the default user agent string.
> Compile in client project version

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/KubernetesDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PersistentVolumeOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
@jimmidyson @iocanel PTAL
- Fixed issue where persistent volume creation requires a namespace
> Fixes #369, no namespace for persistent volumes

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Filterable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/BaseMockOperation.java
Allow filtering for the presence/lack of a label without specifying a value to check.
Providing a null value parameter to the `withLabel(key, value)` and `withoutLabel(key,value)` methods results in queries like: `?labelSelector=key1,key2,!key3`. Convenience methods `withLabel(key)` and `withoutLabel(key)` are also added to the interface.
Note that to be consistent with the other methods of the class, special values are not checked in the key, making it possible to abuse these methods with calls like `withLabel("key=value,key2")`...
> Support for 'exists' type label selector

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
The `username` field in `Config` isn't necessarily set, since it's only used by basic auth. Instead, `user` in `Context` is the name of the user in kubeconfig with the full authentication details specified. This makes the 403 more understandable.
This fixes one issue encountered in: https://github.com/fabric8io/kubernetes-client/issues/396
> Correctly show incorrect API access by username

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
countDownLatch.countDown() is never getting called.
job.getStatus().getActive() is returning null if job is scalled down to 0
The reason here is that the api server does not send "active" field inside the response JSON.
Hence jackson deserializes it to null. Only if the job is active is the active field set to some int.
Hence delete job always takes getConfig().getScaleTimeout() amount of time to terminate.
> Delete job always taking "scaleTimeout" time to delete a job

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ComponentStatusOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ComponentStatusTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
APIResourceList shows that componentstatuses endpoint is not namespaced and hence queries to the componentstatuses is failing.
```
{
"kind": "APIResourceList",
"groupVersion": "v1",
"resources": [
{
"name": "bindings",
"namespaced": true,
"kind": "Binding"
},
{
"name": "componentstatuses",
"namespaced": false,
"kind": "ComponentStatus"
},
....
```
Hence removing namespace support for componentstatuses query.
> Componentstatus is not namespaced. Removing namespace from query

- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java
- openshift-client/src/test/java/io/fabric8/openshift/client/mock/BuildConfigTest.java
@bparees Hope that looks a bit better! Shame there's no way to filter on Build's `status.config.name` & `namespace` - would be safer than relying on labels for this I guess.
> Fix build config reaping

- pom.xml
I didn't find any references to this property. `scr.annotations.version` seems to be the one that's used.
> Remove unused felix.scr.annotations version property

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Reaper.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
- kubernetes-examples/src/main/java/io/fabric8/openshift/examples/DeploymentConfigExamples.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java
Long story short: When deleting a `dc` the rc is not removed. It seems that Openshift will not remove the `rc` if `dc` is still there *(This also applies to oc)*.
So we change the order of things and we delete the DC from within the reaper.
> Reaper now reports if the target resource has been deleted. 

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallback.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/InputStreamPumper.java
The okhttp response was never closed so a warning was being logged in all Kubernetes tests.
"Did you forget to close a response body?"
> OSFUSE-390: Eliminating leaked connections

- pom.xml
Need to update zjsonpatch version due to the license issue. Basically, once the project was forked from https://github.com/flipkart-incubator/zjsonpatch all copyright were changed to Red Hat inc. which is not valid from IP perspective. More details can be found in CQ - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12451
Update to 0.3.0 version is safe - the only changes are coupled with reverting copyrights headers to original state and Jenkinsfile update.
> Updating zjsonpatch to 0.3.0

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CreateOrReplaceable.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CreateOrReplaceResourceTest.java
- kubernetes-tests/src/test/resources/test-pod-create-from-load.yml
Fixes #602
This adds more tests as well as sneaking in a change to allow no args `createOrReplace` following `load` to allow `client.load(is).createOrReplace()` which is currently not possible.
> Fix createOrReplace for Loadables

- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java
- openshift-client/src/test/java/io/fabric8/openshift/client/OpenShiftConfigTest.java
Some environments (like CDK) put the root URL in the `OPENSHIFT_URL` environment variable, instead of the `oapi` base URL. With this fix, both versions will be supported.
> OSFUSE-481: allow using short OPENSHIFT_URL env variable

- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java
Remove line setting `Accept: application/json` header in `OpenShiftOAuthInterceptor`. Certain API requests, e.g. Exec() do not return json, causing OpenShiftClient requests to return 406: Not Acceptable.
I initially looked into writing some tests for this behaviour, but I couldn't think of a clean way to do it. If anyone has insight on an easy way to test this (if there even is one) I'd be happy to take a look. Then again, it is a minor enough error that it should not be a problem.
See: Issue #610
> Don't set Accept: header in OpenShiftOAuthInterceptor

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/WatchTest.java
- Removed never thrown exceptions from the ctor signature
- Only validate the watch URL once on startup
- **Changed reconnect timing to an exponential backoff capped at 32*baseInterval**
- **Now using a single threaded executor for serial event handling (this eliminates an issue where in some cases the connection gets duplicated)**
- Don't try to send ping while the websocket is inactive during a reconnect backoff
- Delay the first ping with the ping interval, don't send right away on open
- Added/modified level of some log statements
- **Ensure that websocket is:**
- **always properly closed (e.g. ping failure) to avoid leaked connections**
- **never double closed (this removes some unnecessary exceptions from the log)**
- Properly queue startup exceptions and don't reconnect in that …
> Various fixes for WatchConnectionManager

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/VisitFromServerGetWatchDeleteRecreateWaitApplicable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/EndpointsOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/ReadinessWatcher.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java
1. client.resource(<instance of hasmetadata>) should make use of the type parameter (rather than using HasMetadata). 
2. We should be able to use waitUntilReady() on  exisiting resource.
3. waitUntilReady() should return the instance on which the readiness check was performed rather than performing internally a new get().
4. Reduce the boilerplate code that is used internally in waitUntilReady().
5. Added a test that for client.resource(pod).waitUntilReady() and client.resource(pod).createAnd().waitUntilReady().
> A couple more improvements on waitables.

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/WatchOverHTTP.java
Falling back to using persistent HTTP Get. 
The code could be DRYer. Getting this out there to get some initial opinions.
@iocanel @jimmidyson @iyanuobidele
> Allow watching resources over HTTP if watching using websocket fails

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
Follow up to https://github.com/fabric8io/kubernetes-client/pull/652 based on https://github.com/fabric8io/kubernetes-client/pull/652#issuecomment-278395155
/cc @jimmidyson @iocanel
> Fix high latency when websocket connection fails

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
The watching via http get was previously happening on the main thread. 
This one ensures that it is executed in a background thread, so that we don't block. This behavior is similar to the websockets client.
P.S. Missed this earlier :) Sorry!
/cc @iocanel @jimmidyson
> Make watching via http async

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Adapters.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfigHolder.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/WithRequestCallable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/FunctionCallable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/RequestConfigurable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/WithRequestCallable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/RequestConfigTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
This is a fix for #631.
It actually allows the call of a function with custom request configuration. In detail:
1. It moves the request specific configuration to a new object called RequestConfig _(forward compatible change)_.
2. The config object internally delegates to RequestConfig (to limit the code changes to the minimum).
3. The RequestConfig delegate is overridable by a thread local variable.
The code actually looks like:  
Pod pod1 = client.withRequestConfig(new RequestConfigBuilder().withOauthToken("TOKEN").build()).call(new Function<NamespacedKubernetesClient, Pod>() {
@Override
public Pod apply(NamespacedKubernetesClient c) {
return c.pods().inNamespace("test").withName("pod1").get();
}
});
Worths mentioning that despite the functional feel, it works with JDK7 too as it uses …
> Add the ability to call a function with custom request configuration

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
You would only look at WebSocket open/close logging when debugging an issue
> Drop watch logging from info to debug

- pom.xml
Just a little upgrade.
As a side note, the Okhttp-ws artifacts are no longer available from Okhttp 3.5.0
https://github.com/square/okhttp/blob/master/CHANGELOG.md
> Upgrade Okhttp to version 3.4.2

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/BytesLimitTerminateTimeTailPrettyLoggable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/BytesLimitable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ContainerResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/PodHandler.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/handlers/BuildHandler.java
Made a fix for issue #633.
Now it is possible to limit log output for pod, like:
`kubernetesClient.pods().withName("pod").limitBytes(1024).getLog();`
Also, please take a look at `PodOperationsImpl`, lines 279-300.
Looks like there was a copy-paste error, so that `withTTY` option where always set to true in irrelevant config methods: `withPrettyOutput()`, `tailingLines()`, `sinceTime()`, `sinceSeconds()`, `terminated()`. I took the liberty of fixing this too.
> #633: Added support for limitBytes parameter on pod logs request

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/MixedOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ThirdPartyResourceOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TPRTest.java
**What's In this PR ?**
Completes the implementation of the top-level ThirdPartyResources as a nonNamespaceOperation based on [k8s-doc](https://kubernetes.io/docs/user-guide/thirdpartyresources/#creating-a-thirdpartyresource)
This is a pre-req to a downstream [project ](https://github.com/apache-spark-on-k8s/spark) tracked at [issue](https://github.com/apache-spark-on-k8s/spark/issues/153). Also a pre-req to supporting CustomObjects (future PR).
**How it was tested**
Unit tests
The final goal is to add support for CustomObjects in k8s through the client. I feel I might need to add the Builder/Model classes to the kubernetes-model project to get this done. I will open an issue at the kubernetes-model to open discussions on this.
/cc @foxish @iocanel @jimmidyson @mccheah @ash211
> complete top-level thirdPartyResource impl

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/WatchTest.java
Fixes https://github.com/fabric8io/kubernetes-client/issues/674.
It was a regression introduced by https://github.com/fabric8io/kubernetes-client/pull/634 which made the `onClose()` event not get called when `close()` is called. 
cc @iocanel @jimmidyson @ash211 @gyoetam
> Fix watch close

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
ExecWatch doesn't support execute a command and collect its std out/err #728
Change usingListener method to not forcely set withTTY to true.
> ExecWatch doesn't support execute a command and collect its stdout/err

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AppsAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AppsAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/AppsAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/RollableScalableResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetRollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerRollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollableScalableResourceOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ScalableReaper.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StatefulSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StatefulSetRollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicaSetTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Added StatefulSet support, under the new "apps" API group. The code is almost identical to ReplicaSet and ReplicationController, so I made some attempt to dedupe the three impls (in `RollableScalableResourceOperation`).
> Support for StatefulSets

- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/LoadAsTemplateTest.java
- kubernetes-tests/src/test/resources/parameters.yml
- kubernetes-tests/src/test/resources/template-with-params.yml
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java
When switching from remote to local template processing using processLocal, I noticed a difference in how template parameters are handled when they are marked as required or not.
With remote processing, non-required parameters with unset values are allowed, while the local processing throws an exception. 
This fix checks the required field before throwing the exception, and sets the value to an empty string if not (as done when doing remote processing).
> Allow non-required fields to be unset when processing templates locally

- pom.xml
Now that we have the 3.7.0 bundle too we can upgrade.
> Upgrade to latest OKHttp client and related bundle 3.7.0

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ParameterMixedOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ParameterNamespaceListVisitFromServerGetDeleteRecreateWaitApplicable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Parameterizable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReplaceValueStream.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
- kubernetes-tests/src/test/resources/template-list-with-number-params.json
- kubernetes-tests/src/test/resources/template-with-number-params.json
- kubernetes-tests/src/test/resources/template-with-number-params.yml
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/TemplateResource.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ReplaceValueStream.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/handlers/TemplateHandler.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
now the processLocal(map) allows the numeric parameters to be replaced so that the template can be properly loaded providing the numeric properties are in the supplied map
> fixes #746 to support loading templates with number parameters

- platforms/karaf/features/src/main/resources/feature.xml
- pom.xml
Syncing back from RH FIS 2.0 branch:
https://issues.jboss.org/browse/OSFUSE-490
> OSFUSE-490: Add capability to override Jackson bundle version

- kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
I'm seeing an exception when trying to use the new HPA endpoint with an adapted client:
```
java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.AutoscalingAPIGroupClient
at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:133)
at io.fabric8.kubernetes.client.DefaultKubernetesClient.autoscaling(DefaultKubernetesClient.java:293)
at io.fabric8.kubernetes.client.KubernetesClient$autoscaling$6.call(Unknown Source)
at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor$_getAutoscalers_closure47.doCall(KubernetesApiAdaptor.groovy:434)
at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor$_getAutoscalers_closure47.doCall(KubernetesApiAdaptor.groovy)
at …
```
> Fix HPA adapter

- README.md
Found this out only thanks to https://stackoverflow.com/questions/43623275/in-the-fabric8-kubernetes-client-events-api-what-does-watcher-action-indicate and https://stackoverflow.com/questions/43598572/in-a-watcher-in-the-fabric8-kubernetes-client-events-api-what-resources-can-i
> Documents how to use the Watcher API

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Lockable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CreateOrReplaceResourceTest.java
Adding a `.lockResourceVersion("...")` to replace to perform optimistic locking.
> Fixes #767: adding lock replace

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Deletable.java
ie. in pods().delete()
The right check would be `!Boolean.TRUE.equals(delete)`
> delete() can return a false value

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
This should fix #852 by not using a resource version on the first call.
Since old versions of kubernetes, if you don't provide a resource version, [the watch starts from the latest observed state](https://github.com/kubernetes/kubernetes/blob/v1.4.2/pkg/storage/watch_cache.go#L292-L296), so there's no need to do a lookup before starting the watch.
Tested with Openshift origin 1.5 and 3.6.
> Fix watcher resourceVersion problem with 3.6

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceDoneable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceList.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/DoneableDummy.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/Dummy.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/DummyList.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/DummySpec.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
this PR adds the ability to register new CRD clients providing a few DTOs and reusing the kubernetes-client DSL and underlying CustomResourceDefinition metadata to implement the REST API
> first spike at a mechanism to support using CRDs

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
- kubernetes-client/src/test/resources/test-kubeconfig
In my case I'm trying to manage clusters in my Kubernetes Federation.  When you have a federation you end up with a context per each cluster as well as federation context to apply things across clusters. 
But some things like `StatefulSet` doesn't have a federation equivalent and therefore you can't apply them to the "global" context. For such things it will be useful to be able to configure each one of them per cluster in a federation. And in order to do this it will be nice to be able to configure context for a config.
This PR adds this ability to specify which context to try to create configuration from.
Added a test. `mvn test` passes.
> Allow to use non default context

- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java
Reverting OSFUSE-640: Fixed basic token overwriting with a stale bearer token"
because of https://issues.jboss.org/browse/OSFUSE-667 and was never asked to be baclported to this branch.
This reverts commit 464544d54a90637418b67c26e49952d0b5a3e2fb.
> [OSFUSE-667]: Regression between FIS 2 - R4 x R5: Revert [OSFUSE-640]

- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java
because of https://issues.jboss.org/browse/OSFUSE-667 and was never asked to be baclported to this branch.
This reverts commit 464544d54a90637418b67c26e49952d0b5a3e2fb.
This is a backport to `v1.4.14.redhat-R5` branch of https://github.com/fabric8io/kubernetes-client/pull/925
> Revert "OSFUSE-640: Fixed basic token overwriting with a stale beare token"

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SerializationUtils.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java
- kubernetes-examples/src/main/resources/multiple-document-template.yml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LoadTest.java
- kubernetes-tests/src/test/resources/multiple-document-template.yml
- kubernetes-tests/src/test/resources/test-template.yml
[yaml spec v1.2 ](http://www.yaml.org/spec/1.2/spec.html#id2760395) contains information about files with multiple documents structure.
> YAML uses three dashes (“---”) to separate directives from document content. This also serves to signal the start of a document if no directives are present. Three dots ( “...”) indicate the end of a document without starting a new one, for use in communication channels.
Example:
```
---
- Mark McGwire
- Sammy Sosa
- Ken Griffey
---
- Chicago Cubs
- St Louis Cardinals
```
The above mentioned structure is supported by Kubernetes but the support for the same was missing in Kuberenetes client.
- Check for presence of multiple document structure in the given input stream based on `---` delimiter,  split it into valid yaml documents and unmarshal each …
> fix: #918 Adds support for multiple documents in single yaml file.

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildOperationsImpl.java
Correcting bad implementation of my previous PR! 
It was using java 7 auto close, so it was sending out always already closed streams...
fixes #939
> Avoid closing the returned Reader object!

- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/handlers/TemplateHandler.java
Without this fix, creating templates using client.resource().createOrReplace, or creating a template as part of a list fails.
> Add missing resource type string in template handler

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
customResource method is kept but deprecated and implementations just
call customResources.
> Rename customResource to customResources.

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
Avoid returning from the WebSocketListener#onFailure if the websocket connection failed (even if the `start`  flag hasn't been set)
Let the code flow to the check if max retries has been reached. 
This way the Watcher#onClose will eventually be called.
> Watcher onClose method is not called #963

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
Running the latest release (3.1.6) we have seen the following exception in the logs:
```2017-12-27 13:10:26,769 WARN  [i.f.k.c.d.i.WatchConnectionManager:191] Exec Failure
java.net.SocketTimeoutException: connect timed out
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
at …
```
> Avoid "java.lang.IllegalStateException: Queue full" 

- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ConfigMapCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/SecretCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/RouteCrudTest.java
> GitHub issue 923

- kubernetes-server-mock/pom.xml
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
KubernetesAttributesExtractor bugs:
expected.add does not modify object
Parse correctly urls without namespace
Parse ingresses correctly
Add some logging to mock server
>  KubernetesAttributesExtractor is not testing anything

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StorageClassOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/StorageClassHandler.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CreateStorageClassExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ListStorageClassExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/StorageClassExamples.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/StorageClassIT.java
- kubernetes-itests/src/test/resources/test-storageclass.yml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StorageSpaceCrudTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
https://github.com/fabric8io/kubernetes-client/issues/869 Added support for StorageClass resource.
> Added support for StorageClass

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodSecurityPolicyOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/PodSecurityPolicyHandler.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodSecurityPolicyExample.java
- kubernetes-examples/src/main/resources/PodSecurityPolicy.yml
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodSecurityPolicyIT.java
- kubernetes-itests/src/test/resources/test-podsecuritypolicy.yml
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodSecurityPolicyCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StorageSpaceCrudTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
> Added support for PodSecurityPolicy

- kubernetes-itests/src/test/java/io/fabric8/openshift/SecurityContexConstraintsIT.java
- kubernetes-itests/src/test/resources/test-scc.yml
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SecurityContextConstraintsCrudTest.java
Added CRUD Test and Regression Test for SecurityContextConstraints
After adding tests, they were failing so fixed the SCC.
It was not working for get, update and list operations.
#996
> Added CRUD Test and Regression Test for SecurityContextConstraints

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/VersionUsageUtils.java
Fixes #983.
This is a simple impl that logs usage of alpha/beta versions only the first time each type is used.
> Log usage of unstable api

- .circleci/config.yml
- CONTRIBUTING.md
- kubernetes-itests/pom.xml
- kubernetes-itests/src/test/java/io/fabric8/openshift/BuildConfigIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/RouteIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/SecurityContextConstraintsIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/TemplateIT.java
- pom.xml
This was because of dependency issue of arquillian
Created two different profile one for Kubernetes and one for Openshift
Changed the Requirement According to Object
If `@RequiresKubernetes` it will run in both profile
If `@RequireOpenshift` it will run in only Openshift profile and will be skipped in Kubernetes
If the user is running the test on Kubernetes, it should hit -P itests-kubernetes profile
and for openshift it should hit -P itests-openshift profile
#1024
Thanks @dipak-pawar for helping.
> Updated regression test as they were not working with Kubernetes

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java
Fixes #1028.
I've manually verified this by building the `kubernetes-plugin` for Jenkins with my modified library and was able to connect to a cluster via a `kubeconfig` provided as a `secretText` by utilizing the `fromKubeconfig` static method added here.
My intent was to reduce code duplication, while still preserving the existing code path with `tryKubeConfig` and with the relative->absolute path rewriting in kubeconfig.
> config: support loading from kubeconfig string

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchOverHTTP.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
Avoid the thread leaking when `watch.waitUntilReady();` throws an exception when it can't establish a connection to k8
> Avoid WatchConnectionManager thread leak

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
info level seems to be inappropriate for this internal processing message as this regularly happens and does not really add much information, looks more like random noise.
Its valuable for debugging though, so I suggest to move this from "info" to "debug" level.
> chore: Switch reconnect backoff message in wach manager to debug level

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IpAddressMatcher.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/IpAddressMatcherTest.java
NO_PROXY value can contain ip range values. In such case proxy shouldn't be used but currently is. This PR implements check whether NO_PROXY contains ip value or ip range value such as 192.168.0.1/8 and correctly matches such range against requested URL ignoring proxy for given ranges.
> Added NO_PROXY support for IP address range value

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
#1013  Using clonedClient seems to be creating connection leaks(as seen in
OkHttp's platform logs when using client). Therefore create a new client
instead of cloning it from previous one.
> Fix #1013 : Kubernetes connection is not getting closed.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java
- kubernetes-examples/src/main/resources/multiple-document-template.yml
Don't use --- as a delimiter to split documents. Instead, split document by '\n', process
line by line and only split when a single '---' found in the document. #1004
> Fix #1004: Multiple document handling breaks if "---" found anywhere in the document

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/WatcherToggle.java
This is related to https://github.com/fabric8io/fabric8-maven-plugin/issues/1263
The client tries to create a standard watch, then falls back to a http watch in some cases (to be understood why it always do so in f-m-p). The problem is that when it cleans up the standard watch, it closes the websocket but it also calls the "onClose" method on the user watcher, and it shouldn't, because the user watcher is going to be used by the fallback http watch.
This avoids the call to the user onClose callback if the watcher is going to be reused.
> Fixes premature call to watcher onClose

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ErrorChannelable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExecWatch.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/TtyExecErrorChannelable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/PodHandler.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecLoopExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecPipesExample.java
This PR stems from jenkins-kubernetes not being able to properly deal with the return code when `exec`ing into a container. The kubernetes-client doesn't provide a separate pipe for the error channel exposed over the websocker, merging it with `stderr` instead.
This changeset exposes the `error` channel as a separate stream, and renames the others to keep a consistent naming strategy. The `resize` channel is deliberately ignored.
> Support `error` websocket channel

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
> Do not repeatly create Config in exec

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
Custom resource definitions and many APIs live in API groups other than
"extensions". The current regex doesn't accept these groups and leads to
silent failures in the mock behavior because the path can't be parsed.
Technically, these API groups should be part of the attributes, but they
can't be extracted from a HasMetadata interface and I suspect we'd be
introducing matching failures if we added them for URL-generated
attributes but not object-generated attributes.
While there, fix typo in the VERSION_GROUP.
> Add support for API groups to attribute extractor.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
This can differ from `kubernetes.default.svc` in some occasions.
Uses the same logic as the go client (https://github.com/kubernetes/client-go/blob/master/rest/config.go#L313-L336)
> Determine kubernetes service host and port from environment if available

- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
If we keep that test, it will return different URl for
every other CI. If we do some changes in test, it will
be similar to other tests like setting masterUrl and all.
This started happening after PR #1086
Asserting not null and is URL is the only solution
but does not make any difference as we have another tests for this func.
> Remove Test

- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesServer.java
Rename 'curdMode' to 'crudMode' and add a comment what it does.
Fixes #1106.
> Fix typo in private var name.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/URLUtilsTest.java
This PR appends query params at the end of the URL so in case of master URL has parameters they are appended correctly at the end.
> fixes(#1089): Appends query params at the end of the URL.

- platforms/karaf/itests/pom.xml
- pom.xml
I want to cut a 4.0.1 and karaf itests are blocking the release, for reasons not clear to me (they seem to work great on circleci, maybe port related reasons).
Let's skip them when using the release profile.
> fix: skip karaf itests when using the release profile.

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/RouteCrudTest.java
Adds the case of openshift url also when doing the path URL match
to work fine with openshift resouce in openshift mock server crud Mode
Fix #1144
> Get Request with OpenShift Mock Server Not Working

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ConfigMapCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java
This supports simple label selectors (eg foo=bar). The != operator would
go beyond the limits of the AttributeSet-based matching in
CrudDispatcher.
There was a test using labels in ConfigMapCrudTest, but it was only
passing because, at the point of execution, all resources match the
label selector. This change moves changes the order of assertions so
that the effect of the label selector is observable.
This should fix #1125, although I haven't tested that code directly.
> Add support for label selectors in the mock server

- CHANGELOG.md
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java
#1162 This should fix the issue that prevent deleting deploymentconfigs in Openshift 3.9.
Something should have changed in Openshift, so that after the call to "delete" the DC returns, the resource is in a temporary state and a immediate call to "delete" the associated RC fails. With this change, the RC is deleted only *after* the DC is completely gone.
I've verified that without this change, the error happens 1 out of 3 attempts, while with the change I've executed more than 10 deletes without errors (it's a heisenbug, cannot do a deterministic test).
> Fix #1162: delete RC after fully deleting DC

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
Bug Fix: #1173
After a command is sent through the ExecWatch object to be executed in a pod, the response is labeled with a StreamID. Previously, StreamID 1 would write to the output stream, and StreamIDs 2 and 3 would write to the error stream. However, these error streams were unreachable by the ExecWatch object (.redirectingError() could not do it). 
The messages that were given StreamID2 were -- error messages from bash (ie. if i try to exec "asdfjadsf", bash should return /bin/sh: 15: asdfjadsf: not found), and protocol for terminated messages. The protocol for a terminated command execution is one or two copies of "# ". With the updated writing to output stream instead of error stream, the user can now recognize this sequence as their command finishing execution. 
I tried to filter …
> Fix #1173 : Send response to Callback for exec commands that have no textual feedback

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ImpersonatorInterceptor.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/UserImpersonationIT.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java
#1178 According to https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation, the `Impersonate-Group` header may be specified multiple times
> Fixes #1178: Impersonate-Group may be specified multiple times

- CHANGELOG.md
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/DeploymentExamples.java
After move from extensions/v1beta1 to apps/v1 , deployments made
mandatory the definition of a selector with match labels.
> Fix deployment examples

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CronJobOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CronJobExample.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/CronJobIT.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CronJobTest.java
> Fix #1172 : Use v1beta1 for CronJob

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/CertUtilsTest.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
Fixes issue [#1099](https://github.com/fabric8io/kubernetes-client/issues/1099).
+ changes how file paths to resources are resolved in tests (to work also Windows).
> fix(#1099): CustomResourceDefinitions: withResourceVersion() causes NoSuchMethodError

- .circleci/config.yml
- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
Fixes #1214
resourceVersions are Strings, so comparing them with compareTo leads to
unexpected results ("9".compareTo("10") is > 0.) Also since the versions
are supposed to be opaque we should not be trying to read any meaning
or ordering into them.
Since messages are processed in order we should just always store the
last processed resourceVersion.
I'm not sure this even needs to use an Atomic* type, but it seems safer
to just leave that in place.
> Fix tracking of watched resource versions

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/PatchUtils.java
The previous initialization was not thread safe. I have seen occurrences
of patches generated with SerializationFeature.WRITE_EMPTY_JSON_ARRAYS
option.
I have been able to reproduce a race condition in debug mode only, I
haven't been able to build a multithread unit test to exhibit the
behaviour.
> Make PatchUtils thread safe

- README.md
Closed the previous PR due to some invalid configuration issues I had.  As per the result of the discussion from that PR, added vCommander under "Properitary Platforms" list.
> Added vCommander to Used By

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java
Plugs a connection leak. 
This is the same symptom as #1198 addresses in several other places. In this case, once you get to line 121, you _know_ you're not going to need to use `response` or `request` for anything other than getting the response status code. The 'response` needs to be closed in order not to leak a connection. Getting its status code still works after closure.
> Close the initial request before discarding it.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ImpersonatorInterceptor.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
Issue - https://github.com/fabric8io/kubernetes-client/issues/1266
* Fix #1266 : Not setting optional `Impersonate-Group` results in NPE in `ImpersonatorInterceptor`
> #1266 Fixing NPE which occurs in 'ImpersonatorInterceptor' when optional 'Impersonate-Group' header is not set

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
Looks like the InputStream not being closed was the source of the leakage for me.  Referencing https://github.com/fabric8io/kubernetes-client/issues/1228 since that was the base of discussion around the issue.
Mixed with the okhttp WebSocket fix, this should get most of the leakages.
> Issue 1228: InputStream not closing correctly during unmarshal action

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
Simple change to fix #1273. Scope from CRD will be used. Method CustomResourceOperationsImpl.isResourceNamespaced will return true only if scope is set to "Namespaced.
> fix(#1273): customResources can't be used with Cluster scoped CRDs.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
Fixes #1246 - brief summary of issue: the exec listener was changed to combine stderr with stdout
This PR just reverts those changes so that stderr is properly written to the stderr stream and kept separate from stdout. 
If adding a simple way for people to use the exec api through the client would be useful, @PaulFurtado described what we've written to do this in [this comment](https://github.com/fabric8io/kubernetes-client/issues/1246#issuecomment-436899940). We'd be happy to take a look at adding something similar to the client.
> Fix #1246: Separate stderr and stdout streams in ExecWebSocketListener

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
`aws-iam-authenticator token --cluster-id <cluster-id>` returns a JSON blob of the form
```
{
"kind": "ExecCredential",
"apiVersion": "client.authentication.k8s.io/v1alpha1",
"spec": {},
"status": {
"expirationTimestamp": "2018-11-28T02:24:39Z",
"token": "<some token>"
}
}
```
This fails to deserialize in `ExecCredentialStatus`. There is a TODO to add some fields, including `expirationTimestamp`, but this is a temporary stopgap to avoid requiring those fields.
> Ignore unknown properties when deserializing ExecCredential

- CHANGELOG.md
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PersistentVolumeExample.java
Added example for PersistentVolume to demostrate NodeAffinity support after
upgrading kubernetes-model
(We can merge this whenever #1269 gets merged)
> Fix #1234: VolumeNodeAffinity Support 

- CHANGELOG.md
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java
The authorize method should never wrap an underlying checked IOException
into an unchecked KubernetesClientException. The IOException is declared
in the calling method (intercept()) and is handled by okhttp's RealCall$
AsyncCall as part of the Interceptor contract. But a RuntimeException is
not handled and okhttp's Dispatcher thread simply exits in this case,
instead of notifying the listener through the onFailure() callback.
Specific scenario that fails without this fix:
A watch is connected via websocket and the authorization token times
out, so the server closes the connection. When the watch first tries to
reconnect, a socket read timeout occurs during the authorization phase.
- Without the fix. this timeout kills the Dispatcher thread and the
WatchConnectionManager is never notified …
> OpenShiftOAuthInterceptor.authorize() should only throw IOException

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
Pick the first kubeconfig file when env var has multiple ones
Example
```
/home/jdoe/.kube/config:/home/jdoe/.kube/config-something-else.yml
```
See https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable
> Support KUBECONFIG env var with multiple paths

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
Realized today the tests were failing locally for me - took me longer then I would like to admit to realize it was due to the multi-file support added recently.
> Modified Config and ConfigTest to use File.pathSeparator to allow for multi-platform support

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
Fixes #1218. I pretty much just emulated #1124.
This is my first PR, so let me know if I missed anything :)
> Fix #1218: Add cascading() override to CustomResource

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
- kubernetes-client/src/test/resources/test-kubeconfig-exec
- kubernetes-client/src/test/resources/test-kubeconfig-exec-win
Fixes https://github.com/fabric8io/kubernetes-client/issues/1332
Fix to use ExecConfig to retrieve credentials 
* using ExecConfig
* re-enabled test-case
> Changed to use ExecConfig instead of additionalProperties

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
Amends #1224 to support the current `apiVersion` documented [here](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins). With #1347 worked around, this has been successfully tested on a GKE cluster using
```yaml
users:
- name: gcp
user:
exec:
apiVersion: "client.authentication.k8s.io/v1beta1"
command: "sh"
args:
- "-c"
- |
gcloud config config-helper --format=json | jq '{"apiVersion": "client.authentication.k8s.io/v1beta1", "kind": "ExecCredential", "status": {"token": .credential.access_token, "expirationTimestamp": .credential.token_expiry}}'
```
(The `gcloud container clusters get-credentials` command recommended by Google rewrites your `~/.kube/config` to use
```yaml
users:
- name: …
user:
auth-provider:
name: gcp
config:
access-token: …
```
> Support client.authentication.k8s.io/v1beta1

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/VersionUsageUtils.java
If you are using custom resources, there is nothing you can do about the fact that [this system is still officially in beta](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#customresourcedefinition-v1beta1-apiextensions-k8s-io) so it is just annoying to get a warning about it in every JVM session. This is particularly noxious in the case of [Jenkins X serverless builds](https://jenkins-x.io/architecture/cloud-native-jenkins/) which print a message like
```
18.333 [id=39]	WARNING	i.f.k.c.i.VersionUsageUtils#alert: The client is using resource type 'customresourcedefinitions' with unstable version 'v1beta1'
```
near the start of every build, as the `jx-resources` plugin (which uses `kubernetes-client` via `jx-java-client`) is initialized and begins updating a …
> Suppress warning about CRDs being beta

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Inputable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
#1008 
We have fixed this issue passing our own `PipedInputStream`
https://github.com/jenkinsci/kubernetes-plugin/pull/427
But the default size makes any exec command really slow. Although it should be configurable somewhere
> Fix #1008 Use a reasonable buffer size for exec stdin

- CHANGELOG.md
- pom.xml
This makes lookup of classes faster in environments that use Jandex, providing better performance in some environments
> chore: create Jandex index

- CHANGELOG.md
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java
The repo currently has an example for Cronjob Controller. It would be nice to have an example code for [Job Controller](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) as well.
> Fix #1371: Add example code for Job Controller

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
Fix #1005
Actually, I'm not sure how it used to work before. Right now I've added a small fix so this operation works:
```
KubernetesList list = client.templates().withParameters(map).load(getClass().getResourceAsStream("/template-with-number-params.yml")).processLocally(map);
```
So basically we're passing parameters in `withParameters` method, hashmap passed in `processLocally` is of no use. Was client able to parse yaml correctly with parameters earlier?
> Fix #1005: Loading a template from file and processing it locally by passing parameters map is broken.

- README.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceList.java
- kubernetes-client/src/test/resources/test-kubeconfig
- kubernetes-client/src/test/resources/test-kubeconfig-exec
- kubernetes-client/src/test/resources/test-kubeconfig-exec-win
- kubernetes-client/src/test/resources/token-generator-win.bat
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/Dummy.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesResponseComposer.java
Reverts some bits of #1322 by @iocanel to try to fix #1347. I am not all that confident I understand the code I am touching so please review carefully.
(No changelog entry needed, since #1322 is not yet released either.)
> Fix #1347: the JSON property is apiVersion, not apiGroupVersion

- CHANGELOG.md
- pom.xml
Fixes #1359
I do not write the `CHANGELOG` for I found the released version tag `v4.1.3` is not sync with `master`
and the master `CHANGELOG` do not contain the v4.1.3
> Upgrade sundrio version to 0.16.5

- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExampleWithTerminalSize.java
Related to issue https://github.com/fabric8io/kubernetes-client/issues/1374.
It's just a workaround, and if we want adjust the terminal size online,  resizeChannel support is needed.
> Add workaround to initialize terminal size while execute bash with tty.

- CHANGELOG.md
- kubernetes-model/kubernetes-model/pom.xml
Adds a missing {maven-resources} to Include-Resource
More information: http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#include-resource
Fixes #1429
> fix(kubernetes-model): META-INF/services is now added back to resulting JAR

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
The original implementation of `CustomResourceOperationsImpl::withResourceVersion()` uses a constructor that discards any previous alterations made with operations such as `withLabel`.
This patch adds the necessary constructors in `BaseOperation`, `HasMetadataOperation` and `CustomResourceOperationsImpl` to allow `withResourceVersion()` to preserve these fields.
> Preserve labels and fields when using CRD's withResourceVersion()

- CHANGELOG.md
- kubernetes-client/pom.xml
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceDefinitionOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDLoadExample.java
- kubernetes-examples/src/main/resources/crd.yml
- kubernetes-examples/src/main/resources/custom-resource.yml
- kubernetes-itests/src/test/java/io/fabric8/commons/DeleteEntity.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java
- kubernetes-itests/src/test/resources/test-crd.yml
- kubernetes-itests/src/test/resources/test-rawcustomresource-definition.yml
- kubernetes-itests/src/test/resources/test-rawcustomresource.yml
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Introduce a rawCustomResource() in client dsl 
rawCustomResource() would allow client to create, delete, list, update custom
resources without having to require Pojos of custom resources. Now the client would only
deal with JSONObjects.
> First draft of custom resources improvements

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ResourceCompare.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/ResourceCompareTest.java
Resource only equal if labels are also a match.
This restrictions prevented us from updating only the labels on the resources when calling `kubeClient.resource(resourceObj).createOrReplace();`
> Issue 1468: Taking resource labels into consideration when comparing resources

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ResourceCompare.java
The fix for issue #1468 introduced a runtime dependency
on Commons Collections just for `MapUtils.EMPTY_MAP`.
However, depending on Fabric8 Kubernetes Client doesn't
transitively bring in Commons Collections, so invoking
the respective codepath results in `NoClassDefFoundError`.
This commit replaces the usage of `MapUtils.EMPTY_MAP`
by `Collections.emptyMap()`, which does the same and
is available in the Java Collections Framework.
> fix #1495: avoid runtime dependency on Commons Collections

- pom.xml
This is necessary for Quarkus 0.13.1+ and fixes warnings as:
```
[WARNING] [io.quarkus.deployment.index.ApplicationArchiveBuildStep] Re-indexing /home/ggastald/.m2/repository/io/fabric8/openshift-client/4.2.0/openshift-client-4.2.0.jar - at least Jandex 2.1 must be used to index an application dependency
[WARNING] [io.quarkus.deployment.index.ApplicationArchiveBuildStep] Re-indexing /home/ggastald/.m2/repository/io/fabric8/kubernetes-model/4.2.0/kubernetes-model-4.2.0.jar - at least Jandex 2.1 must be used to index an application dependency
[WARNING] [io.quarkus.deployment.index.ApplicationArchiveBuildStep] Re-indexing /home/ggastald/.m2/repository/io/fabric8/kubernetes-client/4.2.0/kubernetes-client-4.2.0.jar - at least Jandex 2.1 must be used to index an application dependency
[WARNING] …
```
> chore: use Jandex 2.1.1 in jandex-maven-plugin

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
Was inadvertently removed in ded7e13e
https://github.com/fabric8io/kubernetes-client/commit/ded7e13e50e307d3144b246b2052d451a10fde0c#diff-f97f7e5381172790f1294e7696201bacL298
> Readd missing inPipe

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
- Remove creation of unnecessary OutputStream copying a directory
- Return the dir and not the file when a directory is copied or read
Issue #1507
Changelog
Bug
Fix #1507: remove unnecessary OutputStream copying a directory and return the directory object instead the file object when a directory is copied or read
> Fix some issues copying and reading directories.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExecWatch.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
I add a interface in `ExecWatch` .
I make it simple to support Resize ,please review whether it is proper,
I will add `CHANGE LOG` and UnitTest after you review.
Fixes #1374
related kubenetes code: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/remotecommand/websocket.go
> Add resize terminal Support 

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Filterable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingOperationContext.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationContext.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildOperationContext.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationContext.java
The Kubernetes API allows specifying field selectors where key-value
pair match, but also specifying non-matching key-value pairs using the
operator `!=`: https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/
Currently the Kubernetes Client allows specifying matching field
selectors using the `withField(key, value)` method. And by appending
a `!` (exclamation mark) after the key it's possible to 'hack' also the
non-matching pairs. But should internals change, this will quickly
break.
Instead this PR provides the necessary endpoint to specify non-matching
key-value pairs in field selectors by providing the method
`withFieldNot(key, value)`.
Some decisions to further discuss:
- Non-matching pairs can be specified multiple times with the same key.
Therefore a …
> Fix #1553: Add API for field selectors not matching a value.

- CHANGELOG.md
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CronJobTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/IngressTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicaSetTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicationControllerTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java
assertNotNull replaced with assertTrue for boolean statements in unit tests.
> assertNotNull replaced with assertTrue for booleans

- CHANGELOG.md
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PersistentVolumeTest.java
- kubernetes-tests/src/test/resources/test-persistentvolume.yml
Fixes #1381
Test coverage provided for PersistentVolume.
> PersistentVolumeTest added

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceList.java
Without the type parameter, `list.getItems()` returns a `List<Object>`. It should return `List<T>`. Built-in types implement this correctly, for example `PodList` extends `KubernetesResourceList<Pod>`, so `PodList.getItems()` returns a `List<Pod>`. Adding the type parameter makes this work for custom resources.
> add type parameter to custom resource list

- extensions/knative/model/pom.xml
- extensions/tekton/model/pom.xml
This removes the build warnings seen when building the project:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.fabric8:knative-model:bundle:4.3-SNAPSHOT
[WARNING] The expression ${build.outputDirectory} is deprecated. Please use ${project.build.outputDirectory} instead.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.fabric8:tekton-model:bundle:4.3-SNAPSHOT
[WARNING] The expression ${build.outputDirectory} is deprecated. Please use ${project.build.outputDirectory} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such …
```
> fix(tekton): Fixed build warnings

- extensions/knative/mock/src/main/java/io/fabric8/knative/mock/KnativeMockServer.java
- extensions/tekton/mock/src/main/java/io/fabric8/tekton/mock/TektonMockServer.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock/KubernetesMockServer.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java
- openshift-client/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServer.java
- openshift-client/src/test/java/io/fabric8/openshift/server/mock/OpenShiftMockServer.java
- openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServer.java
This is prevented because it breaks the mock-webserver in Java 11
The actual problem with mock-webserver seems to be an okhttp issue, but we can easily work around it here by ensuring that http2 is never tried (kubernetes-api server isn't http2 anyway so there no point in even attempting to use http2).
This is not a problem in Java 8 because the default installations of Java 8 don't support http2
> Make sure http2 is not tried

- CHANGELOG.md
- kubernetes-client/src/test/resources/test-template.json
- kubernetes-client/src/test/resources/test-template.yml
- kubernetes-itests/src/test/java/io/fabric8/openshift/TemplateIT.java
- kubernetes-model/kubernetes-model/src/main/java/io/fabric8/openshift/api/model/Template.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/GroupTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OpenshiftRoleTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SubjectAccessReviewTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/UserTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/SubjectAccessReviewOperationImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java
This PR aims to support OpenShift 4.x endpoints Fix #1631
> feat(openshift): Support OpenShift 4.x API Groups. Fixes #1631

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
When the Kubernetes URL used doesn't specify a port
(e.g., https://example.com/api/v1/...), the origin header for
watch requests ends up with a port of -1 (e.g., https://example.com:-1).
This happens because calling `getPort()` on a java.net.URL object that
does not have a port explicitly specified will always return -1. The
return value was always just inserted into the origin header.
Now, we check for this and only append a port to the origin header if
`getPort()` returns something other than -1. We make this change in both
the WatchConnectionManager and WatchHTTPManager classes.
I wasn't able to come up with a way to make a test for this, because the 
mock Kubernetes server support specifying the port, and especially not 
the defaults of 80/443. 
Fixes issue #1667
> Check for port before setting Origin header for watch requests.

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
Mock web server is currently removing the trailing s from endpoints when searching for objects in the API. This prevents it from finding created endpoints. Adding endpoints to the exception list of objects to be considered pluralized.
> Endpoints should stay pluralized

- CHANGELOG.md
- kubernetes-model/kubernetes-model/src/main/java/io/fabric8/openshift/api/model/Template.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/GroupTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/KubernetesOperationTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OAuthClientTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OpenshiftRoleBindingTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OpenshiftRoleTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ProjectRequestTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ProjectTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SecurityContextConstraintsTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SubjectAccessReviewTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/UserTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/SubjectAccessReviewOperationImpl.java
Template and other openshift-related resource operations may use the /apis endpoint if and only if the API Group name is specified. If for some reason the API Group Name is not declared (for example, a Template object with apiVersion:v1), then the /oapi endpoint is used.
Fixes #1684
> fix: Fixed URL resolution algorithm

- CHANGELOG.md
- kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
- kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/MutatingWebhookConfigurationTest.java
- kubernetes-model/kubernetes-model/src/test/resources/valid-mutating-webhook-configuration.json
When trying to parse this file:
```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
name: istio-sidecar-injector
namespace: istio-system
labels:
app: sidecarInjectorWebhook
chart: sidecarInjectorWebhook
heritage: Tiller
release: istio
webhooks:
- name: sidecar-injector.istio.io
clientConfig:
service:
name: istio-sidecar-injector
namespace: istio-system
path: "/inject"
caBundle: ""
rules:
- operations: [ "CREATE" ]
apiGroups: [""]
apiVersions: ["v1"]
resources: ["pods"]
failurePolicy: Fail
namespaceSelector:
matchLabels:
istio-injection: enabled
```
We get the following error:
```
com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:admissionregistration.k8s.io/v1beta1#MutatingWebhookConfiguration
at [Source: …
```
> Add admissionregistration to Packages.

- CHANGELOG.md
- kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/IntOrString.java
- kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/IntOrStringTest.java
when I use `kubernetes-client` to fetch some resource in kubernetes, especially for `Ingress` or `Service`, the port in that is with type `IntOrString`, and with field `Kind` value `null`. This bring on many troubles.
> Fixed deserialize of `IntOrString` with correct `Kind` instead of `null`

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ServiceOperationsImpl.java
I encountered an incorrect port forwarding (on service) when I had more than one namespace. In each namespace there were services with the same name. When I called portForward on service it randomly chose one of these services instead of the service with current namespace.
This pull request should remedy this behaviour.
> fixes portforwarding when there are more services with the same name in multiple namespaces

- kubernetes-client/pom.xml
- platforms/karaf/features/src/main/resources/feature.xml
- pom.xml
- uberjar/pom.xml
Jackson release [micro-patches](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#micro-patches) for jackson-databind independently of the core to fix security issues.
This updates the jackson-databind version to the latest available 2.9.9.3
> Update jackson-databind to 2.9.9.3

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterRoleBindingOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterRoleOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ComponentStatusOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CronJobOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceDefinitionOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/MutatingWebhookConfigurationOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NodeOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PersistentVolumeOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodSecurityPolicyOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PriorityClassOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ServiceOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StatefulSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StorageClassOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ValidatingWebhookConfigurationOperationsImpl.java
- kubernetes-client/src/main/resources/resource-handler.vm
- kubernetes-client/src/main/resources/resource-operation.vm
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceIT.java
Fix #1674 
@dsimansk : I've tested this on the following scenarios
1.
```
client.resource(aResource).withGracePeriod(0).cascading(true).delete();
```
Cascade deletion is performed since it's explicitly specified
2.
```
client.resource(nginxDeployment).withGracePeriod(0).cascading(false).delete();
```
Cascade deletion is not performed 
3.
```
client.resource(nginxDeployment).withGracePeriod(0).delete();
```
Cascade deletion is performed since it's default behavior in `kubectl ` also
4.
```
client.apps().deployments().inNamespace("default").withName("nginx").cascading(false).delete();
```
Cascade deletion is not performed since it's overriden by dsl
5.
```
client.apps().deployments().inNamespace("default").withName("nginx").delete();
```
Cascade deletion is performed since it's like that in …
> Fix #1674: Cascade delete can't be overriden

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
Also makes the handling of resourceVersion in WatchHTTPManager identical to that of WatchConnectionManager.
> Remove lexicographic resource version check

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
- pom.xml
This uses the types exposed in https://github.com/fabric8io/mockwebserver/pull/45 to implement EXISTS/NOT_EXISTS filtering of labels via the single argument overloads of the `.withLabel` and `.withoutLabel` methods.
> Add support for EXISTS/NOT_EXISTS filtering

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchOverHTTP.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
Reset resource version to null and schedule reconnect in case of HTTP_GHONE
This tries to address https://github.com/fabric8io/kubernetes-client/issues/1529
> schedule reconnect in case of HTTP_GONE

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java
bcpkix-jdk15on have only 400kb instead of 4.5MB from bcprov-ext-jdk15on
With this check we can take advantage of a BouncyCastleProvider that is already set (for example by the jenkins plugin bouncycastle-api)
> Check if BouncyCastle provider is set

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
I had a situation where one method in my code called a second, which called a third, which called `Watchable.watch`, and I _think_ `watch` threw up an exception (in this case due to an RBAC mistake) which was caught ultimately in my first method (according to the method name recorded by `java.util.logging`)…but it was hard to tell for sure since the stack trace including `watch` was nowhere to be seen:
```
io.fabric8.kubernetes.client.KubernetesClientException: deployments.apps "etc" is forbidden: User "system:serviceaccount:somens:someacct" cannot watch resource "deployments" in API group "apps" in the namespace "somens"
at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:206)
at …
```
> Utils.waitUntilReady should record the stack trace of the caller before rethrowing an exception

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
> Fix #1803: Missing "/" in request url while using customresource client

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
> Fix #1775: KubernetesList.list().delete(resources) orphanDependents semantics change between 4.1.3 and 4.5.2

- extensions/tekton/model/pom.xml
- extensions/tekton/model/src/main/java/io/fabric8/tekton/pipeline/v1alpha1/ArrayOrString.java
- extensions/tekton/tests/src/test/java/io/fabric8/tekton/pipeline/v1alpha1/ArrayOrStringTest.java
- extensions/tekton/tests/src/test/java/io/fabric8/tekton/test/crud/PipelineCrudTest.java
Custom serialization & deserialization for ArrayOrString type. Implementation is similar to `io.fabric8.kubernetes.api.model.IntOrString`. 
This fixes #1801
> [Tekton] Custom serialization & deserialization for ArrayOrString type

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java
Users of the informer API shouldn't be seeing these debug statements. Since it isn't added to any other type of notification, I've just removed it for now.
> Avoid spurious print statement before invoking ResourceEventHandler.onAdd()

- extensions/service-catalog/client/pom.xml
- extensions/service-catalog/model/pom.xml
- kubernetes-client/pom.xml
- kubernetes-model/pom.xml
- platforms/karaf/features/src/main/resources/feature.xml
- pom.xml
- uberjar/pom.xml
Allow the use of the Jackson BOM to define the versions of the dependencies of Jackson and clean up the definitions of the dependencies in child poms.
This also updates Jackson to 2.9.10 which is backward compatible.
> chore(deps): use Jackson BOM 2.9.10

- .gitignore
- CHANGELOG.md
- extensions/knative/tests/pom.xml
- extensions/service-catalog/model/pom.xml
- extensions/service-catalog/tests/pom.xml
- extensions/tekton/tests/pom.xml
- kubernetes-client/pom.xml
- kubernetes-examples/pom.xml
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodSecurityPolicyExample.java
- kubernetes-tests/pom.xml
- openshift-client/pom.xml
- pom.xml
The SLF4J is used as logging dependency, log4j is used only on tests, so this replaces the log4j declaration for slf4j-simple in the test scope.
This cleanup helps to reduce the dependencies used in the project and keep a single implementation in place.
This also removes the unnecessary dependency on jul-to-slf4j, which ends up being transitively included in projects that use kubernetes-client.
> Cleanup log4j dependency from project

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
As discussed in #1827, this PR sets the default grace period to `-1` seconds as default. That should make the client not specify any grace period when deleting resources and this respect the grace period configured in the resource it self (e.g. `terminationGracePeriod` field in PodSpec) or the Kubernetes default which is IMHO the most natural default behavior. When you test it for example with Pod, you should see that:
* If the Pod specifies its own grace period it is respected by default
* If the Pod doesn't specify any grace period, the Kubernetes default 30 seconds are used
* If the client specifies the grace period using `withGracePeriod(...)`, the value from client is used.
> Respect the termination grace period from the Kubernetes resource as a default value

- extensions/knative/model/pom.xml
- extensions/service-catalog/model/servicecatalog-model/pom.xml
- extensions/tekton/model/pom.xml
- kubernetes-model/kubernetes-model/pom.xml
`${basedir}` is a deprecated maven property, change it for `${project.basedir}`
* https://maven.apache.org/ref/3.2.5/maven-model-builder/index.html
* https://github.com/cko/predefined_maven_properties/blob/master/README.md
> chore: change deprecated basedir maven property

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchOverHTTP.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
This reverts #1800 due to the concern pointed out [here](https://github.com/fabric8io/kubernetes-client/pull/1800#issuecomment-549561724).
> Revert pr 1800

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java
- kubernetes-tests/src/test/resources/test-statefulset.yml
I've added a test that expose my issue.   I've also included a simple change that resolves the problem on the code path we are using.   It is possible other code paths that may be susceptible to this issue too. HTH
> Fix #1856: Prevent NPE loop when deleting locally loaded scaleable resource

- CHANGELOG.md
- kubernetes-itests/pom.xml
- pom.xml
During his testing @manusa found out that integration tests are
not getting executed during their run on CircleCI. The reason was due
to incompatibility of Junit 5 with Arquillian. I've reverted to Junit 4
in kubernetes-itests/ module for now.
We can update this whenever this gets resolved:
https://github.com/arquillian/arquillian-core/issues/137
> Fix Disabled integration tests.

- CHANGELOG.md
- kubernetes-client/pom.xml
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ContainerResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/PodResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Uploadable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListener.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OptionalDependencyWrapper.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListenerTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/OptionalDependencyWrapperTest.java
- kubernetes-client/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- kubernetes-client/src/test/resources/upload/upload-sample.txt
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
- pom.xml
Scratch implementation to support directory and file uploads to a pod.
As stated here https://github.com/fabric8io/kubernetes-client/issues/1765#issuecomment-552891575, feature implementation using available methods (i.e. `exec`) is possible but performance is really bad.
Implemented WebSocket interaction from scratch for easier and better-controlled stream piping.
Implementation performed in helper classes so PodOperationsImpl class doesn't get cluttered and to allow very granular unit testing.
Closes #1765
> Fix #1765 Ability to upload files to a pod

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListener.java
Remove reference to `StringUtils` included in non-required dependency added by accident in the previous pull request (https://github.com/fabric8io/kubernetes-client/pull/1865).
> Remove reference to missing dependency StringUtils (commons-lang)

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
I tried and failed to write a unit test for this change.  The mock server allows you to set up expectations about a` server.expect().delete().withPath()`..., but there seem to be no way to actually set an expectation  about the request body (to validate the delete options).  I noticed the `server.getLastRequest()` exists, but this doesn't help me in this case.  `getLastRequest()` gives me the delete for the deployment, I need to access the penultimate which would be the DELETE for my replicaset.
> Fix #1859 - Pass caller's propagation-policy/cascade options to the underlying replicaset when deleting a deployment

- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java
Fixes #1603
No exception in thread after removing the use of accept() method. 
It's only being used in 2 files (this one and LoadExample) and the multiple documents are loading with no issues without it.
> Fixed LoadMultipleDocumentsFromFileExample

- CHANGELOG.md
- kubernetes-model/Gopkg.lock
- kubernetes-model/Gopkg.toml
- kubernetes-model/README.md
- kubernetes-model/cmd/generate/generate.go
- kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
- kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
Fix #1872 
+ Updated Kubernetes Model to Kubernetes 1.16
+ Added these new resources to Kubernetes Model
- CreateOptions
- GetOptions
- UpdateOptions
- PatchOptions
- EndpointSlice
- VolumeAttachment
- CSIDriver
- CSINode
- Lease
> Fix #1872: Support for kubernetes 1.17

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/EditReplacePatchable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/StatusUpdatable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedCustomResourceApiTest.java
Fix #1548 
`/status` is one of the supported subresources in Kubernetes API
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource
> Fix #1548: Unable to update status on Custom Resources

- CHANGELOG.md
- kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
- kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java
Fix #885 #1895 
+ Added parsing logic to parse `format` from `amount` string
+ Added equality operator for comparing Quantity objects regardless of their formats
> Refactor Quantity Class to handle format

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/MetricAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/MetricAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/MetricAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NodeMetricOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodMetricOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/TopExample.java
- kubernetes-model/Gopkg.lock
- kubernetes-model/Gopkg.toml
- kubernetes-model/cmd/generate/generate.go
- kubernetes-model/kubernetes-model/pom.xml
- kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Duration.java
- kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
- kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/MetricsTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Fix #1282 
This PR enables fetching metrics from Kubernetes server via these dsl 
```
client.top().pod().metrics();
client.top().node().metrics();
```
> Fix #1282: Add Support for fetching Kubernetes Metrics

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ServiceOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceTest.java
- kubernetes-tests/src/test/resources/test-service.yml
Fix #1925 
While replace method, client was showing variable behaviors when done through different
ways in dsl. For example,
client.services().inNamespace("test").createOrReplace(item);
Used to load Service from server since reloadingFromServer was set to true in this case but
if we use a generic handler reloadingFromServer was set to false. I think in case of replace
operations we should always load object from server since Kubernetes API doesn't accept
patching Service object wihout ClusterIP.
> Fix #1925: Kubernetes Service should always be loaded from server while patching it.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Cache.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/DeltaFIFO.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Indexer.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/CacheTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/DeltaFIFOTest.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CustomResourceInformerExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/InformerExample.java
Fix #1894 
This PR contains some improvements/changes that happened since last port of
this feature from official go client + official java client
> Fix #1894: SharedInformer Improvements

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java
Fix #1805
Modified BackwardCompatibilityInterceptor for handling /oapi
failures in case of OpenShift
> Fix #1805: Unable to create Template on OCP4

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
The `WatchHTTPManager` currently uses a default jackson `ObjectMapper` but this prevents the user from reconfiguring the object mapper with custom modules, which can in turn break deserialization into objects which use types handled by those modules. This PR updates the `WatchHTTPManager` to use the `Serialization` util and its `ObjectMapper`
> Watch: Use Serialization not a default ObjectMapper

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
When loading a YAML file containing multiple documents, not all documents
are unmarshalled when loading a file with LF line endings in a windows
machine. Current fix considers any line ending in a platform independent
way.
Fixes: #1874
> fix: YAML with multiple documents parsed to lists

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
Fixes #1177 
According to the official [documentation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens):
> the authenticator uses the id_token (not the access_token) from the OAuth2 token response as a bearer token
This explains why there is no `access-token` in the file.
> Fix: authenticator uses id-token from ~/.kube/config

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImplTest.java
In `CustomResourceOperationsImpl` construction
`KubernetesDeserializer::registerCustomKind` is invoked without
`apiVersion` and with `kind` set to the class name. This could lead to
issues when deserializing custom resources, in my example:
```
com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:camel.apache.org/v1alpha1#Integration
at [Source: (String)"{"type":"DELETED","object":{"apiVersion":"camel.apache.org/v1alpha1","kind":"Integration","metadata":{"annotations":{"prometheus.io/port":"9779","prometheus.io/scrape":"true","syndesis.io/deploy-id":"i-M0SZstrdU_fCuujYkqGz:2","syndesis.io/deployment-version":"2","syndesis.io/integration-id":"i-M0SZstrdU_fCuujYkqGz","syndesis.io/integration-name":"t2l"},"creationTimestamp":"2020-02-19T13:14:10Z","generation":1,"la …
```
> fix: apiVersion and kind from CRD in registration

- kubernetes-client/pom.xml
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceDoneable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceList.java
Most of the api model already has toString implementations providing sufficient insight during runtime. The CustomResource and associated classes was missing a toString implementation.
Similar to the many parts of the kubernetes client codebase, this has been implemented using lombok.
> Generating toString for custom resource classes

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallback.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BlockingInputStreamPumper.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/InputStreamPumper.java
I wrote some code to watch logs from a container in a pod, but found that when the pod was deleted, log inputstream that got from PodOperationsImpl.watchLog().getOutput() didn't close and read would hang forever. 
To reproduce the issue, following the steps below :
Step 1. create a simple pod, any image will be ok as long as it can long run and give some output continuously . (Infact, if the pod is not exists, the java code here would hang in the same way)
```
apiVersion: v1
kind: Pod
metadata:
name: t01
namespace: test
spec:
containers:
- image: any-image
name: default
```
Step 2: Run the code 
```
public static void main(String[] args) throws IOException {
KubernetesClient client = new DefaultKubernetesClient();
InputStream in = client.pods()
.inNamespace("test")
.withName("t01") …
```
> fix: Do cleanup after LogWatchCallback finished

- README.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-tests/pom.xml
- platforms/karaf/itests/pom.xml
- pom.xml
- uberjar/pom.xml
- uberjar/src/main/java/io/fabric8/kubernetes/clnt/Uberjar.java
- Examples code excluded from code coverage
- Links to project specific urls (issues, home, ci, etc.)
- Skipped Karaf iTest
- JaCoCo coverage aggregation
I don't have access to Fabric8io organization in Sonar Cloud.
Moved project to JKube organization in order to be able to apply a different permission template for the project so that PRs don't require a token in order to execute and upload analysis (GH Actions don't propagate secretes to PR workflow executions for obvious security reasons)
> ci: Tuning Sonar Analysis + Fix Bug to see report

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Createable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/KubernetesListOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/SubjectAccessReviewDSLImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/SubjectAccessReviewOperationImpl.java
> Fix #1820: Override Createable.create(T) to avoid generic array creation

- extensions/knative/model/pom.xml
- extensions/knative/model/src/main/java/io/fabric8/knative/serving/v1/ServiceStatus.java
The auto-generated version of the model class makes the field a URL-class instance, whereas Knative 0.12 returns a plain String.
Corresponding GH issue: https://github.com/fabric8io/kubernetes-client/issues/1727
Signed-off-by: Florian Wiesner <florian.wiesner@oracle.com>
> Fixing the deserializing issue with ServiceStatus and its url.

- CHANGELOG.md
- pom.xml
As reported in issue #2031 (@Morty-se) that has been deleted :flushed:
> chore(deps): bump commons-compress from 1.18 to 1.20 (fix CVE-2019-12402)

- CHANGELOG.md
- kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
- kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java
Added multiplication to the amount during parsing exponential values.
Fixes https://github.com/fabric8io/kubernetes-client/issues/2052
> Fixed parsing of exponential values

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImplTest.java
Fix #2075 
The current implementation in CustomResourceOperationsImpl passes the wrong apiVersion and Kind values to KubernetesDeserializer.registerCustomKind(...).
apiVersion and Kind for a CustomResourceDefinition are always apiextensions/v1beta1 and CustomResourceDefinition.
The values from the spec needs to be passed for registering the custom kind in the deserializer.
> fixes #2075 KubernetesDeserializer registration for CustomResources

- CHANGELOG.md
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/CronTab.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/CronTabList.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/CronTabSpec.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/CronTabStatus.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/DoneableCronTab.java
- kubernetes-tests/src/test/resources/crontab-crd.yml
Added CustomResourceCrudTest for demonstrating usage of CRUD mode
for Custom Resources.
> Fix #2019: customResource.get() Returns 404 if name is specified

- kubernetes-model/kubernetes-model/pom.xml
- kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/admission/AdmissionRequest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/AdmissionReviewTest.java
- kubernetes-tests/src/test/resources/admissionreview-withpatchoptions.json
- kubernetes-tests/src/test/resources/admissionreview-withupdateoptions.json
- kubernetes-tests/src/test/resources/admissionreview.json
Fix #1898 
CreateOptions, DeleteOptions, UpdateOptions, PatchOptions are implementing KubernetesResource
But in all rawExtensions types are mapped to HasMetadata. I had to override the default
generated class in order to get parsing to work.
> Fix #1898: Fix failure in Deserialization for AdmissionRequest class

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/VersionInfo.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterOperationsImpl.java
- kubernetes-model/Gopkg.lock
- kubernetes-model/cmd/generate/generate.go
- kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
- kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/VersionInfoTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
Fix #2046 
Right now I'm just converting Openshift v4's `ClusterVersion` object to `VersionInfo` which doesn't seem very elegant to me also :confused: . Shall I introduce another method in DSL like this:
```
ClusterVersionList clusterVersion()
```
But then it would be user's responsibility to fetch all the necessary parts.
> Fix #2046: OpenshiftClient getVersion returns null for Openshift ContainerPlatform v4

- CHANGELOG.md
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java
Fix #2054: Corrected JobExample to first wait till pods created by job complete first and then
print job logs
> Fix #2054: JobExample doesn't work

- pom.xml
The --release compiler flag is required when building the project with a jdk > 8 to produce the right byte code for jdk8 (see https://github.com/eclipse/jetty.project/issues/3244#issuecomment-495322586).
Otherwise, there are issues e.g. with the PortForwarderWebsocket.
> Javac release compiler flag

- CHANGELOG.md
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/DefaultTektonClient.java
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/V1alpha1APIGroupClient.java
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/V1alpha1APIGroupExtensionAdapter.java
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/V1beta1APIGroupClient.java
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/V1beta1APIGroupExtensionAdapter.java
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/dsl/V1alpha1APIGroupDSL.java
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/dsl/V1beta1APIGroupDSL.java
- extensions/tekton/client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
- extensions/tekton/client/src/main/resources/resource-handler-services.vm
- extensions/tekton/client/src/main/resources/resource-handler.vm
- extensions/tekton/client/src/main/resources/resource-operation.vm
- extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/PipelineList.java
- extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/PipelineResourceCreate.java
- extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/PipelineResourceList.java
- extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/TaskCreate.java
- extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/TaskRunCreate.java
- extensions/tekton/generator/cmd/generate/generate.go
- extensions/tekton/model/src/main/java/io/fabric8/tekton/TektonResourceMappingProvider.java
- extensions/tekton/model/src/main/java/io/fabric8/tekton/pipeline/v1alpha1/ArrayOrString.java
- extensions/tekton/model/src/main/resources/schema/tekton-schema.json
- extensions/tekton/tests/src/test/java/io/fabric8/tekton/test/crud/V1alpha1PipelineCrudTest.java
Fixes #2115
Added dsl support for `client.v1alpha1().*` and `client.v1beta1().*` for respective apigroups. Kudos to @Fabian-K  for initial work on this
>     Fix #2115: Add Support for keeping both v1alpha1 and v1beta1 apis in tekton extensions

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
Support for multiple values in KUBECONFIG was already implemented in https://github.com/fabric8io/kubernetes-client/pull/1306
I changed log level to warn in case of multiple `kubeconfig` are found in `KUBECONFIG`
environment variable.
Fix #2174
> Fix #2174: Warn for multiple values in KUBECONFIG variable

- extensions/tekton/client/src/main/resources/resource-operation.vm
- extensions/tekton/generateModel.sh
- extensions/tekton/generator-v1alpha1/cmd/generate/generate.go
- extensions/tekton/generator-v1beta1/cmd/generate/generate.go
- extensions/tekton/model-v1alpha1/src/main/resources/schema/tekton-schema-v1alpha1.json
- extensions/tekton/model-v1beta1/src/main/resources/schema/tekton-schema-v1beta1.json
- generator/pkg/schemagen/generate.go
- kubernetes-model/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Namespaced.java
This PR updates the generation logic for *OperationsImpl to include proper scoping (namespaced vs cluster-wide) for all parts using the rewritten go generator.
Changes:
- go configuration requires scoping definition for all CRDs
- marker interface 'Namespaced' added
- go generator adds the marker interface to all Namespaced CRDs
- during the generation of the *OperationsImpl, the marker interface is used to detect the proper scoping.
This fixes #2193
> Tekton OperationsImpl Scope Fix

- CHANGELOG.md
- uberjar/pom.xml
Apparently uber-jar configuration has been wrong for a while now.
Service entry declarations were being lost because they collided both for openshift-client and
for kubernetes-client modules.
uberjar: `maven-shade-plugin:3.2.3:shade `
```
[WARNING] kubernetes-client-4.10-SNAPSHOT.jar, kubernetes-openshift-uberjar-4.10-SNAPSHOT.jar, openshift-client-4.10-SNAPSHOT.jar define 3 overlapping resources:
[WARNING]   - META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
[WARNING]   - META-INF/services/io.fabric8.kubernetes.client.ResourceHandler
[WARNING]   - META-INF/services/io.fabric8.kubernetes.client.ServiceToURLProvider
```
See: https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer
Should fix: #2066
> fix: Uber Jar includes merged service entry for multiple implementations of the same interface

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImplTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedCustomResourceApiTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Add a customResources method which takes a CustomResourceDefinitionContext instead of CustomResourceDefinition. Use that in CustomResourceOperationsImpl. Add a 'kind' field to CustomResourceDefinitionContext, defaulting to getKind if not specified
Fixes https://github.com/fabric8io/kubernetes-client/issues/2199
~This is a WIP (work in progress) because I am unable to run the tests in my environment. I haven't added any new tests yet, either. I'll take a look at that, though I think this should largely be covered by existing.~ I've taken a look at tests and updated existing tests.
This approach breaks the KubernetesClient interface due to the exposure of a new method for implementers to implement. I imagine most users are simply using one of the existing implementations, so I've left the …
> Enable querying for customResources using only CustomResourceDefinitionContext instead of full CustomResourceDefinition

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
> fix: JDK8 always uses http/1.1 protocol (Prevent OkHttp from wrongly enabling http/2)

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Seems like passing namespace with `new OperationContext().withNamespace("ns1")` was broken. We were losing all the necessary fields populated by default in `OperationContext` due to a new instance being passed by the user. This
PR fixes it by merging passed `operationContext` with client's existing `operationContext`
Related to #1075
> Add support for Namespaced SharedInformers

- CHANGELOG.md
- kubernetes-client/src/main/resources/resource-handler-services.vm
- uberjar/pom.xml
- uberjar/src/test/java/io/fabric8/kubernetes/clnt/UberJarTest.java
> Fix #2218: Uberjar: Package rewrite issues in META-INF/services

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Evictable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/PodResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
- kubernetes-model/kubernetes-model-policy/cmd/generate/generate.go
- kubernetes-model/kubernetes-model-policy/src/main/resources/schema/kube-schema.json
- kubernetes-model/kubernetes-model-policy/src/main/resources/schema/validation-schema.json
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
Evictions allow for safer deletions, respecting PodDisruptionBudget. This PR adds support to the dsl, and adds Eviction to the generated schema. `Evictions` take a `DeleteOptions`, but don't support any of the fields yet except `dryRun` in 1.18. I decided not to add client support for `dryRun` in this implementation because it would involve a bunch more changes to the various generics and interfaces. DryRun support should be a separate contribution if desired, since it applies to more than just Eviction.
For reference, see:
- [Eviction API Docs](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#the-eviction-api)
- [Eviction type](https://github.com/kubernetes/kubernetes/blob/abe6321296123aaba8e83978f7d17951ab1b64fd/pkg/apis/policy/types.go#L113-L123)
- [Eviction API …
> Adds basic support for Kubernetes Pod Eviction API

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
I noticed that I had typoed the error code. Per [Pod Eviction API docs](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#the-eviction-api) it should be a 429, not 529. I tested and verified that it indeed is a 429 that gets sent, and currently we are not catching it properly.
I've improved the PodIT test to explicitly cover this case. I can't run the test in my environment, so will see how it looks in circleci.
> Fix evict error code to be the appropriate value of 429

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/FallbackHasMetadata.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/RawHasMetadata.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
I've been using the raw API recently and noticed two bugs:
1. There was a trailing slash added to the end of POST requests. This was causing the KubernetesAttributeExtractor to fail to extract metadata from the request path. The simple fix here would be to allow a trailing slash in KubernetesAttributeExtractor path regex, but I believe the correct fix is to not add the trailing slash at all. No paths in the kube api docs have trailing slashes. I refactored RawCustomResourceOperationsImpl a bit to fix this issue, and added some tests.
2. Users of the RawCustomResourceOperationsImpl do not need to register a custom kind with the KubernetesSerializer. As such, the KubernetesAttributeExtractor fails to extract metadata from these resources. The attributes in the CrudDispatcher map then do not …
> Fixes for Raw Custom Resource API testing

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ImageEditReplacePatchable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentRollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/StatefulSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ReplicationControllerOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicaSetTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicationControllerTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java
> Fix #1868: Add Support for rolling update

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
- kubernetes-client/src/test/resources/test-kubeconfig-nocurrentctxt.yml
This PR changes `io.fabric8.kubernetes.client.Configuration` so that it stores all contexts that exist in the kubeconfig, does the same with the current context and exposes them via getters.
fixes #2215
> expose current (named) and all (named) contexts

- CHANGELOG.md
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/test/java/io/fabric8/openshift/client/dsl/AdaptTest.java
> Fix #2296: No adapter available for type:interface io.fabric8.kubernetes.client.dsl.V1APIGroupDSL

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
This fixes https://github.com/fabric8io/kubernetes-client/issues/2285
Rather than try to actually handle exception propagation for create-then-replace, I decided to mirror the BaseOperation implementation which does a get then branch accordingly. I added a couple tests.
> Update createOrReplace to work more like BaseOperation

- kubernetes-model-generator/go.mod
- kubernetes-model-generator/go.sum
- kubernetes-model-generator/kubernetes-model-admissionregistration/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-admissionregistration/src/main/resources/schema/validation-schema.json
- kubernetes-model-generator/kubernetes-model-apiextensions/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-apiextensions/src/main/resources/schema/kube-schema.json
- kubernetes-model-generator/kubernetes-model-apiextensions/src/main/resources/schema/validation-schema.json
- kubernetes-model-generator/kubernetes-model-apps/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-autoscaling/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-autoscaling/src/main/resources/schema/validation-schema.json
- kubernetes-model-generator/kubernetes-model-batch/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-certificates/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-coordination/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-core/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-discovery/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-events/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-extensions/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-metrics/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-networking/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-policy/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-rbac/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-scheduling/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-settings/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-storageclass/cmd/generate/generate.go
- kubernetes-model-generator/openshift-model/cmd/generate/generate.go
- kubernetes-model-generator/pkg/schemagen/generate.go
This PR modifies `kubernetes-model-generator` to accommodate manual type mapping. This was discussed in https://github.com/fabric8io/kubernetes-client/pull/2288 . With this in place we should be able to provide a HashMap in which we can configure which go structs should be mapped to some already existing java types
> Added a manualTypeMapping parameter for providing manual type mappings

- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadataComparator.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/KubernetesList.java
- kubernetes-model-generator/openshift-model/src/main/java/io/fabric8/openshift/api/model/Template.java
The openshift-model needs to make use of the HasMetadataComparator and therefore
it should reside in an exported package
fixes #2309
> move HasMetadataComparator to exported package

- .github/PULL_REQUEST_TEMPLATE.md
Recently @manusa added a pull request template in [Eclipse JKube](https://github.com/eclipse/jkube/blob/master/.github/pull_request_template.md). I think it would also be very useful for Fabric8 Kubernetes Client as we get lots of contributions outside of our organization
> Chore: Add Pull Request template

- CHANGELOG.md
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/EventTest.java
Fix #2328 
KubernetesDeserializer was missing the case when Kubernetes resource only had apiVersion and
no apiGroup when resolving Kubernetes resources with the same names.
> Fix #2328: Using Watcher<Event> leads to "JsonMappingException: No resource type found for:v1#Event"

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandler.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/KubernetesListHandler.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ResourceHandlerTest.java
This PR changes `KubernetesListHandler.getKind()` from returning `"Service"` to returning `"List"`.  The latter is what `KubernetesList.getKind()` returns, and the former causes the resulting `ResourceHandler.Key` to be identical to what is computed for `ServiceHandler`, meaning `Handlers.of(key)` can return the wrong handler.
In practice the problem noted above can cause the Kubernetes client to fail when working with `kind: Service` YAML manifests, in some circumstances.  This was observed under OSGi using the `DefaultKubernetesClient`.  `Handlers.of(<Service,v1>)` returned the `KubernetesListHandler` which subsequently threw the following exception:
```
Failed after 466ms: io.fabric8.kubernetes.api.model.Service cannot be cast to io.fabric8.kubernetes.api.model.KubernetesList …
```
> Test and fix for the wrong "Kind" declared on KubernetesListHandler

- CHANGELOG.md
- doc/CHEATSHEET.md
- extensions/knative/client/src/main/resources/resource-handler.vm
- extensions/service-catalog/client/src/main/resources/resource-handler.vm
- extensions/tekton/client/src/main/resources/resource-handler.vm
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/GracePeriodConfigurable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CascadingEditReplacePatchDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/EditReplacePatchDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/WatchListDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PropagationPolicyTest.java
> Fix #2269: Setting a grace period when deleting resource using `withPropagationPolicy()`

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigTest.java
- openshift-client/pom.xml
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java
- openshift-client/src/test/java/io/fabric8/openshift/client/dsl/internal/ArchiveFileInputStreamRequestBodyTest.java
Relates to #2032
+ Add BuildConfig's name and namespace in query parameters in order to align with `oc`
+ Use BufferedInputStream while uploading the archive file to the sink.
+ Add recent events to exception message and some logging in case of upload failure of archive file
> Improve error handling on stream closing errors in S2I binary build

- .github/workflows/e2e-tests.yml
bump workflow action-setup-* versions + kubernetes to 1.18.6
> chore: bump workflow action-setup-* versions + kubernetes to 1.18.6

- CHANGELOG.md
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NetworkingV1beta1IngressTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1CustomResourceDefinitionTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1HorizontalPodAutoscalerTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1MutatingWebhookConfigurationTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1ValidatingWebhookConfigurationTest.java
- kubernetes-tests/src/test/resources/test-crd-no-apiversion.yml
- kubernetes-tests/src/test/resources/test-hpa-no-apiversion.yml
- kubernetes-tests/src/test/resources/test-ingress-no-apiversion.yml
- kubernetes-tests/src/test/resources/test-mwc-no-apiversion.yml
- kubernetes-tests/src/test/resources/test-vwc-no-apiversion.yml
- kubernetes-tests/src/test/resources/valid-deployment-without-apiversion.json
Fix #2316 
In case of duplicate Kubernetes resources found, when no apiVersion
is provided return first item found instead of null
> Fix #2316: Cannot load resource from stream without apiVersion

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
Since we added `Namespaced` interface all new CustomResources must
implement this interface in order to be discovered as a Namespaced
entity. Adding this to docs are explicit notes so that they are more
clearly visible.
Related to #2331 
> Doc: Update docs in places where POJOs are required.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
> Fix #2319: Create Config without using auto-configure functionality or setting env variables

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SecurityContextConstraintsTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
- kubernetes-tests/src/test/resources/test-scc.yml
Fix #2373 
Looks like code added in #1956 BackwardCompatibilityInterceptor wasn't handling
`/oapi` `failures properly.
Fix BackwardCompatibilityInterceptor logic for routing to OpenShift 3 `/oapi/v1`
endpoints when OpenShift 4 `/apis/{group}/v1` endpoints not found. Also added some
tests to assert desired behavior
> Fix #2373: Unable to create a Template on OCP3

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CreateOrReplaceable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ResourceCompare.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/ResourceCompareTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceIT.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CreateOrReplaceResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NetworkingV1beta1IngressTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PersistentVolumeClaimTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedCustomResourceApiTest.java
Fix #2292 
+ Updated BaseOperation#createOrReplace to fallback to replace() after doing create() rather than get() -> replace()
+ Updated ResourceCompare#equals() to only compare entities present in provided resource when compared with
resource from cluster.
> Fix #2292: Update BaseOperation#createOrReplace()

- .github/workflows/build.yml
- .github/workflows/javadocs.yml
- CHANGELOG.md
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ProjectTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/ProjectOperation.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/ProjectRequestOperation.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Fix #2311 
Just like `oc adm create-bootstrap-project-template` generates a template yaml for
project request resources to be created; OpenShiftClient should be able to
generate + Apply resources based upon project request name, description, display name,
requesting user and admin user. It should create the following resources:
- Project (actual project to be created)
- RoleBinding system:deployers
- RoleBinding system:image-builders
- RoleBinding system:image-pullers
- RoleBinding admin
> Fix #2311: Add Support for creating bootstrap project template

- CHANGELOG.md
- doc/CHEATSHEET.md
This PR add a simple serialization to YAML in the cheatsheet. I couldn't find any documentation on this easily. It should also closes #2363.
> doc: add YAML serialization example in the cheatsheet

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesResponseComposer.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java
Fixes #2306: make Informers work with KubernetesServer CRUD mode
> Fixes Issue 2306: make Informers work with KubernetesServer CRUD mode

- CHANGELOG.md
- extensions/knative/tests/src/test/java/io/fabric8/knative/test/RouteTest.java
- extensions/knative/tests/src/test/java/io/fabric8/knative/test/crud/RouteCrudTest.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ResourceCompare.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/ResourceCompareTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/RouteCrudTest.java
Fix #2354 
Somehow resource was being returned as `null` from `fromServer.get()` call due to no
namespace being provided. Added a case of Null items in `ResourceCompare#equals`
> Fix #2354: Fix NullPointerException in ResourceCompare when no resource is returned from fromServer.get()

- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
fix: Improved running time of WatchTest (from ~2 minutes to ~3 seconds)
Relates to: #2425 
> fix: Improved running time of WatchTest (from ~2 minutes to ~3 seconds)

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/GeneratorRunConfig.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/GeneratorRunConfigUtil.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/PodGeneratorImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/GeneratorRunConfigUtilTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/PodGeneratorImplTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Fix #2284 
Add support for client.run() with which we should be able to create
Pod/Deployments just based on few parameters. For example, creating
a simple pod should be like:
```
client.run().pods().withName("nginx").withImage("nginx:1.39").done()
```
> Fix #2284: Support running/creating a particular image in a Pod operation

- kubernetes-itests/pom.xml
- kubernetes-tests/pom.xml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
- pom.xml
> Improve running time of DefaultSharedIndexInformerTest

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
"Refactoring multi-catch blocks, and the InterruptedExceptions, ExecutionException, IOException in the BaseOperation.java"
Fixes #2398 
-->
- [] Feature (non-breaking change which adds functionality)
.
I have tested this locally and I can see Maven Builds are successful after the changes. 
Please let me know in case of any changes needed.
> "Refactoring multi-catch blocks, and the InterruptedExceptions, ExecutionException, IOException in the BaseOperation.java"

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PersistentVolumeClaimTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
fix #2445 : ConfigMap and other resources are replaced
- Reverted **behavior** of BaseOperation#createOrReplace method (and similar)
to the previous behavior.
API will always be hit, POST to try to create, and PUT in case POST fails.
This reverts the behavior trying to mimic kubectl and not performing
the second PUT request in case the resource is identical to the server version.
> fix: ConfigMap and other resources are replaced

- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java
InterruptedExceptions are not handled properly in ProjectRequestsOperationImpl.java, we can see the same from the Sonar Bug report.
This PR should fix the same for ProjectRequestsOperationImpl.java
> Properly Handling InterruptedExceptions

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
From downstream: https://github.com/jboss-fuse/kubernetes-client/pull/12
On newer Kubernetes, when WebSockets are not available, the server returns 503 Service Unavailable status code (formerly it returned 200 OK). Watch service needs to consider this response code too when trying to fall back to HTTP watch.
> Quickstarts fails on OCP 4.6

- .github/workflows/build.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/javadocs.yml
- .github/workflows/license.yml
- .github/workflows/sonar.yml
> Chore: Use Java 8 in Github Actions instead of Java 11

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/BuildConfigIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/RouteIT.java
- kubernetes-itests/src/test/resources/buildconfig-it.yml
- kubernetes-itests/src/test/resources/deploymentconfig-it.yml
- kubernetes-itests/src/test/resources/imagestream-it.yml
- kubernetes-itests/src/test/resources/route-it.yml
Fix #2467 
BackwardCompatibilityInterceptor should only convert openshift4 to openshift3 requests
on receiving 404
> Fix #2467: OpenShiftClient cannot replace existing resource with API version =! v1

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
Fix #2474 
Fix NullPointerException when using Config.fromKubeconfig
> #2474 - Fix NullPointerException when using Config.fromKubeconfig

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceIT.java
- kubernetes-itests/src/test/resources/service-it.yml
Fix #2399 
Removes overridden replace() method in `ServiceOperationsImpl`
> Fix #2399: Cannot change the type of the Service from ClusterIP to ExternalName

- CHANGELOG.md
- extensions/knative/client/pom.xml
- extensions/service-catalog/client/pom.xml
- extensions/tekton/client/pom.xml
- extensions/volumesnapshot/client/pom.xml
- kubernetes-client/pom.xml
- kubernetes-model-generator/kubernetes-model-core/pom.xml
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
- openshift-client/pom.xml
- platforms/karaf/features/src/main/resources/feature.xml
- platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/FeatureInstallationTest.java
- platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/KubernetesDeserializerTest.java
- platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/PropertiesOverrideTest.java
- platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/ServiceTest.java
- platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/TestBase.java
- platforms/karaf/itests/src/test/resources/deserializer_openshift_test.yaml
- platforms/karaf/itests/src/test/resources/deserializer_test.yaml
- pom.xml
fix #2479 : KuberentesDeserializer works on OSGi runtime environments
- Added specific imports (kubernetes-client) & exports for model modules
- Support for Java ServiceLoader API exported Handlers (OpenShift Client only) + tests
- Refactored Apache Karaf tests
> fix: KuberentesDeserializer works on OSGi runtime environments

- CHANGELOG.md
- kubernetes-client/pom.xml
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/VersionInfo.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/PatchUtils.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java
- kubernetes-itests/src/test/resources/deploymentconfig-it.yml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LoadTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/VersionInfoTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftLoadTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftVersionInfoTest.java
- openshift-client/pom.xml
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftClusterOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftNamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftNamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/patchmixins/BuildMixIn.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/readiness/OpenShiftReadiness.java
- openshift-client/src/test/java/io/fabric8/openshift/client/dsl/base/TestUnmarshal.java
Fix #2141: Decouple OpenShift Model from Kubernetes Client
This change may be breaking for users who might be using KubernetesClient for OpenShift operations(like we were doing in our tests)
> Fix #2141: Decouple OpenShift Model dependency from Kubernetes Client

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java
> Fix #2452: Make Readiness.isReady() publicly available from a wrapper method in KubernetesResourceUtil

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Filterable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/PodOperationUtilTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/EventTest.java
Fix #2460
Added an `withInvolvedObject(ObjectReference objectReference)` method in Filterable
interface which would transform object references into fieldsSelector values
> Fix #2460: Querying for an event based on InvolvedObject fields

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/TemplateIT.java
- kubernetes-itests/src/test/resources/deploymentconfig-it.yml
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
Revert #2373
This commit reverts 293ab9d445291de389d438f4a857928722230dba which was added in order
to fix #2373. This behavior was causing problems with Strimzi's Kubernetes Client
upgrade: https://github.com/strimzi/strimzi-kafka-operator/pull/3553 . On bisecting
the failing test, I found this commit as culprit. Git bisect log:
```
kubernetes-client : $ git bisect log
git bisect start
git bisect bad ea09419284b32e6da70aadfaf9022485f2bec594
git bisect good c5fe5488dc15ed3d4795a3b3d676549c24c2e744
git bisect bad 262e35f09be835bf5f3b5fbc4c16791224fbc390
git bisect bad d13a86480f699735dcc8e0ece90c24d4e49079e8
git bisect good f1d695d59ce50a9067639df0b79855f03096adc8
git bisect good 0b1e0668788aaf2d7f0e706f111ca67456cbb36c
git bisect bad 14cae945ee20ce1ac980d492e53d388aa93eb371
git bisect bad …
```
> Revert BackwardCompatibilityInterceptor's behavior of changing /apis to /oapi URLs

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/FilterWatchListMultiDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/NonNamespaceOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Operation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Resource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/VersionWatchAndWaitable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/WatchAndWaitable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/WatchListDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentRollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetRollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/StatefulSetRollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/DeploymentRollingUpdater.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/ReplicaSetRollingUpdater.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/PodOperationUtilTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java
Allow `withResourceVersion()` to be followed by `waitUntilCondition()`. This enables recovery from HTTP 410 GONE errors, at the cost of breaking the current API slightly, i.e. new `WatchAndWaitable` interface, and replacing `VersionWatchable` with `VersionWatchAndWaitable`. I've also removed a now-surplus type parameter from `WatchListDeletable`.
The existing code for handling `waitUntilCondition()` for a `ResourceList` looks like it could fail with `ConcurrentModificationException` errors if multiple threads try to modify the `result` and `itemsWithConditionNotMatched` lists simultaneously, and so I have used `CompletableFuture`s instead.
Fixes #2414 
> Allow waitUntilCondition() to follow withResourceVersion().

- CHANGELOG.md
- kubernetes-model-generator/kubernetes-model-discovery/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-events/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-extensions/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-metrics/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-networking/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-policy/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-rbac/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-scheduling/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-settings/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/kubernetes-model-storageclass/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- kubernetes-model-generator/openshift-model/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
Fix #2488
Remove unused io.fabric8.kubernetes.api.KubernetesResourceMappingProvider from kubernetes model packages
> Fix #2488: Unable to derive module descriptors for Kubernetes Model Jars

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
We changed `customResource()` typed API to require POJOs to implement `io.fabric8.kubernetes.api.model.Namespaced`
for Namespaced resources, but we didn't add any documentation about this breaking change. This PR tries to add
documentation regarding this in javadocs and CHANGELOG
> Doc: Add documentation about customResource API change related to Namespaced interface

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudAttributesExtractor.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtension.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesServer.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudWithCRDContextTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/DoneableEntandoBundleRelease.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/EntandoBundleRelease.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/EntandoBundleReleaseList.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/EntandoBundleReleaseSpec.java
Fix #2146 
Kubernetes Mock Server would now accept an extra optional parameter of list of CustomResourceDefinitionContext:
```
KubernetesServer(boolean https, boolean crudMode, List<CustomResourceDefinitionContext> crdContextList);
```
This CustomResourceDefinitionContext list would be propagated to KubernetesAttributeExtractor and would be
used while resolving Kind from Plural names
> Fix #2146: Add Support for specifying CustomResourceDefinitionContext while initializing KubernetesServer

- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
Signed-off-by: Stanislav Knot <sknot@redhat.com>
Quantity class has these lombok annotations in the header:
1. `ToString`
2. `EqualsAndHashCode`
but this class is also implementing methods `toString` and `equals`. 
> Remove lombok annotations from Quantity class

- CHANGELOG.md
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
This PR fixes the issue described in #2537 where the `isReady()` method does not work for DeploymentConfig because it calls `Readiness.isReady()` instead of `OpenShiftReadiness.isReady()` This PR adds override into `OpenShiftOperation` which uses `OpenShiftReadiness` for OpenShift resources. As a test I added it to the existing `waitUntilReady` test.
> Fix isReady call for DeploymentConfigs

- .github/workflows/e2e-tests.yml
Upgrade `manusa/actions-setup-minikube` + `manusa/actions-setup-openshift` to the latest version.
Removes the following warnings caused by [CVE-2020-15228](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w):
```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Relates to:
- https://github.com/manusa/actions-setup-minikube/issues/22
- …
> chore: Upgrade actions-setup-minikube to v2.0.1 + -openshift to v1.1.2

- README.md
Add syntax highlight to examples in "Mocking Kubernetes" chapter (I don't want t-shirt, only colorful annotation and keywords 🙂)
> README: Add syntax highlight to examples in "Mocking Kubernetes" chapter

- .github/workflows/e2e-tests.yml
- CHANGELOG.md
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/JobIT.java
I've seen it many times that our e2e tests fail at Install Kubernetes Client
step, maybe we can move it to a separate job which e2e tests can reuse rather
than building client again everytime.
Also, increased log wait timeout to 30 seconds for JobIT's log test
> Chore: Allow e2e workflows to use Maven Cache

- CHANGELOG.md
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/readiness/OpenShiftReadiness.java
This is to make `OpenShiftReadiness` a drop-in replacement
for `Readiness` for OpenShift users.
Fixes #2557.
> add missing OpenShiftReadiness.isReadinessApplicable

- .github/workflows/e2e-tests.yml
> Github Action Cache should be unique for all pull requests

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/CreateOrReplaceHelper.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/DeleteAndCreateHelper.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/CreateOrReplaceHelperTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/DeleteAndCreateHelperTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/CreateOrReplaceIT.java
- kubernetes-itests/src/test/resources/createorreplace-it-testlist-v1.yml
- kubernetes-itests/src/test/resources/createorreplace-it-testlist-v2.yml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
> WIP: Workaround for #2292

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/HasMetadataTest.java
Adds convenience methods on CustomResource. Not sure if it makes sense to add them at that level?
> feat: add isMarkedForDeletion and finalizer-related methods

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Add utility method to get age of a kubernetes resource in `KubernetesResourceUtil`
Fixes #2590
> Add utility to get age of a resource

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceList.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImplTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/Foo.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/FooList.java
Currently, when the client is asked to retrieve a `MixedOperation` instance to deal with custom resources based solely on the custom resource's class, it will try to infer a `KubernetesList` implementation associated with that custom resource class. However, this currently requires users to provide such an implementation which should be named as the custom resource class with the `List` suffix in the same package. This kind of defeats the purpose of only requiring the custom resource class. This change makes it so that, if a custom list implementation satisfying the above criteria is not found, `CustomResourceList.class` is returned, which should work adequately as a default.
> fix: make inferListType return CustomResourceList if no custom list exist

- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/HasMetadataTest.java
Fix the name of the finalizer name matcher. Breaks interface but since it was just introduced in 5.0.0-alpha-1, it's a good time to fix it before it's used. 
> fix: improve matcher to make it more DNS-spec compliant

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Watcher.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/WatcherException.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/WaitForConditionWatcher.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamedRunnable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawWatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ReflectorWatcher.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/ReadinessWatcher.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/WatcherToggle.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationWatchTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/WaitForConditionWatcherTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManagerTest.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CronJobExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/FullExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/WatchExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/PodWatchEquivalent.java
- kubernetes-examples/src/main/java/io/fabric8/openshift/examples/WatchBuildConfigs.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/WatchIT.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/EventTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
refactor: `Watcher#onClose` has dedicated `WatcherException` as parameter.
- Refactored common parts of Watcher implementations into `AbstractWatchManager`
I've refactored the `Watcher` interface and the methods calling it.
The interface now provides a dedicated default argument-less `onClose()` method. This method should always be called upon Watcher completion. Implementations should override this method in case operations (e.g. cleanup) should be performed once the Watcher is closed.
The previous `onClose(WatcherException cause)` is kept and only invoked whenever an exception occurs during the Watcher life-cycle (once the watch connection is open and established).
To be clear, Exceptions that happen during Watch initiation should be captured with code like (this has not changed): …
> refactor: Watcher.onClose has dedicated WatcherException as parameter.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OIDCTokenRefreshInterceptor.java
Fixes #2631 
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
In this PR we introduce a little check for nulls in OIDC handling for interceptors. In any case, if the current context is null, no auth info is generated whatsoever.
> Fix #2631 - Handle null values when getting current context on OIDC interceptors

- .github/workflows/sonar.yml
Fix warning "The version of Java (1.8.0_275) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 11."
https://sonarcloud.io/documentation/appendices/move-analysis-java-11/
<!--
> Move Sonar analysis to Java 11

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
- kubernetes-client/src/test/resources/test-pod-manifest-with-aliases.yml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceQuotaTest.java
Fix #2510 
Modify the way we deserialize Yaml objects. Load them into raw HashMap
using SnakeYAML and then use Jackson to convert them to JSON and finally
the required object
> Fix #2510: Yaml containing aliases rejected due to FasterXML bug

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/BindingOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/BindingOperationsImplTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/BindingTest.java
fix #2656: Binding operations can be instantiated
> fix: Binding operations can be instantiated

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContextTest.java
fix: CustomResourceDefinitionContext.fromCrd support for v1 CustomResourceDefinition
Relates to #2611
CC: @adietish 
> fix: CustomResourceDefinitionContext.fromCrd support for v1 CustomResourceDefinition

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ControllerTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ReflectorTest.java
Fix #2651 
Refactor Reflector to ignore resync if resyncPeriod is set to zero
> Fix #2651: SharedInformers should ignore resync on zero resyncPeriod

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/WaitForConditionWatcher.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/WaitForConditionWatcherTest.java
These changes have been running for us internally for 6 months or so, but I never got a chance to upstream them. We'd like to bring our fork more in-line with mainstream, so here is a group of changes related to watcher reliability:
- _If the target of a watch is deleted, it will never satisfy the watch condition_
We saw this case where you are watching a resource hoping it will hit a particular condition, if the resource gets deleted while you are waiting the watcher will simply go on forever until the timeout. This change makes it fail much faster in the case where it will never succeed.
- _Path segment based filters have spotty support in newer kube api versions. Field selector seems to work everywhere_
It looks like this was added [3.5 years …
> Fixes around exceptional cases in watchers

- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrud1109Test.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/FooBar.java
Tidied 1109 test to show clearer intentions 
- documented test cases
- Added extra verification to assert RAW HTTP path is as expected
Please provide a description of what your PR does providing a link (if applicable) to the issue it fixes. It is
really helpful for people who would review your code.
-->
> fix: tidied 1109 test to show clearer intentions

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Cache.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/CacheTest.java
We sometimes need to index into the Cache/Indexers when we know a namespace/name rather than have a HasMetadata on hand. We could generate this ourself, but I felt it was more safe to provide a convenience method. This way if the cache key format ever changes in the future, anyone looking up directly by namespace/name will also be automatically updated to sync with those passing in a HasMetadata.
> add a method which directly takes a namespace and name

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrud1109Test.java
fix: kind for CustomResourceDefinition is `CustomResourceDefinition`
- Current behavior is to override the CustomResourceDefinition kind field value
with that of the CR it's defining which is not OK.
> fix: kind for CustomResourceDefinition is `CustomResourceDefinition`

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CascadingDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ListVisitFromServerGetDeleteRecreateWaitApplicable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/VisitFromServerGetWatchDeleteRecreateWaitApplicable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/DeleteAndCreateHelper.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/DeleteAndCreateHelperTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceIT.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
As the title says, this is something the API supports but kubernetes-client's generics were just not set up properly to allow crafting such a request. This updates the generics to support that use-case. Added an IT and unit test for the new functionality.
> Allow specifying PropagationPolicy when using deleteExisting

- kubernetes-itests/src/test/java/io/fabric8/openshift/BuildConfigWatchIT.java
- kubernetes-itests/src/test/resources/ruby-new-app.yml
We instantiate BuildConfig in Eclipse JKube while doing S2I builds. Adding an integration test for that so that we don't break this again in the future.
Related to https://github.com/fabric8io/kubernetes-client/issues/2668
> Add an integration test for BuildConfig instantiation

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Fix #2695: fromCustomResourceType should be of type `CustomResource`.
The method previously accepted a Class<? extends HasMetadata> which is wrong since the created instance is then casted to a CustomResource type.
> fix: fromCustomResourceType is of type `CustomResource`

- kubernetes-model-generator/kubernetes-model-discovery/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-discovery/src/main/resources/schema/kube-schema.json
- kubernetes-model-generator/kubernetes-model-discovery/src/main/resources/schema/validation-schema.json
- kubernetes-model-generator/kubernetes-model-discovery/src/test/java/io/fabric8/kubernetes/api/model/discovery/v1beta1/EndpointSliceTest.java
- kubernetes-model-generator/kubernetes-model-discovery/src/test/resources/valid-endpointslice.json
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/EndpointSliceTest.java
- platforms/karaf/itests/src/test/resources/deserializer_test.yaml
Kubernetes Discovery apiVersion is `discovery.k8s.io` not discovery
Related to #2702 
> Fix Kubernetes Discovery ApiVersion in Model generator script

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java
- kubernetes-itests/src/test/resources/rawcustomresourceit-crud-inputstream.yml
Fix #2687 
Removed colliding variables from parent OperationSupport class and added
a call to super in constructor
> Fix #2687: RawCustomResourceOperationsImpl ignores provided Config

- extensions/knative/model/src/test/java/io/fabric8/knative/ModelTest.java
- extensions/tekton/model-v1beta1/src/test/java/io/fabric8/tekton/ModelTest.java
- model-annotator/src/main/java/io/fabric8/kubernetes/ModelAnnotator.java
This is a backport from master. Since, we've already broken the model jar into pieces, it does make sense to add it on 4.x too.
> fix(#2596) Add buildable ref for container, port and volume

- CHANGELOG.md
- extensions/knative/client/pom.xml
- extensions/knative/model/pom.xml
- extensions/tekton/model-triggers/pom.xml
- extensions/volumesnapshot/client/pom.xml
- extensions/volumesnapshot/model/pom.xml
- kubernetes-model-generator/kubernetes-model-common/pom.xml
- kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/Generated.java
- kubernetes-model-generator/kubernetes-model-coordination/src/main/java/io/fabric8/kubernetes/api/model/coordination/v1/LeaseSpec.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/KubernetesList.java
- kubernetes-model-generator/openshift-model-operatorhub/src/main/java/io/fabric8/openshift/api/model/operatorhub/v1alpha1/OperatorVersion.java
- kubernetes-model-generator/openshift-model/src/main/java/io/fabric8/openshift/api/model/Template.java
- kubernetes-model-generator/pom.xml
- model-annotator/pom.xml
- pom.xml
-------
The pull request removes uneeded dependencies from the project.
> fix: cleanup uneeded dependencies

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/CustomResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/EntandoBundleRelease.java
Makes typical use cases automatic, provide `initSpec` and  `initStatus` method on `CustomResource` to let user provide their own custom implementation if the default doesn't work for their use case. Fixes #2744.
> Automatically instantiate spec and status fields

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java
Fixes #2612. 
When using a Kubernetes provider that uses OAuth tokens, such as GKE, the existing token will expire after some amount of time, and the client will receive 401 HTTP_UNAUTHORIZED. Instead of assuming this is related to only OIDC tokens, make OIDCTokenRefreshInterceptor more generic and if the auth provider is not OIDC, try to load the latest kubeconfig from disk and use the token provided there. This solves the issue for providers like GKE if the user ensures their kubeconfig location contains a valid token.
Also fixes a response leak in the interceptor.
> Fix #2612: add support for checking latest kubeconfig in Interceptor

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java
As discussed in #2717, it's not a good idea to take InputStream for
edit() methods which simply does a PATCH to Kubernetes APIServer.
> Fix #2717: Remove edit() methods from RawCustomResourceOperationsImpl taking InputStream arguments

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CertificatesAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CertificatesAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1CertificatesAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1CertificatesAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1CertificatesAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1CertificatesAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CertificatesAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1CertificatesAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1beta1CertificatesAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/CertificateSigningRequestIT.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1CertificateSigningRequestTest.java
- kubernetes-tests/src/test/resources/test-v1-csr.yml
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Fix #2703 
+ Added a new `client.certificates()` DSL to KubernetesClient
+ Mark `client.certificateSigningRequests()` as `@Deprecated`
> Fix #2703 : Add support for `certificates.k8s.io` v1 and v1beta1 API in KubernetesClient DSL

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1SchedulingAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1SchedulingAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1SchedulingAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1SchedulingAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1SchedulingAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1beta1SchedulingAPIGroupDSL.java
- kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodPriorityExample.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PriorityClassTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1PriorityClassTest.java
- kubernetes-tests/src/test/resources/test-v1-priorityclass.yml
- Added v1() and v1beta1() DSLs to SchedulingAPIGroupDSL for
PriorityClass. Now they're available in
- `client.scheduling().v1().priorityClasses()`
- `client.scheduling().v1beta1().priorityClasses()`
- Marked `client.scheduling().priorityClass()` as `@Deprecated` in favor of new APIs
> Add DSL support for `scheduling.k8s.io` v1 and v1beta1 to SchedulingAPIGroupDSL

- CHANGELOG.md
- README.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java
Fix #2716 
Added a flag "kubernetes.disable.backwardsCompatibilityInterceptor"
which will skip addition of BackwardCompatibilityInterceptor in
OkHttpClient created in HttpClientUtils.createHTTPClient
> Fix #2716: Add a property to disable BackwardCompatibilityInterceptor

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/WatchListDeletable.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/PodOperationUtilTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PropagationPolicyTest.java
Fix #2745 
Add `PropagationPolicyConfigurable<EditReplacePatchDeletable<T>>` to `WatchListDeletable` interface so that it's available in all `Filterable<T>` methods
> Fix #2745: Filtering Operations can't configure PropagationPolicy

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/ReadinessWatcher.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/readiness/ReadinessTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeploymentIT.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceIT.java
- kubernetes-itests/src/test/resources/service-it.yml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftNamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftNamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/readiness/OpenShiftReadiness.java
- openshift-client/src/test/java/io/fabric8/openshift/client/internal/readiness/OpenShiftReadinessTest.java
Fix #2672 
Use `waitUntilCondition(Objects::nonNull, amount, timeUnit)` instead of waitUntilReady for `Service` resource
> Fix #2672: WaitUntilReady for Service resource throws IllegalArgumentException

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/readiness/OpenShiftReadiness.java
fix: Replace double-checked locking idiom with the more suitable initialization-on-demand holder idiom
Initial implementation of the singleton contained a typo (missing `volatile` variable declaration).
Since this pattern is [dangerous](https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html) and [not](https://www.infoworld.com/article/2074979/double-checked-locking--clever--but-broken.html?page=2) [recommended](https://rules.sonarsource.com/java/tag/multi-threading/RSPEC-2168), I replaced it with the more suitable (for this case) [Initialization-on-demand holder idiom](https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom).
cc: @Ladicek 
> fix: Replace double-checked locking idiom with initialization-on-demand holder idiom

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1ApiextensionAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1ApiextensionAPIGroupDSL.java
CustomResourceDefinitions api DSL should not have inNamespace exposed.
This was due to my mistake while adding apiextensions() DSL in
https://github.com/fabric8io/kubernetes-client/pull/2359
> Apiextensions DSL uses NonNamespaceOperation for CustomResourceDefinitions

- CHANGELOG.md
- crd-generator/pom.xml
- crd-generator/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
- crd-generator/src/main/java/io/fabric8/crd/generator/utils/Types.java
- crd-generator/src/main/java/io/fabric8/crd/generator/v1/JsonSchema.java
- crd-generator/src/main/java/io/fabric8/crd/generator/v1beta1/JsonSchema.java
- crd-generator/src/test/java/io/fabric8/crd/example/person/Address.java
- crd-generator/src/test/java/io/fabric8/crd/example/person/Person.java
- crd-generator/src/test/java/io/fabric8/crd/generator/utils/TypesTest.java
- crd-generator/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
- pom.xml
`Types.applyTypeArguments` doesn't crash when encountering differing
cardinality between type definition and actual arguments, which was the
case when encountering an enum property. Such properties are now
generated by enumerating their cases name and recording them in the
validation schema. Not sure if that actually covers all cases.
Fixes #2819.
> fix: simple enums are now supported when generating CRDs

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Pluralize.java
Replace occurrences of Function<T, T> with UnaryOperator<T>. Imports are also reorganized in the touched class.
Fixes #2766 
> Issue-2766: Replace occurrences of Function<T, T> with UnaryOperator<T>

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtension.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtensionClientAndServerStaticTests.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtensionClientAndServerTests.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/APIServiceTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildTest.java
- openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/EnableOpenShiftMockClient.java
- openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtension.java
- openshift-server-mock/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtensionClientAndServerStaticTests.java
- openshift-server-mock/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtensionClientAndServerTests.java
- openshift-server-mock/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtensionStaticTests.java
- openshift-server-mock/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtensionTests.java
Fix #2699 
- Add OpenShiftMockServerExtension based on KubernetesMockServerExtension
- Refactor KubernetesMockServerExtension to set TestClass's KubernetesMockServer
-  Right now KubernetesMockServerExtension only sets TestClass's KubernetesClient field if present. This is good for CRUD mode but for use cases where we want to set expectations; we can't use it. This PR also refactors KubernetesMockServerExtension to consider both KubernetesClient and KubernetesMockServer fields in TestClass and initialize them accordingly
I haven't updated all tests in `kubenetes-tests` to get rid of KubernetesServer `@Rule`. I think we can create an easy hack to replace it with this Junit5 extension
> Fix #2699: Add support for `@EnableOpenShiftMockClient` for OpenShiftClient

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PropagationPolicyTest.java
Fix #2781 
Align RawCustomResource delete API to return a boolean value indicating
status for deletion just like we have in regular DSL. Right now we're
just throwing an exception in case item doesn't exist in server.
> Fix #2781: RawCustomResourceOperationsImpl#delete should return a boolean value

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java
This is simply fixing the format of the log, and it also log the exception itself to get an informative stacktrace
It fixes #2857 
> Fix #2857: Fix the log of an unexpected error from an Informer's EventHandler

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java
Fix #2783 
Use refresh_token from response to persist refresh-token in kubeconfig not access_token
> Fix #2783: OpenIDConnectionUtils#persistKubeConfigWithUpdatedToken persists access token instead of refresh token

- kubernetes-itests/pom.xml
Since openshift-client already brings kubernetes-client as a transitive
dependency. No need to keep kubernetes-client explicitly.
Related to https://github.com/fabric8io/kubernetes-client/issues/2845
> Remove kubernetes-client dependency from kubernetes-itests

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java
This is just a follow up for #2853 to use `Gettable` instead of `Supplier`, this change avoids the unbox from Gettable and box to Supplier and use directly Gettable instead (which is a Supplier with a different name)
> fix: Use Gettable instead of Supplier to get current item

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/KubernetesListOperationsImpl.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceIT.java
test: Improve ResourceIT test resiliency
> test: Improve ResourceIT test resiliency

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/PodOperationUtil.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/OperationContextTest.java
Reduce some code smells from OperationContext class, and also use primitive booleans in BaseOperation.
There is a small improvement in the `with*` instantiation of OperationContext where if the same value is provided, the same instance is returned instead of creating an unnecessary copy.
> Reduce code smells in OperationContext class

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawClusterScopedCustomResourceIT.java
- kubernetes-itests/src/test/resources/rawclusterscopedcustomresource-it.yml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
Fixes #2780
+ Move namespace and name to be member fields rather than being specified in method parameters so that they can be configured using `withName`, `inNamespace` methods
+ Right now these single argument delete methods are quite confusing. On first look user might think it's for deleting a Cluster Scoped Custom Resource. Hence, modifying it to behave differently based on Scope provided in CustomResourceDefinitionContext
- Added get(), list() methods to Raw CustomResource API in order
to make it more consistent with KubernetesClient DSL
- Added an Integration test for Cluster scoped Custom resource
> Fix #2780: Refactor RawCustomResourceOperationsImpl#delete(String)

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/SharedInformerFactoryTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Fix #2746 
SharedInformerFactory has `informers` and `startedInformers` Map fields
which use `Type` as key. This limits us to use only one
SharedIndexInformer corresponding to a particular type. We should make a
key based on OperationContext's elements like apigroup, apiversion,
namespace, name.
> Fix #2746: SharedInformerFactory should use a key based on OperationContext rather than Type in Map storing registered informers

- doc/CHEATSHEET.md
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/AnimalSpec.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/AnimalStatus.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/CronTabSpec.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/CronTabStatus.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/EntandoBundleRelease.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/EntandoBundleReleaseSpec.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/PodSetSpec.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/PodSetStatus.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/StarSpec.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/StarStatus.java
A user interested in CustomResources pinged me with [link to CHEATSHEET ](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api), I realized it's outdated with 5.x improvements
+ Remove unnecessary `implements KubernetesResource` from CustomResource
POJOs
+ Remove unnecessary `@JsonDeserialize` from test CustomResource POJOs
+ Update CHEATSHEET Typed API samples as per 5.x
> Doc: Update CHEATSHEET and tests CustomResource POJOs

- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
+ Added test for SharedIndexInformer for a ServiceAccount type to monitor
events filtered with labels across all namespaces and in a particular
namespace to verify that the use case actually works on master.
+ Minor Cleanup in DefaultSharedIndexInfomerTest to avoid code
duplication while setting MockServer expectations
Related to https://github.com/fabric8io/kubernetes-client/issues/2801
> Chore: Add test for ServiceAccount SharedIndexInformer watching resources with labelSelectors

- CHANGELOG.md
- extensions/chaosmesh/client/src/main/resources/resource-handler.vm
- extensions/knative/client/src/main/resources/resource-handler.vm
- extensions/service-catalog/client/src/main/resources/resource-handler.vm
- extensions/tekton/client/src/main/resources/resource-handler.vm
- extensions/volumesnapshot/client/src/main/resources/resource-handler.vm
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandler.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CascadingDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/KubernetesListOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/KubernetesListHandler.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/DeleteAndCreateHelper.java
- kubernetes-client/src/main/resources/resource-handler.vm
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PropagationPolicyTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/handlers/ProjectRequestHandler.java
- openshift-client/src/main/resources/resource-handler.vm
Fix #2885 
+ Add gracePeriodSeconds parameter in ResourceHandler#delete
+ Modified CascadingDeletable interface so that it includes
GracePeriodConfigurable and PropagationPolicyConfiguratble
> Fix #2855: .withPropagationPolicy and .withGracePeriod DSL methods can't be combined resource() deletion

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
Method removed in #2667 is still used by dependent projects (cc @ppatierno)
Restored the missing method and added a `@Depreaction` annotation yet to be discussed.
Relates to #2738
> fix: Restore method removed without prior notice

- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java
`Quantity.getAmountInBytes` should fail in case an invalid format is passed instead of ignoring it.
> Fail on invalid formats

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/SecretCrudTest.java
Fix #2802 
Right now when a resource with no metadata is created, instead of throwing KubernetesClientException, we're throwing a
NullPointerException here:
KubernetesAttributesExtractor.extractMetadataAttributes:L154
KubernetesMockServer should validate whether object sent in the request body contains metadata or not
Note that this doesn't solve your issue when you're using
KubernetesMockServer in expectations mode since you set what you'll be
getting as response to be received by yourself
> Fix #2802: Kubernetes Mock Server Crud Mode should reject invalid Kubernetes resources

- README.md
This changes the badges for maven central from shields.io to maven-badges.herokuapp.com, the issue with shields.io is that they aren't updated correctly (or the cache fails to refresh) when there is a new release showing old versions. Also, they are now in a table instead of a list.
> Change badges for the list of client modules

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/EventingAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/EventingAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1EventingAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1EventingAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1EventingAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1EventingAPIGroupExtensionAdapter.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/EventingAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1EventingAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1beta1EventingAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/MockOkhttpClientUtils.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1EventsTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1beta1EventsTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Fix #2837 
+ Add support for v1() and v1beta1() models for `events.k8s.io` APIGroup
> Fix #2837: Add Support for `events.k8s.io` APIGroup DSL

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
RawCustomResourceOperationsImpl should also consider the case of Core
APIGroup when apiGroup is null/empty. It should use /api instead of
standard /apis
This is related to https://github.com/fabric8io/kubernetes-client/issues/2929 . With this we should be able to use Raw API for now until we provide a new unstructured() DSL
> RawCustomResourceOperationsImpl should also work with standard resources

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudAttributesExtractorTest.java
Fix for issue https://github.com/fabric8io/kubernetes-client/issues/2921
> Fix #2921 adding generated metadata

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
Trying to use the `edit` of a CR I found a couple of issues:
- it throws `ClassCastException` if there are external json modules registered e.g.: https://github.com/andreaTP/fabric8-edit-as-patch/blob/master/src/main/scala/Main.scala#L59
- edit perform a `PUT` while it's supposed to be a `PATCH` as per: https://github.com/fabric8io/kubernetes-client/blob/8d0957cac72cc27083a53faa84a7e80a7470b8e1/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L37-L39
this PR address both issues.
I tested the final result with this demo project:
https://github.com/andreaTP/fabric8-edit-as-patch
run with: `sbt run`
I don't know how/where to add more exhaustive tests, I'm looking forward to guidance here 🙏
> Edit a CustomResource should result in a patch

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
See #2989 this addresses the creation of invalid yaml, when using subtypes.  This is happening in the Strimzi project due to https://github.com/strimzi/strimzi-kafka-operator/blob/ab9df1d231c08ddfd5c947f7beddf963b77e7fec/api/src/main/java/io/strimzi/api/kafka/model/storage/Storage.java#L21
> fix for #2989 disable the native type id feature for yaml

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
When the proxy properties are set (http.proxy, no.proxy...) and the master host should not go through the proxy, okhttp is still tunneling over the proxy, we should disable the proxy in case where the master url should not go through the proxy
it is working also when the proxy.url is not found
> Set no_proxy in the okhttp builder in case the proxy_url is null

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ReflectorWatcher.java
Fix for #2991 - event received logged at too high of a level.
> cleaning up the reflectorwatcher logging

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java
fixes https://github.com/fabric8io/kubernetes-client/issues/3027
According to kubernetes/kubernetes#90482, the firstTimestamp/lastTimestamp and eventTime fields are optional, so clients must tolerate events without those timestamps set.
> fix NPE when sorting events in KubernetesResourceUtil

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
> chore: make RawCustomResourceOperationsImpl watch methods to return Watch

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java
Support FIPS mode in kubernetes-client with BouncyCastleFipsProvider сonnected externally.
Solving the issue described in https://github.com/fabric8io/kubernetes-client/issues/2732
> Support FIPS mode in kubernetes-client with BouncyCastleFipsProvider

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Cache.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReflectUtils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/CacheTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/ReflectUtilsTest.java
Fix #2978 
Adds null check on cache object metadata.
> Fix NPE on initial requests while syncing

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Patchable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/PatchContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/PatchType.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/PatchTest.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PatchIT.java
- kubernetes-itests/src/test/resources/patch-it.yml
Fix #2701 #2645
Add support for patching Kubenetes resources like we do in kubectl :
```
kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}
kubectl patch node k8s-node-1 -p $'spec:\n unschedulable: true'
kubectl patch -f node.json -p '{"spec":{"unschedulable":true}}'
kubectl patch pod valid-pod -p
'{"spec":{"containers":[{"name":"kubernetes-serve-hostname","image":"new image"}]}}'
kubectl patch pod valid-pod --type='json' -p='[{"op": "replace", "path":
"/spec/containers/0/image", "value":"new image"}]'
```
User should now be able to patch like above mentioned scenarios using KubernetesClient like this:
```java
// Strategic Merge Patch
kubernetesClient.pods().inNamespace("ns1").withName("foo")
.patch("{\"metadata\":{\"annotations\":{\"bob\":\"martin\"}}}")
// Specify …
```
> Fix #2701: Add Support for partial Patch for Kubernetes resources with Json Merge, Strategic Merge and Json patch

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/CreateOrReplaceHelper.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CustomResourceInformerExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/PodExecEquivalent.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/PodWatchEquivalent.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/PortForwardEquivalent.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/WatchEventsListener.java
Here is a review of the catch of the InterruptedException and their logs. I have done more than looking to the core code of the client. These suggestions are up for debate, and thus can be reverted in this PR.
So, every log about an nominal InterruptedException is now in debug, with the message of the exception but not the stack trace.
Special cases on some catch that I found:
* `BaseOperation#createOrReplace`: there used to be a `printStackTrace`. I tried to improve it by a log and propagate the status of the interrupted thread. But considering the case here, maybe there is more to do.
* `CreateOrReplaceHelper#createOrReplaceItem`: same considerations
* `CHEATSHEET.md`: I have found these weird piece of catch without the `try` keyword. I took the liberty to juste remove it. Javac will …
> Fix #3015: Log InterruptedException in debug when it is a nominal terminating behavior

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformer.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ReflectorWatcher.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ControllerTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Adding a SharedInformer isRunning method, with some additional minor cleanups.  As best as I can determine if this returns true, the informer should still expect to receive events.  This does not address using the SharedInformerEventListener or some other mechanism to forward any possible abnormal termination exception to.
> Informer watch status

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
#3057 
The debug log is excessive when using deserialization, this will omit that.
> fix #3057 adding read only to fields that don't need set

- CHANGELOG.md
- extensions/tekton/model-triggers/src/main/java/io/fabric8/tekton/TektonTriggersResourceMappingProvider.java
We missed enhancing the TektonTriggersResourceMappingProvider during https://github.com/fabric8io/kubernetes-client/pull/2948 😇
> Add missing entry for Trigger CRD to TektonTriggersResourceMappingProvider

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/VersionInfo.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/VersionInfoTest.java
Fix #3047
NPE when getting version when there is no build date.
* Add null check for build date before trying to parse it.
> fix #3047: NPE when getting version when there is no build date

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ReflectorWatcher.java
further cleanups to the Informer onClose behavior
We don't need to call anything for the non-exceptional onClose.  It will only be triggered by the Reflector calling Watch.close.  Every other closing event will go through the exceptional onClose.  Of those calls we only want special handling for http_gone. - everything else we want to simply let watch framework keep retrying.
This supersedes the reflector changes from #3029
> Fix #3024 removing any onClose action

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
Fixes potential NPE when delete CR response is empty.
Delete operation response can be empty in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L1030
This lead to NPE when trying to read status object from response in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L1034
> fix: Potential NullPointerException on custom resource delete

- crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
Temporarily disable CRDGeneratorTest (#3102)
> test: Disable CRDGeneratorTest

- extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/TaskRunCancel.java
This is an example / documentation PR only. It attempts to provide an example of how to cancel a Tekton TaskRun to resolve the issues I faced in getting it to work in 
Fix https://github.com/fabric8io/kubernetes-client/issues/3084
- [ x] Chore (non-breaking change which doesn't affect codebase;
- [x ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
> Document CancelTaskRun example

- CHANGELOG.md
- extensions/knative/tests/src/test/java/io/fabric8/knative/test/crud/ServiceCrudTest.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudAttributesExtractorTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java
Addresses #3088 so that the mock server is aware of the status subresource (except for patch /status).
This also addresses several issues with replace:
- it's implemented as an update, rather than delete/add
- the uid is retained
I believe these changes will help resolve https://github.com/java-operator-sdk/java-operator-sdk/issues/396
This does not address create conflicts - I've left that commented out in this pr as there seem to be quite a few tests to correct.
Fix #3088
> adding status handling to the mock server

- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Fix #3036 
I wasn't able to reproduce it locally but I saw it again on [CI today](https://github.com/fabric8io/kubernetes-client/runs/2568190926?check_suite_focus=true)
I noticed that while comparing `lastResourceVersion` we had an additional 1 second wait timeout in other tests. Added 1 second wait time to lastResourceVersion in testAllNamespacedInformer() to sync just like done in [testNamespacedPodInformer()](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java#L139) and
[testInformerWithNamespaceAndNameConfigured()](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java#L182) …
> Chore #3036: Fix flaky lastResourceVersion failure in DefaultSharedIndexInformerTest

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptorTest.java
- kubernetes-client/src/test/resources/test-kubeconfig-tokeninterceptor
Token refreshes happen after a 401 and retries to call to the k8s API. On a local machine using AWS EKS, token generation is done via an Exec task and not an authprovider. The token refresher was only refreshing in case authprovider was not null thus was throwing a kubernetesclientexception after a small timeout (10-15 min to my memory) imposed by AWS.
This PR makes sure to refresh token via autoconfigure in any case..
Fixes #3097 
> Fixes #3097 : refresh token with autoconfigure even if authprovider is null

- kubernetes-server-mock/pom.xml
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/FallbackHasMetadata.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudAttributesExtractorTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java
fix for #3095 - it requires a few tweaks to check for the existing items.
It does highlight an issue with raw attribute extraction - I've commented out the relevant test for now, but you could take this a step further and try to make that extraction work.
cc @rohanKanojia 
> fix: #3095 adding detection of create conflicts

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java
There are a few file descriptor leaks in cert utils: Fix #3062
> wrap input stream used to load certs in a try so they're automatically closed

- CHANGELOG.md
- kubernetes-itests/src/test/java/io/fabric8/openshift/SelfSubjectAccessReviewIT.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/SubjectAccessReviewIT.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java
Fix #2529 
Right now all create only resources in `authorization.k8s.io` apiGroup
seem to be returning HTTP_OK/HTTP_CREATED even if there are no bearer
token headers set in request. Due to this, we were always skipping token
update since we only check for HTTP_UNAUTHORIZED/HTTP_FORBIDDEN response
codes.
Added an exception in OpenShiftOAuthInterceptor to always force token
update in case url contains Kubernetes/OpenShift authorization apiGroup
> Fix #2529: SelfSubjectAccessReview broken with OpenShiftClient

- crd-generator/api/src/main/java/io/fabric8/crd/generator/Resources.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/decorator/Decorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/decorator/NamedResourceDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/decorator/ResourceProvidingDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/CustomResourceHandler.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddCustomResourceDefinitionResourceDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddCustomResourceDefinitionVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddSchemaToCustomResourceDefinitionVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddStatusSubresourceDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddSubresourcesDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/CustomResourceDefinitionVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/SetServedVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/SetStorageVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/SortPrinterColumnsDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/CustomResourceHandler.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddAdditionPrinterColumnDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddCustomResourceDefinitionResourceDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddCustomResourceDefinitionVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddSchemaToCustomResourceDefinitionVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddStatusSubresourceDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddSubresourcesDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/CustomResourceDefinitionVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/EnsureSingleStorageVersionDecorator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/SortPrinterColumnsDecorator.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/ResourcesTest.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
- pom.xml
> Bump sundrio to 0.40.1

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudAttributesExtractorTest.java
Fix for #3135 - adding mock support for a json patch of status, and rejecting other patch types.
I could not find existing json merge or strategic merge logic in the existing dependencies.  It looks like jakarta.json-api provides a json merge patch utility - but it seems easier for now to just return an unsupported status.
> fix #3135 adding support for patchStatus and detection of patch type

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtensionTests.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/MockServerKubeconfigTest.java
- kubernetes-server-mock/src/test/resources/testkubeconfig
- openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServer.java
- openshift-server-mock/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtensionStaticTests.java
- openshift-server-mock/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtensionTests.java
Fix #3152 
Fix #3064
KubernetesMockServer is using [ConfigBuilder](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock/KubernetesMockServer.java#L77) which tries to autoconfigure
Config by reading it automatically from local kubeconfig. this results
in issues where some code might accidentally read token/context set in
KubernetesClient's config which is set by Config autoconfigure.
This PR explicitly sets token, contexts to null/empty so that mockServer
tests run independently of local Kubernetes config
> KubernetesMockServer should not read local `.kube/config`

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/PatchContext.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/WatchIT.java
Addressing the integration test timing issue seen in https://github.com/fabric8io/kubernetes-client/pull/3136#issuecomment-843243513 with a strategic merge patch.
@rohanKanojia it feels a little verbose to create a patch context of a given patch type - should there be utility methods for that?
> using a strategic merge to prevent a 422

- crd-generator/api/src/main/java/io/fabric8/crd/generator/CRDGenerator.java
This is meant to fix the issue with the malformed URI on windows.
The fix has not been verified manually, but usually this short of issues are handled better when you delegate to java itself.
> fix: Use File.toURI() to create the generated crd uri.

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/StatusUpdatable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CreateOrReplaceResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedCustomResourceApiTest.java
This fix deprecates updateStatus now that there are other operations.  It also consolidates more util calls, makes some of the messages more consistent, and uses the passed in resourceVersion first in a replace operation.
> fix #3149 #3127 - deprecate updateStatus(item) operation and use resourceVersion if available

- crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
This fixes an issue with when generating schema for items annotated with the `JsonProerty` annotation.
> fix: handling of JsonProperty when generating crds.

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterOperationsImpl.java
- kubernetes-itests/src/test/java/io/fabric8/openshift/VersionIT.java
- openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftClusterOperationsImpl.java
Fix #3189 
assert response code after getting response from apiServer rather than
depending upon fragile null check.
> Fix #3189: VersionInfo contains null data in OpenShift 4.x

- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PersistentVolumeClaimIT.java
A fix for intermittent test issue seen here https://github.com/fabric8io/kubernetes-client/pull/3164#issuecomment-850764495
> using strategic merge to prevent 422

- CHANGELOG.md
- README.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ExponentialBackoffIntervalCalculator.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
Fix #3087 
This PR introduces configurable retry with exponential backoff for HTTP operations.
As according to the [API conventions](https://github.com/fabric8io/kubernetes-client/issues/3087) when the HTTP status code is one of the followings:
- 500 StatusInternalServerError
- 503 StatusServiceUnavailable
- 504 StatusServerTimeout
Then the suggested client recovery behavior is "retry with exponential backoff".
Although in case of 504 it is "Increase the value of the timeout param and retry with exponential backoff" but in this PR I would only focus on the retries. That can be implemented in a follow up PR.
For the intention behind please check: https://github.com/fabric8io/kubernetes-client/issues/3087.
> Retry HTTP for status >= 500 (exponential backoff)

- CHANGELOG.md
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/PodSecurityPolicyReviewTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/PodSecurityPolicySelfSubjectReviewTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/PodSecurityPolicySubjectReviewTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftCreateOnlyResourceOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftCreateOnlyResourceNonNamespaceOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
+ Add DSL support for the following resources in  `security.openshift.io/v1` apiGroup:
- PodSecurityPolicyReview `openShiftClient.podSecurityPolicyReviews()`
- PodSecurityPolicySelfSubjectReview `openShiftClient.podSecurityPolicySelfSubjectReviews()`
- PodSecurityPolicySubjectReview `openShiftClient.podSecurityPolicySubjectReviews()`
Related to #2949
> Add missing resources in `security.openshift.io` apiGroup in OpenShiftClient DSL

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
Full context is in https://github.com/fabric8io/kubernetes-client/issues/3170
It's making a method public in order to modify http client properties such as `connectionPool`.
> allow overriding custom http client properties

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CreateOrReplaceable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Editable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Patchable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Replaceable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/StatusReplaceable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
Based upon the discussion on #3078 more javadocs seemed in order to help clarify usage and the possibility of items being modified.
> fix #3078: adding more javadocs around operations

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/CustomResourceDefinitionProcessor.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudAttributesExtractorTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java
- kubernetes-tests/src/test/resources/crontab-crd.yml
#3144 this adds broader crd awareness to the mock server - primarily for determining if status is a subresource.  If there is no crd, it's assumed that status is not a subresource.
There's also a minor change to not send events from patches that result in no changes to the resource.
> fix fabric8io#3144: making the crud mock logic more crd aware

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
Partially addresses #3076  by allowing the ObjectMetadata to be seen as buildable.
> fix #3076: updating the buildable annotation for customresource

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SharedInformerOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ApiVersionUtil.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContextTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/SharedInformerFactoryTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/ApiVersionUtilTest.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CustomResourceInformerExample.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/DynamicSharedIndexInformerExample.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Fix #3228 
Introduce a new method in SharedInformerFactory which will only accept
CustomResourceDefinitionContext, types would automatically be assumed
to be GenericKubernetesResource and GenericKubernetesResourceList.
Till now we were deciding whether a resource is namespaced or not
depending upon whether it implements Namespaced interface or not. But
having dynamic informers required change to consider `scope` field in
CustomResourceDefinitionContext as well, hence I introduced a new class
SharedInformerOperationsImpl which overrides `isResourceNamespaced()` so
that it can be configured from calling methods.
> Fix #3228: Add support for Dynamic informers for custom resources in KubernetesClient

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/SharedInformerFactoryTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Fix #2937
Fix #3235
+ Add a new method `getExistingSharedIndexInformers()` to
SharedInformerFactory which would return a list of entries containing
registered SharedIndexInformer and their respective OperationContext.
This is added to overcome limitation of old `getExistingSharedIndexInformer(Class<T> apiTypeClass)`
in case there are two informers registered with same type. Based on @hibnico 's suggestion https://github.com/fabric8io/kubernetes-client/issues/2937#issuecomment-815836081
> Fix #2937: Add `SharedInformerFactory#getExistingSharedIndexInformers()` to return list of registered informers

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/MetricOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NodeMetricOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodMetricOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/MetricsTest.java
Fix #3225 
Refactor NodeMetricOperationsImpl and PodMetricOperationsImpl to move
common logic to MetricOperationsImpl
> Fix #3225: Pod metric does not have corresponding label selector variant

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java
related to #3001, ignoring reconnect when closed should not be a warn
> reconnect warning is too high

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
- kubernetes-client/src/test/resources/test-kubeconfig-exec-win
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
Fix #3244 #3243 
This fixes data loss when using `PipedInputStream` to pump output from exec command. Since this user-provided resource was auto-closed on websocket connection close, client was unable to read contents of the buffer after last chunk was received. (#3243)
Handling of `PipedOutputStream` provided for `stdin` was changed in same fashion, although the impact there is not that big due to how the pair is implemented.
I've run the unit tests in my Windows environment and fixed any issues with tests I encountered there (none of them were related to pipes, rather OS quirks). (#3244)
> Fix for #3243, #3244 Prevent data loss when client provides pipes to exec

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Informable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Resource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/WatchListDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformer.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStore.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/SharedProcessor.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/SharedInformerFactoryTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/InformTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
A possible implementation for the informer mentioned in https://github.com/fabric8io/kubernetes-client/pull/3230#pullrequestreview-682321798
This implementation is just a simple wrapper over a Watch - no additional threads are consumed.
It is not a SharedIndexInformer because of the simplification that it is already started, which means that Indexers cannot be added.  Since I haven't needed to use Indexers I'm probably biasing this toward simplicity.
For generic functionality I've added a second commit to expand the existing RawCustomResourceOperationsImpl - it's a little cumbersome.  Narrowing to a more specific interface than the SharedInformer (run isn't needed, etc.) would help a little. The pro is that this doesn't require yet exposing the GenericKubernetesResource for #3233 - but as …
> Adding a dsl inform method

- CHANGELOG.md
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/V1alpha1APIGroupClient.java
- extensions/tekton/client/src/main/java/io/fabric8/tekton/client/dsl/V1alpha1APIGroupDSL.java
- extensions/tekton/generator-triggers/cmd/generate/generate.go
- extensions/tekton/model-triggers/src/main/java/io/fabric8/tekton/TektonTriggersResourceMappingProvider.java
- extensions/tekton/model-triggers/src/main/resources/schema/tekton-schema-triggers.json
This adds support for the ClusterInterceptor CR of Tekton Triggers
> [tekton] add support for ClusterInterceptor

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Cache.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/CacheTest.java
Addresses the npe seen by #3272 and adds missing synchronization when accessing index related fields.
> fix #3272: addressing npe and index logic in general

- CHANGELOG.md
- doc/CHEATSHEET.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ReflectorTest.java
Based upon trying to close out #3101 it seems better to refine the flag behavior so that it will be better as health checks.  So now if a non-http gone exception is provided we'll also report running = false.  And in the http gone case we won't report anything as wrong until something fails with the re-list/watch.
> fix #3101 making isWatching better reflect health

- extensions/certmanager/client/src/main/resources/resource-operation.vm
- extensions/certmanager/model-v1/pom.xml
- extensions/certmanager/model-v1/src/main/java/io/fabric8/certmanager/api/model/v1/CertificateRequestSpec.java
- extensions/certmanager/model-v1beta1/pom.xml
- extensions/certmanager/model-v1beta1/src/main/java/io/fabric8/certmanager/api/model/v1beta1/CertificateRequestSpec.java
- extensions/certmanager/tests/src/test/java/io/fabric8/certmanager/test/crud/V1CertificateRequestTest.java
+ I was trying out CertManager Extension for a blogpost. I realized none
of the resource's apiGroup/apiVersion were getting resolved due to a
possible typo in Operations class template
+ Added a custom class CertificateRequestSpec in order to override
generated class's request field. In go struct it's [`byte[]`](https://github.com/jetstack/cert-manager/blob/master/pkg/apis/certmanager/v1/types_certificaterequest.go#L97) but there
is no explicit byte type in reflect package. I'm not really sure how
to handle this in generator
> Fix wrong variable name in CertManager Operations class template + wrongly generated CertificateRequestSpec class

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/WatchListDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
Prevents the waitable methods from being called on a list context.
> fix #3278: should not allow wait at a list context

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
Fixing #3291: Retrying the HTTP operation in case of IOException too.
Tested with unit tests.
With the following logger config:
```
$ cat kubernetes-client/src/test/resources/simplelogger.properties
org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.log.io.fabric8.kubernetes.client.dsl.base = debug
```
the unit tests produced the following example output (partial output):
```
[main] DEBUG io.fabric8.kubernetes.client.dsl.base.OperationSupport - HTTP operation on url: https://172.17.0.2:8443/api/v1/pods/test-pod should be retried as the response code was 500, retrying after 2000 millis
[main] DEBUG io.fabric8.kubernetes.client.dsl.base.OperationSupport - HTTP operation on url: https://172.17.0.2:8443/api/v1/pods/test-pod should be retried after 4000 millis because of …
```
> Retry HTTP operation in case IOException too (exponential backoff)

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ScalableResource.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodControllerOperationContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingOperationContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/StatefulSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ReplicationControllerOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/ReplicaSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/PodOperationUtil.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/PodOperationUtilTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicaSetTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicationControllerTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/apps/DeploymentConfigOperationsImpl.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildOperationsImpl.java
Fix #2712 
Add support for providing `inContainer(String containerName)` method in controller operation classes to be able to specify containers while fetching logs from multi-container resources
> Fix #2712: Add Support for watching logs in multi-container Controllers

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/StatefulSetOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/BindingOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ComponentStatusOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ReplicationControllerOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/DeploymentOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/ReplicaSetOperationsImpl.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
Based upon #3284 this pr:
- uses handler logic to get a builder
- just using serialization for cloning
- clarifies the apiversion methods on baseoperation and operationsupport
> fix #3284: using handlers to get a builder

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/SharedProcessor.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/SharedProcessorTest.java
Prevents npes after the processor has been stopped.
> fix #3304: preventing npe race condition on stop

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/SharedInformerFactoryTest.java
Fix #3295 
We were assuming kind to be equal to class name while registering
CustomResource POJO to KubernetesDeserializer. This can be a wrong
assumption in case user decides to override kind via the `@Kind`
annotation.
Use `HasMetadata.getKind(apiTypeClass)` to resolve Kind rather than
assuming it to be class name.
> Fix #3295: Fix wrong kind getting registered in KubernetesDeserializer in SharedInformerFactory

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStore.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStoreTest.java
Changes actual additions and updates into regular, not sync events.
Fix #3318 
> fix #3318: add and actual updates on relist should not be sync events

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperationRequestBuilder.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManagerTest.java
fix for #3328 moves the informer type conversion logic up to the abstractwatchmanager to apply to watches as well.
> fix #3328: moving the watch type conversion logic up

- CHANGELOG.md
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/EventsIT.java
- kubernetes-model-generator/kubernetes-model-core/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/MicroTime.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/MicroTimeSerDes.java
- kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/kube-schema.json
- kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/validation-schema.json
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/EventTest.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/MicroTimeTest.java
- kubernetes-model-generator/kubernetes-model-core/src/test/resources/valid-event.json
- kubernetes-model-generator/kubernetes-model-events/src/main/resources/schema/validation-schema.json
Fix #3240 
Add Custom MicroTime with custom Serializer/Deserializers in order to
convert to a timestamp string 
> Fix #3240: MicroTime serialises incorrectly; Add custom serializer/deserializer for MicroTime class

- CHANGELOG.md
- openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/OpenShiftServer.java
fix: https configuration ignored for OpenShiftServer in CRUD mode
> fix: https configuration ignored for OpenShiftServer in CRUD mode

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1AdmissionRegistrationAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1AdmissionRegistrationAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1AdmissionRegistrationAPIGroupClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1AdmissionRegistrationAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1beta1PolicyAPIGroupDSL.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
All Cluster Scoped Kubernetes resources should use NonNamespacedOperation #3325
> modified Cluster Scoped Kubernetes resources to NonNamespacedOperation

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/EditReplacePatchDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ReplaceDeletable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLockTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/LeaseLockTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CreateOrReplaceResourceTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/image/ImageSignatureOperationsImpl.java
This PR allows using optimistic locking with deletion operations, like so:
```java
k8sClientResource.lockResourceVersion(resourceVersion).delete();
```
Fixes #3316
> Allow delete with optimistic lock

- README.md
- doc/FAQ.md
- doc/KubernetesClientWithIPv6Clusters.md
Add a section in documentation which informs users about excluding
OkHttp dependency from KubernetesClient and adding a direct OkHttp 4
dependency in order to resolve OkHttp 3.x bug
Related to https://github.com/fabric8io/kubernetes-client/issues/2632
> Document workaround for Kubernetes IPv6 Clusters using KubernetesClient

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandler.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Listable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Watchable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperationRequestBuilder.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/ListerWatcher.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ReflectorTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/InformTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicaSetTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicationControllerTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsImpl.java
This is to address #3349.  After trying out the changes accepting a unaryoperator with the options, it seemed simpler to just have the context override whatever the user passes in - which is the expected behavior with forcing the watch property to true on a watch.  With this change that is being done consistently for the labels, fields, and resourceVersion as well, and the javadocs have been updated appropriately.
For consistency this means if you try to do something like
```
.withResourceVersion("x").watch("y", watcher);
```
that y is ignored (since that watch method was already deprecated that shouldn't be an issue).  Alternatively an exception could be thrown when the values conflict - similar to what happens when withName and the item name conflict.
test, version modification, …
> fix #3349: adding consistency to the handling of option values

- CHANGELOG.md
- extensions/camel-k/generator-v1/cmd/generate/generate.go
- extensions/camel-k/generator-v1alpha1/cmd/generate/generate.go
- extensions/certmanager/generator-v1/cmd/generate/generate.go
- extensions/certmanager/generator-v1alpha2/cmd/generate/generate.go
- extensions/certmanager/generator-v1alpha3/cmd/generate/generate.go
- extensions/certmanager/generator-v1beta1/cmd/generate/generate.go
- extensions/chaosmesh/generator/cmd/generate/generate.go
- extensions/knative/generator/cmd/generate/generate.go
- extensions/service-catalog/generator/cmd/generate/generate.go
- extensions/tekton/generator-triggers/cmd/generate/generate.go
- extensions/tekton/generator-v1alpha1/cmd/generate/generate.go
- extensions/tekton/generator-v1beta1/cmd/generate/generate.go
- extensions/volumesnapshot/generator/cmd/generate/generate.go
- generator/pkg/schemagen/generate.go
Fix #3372 
Instead of assuming a hardcoded value "io.fabric8", allow this parameter
to be configured from the client which will be using the generator in
order to be more flexible in terms of generate model package naming.
> Fix #3372: Add generatedTypesPrefix option to Model Generator

- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
- kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceCrudTest.java
I added the metadata.name and metadata.namespace to the `AttributesSet` to allow the research of resources with `withField` method.
> feature: support of withField research

- CHANGELOG.md
- kubernetes-model-generator/kubernetes-model-apiextensions/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-apiextensions/src/generated/java/io/fabric8/kubernetes/api/model/KubeSchema.java
- kubernetes-model-generator/kubernetes-model-apiextensions/src/generated/java/io/fabric8/kubernetes/api/model/apiextensions/v1/ConversionRequest.java
- kubernetes-model-generator/kubernetes-model-apiextensions/src/generated/java/io/fabric8/kubernetes/api/model/apiextensions/v1/ConversionResponse.java
- kubernetes-model-generator/kubernetes-model-apiextensions/src/generated/java/io/fabric8/kubernetes/api/model/apiextensions/v1/ConversionReview.java
- kubernetes-model-generator/kubernetes-model-apiextensions/src/main/resources/schema/kube-schema.json
- kubernetes-model-generator/kubernetes-model-apiextensions/src/main/resources/schema/validation-schema.json
- kubernetes-model-generator/kubernetes-model-apiextensions/src/test/java/io/fabric8/kubernetes/api/model/apiextensions/v1/ConversionReviewTest.java
- kubernetes-model-generator/kubernetes-model-apiextensions/src/test/resources/valid-conversionreview.json
Fix #3336 : Added ConversionReview in API extensions model
> Fix #3336: Added ConversionReview in API extensions model

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceTest.java
Addressing #3378 so that calls to resources will use the existing operation if possible.
A change log isn't needed as the feature has not been released yet.
> fix #3378: returning the built-in operation for resources calls

- extensions/certmanager/examples/src/main/java/io/fabric8/certmanager/examples/ClientFactory.java
- extensions/knative/examples/src/main/java/io/fabric8/knative/api/examples/ClientFactory.java
- extensions/service-catalog/examples/src/main/java/io/fabric8/servicecatalog/examples/ClientFactory.java
- extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/ClientFactory.java
- kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/KubernetesVersionExample.java
Fix #3400
I have replaced the C-Style array declarations with Java-Style array declarations. 
Example:
```java
public static void main(String args[]) { 
```
has become:
```java
public static void main(String[] args) {
```
> Replaced C-Style array declarations with Java-Style

- CHANGELOG.md
- crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/JsonSchema.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/JsonSchema.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/joke/JokeRequestSpec.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
Add annotation based support for field descriptions in the CRD Generator using `JsonPropertyDescription`
The code already supports overriding property names using `JsonProperty`: use the same pattern for supporting descriptions.
- snipped output from the test Joke CRD
```
properties:
category:
description: category-description
type: string
```
Fixes #3287
> Fix #3287: Add support for field descriptions in CRD Generator

- CHANGELOG.md
- extensions/knative/tests/src/test/java/io/fabric8/knative/test/ResourceTest.java
- model-annotator/src/main/java/io/fabric8/kubernetes/ModelAnnotator.java
Partial fix for #3433. The end goal should be to use a single annotator for every generator module.
Relates to https://github.com/quarkusio/quarkus/issues/19950
cc: @Fabian-K 
> fix: Extension annotator doesn't generate XxxEditable classes

- CHANGELOG.md
- crd-generator/api/src/main/java/io/fabric8/crd/generator/CRDGenerator.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/utils/Types.java
Fix #3442
Builds on top of #3438 which would need to be merged first before merging this PR. 
> Make sure new CRDGenerator instances start with a clean generation context

- CHANGELOG.md
- crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
When looping through annotated fields/methods, the current code assumes a `String` type `value` attribute. This fails with a `ClassCastException` if any annotation uses a different type.
`JsonSchemaTest` fails with a
```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
```
error without the fix; passes with the fix.
Fixes #3450
> Fix #3450: Cast to String for specific annotations in CRD Generator

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Informable.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformer.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/SharedProcessor.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java
It can be useful to have a common event handler across several types.  Rather than requiring users to make that type specific, we can loosen the typing to accept any super class of the informer type.
> enhancement: allowing for more super class event handlers

- CHANGELOG.md
- README.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptorTest.java
- kubernetes-client/src/test/resources/test-kubeconfig-tokeninterceptor-oidc
Token refresh was unsuccessful after failed authentication when running incluster. The reason was that TokenRefreshInterceptor was expecting kubeconfig file to exists, even though in incluster mode it does not exist.
* Removes kubeconfig handling from TokenRefreshInterceptor and re-uses existing logic in autoconfig instead, which is prepared for both in/out-of-cluster use cases.
* Adds system property for previously hardcoded token path to facilitate unit testing.
* Adds copy of auth-provider from model to config to avoid config parsing in TokenRefreshInterceptor.
Fixes #3312
Signed-off-by: Tero Saarni <tero.saarni@est.tech>
> fix: TokenRefreshInterceptor throws when running incluster

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
> fix #3384: addressing that in can be null

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManagerTest.java
fix for #3484 informers are reporting the wrong isWatching value because onClose(exception) and onClose are both being called for a single closure.  The latter toggles the isWatching flag to false after the new watch has been established.
> fix #3484: ensuring that only one close method is called successfully

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/OperationInfo.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DefaultOperationInfo.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java
If the exception occurred from an HTTP request, use that information
to populate information about the target resource.
Fixes #3491
> feat: provide more details to KubernetesClientException

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Watcher.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
Fix  #2171 - Support BOOKMARK events
> fix: added BOOKMARK as a type in Watcher enum

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseKubernetesClient.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Client.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/ApiGroupResourceListsIT.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/EventsIT.java
- kubernetes-model-generator/kubernetes-model-core/cmd/generate/generate.go
- kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/APIResource.java
- kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/APIResourceList.java
- kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/KubeSchema.java
- kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/kube-schema.json
- kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/validation-schema.json
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/LoadAsTemplateTest.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
- openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
- openshift-client/src/main/java/io/fabric8/openshift/client/NamespacedOpenShiftExtensionAdapter.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftExtensionAdapter.java
- openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftAdapterSupport.java
- openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
- openshift-client/src/test/java/io/fabric8/openshift/client/OpenShiftConfigTest.java
- openshift-client/src/test/java/io/fabric8/openshift/client/dsl/AdaptTest.java
- openshift-client/src/test/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperationTest.java
- openshift-client/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServer.java
Supersedes #3405
Fixes #3294
Fixes #3303 
Fixes issue when compiling in JDK 8.
Sundrio has an issue when traversing the AST path for OkHttpClient (return type in previos Config#adaptClient).
The new commits on top of #3405 remove the adaptClient from the Config classes and places a similar method in the BaseClient class. The Config class is a little more anemic but at least OkHttpClient adaptation has been abstracted :shrug:. 
> Exposing apigroups and apiresources

- extensions/certmanager/mock/src/main/java/io/fabric8/certmanager/server/mock/CertManagerServer.java
- extensions/certmanager/model-v1/src/main/java/io/fabric8/certmanager/api/model/acme/v1/ACMEChallengeSolverHTTP01Ingress.java
I have fixed the lack of diamond operator in the instantiation of `additionalProperties` Map.
#3163
> Fixed the lack of diamond operator in the instantiation of "additionalProperties" Map

- CHANGELOG.md
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java
fix #3353: addressing extra quoting in quantity serialization by using text rather than toString.
> fix #3353: addressing extra quoting in quantity serialization

- .github/workflows/e2e-tests.yml
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/GenericResourceIT.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
test: fix: CRD IT uses its own resources
CustomResourceDefinitionIT should no longer fail as it's not using resources shared across other test suites
> test: fix: CRD IT uses its own resources

- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
Took another look at the template deserialization issue and thought it would be worth proposing this solution - there does not seem to be a great way to trap this error using other jackson mechanisms.
> fix #3460: support for deserializing templates with non-string params

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
Addresses #3561 and other okhttp usage that is not closed.
> fix #3561: ensuring closure of okhttp resources

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/serialization/BeanPropertyWriterDelegate.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/serialization/SettableBeanPropertyDelegate.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/serialization/UnmatchedFieldTypeModule.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationAdditionalPropertiesTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/serialization/SettableBeanPropertyDelegateTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/serialization/UnmatchedFieldTypeModuleTest.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
- kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
- kubernetes-tests/src/test/resources/template-with-multiple-objects.yml
This is a partial implementation of what's described in https://github.com/fabric8io/kubernetes-client/issues/3460#issuecomment-925729235
The new behavior is as follows (edited after https://github.com/fabric8io/kubernetes-client/pull/3574#issuecomment-963379719):
1. A resource is deserialized into a KubernetesResource instance.
2. The resource can contain unknown fields and/or fields with mismatched types (e.g. DesploymentSpec#replicas with a String instead of an Integer)
3. Properties matching any of the categories mentioned in the previous step can stored in the `additionalProperties` Map (if present)
a. By default, this unmatched types deserialization is enabled only for Templates
b. Behavior can be enabled for all types by `Serialization.UNMATCHED_FIELD_TYPE_MODULE.setRestrictToTempla …
> UnmatchedFieldTypeModule to deal with mismatched target types for fields

- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformerResyncTest.java
This commit is a simple refactoring to change the `ternary operator` to `Math.max`.
And also found an unused variable in `DefaultSharedIndexInformerResyncTest` and deleted it (operationContext).
* commits
* refactor(iss_3546): refactored to use `Math.max` instead of `tenary operator`
* refactor(iss_3546): removed unused code in test
> Refactor #3546:  Using Math.max ​​instead of the ternary operator

- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesServer.java
- openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/OpenShiftServer.java
fix: Add KubernetesMockServer accessor to JUnit4 KubernetesServer rules
Related to: https://github.com/quarkusio/quarkus/pull/21362
> fix: Add KubernetesMockServer accessor to JUnit4 KubernetesServer rules

- generator/pkg/schemagen/generate.go
- generator/pkg/schemagen/json.go
- kubernetes-model-generator/kubernetes-model-jsonschema2pojo/src/main/java/io/fabric8/kubernetes/jsonschema2pojo/Fabric8ObjectRule.java
- kubernetes-model-generator/kubernetes-model-jsonschema2pojo/src/main/java/io/fabric8/kubernetes/jsonschema2pojo/Fabric8RuleFactory.java
- model-annotator/src/main/java/io/fabric8/kubernetes/ModelAnnotator.java
Given the Golang model:
Go type `Tracing_CustomTag` that uses a field `Type` which is an interface `isTracing_CustomTag_Type`:
```go
type Tracing_CustomTag struct {
Type                 isTracing_CustomTag_Type `protobuf_oneof:"type"`
}
```
Where the interface is defined in:
```go
type isTracing_CustomTag_Type interface {
isTracing_CustomTag_Type()
MarshalTo([]byte) (int, error)
Size() int
}
```
The implementations of this interface are defined in:
```go
type Tracing_CustomTag_Literal struct {
Literal *Tracing_Literal `protobuf:"bytes,1,opt,name=literal,proto3,oneof" json:"literal,omitempty"`
}
type Tracing_CustomTag_Environment struct {
Environment *Tracing_Environment `protobuf:"bytes,2,opt,name=environment,proto3,oneof" json:"environment,omitempty"`
}
type Tracing_CustomTag_Header …
```
> Support auto generation of interfaces by providing implementations

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Handlers.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandlerImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/KubernetesListOperationsImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/GenericResourceIT.java
For #3555 this wires in the generic builder, which is used implicitly for all client.load operations and resource inNamespace.
Fix #3555
> fix #3555 using the new builder for generic resources

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
- kubernetes-client/src/test/resources/test-ec-kubeconfig
Currently when Config object is created using `Config.fromKubeConfig` and loading from a YAML string, the keyAlgorithm doesn't get updated it defaults to RSA and hence the issue #3535 , this PR seems to fix this.
> Fix Issue #3535: Not identifying ECDSA client key

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
Fix #3598 - the dependent future (after apply) was being canceled - which did not cause the upstream future to cancel and therefore cleanup the watch resources.
> fix #3598: the wrong future was being cancelled, which did not cleanup

- generator/pkg/schemagen/generate.go
- generator/pkg/schemagen/json.go
Given the Golang model:
Golang type `PeerAuthentication_MutualTLS` that uses a const:
```go
type PeerAuthentication_MutualTLS_Mode int32
type PeerAuthentication_MutualTLS struct {
// Defines the mTLS mode used for peer authentication.
Mode                 PeerAuthentication_MutualTLS_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=istio.security.v1beta1.PeerAuthentication_MutualTLS_Mode" json:"mode,omitempty"`
}
```
Where the const is:
```go
type PeerAuthentication_MutualTLS_Mode int32
const (
// Inherit from parent, if has one. Otherwise treated as PERMISSIVE.
PeerAuthentication_MutualTLS_UNSET PeerAuthentication_MutualTLS_Mode = 0
// Connection is not tunneled.
PeerAuthentication_MutualTLS_DISABLE PeerAuthentication_MutualTLS_Mode = 1
// Connection can be either plaintext or mTLS …
```
> Support enums in generator

- generator/pkg/schemagen/generate.go
- generator/pkg/schemagen/json.go
- kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/JsonUnwrappedDeserializer.java
- kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/UnwrappedTypeResolverBuilder.java
- kubernetes-model-generator/kubernetes-model-common/src/test/java/io/fabric8/kubernetes/model/jackson/JsonUnwrappedDeserializerTest.java
- kubernetes-model-generator/kubernetes-model-jsonschema2pojo/src/main/java/io/fabric8/kubernetes/jsonschema2pojo/Fabric8ObjectRule.java
- model-annotator/src/main/java/io/fabric8/kubernetes/ModelAnnotator.java
As part of https://github.com/fabric8io/kubernetes-client/pull/3594, the go generator will generate the interfaces and their implementations. Example:
Go type `Tracing_CustomTag` that uses a field `Type` which is an interface `isTracing_CustomTag_Type`:
```go
type Tracing_CustomTag struct {
Type                 isTracing_CustomTag_Type `protobuf_oneof:"type"`
}
```
Where the interface is defined in:
```go
type isTracing_CustomTag_Type interface {
isTracing_CustomTag_Type()
MarshalTo([]byte) (int, error)
Size() int
}
```
The implementations of this interface are defined in:
```go
type Tracing_CustomTag_Literal struct {
Literal *Tracing_Literal `protobuf:"bytes,1,opt,name=literal,proto3,oneof" json:"literal,omitempty"`
}
type Tracing_CustomTag_Environment struct {
Environment …
```
> Fix deserialization of interfaces in the generated model

- pom.xml
Volcano extension have been introduced In https://github.com/fabric8io/kubernetes-client/pull/3580 , but didn't add dependcy to kubernetes-client to root pom.
It's used to align the version of volcano extension dependency with that of the kubernetes client
So, we should add the Volcano dependency like other extensions:
https://github.com/fabric8io/kubernetes-client/blob/de4468047e844ab4b5879bccf7be59ee6dd7ebfe/pom.xml#L372-L432
Closes: https://github.com/fabric8io/kubernetes-client/issues/3610
> Fix: Add volcano dep into root pom

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/WatchIT.java
Fix for #3609 - if a websocket message processing thread is held long enough, a scheduled thread will initiate failure / reconnect while it's still being held - possibly leading to unexpected concurrent processing.
> fix #3609 addressing concurrency with long running Watcher methods

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/ResourceDefinitionContext.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContextTest.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/ResourceDefinitionContextTest.java
fix #3620: throw a meaningful exception if no kind/plural, and default plural based upon kind.
It looks like the code is tolerant to the other fields being missing - including group.
> fix #3620: throw a meaningful exception if no kind/plural, default plural

- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/GenericKubernetesResource.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/GenericKubernetesResourceTest.java
- kubernetes-model-generator/kubernetes-model-core/src/test/resources/generic-kubernetes-resource/complex-structure-resource.json
Allow the easy retrieval of field values from the additionalProperties Map.
The purpose of this method is to simplify the task when working with GenericKubernetesResources. With the proposed `GenericKubernetesResource#get` method, the following statements can be simplified:
```java
// before
int field = (Integer)gkr.getAdditionalProperties().get("field");
// after
int field = gkr.get("field");
// before
String value = ((Map)gkr.getAdditionalProperties().get("field")).get("nested").toString();
// after
String value = gkr.get("field", "nested");
// or
String value = gkr.get("field.nested");
// before
String value = ((Map)((List)((Map)gkr.getAdditionalProperties().get("field")).get("nested")).get(1)).get("inArray").toString();
// after
String value = gkr.get("field", "nested[1]", "inArray"); …
```
> feat: Get method for GenericKubernetesResource

- CHANGELOG.md
- kubernetes-model-generator/kubernetes-model-metrics/pom.xml
- kubernetes-model-generator/kubernetes-model-metrics/src/generated/java/io/fabric8/kubernetes/api/model/metrics/v1beta1/NodeMetrics.java
- kubernetes-model-generator/kubernetes-model-metrics/src/main/resources/schema/kube-schema.json
- kubernetes-model-generator/kubernetes-model-metrics/src/main/resources/schema/validation-schema.json
- kubernetes-model-generator/kubernetes-model-metrics/src/test/java/io/fabric8/kubernetes/api/model/metrics/v1beta1/NodeMetricsTest.java
- kubernetes-model-generator/kubernetes-model-metrics/src/test/resources/valid-nodemetric.json
- kubernetes-model-generator/pkg/schemagen/generate.go
Fix #3662 
NodeMetrics should not implement Namespaced interface
> Fix #3662: NodeMetrics should be marked as Cluster Scoped resource

- CHANGELOG.md
- kubernetes-client/pom.xml
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ApiVersionUtil.java
- kubernetes-itests/src/test/java/io/fabric8/commons/ClusterEntity.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/APIServiceIT.java
- kubernetes-itests/src/test/java/io/fabric8/kubernetes/PluralizeIT.java
- kubernetes-itests/src/test/resources/apiservice-it.yml
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/Pluralize.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/PluralizeTest.java
- kubernetes-model-generator/pom.xml
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NodeMetricsTest.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodMetricsTest.java
fix #3639: NodeMetrics and PodMetrics can have informers
fix #3668: APIServiceIT doesn't manipulate the API server directly (no write operations)
- Related to: #3589
Added E2E test to make sure that Pluralize works on all cluster resources (at least on the cluster where the test is performed)
- Added integration test for top()/inform() on PodMetrics and NodeMetrics resources
@shawkins please check the following snippet:
```java
testCases = new ArrayList<>(new OperationSupport(client.getHttpClient(), client.getConfiguration())
.restCall(APIResourceList.class, "api/v1").getResources());
```
I didn't find a better way to list these (core) resources.
> fix: NodeMetrics and PodMetrics can have informers

- crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
fix #3686 
`JsonIgnore` should be correctly handled by the CRD generator.
> Ignore fields annotated with JsonIgnore during CRD generation

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpWebSocketImpl.java
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
Supersedes closes #3559
A replacement for #3559 post okhttp refactoring.  There were a couple of refinements to make sure that timeout exceptions bubble up as expected.  With this change the connect and websocket (which defaults to the smallest amount of time) timeouts are enforced during waitUntilReady.
> refining #3559 - allows the connect and websocket timeouts to apply to watches instead of hardcoded timeout

- crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/JsonSchema.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/JsonSchema.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJson.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/json/ContainingJsonSpec.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
> Handle JsonNode fields by adding x-kubernetes-preserve-unknown-fields

- .github/workflows/build.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/gobuild.yml
- .github/workflows/javadocs.yml
- .github/workflows/license.yml
- .github/workflows/sonar.yml
- .github/workflows/windows-build.yml
I noticed that the CI is piling up a lot of running Actions, this should reduce the pressure and overall improve the performance.
Ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
> [chore] Use concurrency limits to reduce the queue on GH Action

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientBuilderImpl.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientFactoryTest.java
Fix #3697 
Fix #3699 
To address #3697 the previous interceptor response needs explicitly closed before issuing the next call.  This was handled by each interceptor previously, but due to the refactoring it needs to be elevated to the adapter.
> fix #3697: closing the initial interceptor response

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/Pluralize.java
- kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/PluralizeTest.java
- kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/HasMetadataTest.java
> fix: properly return full resource name for resources with empty group

- CHANGELOG.md
- pom.xml
Fix #3588 
Add missing modules to `<dependencyManagement>` in kubernetes client
parent pom
> Chore #3588: `openshift-server-mock` not listed in dependencyManagement in main pom

- CHANGELOG.md
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
- kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesResponseComposer.java
- kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/MetadataCrudTest.java
Adding basic resourceVersion handling for #3255 - does not add list/watch querying based upon resourceVersion..
fix #3255
> fix #3255 adding basic resourceVersion handling

- crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/json/Foo.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
This builds on top of #3684 I'll rebase on master as soon as the other gets merged.
Fix #3683
In presence of a class containing a "catch everything" field annotated with `JsonAnyGetter` or `JsonAnySetter`, we should produce `x-kubernetes-preserve-unknown-fields` as well.
> Preserve unknown fields in presence of JsonAnyGetter or JsonAnySetter

- crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
- crd-generator/api/src/main/java/io/fabric8/crd/generator/annotation/SchemaFrom.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/Extraction.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/ExtractionSpec.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/Foo.java
- crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/FooExtractor.java
- crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
Kind of fix: #3651 
This is a big hammer to let people "swap" a class instantiation for CRD generation purposes only.
Using this trick should be possible to workaround missing features and possible issues with the generator.
cc. @metacosm this is a possible technical implementation for your proposal.
> Introduce SchemaFrom annotation as escape hatch

- CHANGELOG.md
- kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
- kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationSingleDocumentUnmarshalTest.java
- kubernetes-client/src/test/resources/serialization/document-with-leading-and-trailing-document-delimiter.yml
- kubernetes-client/src/test/resources/serialization/document-with-leading-document-delimiter.yml
- kubernetes-client/src/test/resources/serialization/document-with-no-document-delimiter.yml
- kubernetes-client/src/test/resources/serialization/document-with-trailing-document-delimiter.yml
Fix #3648 
Serialization.unmarshal doesn't handle the case when YAML contains only
single document but yet contains a leading or trailing document
delimiter(`---`).
Trim YAML document delimiters in case of single documents
> Fix #3648: `Serialization.unmarshal` fails to deserialize YAML with single document in presence of document delimiter(`---`)
