CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java
Fix #3568
Pod file upload seems be be creating invalid exec command for upload if
the file is directly in root path e.g. `/cp.log`. We create parent
directory of file by creating a substring based on last index of `/`.
This returns an empty string for a string like `/cp.log`.
Assume directory path to be `/` when directory is returned as empty string.
=> Fix #3568: Pod upload file fails if file is directly in root path

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Uploadable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java
Fix #3721
Refactor PodUpload.upload implementation to expose a method which will
receive InputStream which can be reused by newly added
upload(InputStream) method
=> Fix #3721: Add support for uploading file via InputStream

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Informable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/ListerWatcher.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStore.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/SyncableStore.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStoreTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ReflectorTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformerResyncTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/DefaultSharedIndexInformerIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/InformTest.java
Related to #3587 #3616 - adds limit / batch fetching support to informers.  This can cut down on the size of the responses from the server and eventually the memory footprint of an informer.  To support the latter this will not fall back to fetching the entire list like the go client - this may need some refinement as currently it will just keep retrying.
If the limit is not specified, the default is to fetch everything in a single list.
A behavioral difference introduced here is that the affect of a relist is no longer atomic on the cache - rather each item in the relist will perform a cache update and create an event as it is seen.  Since the cache is still eventually consistent either way, I think this change is not a concern.
The javadocs call out a performance warning - it seems that …
=> fix #3587: adding inform support for limit/batch fetching

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/example/basic/BasicSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
=> A Java Long should generate a field of type integer in the CRD

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CreateOrReplaceable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Patchable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Replaceable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollableScalableResourceOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/CreateOrReplaceHelper.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/CreateOrReplaceHelperTest.java, kubernetes-itests/src/test/java/io/fabric8/openshift/ServiceToURLIT.java, kubernetes-itests/src/test/resources/test-crd.yml, kubernetes-itests/src/test/resources/test-ingress-extensions.yml, kubernetes-itests/src/test/resources/test-ingress.yml, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ConfigMapCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CreateOrReplaceResourceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V2beta1HorizontalPodAutoscalerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V2beta2HorizontalPodAutoscalerTest.java, kubernetes-tests/src/test/resources/test-resourcequota-deployment.yml, kubernetes-tests/src/test/resources/test-v2beta1-horizontalpodautoscaler.yml, kubernetes-tests/src/test/resources/test-v2beta2-horizontalpodautoscaler.yml, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/core/NetworkAttachmentDefinitionOperationsImpl.java
Guards against the basic operations from modifying passed in resources.
I couldn't see any other places besides the JobOperationsImpl where we making similar modifications.
=> fix #3756 prevent modifications by standard operations to user objects

CHANGELOG.md, extensions/camel-k/client/pom.xml, extensions/camel-k/model-v1/pom.xml, extensions/camel-k/model-v1alpha1/pom.xml, extensions/certmanager/client/pom.xml, extensions/certmanager/model-v1/pom.xml, extensions/certmanager/model-v1alpha2/pom.xml, extensions/certmanager/model-v1alpha3/pom.xml, extensions/certmanager/model-v1beta1/pom.xml, extensions/chaosmesh/client/pom.xml, extensions/chaosmesh/model/pom.xml, extensions/istio/client/pom.xml, extensions/istio/model-v1alpha3/pom.xml, extensions/istio/model-v1beta1/pom.xml, extensions/knative/client/pom.xml, extensions/knative/model/pom.xml, extensions/pom.xml, extensions/service-catalog/client/pom.xml, extensions/service-catalog/model/pom.xml, extensions/tekton/client/pom.xml, extensions/tekton/model-triggers/pom.xml, extensions/tekton/model-v1alpha1/pom.xml, extensions/tekton/model-v1beta1/pom.xml, extensions/verticalpodautoscaler/client/pom.xml, extensions/verticalpodautoscaler/model-v1/pom.xml, extensions/volcano/client/pom.xml, extensions/volcano/model-v1beta1/pom.xml, extensions/volumesnapshot/client/pom.xml, extensions/volumesnapshot/model/pom.xml, pom.xml
Fix #3761
Unlike `kubernetes-client`/`openshift-client` modules whose jars are
generated via maven jar plugin; Extension jars seem to be generated via
maven bundle plugin. Add an entry for `jandex.idx` file to extension
parent pom which would be included by client and model modules'
`Include-Resource` properties.
=> fix(extensions): Extension Jars don't contain `META-INF/jandex.idx` file (#3761)

kubernetes-itests/pom.xml, pom.xml
This PR removes the redundant arquillian deps in the <profile> section of the ids `itests-kubernetes` and `itests-openshift` and move the arquillian dependency to <dependency-management> section
Fix #3759 
What types of changes does your code introduce? Put an `x` in all the boxes that apply
=> Move the Arquillian dep to <dependency management> section

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java
Fix #3671
Add validation for case when no port is provided in proxy URL. Now we
would throw IllegalArgumentException in case resolved port is less than
zero (It's resolved to `-1` by `java.net.URL` class when no port is
being provided)
=> fix(kubernetes-client) : HTTP(s) Proxy Port is not defaulted or validated (#3671)

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
This is a proposal to fix the specific issue reproduced in #3785 
Instead of relying on the `KubernetesDeserializer` fallback mechanism here we are trying to deserialize the `WatchEvent`s using the specific deserializer for the type.
cc. @shawkins
=> Deserialize WatchEvents using the specific object type

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
The YAML serializer is mainly used in order to parse the kubernetes config. 
This change should not have any functional effect whatsoever, but it paves the way for what I have in mind as a follow-up, which is to provide a public method that allows for clearing out the YAMLMapper (the reasoning being that this is a very heavy object that most likely is only used when the client is first booted).
=> Limit usage of YAML Serializer

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/NonNamespaceOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Resource.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PatchIT.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/TypedCustomResourceIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java
Fix #3772
Remove reference to `WritableOperation<T>` interface from
NonNamespaceOperation as it exposes `edit()`, `patch()` and other
mutating operations.
=> fix (kubernetes-client) : `edit()`, `patch()` and other mutating operations shouldn't be allowed in NonNamespaceOperation (#3772)

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/serialization/BeanPropertyWriterDelegate.java
When performing a small profiling of a sample Operator SDK application,
I noticed that BeanPropertyWriterDelegate was leading to a lot of
allocations due to the use of lambdas.
Lambdas are great, but can lead to performance issues when used on the
hot path of the code, which this class seems to be.
Furthermore, the change does not reduce the readability of the code
=> Apply minor optimization for to decrease allocations

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/NonNamespaceOperation.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/TypedCustomResourceIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java
This was introduced by mistake in Dry Run implementation as part of
WritableOperation and was subsequently removed in
https://github.com/fabric8io/kubernetes-client/pull/3798
But it makes sense for replace operation to work without name. It can be
inferred from the passed object. Read this discussion for more details https://github.com/fabric8io/kubernetes-client/pull/3798#issuecomment-1029958757
=> fix (kubernetes-client) : reintroduce Replaceable interface in NonNamespaceOperation

kubernetes-client/pom.xml, kubernetes-tests/pom.xml
This PR replaces `org.bouncycastle:bcprov-ext-jdk15on` to `org.bouncycastle:bcprov-jdk15on`. Both of them are similar, `ext-jdk15on` contains NTRU algorithms which I think is not being used in the code after testing. 
=> Change bouncycastle dependency from `org.bouncycastle:bcprov-ext-jdk15on` to `org.bouncycastle:bcprov-jdk15on`

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExecListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListener.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListenerTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListenerTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
Builds on the change for upload to move the exit code handling into the base exec.
After this change if ExecWatch were to expose a way to directly send, or a way to notify when the inputstream is exhausted, it is possible to eliminate the pod upload websocket listener.
=> fix #3813: adding onExit to execwatch

java-generator/core/src/main/java/io/fabric8/java/generator/CRGeneratorRunner.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testCrontabCrd.approved.txt, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testJokeCrd.approved.txt, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testKeycloakCrd.approved.txt
Support "served" and "storage" version of the generated Java CR.
=> [java-gen] Support storage and served in generated CR version

kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
Under the covers there is an exception: 
```io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.39.30:8443/api/v1/namespaces/itest-6ebb12ba/pods/pod2/eviction. Message: Cannot evict pod as it would violate the pod's disruption budget.. Received status: Status(apiVersion=v1, code=429, details=StatusDetails(causes=[StatusCause(field=null, message=The disruption budget test-pdb is still being processed by the server., reason=DisruptionBudget, additionalProperties={})], group=null, kind=null, name=null, retryAfterSeconds=10, uid=null, additionalProperties={}), kind=Status, message=Cannot evict pod as it would violate the pod's disruption budget., metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, …
```
=> fix #3840: adding a wait for eviction

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java, platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/TestBase.java
- Prevent NPE when config does not exist
=> [#3700] Change ManagedKubernetesClient OSGi ConfigurationPolicy to REQUIRE

CHANGELOG.md, extensions/volcano/examples/src/main/java/io/fabric8/volcano/examples/QueueCreate.java, extensions/volcano/examples/src/main/java/io/fabric8/volcano/examples/Utils.java, extensions/volcano/examples/src/main/java/io/fabric8/volcano/examples/v1beta1/QueueCreate.java, extensions/volcano/generator-v1beta1/cmd/generate/generate.go, extensions/volcano/generator-v1beta1/go.mod, extensions/volcano/model-v1beta1/src/main/resources/schema/volcano-schema.json, extensions/volcano/tests/src/test/java/io/fabric8/volcano/test/crud/V1Beta1VolcanoTest.java, extensions/volcano/tests/src/test/java/io/fabric8/volcano/test/crud/VolcanoTest.java, extensions/volcano/tests/src/test/java/io/fabric8/volcano/test/request/QueueTest.java
This patch fix the volcano queue type, it should be `Cluster`.
- Fix Queue type: change `schemagen.Namespaced` to `schemagen.Cluster`
- Add example for queue create, and it works as integrations test in real K8S.
- Adapt volcano queue test
Closes: https://github.com/fabric8io/kubernetes-client/issues/3848
=> fix #3848: Add queue support (cluster level) for Volcano extension

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/CertUtilsTest.java
Fix #3582 
Fix #3738 
SSL truststore can be loaded in FIPS environments
=> fix: SSL truststore can be loaded in FIPS environments

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
Adds a missing throws to usages of launderThrowable
=> fix #3818: adding missing throws to launderThrowable

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JArray.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JMap.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitive.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testKeycloakCrd.approved.txt, java-generator/it/src/it/cert-manager/expected/AuthSpec.java
This PR aims at improving the Java (from CRD) generator feature in its baseline implementation, by adding support for generating basic Javadoc comments for a POJO fields as part of the model, by using an YAML element `description` as the source of information.
As discussed in the [issue for the baseline implementation](https://github.com/fabric8io/kubernetes-client/issues/3642), it seems reasonable to track this enhancement separately, hence this is a draft and a review by @andreaTP as the original contributor of the baseline implementation would help in evaluating whether it could be accepted.
Fixes #3762
=> [java-gen] Adding support for basic Javadoc comments generation

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/annotation/SchemaSwap.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/utils/Types.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/ExtractionSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/IncorrectExtraction.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/IncorrectExtraction2.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/ResourcesTest.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java, doc/CRD-generator.md
This is a ~~Draft~~ implementation of `SchemaSwap`.
The annotation serves to enable the use-case where you want to generate a valid CRD from a model that you don't own.
e.g.:
The model comes as a dependency on the classpath and you cannot add `SchemaFrom` annotations to it.
Issue found in (cc. @vmuzikar):
https://github.com/keycloak/keycloak/pull/9759
I'm opening this PR as Draft to start the conversation regarding pros/cons and alternatives to this approach.
PRO:
- it enables to inject the equivalent of `SchemaFrom` annotations in a hierarchy without punctual changes
- the type checker is mostly preventing big issues
- ~~[not implemented yet] we can implement a~~ guard to throw an exception in case of fields/classes not found
~~CONS:~~
- ~~the CRD api module cannot be easily executed …
=> [crd-generator] Implement SchemaSwap

CHANGELOG.md, doc/CHEATSHEET.md, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
Updating the docs and an example to not reference registerCustomKind
=> fix #1285 removing registerCustomKind and updating to v1

CHANGELOG.md, kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
The CrudDispatcher map is a synchronized map. The implementation of the standard map operations are already internally synchronized, but it explicitly states that iterating the map in any way should be synchronized. Occasionally in a multi-threaded scenario access to the map results in a ConcurrentModificationException because of a lack of synchronization.
=> Fixes #3880: Synchronize access to map in KubernetesCrudDispatcher

CHANGELOG.md, doc/MIGRATION-v6.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java, kubernetes-itests/src/test/resources/test-podsecuritypolicy.yml, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/internal/KubernetesDeserializerTest.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/core/TemplateOperationsImpl.java
This updates the search strategy used by the KubernetesDeserializer - to not use classes with conflicting apiGroups.  
~~It goes further to not use classes with conflicting versions - but that leads to several test failures.  That was a concern of @andreaTP when dealing with multiple versions - if they are custom resources which do not implement additionalProperties, then it could be a lossful conversion (if ignoring unmatched fields) or an exception when fields don't match.~~  
Sorry I wasn't thinking straight, the internal types are only going to be from what's in the PACKAGES, so any laxity made there on version matching won't affect custom types.
=> fix #3859: refinements to how a deserialization class is chosen

doc/MIGRATION-v6.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ContainerResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Copiable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/CopyOrReadable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Deletable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Evictable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Loggable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/MultiDeleteable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/PodResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Uploadable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ResourceAdapter.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/StatefulSetOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ReplicationControllerOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/DeploymentOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/ReplicaSetOperationsImpl.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodEvictionIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/apps/DeploymentConfigOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildOperationsImpl.java
To eliminate the possibility of null, Boolean is being replaced by boolean where appropriate in the api.  Also throwing a 404 from evict to differentiate from eviction failure.
=> fix #3853: replacing Boolean with boolean and throwing a 404 from evict

.github/workflows/e2e-tests.yml
ci: E2E cache only persisted/retrieved for current run
=> ci: E2E cache only persisted/retrieved for current run

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testKeycloakCrd.approved.txt, java-generator/it/src/it/cert-manager/expected/Auth.expected
Support for `JsonPropertyDescription` (to mirror the CRD generator).
=> [java-gen] Support JsonPropertyDescription

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
The generation field in the Object Metadata should be an Integer (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#objectmeta-v1-meta).
I'm using the Mock to test the api from https://github.com/kubernetes-client/c and it fails to parse the generation field because it is actually a string.
=> mock: generation is an Integer field

httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java
In JdkHttpClientImpl, webSocketBuilder is copied before going through interceptors. But the original webSocketBuilder is used to make the request to the API server.
This PR changes this by using the copied webSocketBuilder for the request.
=> Fix #3950: make sure modifications on jdk websocket done by interceptors are not lost

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpWebSocketImpl.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocket.java
Fix #3957 
In `PodOperationsImpl` class the `buildAsync` method is called with `ExecWebSocketListener`.
The `ExecWebSocketListener` is opening `outputPipe` and `errorPipe` in `onOpen`.
If the `future` is completed before the `outputPipe` and `errorPipe` are open, then the consumer can read from the pipes before  they are open. 
The pipes should be open first and then the future should be marked as complete. 
=> fix #3957: Lister `onOpen` should be called before marking the connection open

README.md
As @shawkins pointed out, the name of the env var in the docs is incorrect, [ref](https://github.com/fabric8io/kubernetes-client/issues/3996#issuecomment-1077617342)
=> [chore] Fix Backwards Compatibility Interceptor environment variable name in doc

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestHttpHeaders.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestHttpRequest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestHttpResponse.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupportTest.java
This PR resolves #3892 
- Refactor `assertResponseCode` method to return early
- Reorder the modifiers on `RequestMetadata.EMPTY` to follow the Java Language Specification
=> Refactor #3892: trivial refactoring on OperationSupport

CHANGELOG.md, doc/MIGRATION-v6.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Informable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/SharedIndexInformer.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformer.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/cache/Indexer.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/cache/Store.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/informers/cache/MapIndexer.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorStore.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/SharedProcessor.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/SyncableStore.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorStoreTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/InformTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
This addresses a host of informer related requests:
Fix #3969 - stop emitting sync events on relist - it was simplest to make this change to support #3968
Fix #3968 - added SharedInformer.initialState to set
Also took the parts of #3943 that were most general purpose, such as being able to add/remove indexers at any time, along with deprecating Informable.withIndexers
=> Several informer related changes

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JArray.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JMap.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitive.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testCrontabCrd.approved.txt, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testJokeCrd.approved.txt, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testKeycloakCrd.approved.txt, java-generator/it/src/it/cert-manager/expected/Auth.expected
This PR is proposing changes which are required in order to provide support for nullable/non-nullable fields generation in the Java model.
Fixes #3975 
=> [java-gen] Adding support for nullable fields generation

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/annotation/SchemaSwap.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/utils/Types.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/ExtractionSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/IncorrectExtraction.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/IncorrectExtraction2.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/ResourcesTest.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java, doc/CRD-generator.md, pom.xml
Backporting SchemaSwap (#3797) to the 5.12 branch.
cc. @manusa 
=> Backport SchemaSwap

kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/IntOrString.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/IntOrStringTest.java
fix: IntOrString supports null values
- For backwards compatibility, IntOrString should still support
null values.
Relates to:
- #3806 
=> fix: IntOrString supports null values

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JArray.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JMap.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitive.java, java-generator/core/src/test/java/io/fabric8/java/generator/ApprovalTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testAkkaMicroservicesCrd.approved.txt
Draft/attempt to support default values generation in a different way than in https://github.com/fabric8io/kubernetes-client/pull/3944. 
The approach here is to delegate the actual deserialization of the default value (as a `JsonNode` content) to the `Serialization::unmarshal` method, which is used already extesilvely in the client.
Consequently, the generated code will depend on `io.fabric8.kubernetes.client` classes and the actual deserialization will take place at runtime.
Fixes https://github.com/fabric8io/kubernetes-client/issues/3869
FYI @andreaTP 
=> [java-gen] Adding support for default values (Serialization::unmarshal based)

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Client.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/ApiGroupResourceListsIT.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PluralizeIT.java
Fix #4065
Adds a way to get the core api resources, this will allow for implementation of things like: #887
=> fix #4065: use Client.getAPIResources("v1") for core/legacy resources

doc/MIGRATION-v6.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/BytesLimitTerminateTimeTailPrettyLoggable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ContainerResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/CopyOrReadable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ExecListenable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Execable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Loggable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/PodResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/PrettyLoggable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ScalableResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TailPrettyLoggable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TimeTailPrettyLoggable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TimestampBytesLimitTerminateTimeTailPrettyLoggable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TtyExecErrorChannelable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TtyExecErrorable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TtyExecOutputErrorable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TtyExecable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollableScalableResourceOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/dsl/BuildResource.java, openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/apps/DeploymentConfigOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Addresses #4107 - removing generics from interfaces that only have a single implementation
=> fix #4107: removing excessive generics

README.md
Removing references to Default Kubernetes/OpenShift contructors.
=> updating deprecated direct constructor usage

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Loggable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/StatefulSetOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ReplicationControllerOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/DeploymentOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/ReplicaSetOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/internal/PodOperationUtil.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/internal/PodOperationUtilTest.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/apps/DeploymentConfigOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildOperationsImpl.java
Fix #4093 
Exposing `getLogInputStream()` method to the `Loggable` interface to be able to stream resource log output.
Fixes #4093
=> adding a possibility to get a log as an InputStream from the Loggable resources

CHANGELOG.md, doc/MIGRATION-v6.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/EditReplacePatchable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ResourceAdapter.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/HasMetadataOperation.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ConfigMapCrudTest.java
fix #4142: additional patch methods
also correcting the javadocs wrt the patch base item.
removing logic that infers from the passed in item as the context will
already have the necessary information
=> fix #4142: additional patch methods

.github/workflows/build.yml, .github/workflows/gobuild.yml, .github/workflows/javadocs.yml, .github/workflows/release-snapshots.yaml, .github/workflows/release.yaml, .github/workflows/sonar.yml, .github/workflows/style-checks.yml, .github/workflows/windows-build.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedResourcesApiTest.java
Fix #3990
Access to `resources(...)` DSL method with generic HasMetadata interface
shouldn't be allowed.
=> fix (kubernetes-client) : Throw exception when `HasMetadata` is used in `resources(...)` API (#3990)

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListener.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListenerTest.java
refactor: extracted PortForwarderWebsocketListener and added tests
=> refactor: extracted PortForwarderWebsocketListener and added tests

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/internal/SerialExecutor.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/internal/SerialExecutorTest.java
Classes that depend on the SerialExecutor assume that the tasks are
executed and processed in the order of insertion. This test verifies
this.
=> test: document SerialExecutor expected behavior

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
I should have noticed this with #4163, but for consistency request should be called after the message is processed. Also adding a test to make sure that an exception won't cause message processing to stop - it won't because it's being caught and the call to request is in a finally block just in case.
=> Making the calling of WebSocket.request consistent

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
Serialization isn't marked as internal... out of laziness I was calling the clone method in some downstream projects and saw this was needed.  
The other approach would be to just limit the generic type to KubernetesResources.
=> fix #4171: fixing serialization.clone

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcherPatchTest.java
Fix #4139
Relates to: https://github.com/java-operator-sdk/java-operator-sdk/pull/1280
fix: status changes don't increment metadata.generation field
/cc @csviri
=> fix: status changes don't increment metadata.generation field

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerTest.java
Fix #3758
feat: VersionInfo in KubernetesMockServer can be overridden
=> feat: VersionInfo in KubernetesMockServer can be overridden

crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/PromoteSingleVersionAttributesDecorator.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/DefaultKubernetesClientTest.java, pom.xml
The pull request is mostly bumping sundrio to 0.91.1 and fixing some issues that manifest after this change:
- Drop deprecated code that was internally abusing setters, making them order sensitive.
- Fix incosistent handling of `masterUrl` in Config, so that settings via constructor or setters works the same.
- Fix crd generator issues that occur after fixing handling of `withXXX(null)`.
=> Upgrade sundro to  0.91.1

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
Fix #4216 
When the Kubernetes Mock Server is used in CRUD mode and a resource status is updated using the `replaceStatus()` method, it does not seem to dispatch the update to clients and thus it does not trigger the `waitUntilCondition(...)` or `scale(N, true)` methods waiting for them.
This seems to be caused by the resource version field in metadata not being updated. This PR uses the `deepCopy()` of the existing object (in order to be able to diff it against the updated one) and calls the `setDefaultMetadata(...)` method on it. This now causes the resource version to be updated and that triggers the dispatching of the events tot he clients even when status is updated with `replaceStatus()`
This should close close #4216.
=> Update resource version when `replaceStatus()` is used with Mock Kubernetes Server

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/V1beta1CertificateSigningRequestResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/V1beta1CertificatesAPIGroupDSL.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1CertificatesAPIGroupClient.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/certificates/v1beta1/CertificateSigningRequestOperationsImpl.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CertificateSigningRequestTest.java
Fix #2811
Port `approve()`, `deny()` methods to `client.certificates().v1beta1()` DSL
=> fix (kubernetes-client) : Approve/Reject API should also be available in v1beta1 CertificateSigningRequest DSL (#2811)

doc/MIGRATION-v6.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/CustomResourceList.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CustomResourceV1Example.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/DummyList.java
Partially addresses #3906 - by deprecating CustomResourceList as it provides no additional functionality.
=> chore #3906: deprecating CustomResourceList

CHANGELOG.md, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
Addressing #4041 (once master becomes 6.1).
This is mostly a method name / javadoc issue.  getAmountInBytes does return the number of cores.  I prefer having a non-static method - Quantity.parse(...).getNumericalAmount() vs Quantity.getAmountInBytes(Quantity.parse(...)) - but I didn't go so far as to deprecate the static method.
=> fix #4041: adding an instance method for quantity

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptorTest.java, kubernetes-client-api/src/test/resources/token-refresh-interceptor/kubeconfig.new
Should address #2271.
Platforms such as Amazon EKS since 1.21 rely on `BoundServiceAccountTokenVolume` to have time-limited access tokens. It is expected from kubernetes client implementations to refresh the configuration periodically to get a new token.
From [kubernetes 1.21 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md?rgh-link-date=2021-05-18T09%3A11%3A56Z#changelog-since-v1200)
> Clients should reload the token from disk periodically (once per minute is recommended) to ensure they continue to use a valid token. k8s.io/client-go version v11.0.0+ and v0.15.0+ reload tokens automatically.
Prior work from #3105 addressed it once the token expired, however it doesn't address the current situation where the token is actually valid for 90 …
=> fix #2271: Refresh token every minute

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
Addresses #4250 to allow null polymorphic unwrapped fields.
=> fix #4250: ensuring nullable polymorphic unwrapped works

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java, kubernetes-client-api/src/test/resources/serialization/test-configmap-manifest-bool-dateformat.yml, kubernetes-client-api/src/test/resources/serialization/test-lease-manifest-typed-fields.yml, kubernetes-client-api/src/test/resources/serialization/test-pod-manifest-dateformat-annotation.yml
Related to https://github.com/eclipse/jkube/issues/1647
+ Add custom Resolver for SnakeYaml which will ignore resolving tag if
it's of type Timestamp.This solves some unexpected behavior that snakeyaml
deserializes "2015-01-01 00:00:00" to `java.util.Date` but jackson
serializes java.util.Date to an integer.
+ Also ignore all boolean values which are not `true` or `false`.
Earlier SnakeYaml was also converting `No` to `false`.
=> fix (kubernetes-client-api) : Configure SnakeYaml to ignore converting timestamps to Date objects

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElectorTest.java
=> fix #4246: Catch KubernetesClientException when renewing lock

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStore.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStoreTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
fix #3969 #4222: deferring add events until cache is complete - it was easiest to also keep the change to omit resync events on relist
=> fix #3969 #4222: deferring add events until cache is complete

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/KubernetesClientExceptionTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupportTest.java
=> fix: properly extract resource metadata from URI on HTTP request failures

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
Respect `JsonIgnore` on `enum` properties.
=> [crd-gen] Respect `JsonIgnore` annotation on enum properties

CHANGELOG.md, doc/FAQ.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationContext.java, kubernetes-itests/pom.xml
Fix #4254
Add debug logging for streams that don't have explicit handling.  This is mostly just an internal nicety, but can also be useful to users, when they are tweaking their commands and don't need/want explicit handling for stderr for example.
=> fix #4254: adding debug logging for exec stream messages

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/LeaderElectionRecord.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElectorTest.java
addresses #4320 #4318 for leader election.
@manusa @csviri in the previous refactoring I had already put in a call to onStopLeading when cancelled - however this is not strictly correct.  If you don't have release on cancel set you won't loose the leadership until after the duration has expired.  Should that be refined as well?
=> fix #4320 #4318: implementing release on cancel and fixing transitions

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/DryRunTest.java, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
This is to address #4206.  We cannot throw an exception as it appears that the Config parsing has embedded HasMetadata (extensions) references, which lack type information.  So instead we'll return a generic resource - that should ensure round-trip parse/serialization is also correct.
=> fix #4206: ensuring null won't be returned from kubernetesdeserializer

crd-generator/api/pom.xml, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/annotation/SchemaFrom.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/annotation/SchemaSwap.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/JsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/JsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java, doc/CRD-generator.md, generator-annotations/pom.xml, generator-annotations/src/main/java/io/fabric8/generator/annotation/Max.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Min.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Nullable.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Pattern.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Required.java, pom.xml
Follow up from #4298 , introducing annotations for the fields that we want to support/map.
=> Introduce specific annotations for the generators

generator-annotations/pom.xml
Bumping generator-annotations version to 6.2-SNAPSHOT, so that the snapshot can be built successfully.
Fixes #4385 
- **N/A** - I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
- **N/A** - I have implemented unit tests to cover my changes
- **N/A** - I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
- **N/A** - I tested my code in Kubernetes
- **N/A** - I tested my code in OpenShift
=> Bump the generator-annotations version to 6.2-SNAPSHOT

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
This PR fixes the AbstractJsonSchema.SchemaPropsOptions.getRequired() method in order to return the `required` field value, rather than the `nullable` one.
Fixes #4394 
FYI @andreaTP, @manusa 
- **N/A** - I have implemented unit tests to cover my changes
- **N/A** - I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
=> Fix the SchemaPropsOptions POJO, which getRequired() getter returns the wrong field value

CHANGELOG.md, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/Group.java, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/Version.java, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java
=> fix: provide more context when group/plural are missing

CHANGELOG.md, doc/java-generation-from-CRD.md, java-generator/core/pom.xml, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JArray.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JMap.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitive.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/ValidationProperties.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testAkkaMicroservicesCrd.approved.txt, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testKeycloakCrd.approved.txt, java-generator/it/pom.xml, java-generator/it/src/it/cert-manager/pom.xml, java-generator/it/src/it/enum-ser-deser/pom.xml, java-generator/it/src/it/extensions/pom.xml
The changes are related to those in https://github.com/fabric8io/kubernetes-client/pull/4348 
The generator will now generate the expected annotations, i.e. those defined in `io.fabric8.generator.annotation`, the same ones that a reverse CRD generation from the Java model take into account.
Fix #4384 
I can suash the commits as soon as this is ready for merge or even earlier in case we agree on it. 
FYI @andreaTP, CC  @manusa
=> [java gen] - Support generated annotations

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/annotation/PreserveUnknownFields.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/JsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/JsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java, doc/CRD-generator.md
Signed-off-by: wineway <wangyuweihx@gmail.com>
like https://github.com/fabric8io/kubernetes-client/issues/4313, we need to use a sealed interface as a field type and offer multi implementations for this interface, it seems we can't and don't need to validate its fields in this situation, and we don't want to add something like @JsonAnyGetter might change its serialize behavior. so we think we can add a new annotation `@PreserveUnknownFields` for this scenario.
=> feat: add annotation @PreserveUnknownFields for field

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
refactor: JsonSchema remove preserveSelfUnknownFields
relates to: #4398
=> refactor: JsonSchema remove preserveSelfUnknownFields

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/Reflector.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/ReflectorTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
follow on to the initial changes based upon a test that was added to the backport.  This will make the startup exceptions visible to the stopped future as well.  The handling of that exception may change later with #4408 
=> fix #4365: adding a test for the termination exception

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java, kubernetes-client-api/src/test/resources/test-kubeconfig-exec-null-args, kubernetes-client-api/src/test/resources/test-kubeconfig-exec-win-null-args, kubernetes-client-api/src/test/resources/token-generator-win.bat
Fix https://github.com/fabric8io/kubernetes-client/issues/3733
Closes #4121 
=> fix: Config client authentication exec command should not fail when args is null

CHANGELOG.md, doc/FAQ.md, openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java, platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/TestBase.java
Fix #3864
Just like ManagedKubernetesClient, ManagedOpenShiftClient also doesn't handle `activate()` being called with null properties. Setting Component configuration policy to REQUIRE which would make having configuration object for ManagedOpenShiftClient (i.e. `src/main/resources/assembly/etc/io.fabric8.openshift.client.cfg`) compulsory.
=> fix (openshift-client) : Change ManagedOpenShiftClient OSGi ConfigurationPolicy to REQUIRE (#3864)

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/EditReplacePatchable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ConfigMapCrudTest.java
Fixes #4441 so that patch() is no longer a no-op.  See the CHANGELOG and javadoc updates that try to explain the changes.
=> fix #4441: correcting patch base handling

extensions/camel-k/client/pom.xml, extensions/certmanager/client/pom.xml, extensions/chaosmesh/client/pom.xml, extensions/istio/client/pom.xml, extensions/knative/client/pom.xml, extensions/open-cluster-management/client/pom.xml, extensions/service-catalog/client/pom.xml, extensions/tekton/client/pom.xml, extensions/verticalpodautoscaler/client/pom.xml, extensions/volcano/client/pom.xml, extensions/volumesnapshot/client/pom.xml, httpclient-jdk/pom.xml, httpclient-jetty/pom.xml, httpclient-okhttp/pom.xml, kubernetes-client/pom.xml, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java, openshift-client/pom.xml
- Remove ExtensionAdapter reference from ManagedKubernetesClient, no provider is exposed for ExtensionAdapter interface in kubernetes-client module. `bindExtensionAdapter` and `bindExtensionAdapter` are throwing `NullPointerException` during startup.
- Add `Provide-Capability` field in `openshift-client` and other extensions bundle configurations in order to resolve SPIFly related `NPE` (reported in #3890)
- https://aries.apache.org/documentation/modules/spi-fly.html ([#providers](https://aries.apache.org/documentation/modules/spi-fly.html#_providers))
=> fix (osgi) : Fix OSGi startup exceptions while using KubernetesClient/OpenShiftClient

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperationTest.java
I introduced a regression in #4365 with the refactoring of the exponential backoff - the interval was not carried forward. 
Another, optional, change is to add exceptions that preserve for blocking request stacktraces - that seems better than just the underlying stacktrace which will just be from the httpclient layer.
=> fix #4365 correcting backoff interval

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
Fix #4482
Fix for #4482 we need to specify the current size for a consumeBytes consume otherwise okhttp will attempt to fetch up to 8k and hold up the delivery of anything else that was already accumulated.
=> fix #4482: consumeBytes for okhttp should not fetch more on consume

CHANGELOG.md, extensions/istio/generator-v1alpha3/cmd/generate/generate.go, extensions/istio/generator-v1beta1/cmd/generate/generate.go, extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/meta/v1alpha1/IstioCondition.java, extensions/istio/model-v1alpha3/src/main/resources/schema/istio-schema.json, extensions/istio/model-v1beta1/src/generated/java/io/fabric8/istio/api/meta/v1alpha1/IstioCondition.java, extensions/istio/model-v1beta1/src/main/resources/schema/istio-schema.json
=> Fix #4312: fix timestamp can't be deserialized for IstioCondition

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/JsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/JsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitiveNameAndType.java, java-generator/core/src/test/java/io/fabric8/java/generator/CompilationTest.java, java-generator/it/src/it/extensions/pom.xml, java-generator/it/src/it/preserve-unknown-objects/invoker.properties, java-generator/it/src/it/preserve-unknown-objects/pom.xml, java-generator/it/src/it/preserve-unknown-objects/src/test/java/io/fabric8/it/certmanager/TestPreserveUnkonwnUsability.java, java-generator/it/src/it/preserve-unknown-objects/src/test/resources/dapr-components-crd.yaml, java-generator/it/src/it/preserve-unknown-objects/src/test/resources/sample.yaml
Resolves #4426 
The new encoding seems to be better aligned with the rules:
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema
=> [java-gen] Preserve unknown without type should translate to AnyType

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PatchHandler.java, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PutHandler.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java
Fix #4478 
Fix for #4478 - the mock server patch / put handling usage of the path method inserted an explicit Missing node, which then caused a diff.
=> fix #4478: status handling was inserting an explicit missing node

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/ExceptionHandler.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/SharedIndexInformer.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/informers/ExceptionHandlerTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/SharedInformerFactoryImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/Reflector.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformerResyncTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/ReflectorTest.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CustomResourceInformerExample.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Fix #4408 
cc @csviri 
I couldn't come up with a good way to deal with this all under the covers, so it seemed best to introduce an explicit handler with a signature that's sufficient to cover our default behavior.  This makes the final solution much closer to some of the earlier proposals.  For the method:
```
boolean retryAfterException(boolean isStarted, Throwable t);
```
our current behavior is:
```
(b, t) -> b && !(t instanceof WatcherException)
```
That is we'll retry once started and only if it's not a WatcherException.  
The expectation here is that if you use the runnableInformer method, you can change this behavior by calling something like exceptionHandler((b, t) -> true)
In reviewing the go implementation, I see the following differences:
- Their WatchErrorHandler is doc'd as …
=> fix #4408: allowing for users to set the exception handling behavior

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java
fix #4496 removing list handling from the abstract watch manager.
=> fix #4496: removing list handling from watching

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElectorTest.java
Addresses #4547 by synchronizing the cancel and renew methods
cc @csviri 
=> fix #4547: preventing a cancelled leader elector

.github/workflows/build.yml, java-generator/cli/src/main/java/io/fabric8/java/generator/cli/GenerateJavaSources.java
Fix #4534 
The regression has been introduced here:
https://github.com/fabric8io/kubernetes-client/commit/b05049b359a75d12afa1a759243dbd8b16e04237
=> Fix default handling of skipGeneratedAnnotations

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
Fix #4535
Single quotes in folder or file names were causing corruption of the shell command. The fix changes the ' character to '"'"'
For example a folder called te'st would now get shellQuoted to 'te'"'"'st'
1. ' ends the first quote,
2. " starts second quote,
3. ' is valid character in double quotes
4. " ends the second quote
5. ' starts the third quote
6. The end result when fed into the shell, is as we desired: te'st
https://github.com/fabric8io/kubernetes-client/issues/4535
=> Fix 4535 - support file uploads with filenames containing single quote

httpclient-tests/src/test/java/io/fabric8/kubernetes/client/http/OkHttpClientTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeleteIT.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ConfigMapCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CrudInformerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/EventTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LeaderElectionTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java, kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
Partially addresses #4507 - updating all mock timeouts to be 10 seconds, that seems to be the most common value used across the tests.  We can also consider extracting / parameterizing this.
=> fix #4507: updating timeouts

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java
Fixes #4491 - since this has come up a couple of times we probably need a more explicit message for a RejectedExecutionException from down in okhttp.  Assuming #4430 is committed, this change only needs applied to a single okhttp method.
It's also possible to handle this more generally with a proxied httpclient with close checking, but I don't think that is needed as the other clients either already do that check or provide a better exception.
=> fix #4491: adding a more explicit shutdown exception

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl_CVE2021_20218_Test.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodExecTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
Fixes #4355 - direct or indirect (copy, upload) to exec / attach will now validate or set the container parameter in the same was as the kubectl client.  This requires always fetching the pod prior to the exec / attach call and will always add the container argument.
We do not yet need to do this for log operations as we don't have a similar option to specify "don't get from all" without specifying a container name.
=> fix #4355: adding logic to set/validate the container name

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptorTest.java
fix for #4519 - refining how the config refreshes
It seems like a good idea also to always apply the system/env properties after loading the kubeconfig - https://github.com/fabric8io/kubernetes-client/compare/master...shawkins:refresh_config?expand=1#diff-7506ddc44edef04cb34dcde13c56d00ed3b1d35d848ded8f1924ed44c03db953R608
=> fix #4519: correcting how the config refreshes

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/NamespacedKubernetesClientAdapter.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationSingleDocumentUnmarshalTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/KubernetesClientImpl.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/KubernetesClientImplTest.java, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/runtime/RawExtension.java, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
Fixes #4530 - this removes some of the remaining cases where the `KubernetesDeserializer` was returning null and generalizes support for primitive values.
=> fix #4530: allowing serialization to better handle primitive values

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/it/src/it/cert-manager/expected/Auth.expected, java-generator/it/src/it/preserve-unknown-serdeser/invoker.properties, java-generator/it/src/it/preserve-unknown-serdeser/pom.xml, java-generator/it/src/it/preserve-unknown-serdeser/src/test/java/io/fabric8/it/certmanager/TestPreserveUnkonwnSerDeser.java, java-generator/it/src/it/preserve-unknown-serdeser/src/test/resources/dapr-components-crd.yaml, java-generator/it/src/it/preserve-unknown-serdeser/src/test/resources/sample.yaml
=> [java-generator] Fix additionalProperties ser/deser

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java
Fixes #4509
This took a while to find the root cause:
The internal SPI fallback logic inside `KeyFactory.generatePrivate()` has the weird side effect of latching onto the LAST registered provider (which in our case was Cavium) after `InvalidKeySpecException` is thrown.
This choice is sticky for a single instance of KeyFactory and the fix for our issue is to get fresh `KeyFactory` instance when retrying.
=> Fixed CertUtils.handleOtherKeys() behavior with Cavium

CHANGELOG.md, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientBuilderImpl.java, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpRequestImpl.java, httpclient-jdk/src/test/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientBuilderTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractWebSocketSendTest.java
Fix #4569 - the regression from #4490.  We need more pervasive checks in the jdk client for the 0 (no) timeout value.  
=> fix #4569: accounting for 0 timeouts that are not supported by jdk

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testAkkaMicroservicesCrd.approved.txt, java-generator/it/src/it/default-values-instantiation/invoker.properties, java-generator/it/src/it/default-values-instantiation/pom.xml, java-generator/it/src/it/default-values-instantiation/src/test/java/io/fabric8/it/certmanager/TestDefaultValues.java, java-generator/it/src/it/default-values-instantiation/src/test/resources/empty.yaml, java-generator/it/src/it/default-values-instantiation/src/test/resources/example.yaml
Fix #4530 
Here I'm proposing to specialize the encoding of default values skipping the Jackson deserialization completely.
This is not complete yet as the handling of primitive arrays is still broken. cc. @shawkins 
=> Fix primitive types encoding of default values

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/ClassDependenciesVisitor.java, crd-generator/api/src/test/java/io/fabric8/crd/example/cyclic/CyclicList.java, crd-generator/api/src/test/java/io/fabric8/crd/example/cyclic/CyclicListSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/example/cyclic/RefList.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
The logic in ClassDependenciesVisitor was prone to SO when there were cyclic references in the schema. This should fix it, and the tests are still passing, so hopefully it is safe. 
Fixes #4510
~TBH, I do not fully understand the purpose of ClassDependenciesVisitor, I realize it it used in tests and maybe when someone would want to include the generator in their own code? I would be grateful for some pointers.~
It appears that it exists mostly to facilitate conditional hot reload when used with quarkus, as implemented here https://github.com/quarkiverse/quarkus-operator-sdk/blob/main/core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java#L187
This still works with my changes, see my comment below.
=> Fix StackOverflow on cyclic references involving collections.

CHANGELOG.md, doc/CHEATSHEET.md
Fixes #4580
The method createOrReplace(Secret) from the type ItemWritableOperation is deprecated but this is in the doku
Secret createdSecret = client.secrets().inNamespace("default").createOrReplace(secret1);
changed to
Secret createdSecret = client.secrets().inNamespace("default").resource(secret1).createOrReplace();
https://github.com/fabric8io/kubernetes-client/issues/4580
=> updated [client.secrets] createOrReplace

httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClient.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, httpclient-tests/src/test/java/io/fabric8/kubernetes/client/http/OkHttpClientTest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractAsyncBodyTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractInterceptorTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/WatchHttpManagerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
Follow up to #4430 that moves consumeLines directly to the http watch.
=> fix #4201: moving consumeLines out of the clients

crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddAdditionPrinterColumnDecorator.java, crd-generator/api/src/test/java/io/fabric8/crd/example/joke/JokeRequestStatus.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
This is a proposal to fix #4610 
After this fix, `additionalPrinterColumns` with different paths will be emitted with colliding names. I'm not sure if this has implications.
=> [crd-generator] Fix inconsistent additionalPrinterColumns jsonPath

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java
Relates to #4136 
This tones down the warning that would be logged for things like deprecated apis.
=> fix #4136: logging at warning only if warning was requested

CHANGELOG.md, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/KubernetesNamespacedTestExtension.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java
Addresses #4641 - the changes for https://github.com/fabric8io/kubernetes-client/commit/951a7f58888c2df03d338bf754d6bb9c390c360c introduced a regression via a timing issue of when the websocketfuture is set.
If there is to be another 6.2 release, this should be included.
=> Fix for watch regression

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/HasMetadataOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/KubernetesClientImpl.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/HasMetadataOperationsImplTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsImpl.java
This follows up on a next step of #3972 - remove the internal usage of registerCustomKind.  The static nature of that registration was problematic both for us and for users as the behavior would seem inconsistent.  
This change highlighted that several packages are missing from the KubernetesDeserializer - https://github.com/fabric8io/kubernetes-client/commit/8db8124ef3ac69b980b9ba32dceac0cb1c0ff459 - that commit won't be needed against master if #4511 is committed first, but may be considered for back-porting.
The strategy here is to use some additional jackson logic to convey an element type with list parsing.  list is the only built-in path where we may not have a type already associated with the processing - the other calls, such as a get, will pass the expected type directly; have …
=> Removing internal usage of registerCustomKind

CHANGELOG.md, httpclient-okhttp/pom.xml, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/ConnectionPoolLeakageTest.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpAsyncBodyTest.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpImplAsyncBodyTest.java
Fixes #4666 the AsyncBody implementation even after reading to exhaustion still needs to close the source to satisfy okhttp.
=> fix #4666: addressing okhttp sources needing explicit close

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/it/src/it/default-values-instantiation/src/test/java/io/fabric8/it/certmanager/TestDefaultValues.java, java-generator/it/src/it/default-values-instantiation/src/test/resources/example.yaml
=> [java-gen] Fix default value encoding for enums

CHANGELOG.md, openshift-client/src/main/java/io/fabric8/openshift/client/impl/OpenShiftClientImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java, openshift-client/src/test/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptorTest.java
Partially address #4673 - it at least addresses the regression that was introduced by changing how the RequestConfig was passed down.
The other two cases - making requests smarter about waiting for an existing auth request, or sharing across possible instances of the OpenShift client haven not been addressed.  These are not new to 6.x.
=> fix #4673 ensures token is shared by the same logical instance

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/Reflector.java, kubernetes-itests/src/test/java/io/fabric8/openshift/ProjectRequestIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/InformTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NodeMetricsTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodMetricsTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicaSetTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicationControllerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java, kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
Addresses #4670 by setting an initial list resourceVersion of 0, which matches the behavior of the go client.
=> fix #4670: using a 0 resourceVersion for the initial informer listing

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/run/RunOperations.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/run/RunOperationsTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/KubernetesClientImpl.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/PodRunEquivalent.java
Fix #4633
Deprecates withRunConfig and adds a withNewRunConfig that provides inline access to all of the run config builder methods.  The only reason that RunOperations is not directly a RunConfigNested is that builders are mutable whereas our contexts not - so RunConfigNested nested = run().withNewRunConfig(), is the same instance as nested.withName("name").  If we don't care about the distinction then we can do away with the need to call withNewRunConfig().
=> fix #4633: improving run operations

kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodEvictIT.java
Minor de-flake it appears that even once the other pods is ready that the eviction may not be able to be immediately processed.
=> adds waiting to ensure eviction can be processed

CHANGELOG.md, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClientBuilder.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientFactory.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientFactoryTest.java
Fix #4663
Addresses #4663 by enforcing the request timeout at a higher level and setting connection / request limits to unlimited.
@manusa in looking at the current state what I see is that after 64 websockets okhttp will stop accepting additional websockets or regular requests.  It appears that at least with http1 against the mockserver, you can start as many regular requests you want - waiting to consume the body does not hold the connection, it is immediately released back to the pool.
For jetty 64 concurrent regular requests is all it supports - https://www.eclipse.org/lists/jetty-dev/msg02788.html#:~:text=So%20if%20you%20send%20requests,next%20one%20will%20be%20rejected. maxConnectionsPerDestination.  This number does not affect websockets.  The only way this would be exhausted …
=> fix #4663: changes to help prevent the client from waiting indefinitely

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java
fixes #4563 
I added a fallback where the http client is looked up via the classloader of the `HttpUtils` class if lookup via the thread context classloader fails.
The current impl looks up a http client impl using the thread context classloader. This fails in IDEA (and also in Eclipse/OSGI) because the thread context classloader has no access to the plugin/bundle-resources. 
A typical workaround is to set the thread context classloader to the classloader of the bundle/plugin before calling the code that's using the thread context classloader. This is something one wants to avoid though, because it breaks platform isolation. 
=> chore: fallback to current class cloader if can't find httpClient

java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java
Closes #4661 
Additional fix for #4661
You can check the new output by:
```
mvn clean install -f java-generator/pom.xml -DskipTests 
mvn help:describe -DgroupId=io.fabric8 -DartifactId=java-generator-maven-plugin -Dversion=6.4-SNAPSHOT -Ddetail
```
It looks as follows now:
```
Name: Fabric8 :: Java generator :: Maven Plugin
Description: Java client for Kubernetes and OpenShift
Group Id: io.fabric8
Artifact Id: java-generator-maven-plugin
Version: 6.4-SNAPSHOT
Goal Prefix: java-generator
This plugin has 1 goal:
java-generator:generate
Description: (no description available)
Implementation: io.fabric8.java.generator.maven.plugin.JavaGeneratorMojo
Language: java
Bound to phase: generate-sources
Available parameters:
alwaysPreserveUnknown
User property: …
```
=> Add Maven Plugin descriptions and remove readonly

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ContainerResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/CopyOrReadable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Execable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Loggable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationContext.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollableScalableResourceOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/internal/PodOperationUtil.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/internal/PodOperationUtilTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodExecTest.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/apps/DeploymentConfigOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildOperationsImpl.java
Fix #4637 
Addresses #4637 - generalizes withLogWaitTimeout as withReadyWaitTimeout, which is applicable to all pod operations that require a ready (or succeeded pod).  This uses the same paradigm of just setting the milliseconds - please comment if you want a different name, or the ability to specify the unit as we do with some of the other timeouts.
It also adds a validation to ensure that at least one of the streams is being used.  This doesn't appear to be an issue with other clients as kubectl will always use stdin and python will default to using both stderr and stdout.  I'm open as well to changing our default stream consumption behavior should we want to avoid this exception case.
=> fix #4637: adding a generalized ready timeout to pod operations

java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java
=> Make the Java generator Maven Plugin able to directly download resources

java-generator/cli/src/main/java/io/fabric8/java/generator/cli/GenerateJavaSources.java, java-generator/core/pom.xml, java-generator/core/src/main/java/io/fabric8/java/generator/CRGeneratorRunner.java, java-generator/core/src/main/java/io/fabric8/java/generator/Config.java, java-generator/core/src/main/java/io/fabric8/java/generator/FileJavaGenerator.java, java-generator/core/src/main/java/io/fabric8/java/generator/JavaGenerator.java, java-generator/core/src/main/java/io/fabric8/java/generator/URLJavaGenerator.java, java-generator/core/src/test/java/io/fabric8/java/generator/ApprovalTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/CompilationTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/ConfigTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/URLJavaGeneratorTest.java, java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java
Fix #4709 
Generalizes the generate Java from remote URL CRD.
=> feat(java-generator): generalized Java class generation from remote CRDs

CHANGELOG.md, java-generator/cli/src/main/java/io/fabric8/java/generator/cli/GenerateJavaSources.java, java-generator/core/src/main/java/io/fabric8/java/generator/CRGeneratorRunner.java, java-generator/core/src/main/java/io/fabric8/java/generator/Config.java, java-generator/core/src/test/java/io/fabric8/java/generator/ApprovalTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/ConfigTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/it/src/it/crd-names/pom.xml, java-generator/it/src/it/crd-names/src/test/java/io/fabric8/it/names/TestCRDNames.java, java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java
=> [java-generator] Overridable package name

CHANGELOG.md, kubernetes-model-generator/kubernetes-model-gatewayapi/src/generated/java/io/fabric8/kubernetes/api/model/gatewayapi/v1alpha2/GatewayClass.java, kubernetes-model-generator/kubernetes-model-gatewayapi/src/generated/java/io/fabric8/kubernetes/api/model/gatewayapi/v1beta1/GatewayClass.java, kubernetes-model-generator/kubernetes-model-gatewayapi/src/main/resources/schema/kube-schema.json, kubernetes-model-generator/kubernetes-model-gatewayapi/src/main/resources/schema/validation-schema.json, kubernetes-model-generator/kubernetes-model-gatewayapi/src/test/java/io/fabric8/kubernetes/api/model/gatewayapi/v1beta1/GatewayClassTest.java, kubernetes-model-generator/pkg/schemagen/generate.go
Fix #4654 
GatewayClass is a cluster scoped resource. It should not implement Namespaced interface.
=> fix (kubernetes-model-gatewayapi) : GatewayClass should not implement Namespaced interface (#4654)

crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/PromoteSingleVersionAttributesDecorator.java
This is an attempt to fix #4680 
I think that the Decorator I'm touching might be the root cause of the issue (directly or inderectly related).
Overall, this implementation should be more solid than before.
Let see how it goes 🤞 
=> Attempt to fix occasional CRD generation issues with subresources

httpclient-okhttp/pom.xml, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpWebSocketImpl.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpResponseImplTest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractInterceptorTest.java
Fix #4720
Addresses #4720 - this must have been a latent bug in the jdk interceptor handling that when elevated caused the previous response to not be closed. 
It turns out that we don't need explicit handling in the websocket case - we are passing a null type in the okhttp logic, which auto-closes the response.  The other clients (jdk, jetty) start from exceptional cases that do not provide usable responses.
=> fix #4720: ensuring the previous response is closed

java-generator/core/src/main/java/io/fabric8/java/generator/FileJavaGenerator.java, java-generator/core/src/test/resources/folder/crontab-crd.yml, java-generator/core/src/test/resources/folder/namespace.yml
This improves running the behavior of running the java generator on a random bulk of yaml files.
=> [java-generator] More robust skip of non-CRDs

CHANGELOG.md, junit/kubernetes-junit-jupiter/pom.xml, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/BaseExtension.java, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/HasKubernetesClient.java, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/KubernetesNamespacedTestExtension.java, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/LoadKubernetesManifestsExtension.java, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/api/KubernetesTest.java, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/api/LoadKubernetesManifests.java, junit/kubernetes-junit-jupiter/src/test/java/io/fabric8/junit/jupiter/api/KubernetesTestTest.java, junit/kubernetes-junit-jupiter/src/test/java/io/fabric8/junit/jupiter/api/KubernetesTestWithSuperClass.java, junit/kubernetes-junit-jupiter/src/test/java/io/fabric8/junit/jupiter/api/KubernetesTestWithSuperClassTest.java
feat: `@KubernetesTest` annotation can be used in base test classes
=> feat: @KubernetesTest annotation can be used in base test classes

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Waitable.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/GenericClusterScopedCustomResourceIT.java
This is to address the test failure https://github.com/fabric8io/kubernetes-client/actions/runs/3856547075/jobs/6576802948#step:6:480
More than likely this is due to the change to initially start the informer with a list at a cached version - it's not guaranteed that the newly created crd will initially be there.
=> adding a small note about waitable

java-generator/cli/src/main/java/io/fabric8/java/generator/cli/GenerateJavaSources.java, java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java
Expose the option to download the CRD from URL to the CLI.
=> [java-generator] enable url as a source in the cli

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListener.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListenerTest.java
Fix #4249 
Fix #4726 
There are a lot of unnecessary error logging in the portforwarding logic  - in general we should not log something at an error level that is provided to the user.  In this case there are both client and server throwables returned.  A small change was to also map protocol errors to server exceptions so that they would be available as well.
For the exec logic there's no need to log or provide the exception to the listener if we're already finished.
=> fix #4249 #4726: toning down logging of errors

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractSimultaneousConnectionsTest.java
**Partial** alternative to #4736
- Introduced delayed HttpHandler, delays response delivery until a certain amount of requests/exchanges have been accumulated.
- Introduced artificial back-pressure using a client-server shared CyclicBarrier. New requests are only sent when the server receives and is able to process the previous request.
=> test: refine simultaneous connections test

httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientFactory.java
Closes #4748 
Replaces #4748 with the rebased branch that contains the fix for the simultaneous connection test, and includes the changes to increase the hard max connection limit to 8192.
It's my understanding that this completes the initial working implementation of the client.
@vietj @shawkins 
=> feat(vertx): support for 8192 simultaneous connections

CHANGELOG.md, httpclient-jdk/src/test/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientPostTest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpHeaders.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpPostTest.java
Relates to #4735 (might fix it)
fix: StandardHttpClient sends Expect 100-continue header value
=> fix: StandardHttpClient sends Expect 100-continue header value

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java
Fix #4729 
@manusa  in reviewing the other recent issues along these lines, I think this is another corner-ish case.  It addresses the possibility of a resource leak due to an ill-defined expectation of cancelling the CompletableFutures returned by the http client layer.  If the cancel happens before the future is completed, then the resource may not get closed.
The fix here is to bake that responsibility into the standardhttpclient.  A different way of addressing this is to instead have HttpClient return a CompletionStage - which makes it clear that you are instead supposed to "cancel" via a thenAccept or whenComplete handler that closes things out.
=> fix #4729: completablefuture cancel will close the underlying resource

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testJokeCrd.approved.txt, java-generator/it/src/it/enum-ser-deser/src/test/java/io/fabric8/it/certmanager/TestEnumSerialization.java, java-generator/it/src/it/enum-ser-deser/src/test/resources/cert-manager.crds.1.7.1.yaml, java-generator/it/src/it/enum-ser-deser/src/test/resources/sample1.yaml
=> [java-generator] Fix encoding for empty strings in enums

CHANGELOG.md, doc/FAQ.md
Fix #4418
+ Add breaking change note in CHANGELOG in release v6.1.0
+ Add FAQ regarding changed NO_PROXY behavior
=> doc (kubernetes-client-api) : Add note about changed NO_PROXY behavior with wildcards (#4418)

httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxWebSocket.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpClientNewWebSocketBuilderTest.java
fix(vertx): ReadStream pause before propagating WS message
E2E reveals that the place where ws.pause is called prevents further messages from being received at the Watcher level. The stream needs to be paused first and then propagate the message downstream, in case the handler calls the WebSocket.request method.
/cc @vietj @shawkins 
=> fix(vertx): ReadStream pause before propagating WS message

doc/CHEATSHEET.md
Fix #4776
This is a docs fix for Issue #4776
=> Doc: Cheatsheet ingress should use network v1 api

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/KubernetesCrudDispatcherHandler.java, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PatchHandler.java, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PutHandler.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/crud/KubernetesCrudDispatcherPatchTest.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/crud/KubernetesCrudDispatcherPutTest.java
This PR fixes #4739.
A couple of minor points worthy of discussion:
1. I added the check to the path for `PATCH` as well as `PUT` requests, but I haven't added a unit test for this case.
2. When constructing the error message Kubernetes refers to the resource type using the singular name of the resource (e.g. `configmap`), but I don't have ready access to that in the `KubernetesCrudDispatcherHandler`, so I've used the `metadata.kind` instead (e.g. `ConfigMap`). Therefore there is a slight difference in the `KubernetesClientException` error message.
=> Fix #4739: Mock server doesn't handle optimistic concurrency control

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractCustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/CRDGenerator.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/CustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/CustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedPropertyPathDetector.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/ParallelCRDGeneratorTest.java, crd-generator/apt/src/main/java/io/fabric8/crd/generator/apt/CustomResourceAnnotationProcessor.java, crd-generator/test/pom.xml, doc/CRD-generator.md
In my project I have 10 CRDs classes. 
I've taken a CPU flamegraph and I figured out the usage of java streams api adds a relevant overhead while visiting specs/status classes via reflection. 
Also the visitors can access the crd in parallel since the base typeref is stateless.
Changes included:
- Enable concurrent crd visitors using nCPU threads.
- Moved some hot path code from using streams to old plain java for-loop
FYI I did a similar fix in sundrio: https://github.com/sundrio/sundrio/pull/352
The net result of this patch is that generation time moved from ~30 seconds to to ~11 seconds.  
=> improve: generate crds in parallel and optimize code

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
Trace the warning message if the user has set the service account token system property. Otherwise, simply print a debug message if there is no file in the default location. 
Relates https://github.com/quarkusio/quarkus/issues/30558
=> Don't print warning message when service account token property is unset

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/CRGeneratorRunner.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java
=> [java-generator] Reflect the `scope` field when implementing the `Namespaced` interface

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/SharedIndexInformer.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/Reflector.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/ReflectorTest.java
Fix #4794 
Addresses #4794 ensures event processing will have stopped when the stopped future is completed.  And will also complete the future after isWatching returns false.  However since we have been setting the watching flag proactively to false (and even at the AbstractWatchManager level we call onClose immediately with the Watch.close call), this does not mean that the websocket / http connection is fully gone. 
=> fix #4794: clarifying event processing wrt to a manual informer stop

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/LeaderElectionRecord.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElectorTest.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java
Fully addresses the issue with release on cancel - the prior concurrency fix was not sufficient as we need to consider the fresh resource version.  It seems like there is some optimization of the elector code as the create / update operations don't capture the returned resource version, but having the code this way makes it tolerant to esoteric situations like an api server roll back.
=> fix #4798: correcting leaderelection release behavior

java-generator/core/src/main/java/io/fabric8/java/generator/FileJavaGenerator.java, java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java
A few minor tweaks to the java generator CRD download functionality were found using it on other projects.
=> [java-generator] Fix minor issues with CRD download

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/test/resources/akka-microservices-crd.yml, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testAkkaMicroservicesCrd.approved.txt
=> [java-generator] Escape '*/' in generated JavaDocs

CHANGELOG.md, extensions/istio/tests/src/test/java/io/fabric8/istio/test/v1beta1/GatewayTest.java, extensions/istio/tests/src/test/java/io/fabric8/istio/test/v1beta1/VirtualServiceTest.java, kubernetes-client-api/pom.xml, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationYamlTest.java, platforms/karaf/features/src/main/resources/feature.xml, pom.xml
Supersedes closes #4753
> Migrate from SnakeYAML to [SnakeYAML Engine](https://bitbucket.org/snakeyaml/snakeyaml-engine)
_Originally posted by @asomov in https://github.com/fabric8io/kubernetes-client/pull/4753_
=> Migrate to SnakeYAML Engine

CHANGELOG.md, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkWebSocketImpl.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyWebSocket.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocket.java
Fix #4851 
The other clients already copy the buffer contents.  
An alternative is to use the paradigm of returning a future such that completion indicates the buffer can be reused.
=> fix #4851: cloning the incoming buffer

kubernetes-itests/src/test/java/io/fabric8/kubernetes/GenericCustomResourceIT.java
Small change to prevent a test npe
=> adds a null check - the initial list can be served from cache

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
Fix #4853 
Partially addressing #4846
Adds a similar waiting condition before log operations
=> fix #4853: adding another wait for log operations

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java
Fix #4832 
Alter the regex which is used to extract cidr ranges, which are then tested against the target master url. This change should allow for single digit suffixes eg 10.0.0.0/8 to be matched, where before it did not appear to be. 
=> Fix #4832 - Match cidr with bit suffix <10

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientBuilder.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/KubernetesClientBuilderTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtilTest.java
Fix #4791 
Continue #4792 with my personal account
=> Fix: Handle NullPointerException for Thread.currentThread().getContextClassLoader()

CHANGELOG.md, java-generator/cli/src/main/java/io/fabric8/java/generator/cli/GenerateJavaSources.java, java-generator/core/pom.xml, java-generator/core/src/main/java/io/fabric8/java/generator/CRGeneratorRunner.java, java-generator/core/src/main/java/io/fabric8/java/generator/FileJavaGenerator.java, java-generator/core/src/main/java/io/fabric8/java/generator/WritableCRCompilationUnit.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java
Fix #4723
This is just a placeholder to keep track of the progress in debugging a race happening in the `java-generator`.
How to reproduce the issue:
- clone this repo
- `mvn clean install -DskipTests` once (and have a ☕ meanwhile)
- from now on you will be able to check your changes with `mvn clean install -f java-generator/pom.xml`
- download a "big enough" yaml description, e.g. [this one](https://github.com/kserve/kserve/releases/download/v0.10.0/kserve.yaml)
- run the CLI using jbang: `jbang io.fabric8:java-generator-cli:6.5-SNAPSHOT -s kserve.yaml --target=./test`
running this sequence multiple times produces non-deterministic errors.
Considerations:
- Disabling the `paralleStreams` in [FileJavaGenerator](https://github.com/fabric8io/kubernetes-client/blob/master/java-generator/core/ …
=> [java-generator] Fix a race condition in the usage of JavaParser for large CRDs

CHANGELOG.md, doc/CHEATSHEET.md, junit/kubernetes-server-mock/pom.xml, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/StatusMessage.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/StatusMessageTest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/EphemeralContainersResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/PodResource.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationContext.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/OperationContextTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupportTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImplTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodEphemeralContainersIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
Add new method to PodResource to manager ephemeral containers sub-resource.
Add new interface EphemeralContainersResource to expose operations on this new operation context and is returned by a new method on PodResource.
OperationContext and OperationSupport have been updated to support implementing operations on named resource sub-resources.
Fixes #4758
=> feat(kubernetes-client-api): add pod ephemeral container operations

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientFactory.java
Port of https://github.com/quarkusio/quarkus/pull/30952 / https://github.com/quarkusio/quarkus/issues/30951
=> fix: disable Vertx DNS resolver when creating Vertx instance

java-generator/benchmark/pom.xml, java-generator/benchmark/src/main/java/io/fabric8/java/generator/benchmark/SourceCodeGenerationBenchmark.java, java-generator/benchmark/src/main/resources/kserve.yaml, java-generator/core/src/main/java/io/fabric8/java/generator/FileJavaGenerator.java, java-generator/core/src/main/java/io/fabric8/java/generator/WritableCRCompilationUnit.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/GeneratorResult.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/test/java/io/fabric8/java/generator/ApprovalTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/it/src/it/cert-manager/expected/Auth.expected, java-generator/pom.xml
Fix #4865
This PR:
- replaces some wasteful hidden invocations to `StaticJavaParser.parseClassOrInterfaceType` with explicit javaparser AST nodes constructors
- splits the code generation and writing phases
- performs the writings in independent async tasks
=> [java-generator] performance improvementes

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/ExponentialBackoffIntervalCalculatorTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
Fix #4863
- feat: default HttpClient retry logic to 100ms interval
- feat: request retry backoff limit defaults to 10
Enables the usage of the retry logic with a maximum limit of 10 attempts
=> feat: request retry backoff limit defaults to 10

CHANGELOG.md, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWatchInputStream.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallback.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/ExecWatchInputStreamTest.java
Fix #4885
Addresses PodIT hanging failure with jdk by checking for complete prior to waiting - the issue is that the request for more with jdk will be executed in the calling thread which already holds the lock and can modify the complete flag prior to the wait.
There are also some failures on the JobIT log - but I have not been able to reproduce that.  There are a couple of changes here to help with that logic in general - one is better localize when more is requested.  That should be done inline with the processing call, rather than in a completion handler because it looks like they can be executed in parallel.  The other is that I don't see now anywhere in the jdk client that guarantees the supplied buffers won't change after be passed to consume.  Since we already handled that case …
=> fix #4885: addressing a potential hang with jdk streams

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Client.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ClientAdapter.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/SupportTestingClient.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/BaseClientTest.java
Resolves the next step in #4659, which is to deprecate before full removal - at which point we'll stop internally using it for isAdaptable
Also adding a generic supports method.
=> fix #4659: deprecating support testing client

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/ListerWatcher.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/Reflector.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManagerTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/WatchHttpManagerTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformerResyncTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/ReflectorTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/InformTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NodeMetricsTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodMetricsTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
Fix #4675
This seems like a little less work than updating the mock and other tests with fixed expectations.  Here we'll trigger the shutdown of the websocket after 5 - 10 minutes (the same as the go client).
Another thought is to eliminate the random strategy specifically for the mock client, but that also seems hackish.
=> fix #4675: adding an informer timeout handled directly in our client

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ImageEditReplacePatchable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ImageUpdateable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TimeoutImageEditReplacePatchable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetRollingUpdater.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollableScalableResourceOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollingUpdater.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/StatefulSetOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ReplicationControllerOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ReplicationControllerRollingUpdater.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/ReplicaSetOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/ReplicaSetRollingUpdater.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
Fix #4826
In looking at #4826 it was clear that #4140 was incomplete.  ImageEditReplacePatchable is problematic in several ways - kubectl no longer provides the ability to have client side rollouts of replicasets and replicationcontrollers, so I'm proposing to deprecate the whole interface and the timeout related methods - at this also means there's no reason to keep the rollingTimeout RequestConfig option.  Beyond that the design of the interface leaves access to methods that are unrelated to rollout after timeout is called - to this end instead on inheriting from EditReplacePatchable, a narrower ImageUpdateable has been added and the only method that was actually implemented as respecting the rollout, edit, has been moved up to the ImageEditReplacePatchable interface.
To keep conflicts …
=> fix #4826: refining / deprecating rollout logic

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
Part of #4724 
Expose these nested config classes so that they can be used in reflection.
=> fix (kubernetes-client-api) : Make Config's ExecCredential nested classes `public` (#4724)

CHANGELOG.md, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyWebSocket.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpWebSocketImpl.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocket.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListener.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListenerTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java
Fixes #4891.  The WebSocket interface borrowed from the jdk implementation a requirement of calling request before seeing onClose.  However that requirement was not implemented in the vertx httpclient.  Rather than add backpressure there, a similar fix was added as was done in #4885 - which is if we are doing async handling of onMessage that we'll queue the handling of onClose until after the message processing has completed.  That makes things consistent between asyncbody and websockets.  The jdk implementation will be the only one that requires request to be called to deliver onClose.
Neither this fix nor #4885 explain the issue seen with websocket writes and containerd kube runtimes.  Still not sure what is going on there.
=> fix #4891: removing the backpressure for close

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationContext.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupportTest.java, kubernetes-itests/src/test/java/io/fabric8/openshift/BuildIT.java, openshift-client/pom.xml, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsImpl.java, openshift-client/src/test/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsImplTest.java
Fix https://github.com/eclipse/jkube/issues/2024
`BuildConfigs.instantiateBinary().fromFile()` no longer times out based on the RequestConfig default read timeout value.
This PR addresses a bug present in `OperationSupport` where the overridden settings for RequestConfig in the `OperationContext` were ignored.
The PR fixes the problem with BuildConfig by overriding the `requestTimeout` value for the context `RequestConfig` whenever a `withTimeout` value is provided in the context. It will also default the RequestConfig `requestTimeout` initial timeout to `0` which will effectively disable the client-side timeout kill we perform at `OperationSupport.waitForResult()`:
https://github.com/fabric8io/kubernetes-client/blob/d0ad0140437a22c7b04f08ed9700fbb2ffb8d73a/kubernetes-client/src/main/java/ …
=> fix: BuildConfigs.instantiateBinary().fromFile() does not time out

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientBuilderImpl.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientFactory.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientFactoryTest.java
=> fix: OkHttpClientFactory.additionalConfig can be used to override the default OkHttp Dispatcher

CHANGELOG.md, httpclient-tests/src/test/java/io/fabric8/kubernetes/client/http/OkHttpClientTest.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpRequest.java
Fix #4908 
Minor change to the vertx logic to expose the proper response headers.
=> fix #4908: using the response headers in the vertx response

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/URLFromEnvVarsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/URLFromIngressImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/internal/URLFromServiceUtil.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/URLFromEnvVarsImplTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/URLFromIngressImplTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/internal/URLFromServiceUtilTest.java
Fix #4906 
URLFromIngressImpl should handle `networking.k8s.io/v1` Ingress well.
=> fix (kubernetes-client) : URLFromIngressImpl doesn't consider Ingress in `networking.k8s.io` apiGroup (#4906)

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java
Relates to https://github.com/quarkusio/quarkus/pull/31503
=> fix: typo in HttpClient.Factory scoring system logic

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodExecTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
In trying to run the other clients against the kubernetes-tests, WatchTest had a failure - responding with 200, null was actually providing the literal "null" result.  This is not seen by the okhttp logic because it doesn't provide the response to websocket request exceptions, but we do for the other client types.  Treating this as a status creates a null value and ensuing NPE - but that is swallowed by the current exception handling.  These changes make everything appropriately defensive.
=> fix #4924: handles non-okhttp clients with invalid watch status

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/Reflector.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/InformTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicaSetTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicationControllerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java, kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
Fix #4888
Narrowing the usage of 0 initial resourceVersion.  We don't want to do this if:
- there's a limit specified as it will be ignored by the api server.
- there's initialState specified, since we don't know what the initial resourceVersion is.  While things will be eventually consistent, it's best not to have any misleading events
- we're doing some version of a wait or informOnCondition - as we saw with a couple integration tests that needed their conditions adjusted after this change, it can be unexpected that you are testing state from before the call is made - that is you create an resource, then make a waitOnCondition call and initially it appears that the resource doesn't exists.
This will mean that only direct usage of an informer will default to the 0/cached initial listing. …
=> fix #4888: narrowing where the 0 resourceVersion is used

CHANGELOG.md, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientFactory.java, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java
Fixes #4954 - it appears like expect continue support is not required, at least for our minikube tests.
=> fix #4954: disabling jdk expect continue by default

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxWebSocket.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWatchInputStream.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
Only 1 real issue was fully tracked down with #4910 / #4923 - vertx closeHandler is immediate.  That needs changed to the endHandler, which is notified in order.  Reviewing the vertx logic does also highlight that we'll have a problem if the server ever does send a ping - but that should not currently be the case.  The only "ping" sent currently is the 0 byte message.
For the common failures some additional debugging has been added to the failure message to narrow in on where the problem lies.
I had thought there was a concurrency issue with PodOperationsImpl.readTo, but that shouldn't be the case - the stream was still being closed in the calling method's try.
=> fix #4910 / #4923 addressing inconsistent behavior with exec streams

CHANGELOG.md, openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java, openshift-client/src/test/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptorTest.java
Fix #4970
Do not do token refresh on HTTP_FORBIDDEN response code in order to align better with kubectl and oc
=> fix (openshift-client) : OpenShiftOAuthInterceptor should not refresh on `403` response code (#4970)

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java
Fix #4960 
We should pick up currently logged in cluster's certificate data in case AuthProvider doesn't provide it.
=> fix (kubernetes-client-api) : Default to cluster cert data if `idp-certificate-authority-data` absent in AuthProvider config (#4960)

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/InputStreamReadStream.java, httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/HttpBodyStreamTest.java
Authored by @vietj
Relates to https://github.com/quarkusio/quarkus/issues/31872
The implementation of the InputStream to ReadStream adapter can sometimes do a stack overflow when the InputStream buffer extraction on a worker thread is faster than the event-loop. We should guard against this recursion and trampoline when the reads starts to pile (8).
=> Fix: Vert.x HttpClient stackoverflow

kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamTagIT.java
Fixes #4681 - the other image stream tag tests have waits on the related image stream before checking the tags.  It appears that listing needs to do that as well.
=> fix #4681: adding a wait for the list test

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtension.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/LeaderElectionRecord.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/ResourceLock.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElectorTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLockTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/resourcelock/LeaseLockTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LeaderElectionCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LeaderElectionTest.java
Fix #4477
Fix #4965 
Address #4477 and #4965 - in looking at 4477, I decided to address 4965 as well, but together as to avoid conflicts.  The only major changes here are:
* use merge instead of strategic merge.  This may only be an issue in an extreme corner case - the user specifies a finalizer or ownerReference in the meta provided to the lock configuration, and wants to modify the configmap or lease after the fact to add other finalizers or ownerRefereneces.  Because of the merge, those will be removed.
* moved the version off of the LeaderElectionRecord - in reviewing the go implementation they've introduced a couple of new lock types such that the version is not properly a construct of the record, but of the lock.  Because we're doing a patch we don't really use the whole record …
=> fix #4477 #4965: LeaderElector release public / crud mock compatibility

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java
Fix #4985 
A thread is held per connectionpool to clean idle connections on https://github.com/quarkusio/quarkus/issues/18973 we noticed that this is holding a quarkus classloader that eventually run tests out of memory.  There seems to be only two ways to address this immediately:
1. trigger the cleanup when the pool is empty with a notification that will wake up the job and let it exit.  This is of course not a full fledged part of their api and does change between versions, such that we have to get a hold of a different object.  This is the initial proposal.
2. Add logic that will provide more control over the idle timeout on the ConnectionPool - those are arguments to the pool constructor that can then be provided to the okhttp client builder.  However I'm not sure there's a good …
=> fix #4985: triggering the cleanup of the idle task

CHANGELOG.md, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java
Optimize `Quantity.parse` to avoid regex overhead. While reviewing some JFR profiles from a service using fabric8.io k8s client, I noticed some significant allocations and CPU time spent parsing quantities using regex from interacting with k8s APIs. We can avoid some of these overheads by simplifying the parsing to identify when and where to split quantity and units.
=> Optimize Quantity.parse to avoid regex overhead

httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java
Fix #5002 - moving completion until after headers have been set.
=> fix #5002: moving jetty response completion after headers

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PatchUtils.java
Fixes #4998 by pulling some code from #4662
There is some customization of the yaml output needed to match what jackson is doing - primarily quoting values, but not keys.   The only special case is that the y/n abbreviations as not recognized by snake yaml by default.
=> fix #4998: removing the usage of the yaml mapper

CHANGELOG.md, doc/FAQ.md, junit/kubernetes-junit-jupiter/pom.xml, kubernetes-client-api/pom.xml, kubernetes-client/pom.xml, kubernetes-tests/pom.xml, pom.xml
- bump BouncyCastle to 1.72
- use BouncyCastle JDK 1.8 compatible jars
=> Bump BouncyCastle dependencies

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractInterceptorTest.java
Relates to:
- https://github.com/eclipse/jkube/issues/1950
- https://github.com/eclipse/jkube/issues/2000
Added two more methods to the Interceptor interface. The main intention is to provide enough functionality to implement an `HttpLoggingInterceptor` compatible with every `HttpClient` implementation.
The provided infrastructure will allow to implement (in a subsequent PR) an `HttpLoggingInterceptor` to replace the OkHttp-specific intereceptor which is also flawed.
@shawkins thoughts? As far as I can see, these changes will enable the `HttpLoggingInterceptor` that can be activated based on the configured logging-level. If this one's OK, I'll send the interceptor implementation after merging.
=> feat: additional callback methods for Interceptor interface

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
=> fix: list found httpclient implementations and output selected one

CHANGELOG.md, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationWrappedPolymorphicTest.java, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/BeanPropertyWriterDelegate.java
Fix #5009 
Temporary alternative to #5010 until Istio issues get fixed or gets superseded by #4662
Support for JsonTypeInfo annotations in UnmatchedFieldTypeModule
=> (temp) Support for JsonTypeInfo annotations in UnmatchedFieldTypeModule

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java
Fix #4988 
The prior location of the retry code did not require explicit closure because it was on top of consuming the the whole auto-closed response.  Now that it's been moved, we have to account for the closure before issuing the retry.
@manusa @rohanKanojia should we put in reference tracking cleanup as a fail safe?
=> fix #4988: ensuring the previous response is closed

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListener.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java, kubernetes-itests/src/test/resources/pod-it.yml
Fix #5033 - other clients need an explicit subprotocol.  Added an integration test as well.
=> fix #5033: allow port-forward to work with other clients

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWatchInputStream.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/ExecWatchInputStreamTest.java
Fix #5022 - for most scenarios coming from older releases with multiple exec streams, this will remove the need to proactively read them.  The additional buffering is being done as part of the consume call so sometimes this will mean that once the buffers are full, they must be drained to fill it back up again.
Ideally the user would supply a minimally blocking output stream directly to write into instead.
=> fix #5022: adds a small amount of additional buffering to exec streams

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientFactory.java
Disable Vert.x instance file caching
Port of https://github.com/quarkusio/quarkus/pull/32502
=> fix: disable Vert.x instance file caching

httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/InputStreamReadStream.java
See https://github.com/quarkusio/quarkus/issues/32285
=> Fix for InputStreamReadStream NPE issue

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/CacheImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorStore.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/SharedProcessor.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorStoreTest.java
Addresses the concern from #5015 by making resync a locked operation.  It is safe to do this because all of the resync events will get queued, so it's not a blocking operation as long as the underlying executor is not direct.  The only time the executor is backed by direct execution is for our internal informers, which do not use resync.
=> fix #5015: executing resync as a locked operation

httpclient-jdk/pom.xml, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java, httpclient-jdk/src/test/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpLoggingInterceptorTest.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClient.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyWebSocket.java, httpclient-jetty/src/test/java/io/fabric8/kubernetes/client/jetty/JettyHttpLoggingInterceptorTest.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientBuilderImpl.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientFactory.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpWebSocketImpl.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpHttpLoggingInterceptorTest.java, httpclient-vertx/pom.xml, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpRequest.java, httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/VertxHttpLoggingInterceptorTest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/AsyncBody.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/BufferUtil.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpLoggingInterceptor.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpRequest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpStatusMessage.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClientBuilder.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpRequest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocketHandshakeException.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocketResponse.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocketUpgradeResponse.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpLoggingInterceptorTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractInterceptorTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java
Relates to (should fix):
- https://github.com/eclipse/jkube/issues/1950
- https://github.com/eclipse/jkube/issues/2000
**PoC** to replace the OkHttp-specific `HttpLoggingInterceptor` with a Fabric8-specific implementation that works across all of our `HttpClient`s.
The `HttpLoggingInterceptor` implementation is following a deferred approach. This means that the messages are only logged once the server responds and the response is completely processed by the client. This allows to log the request (and its body), the response, and the response body in a neat and grouped way. Other alternatives can be considered.
The `Interceptor` interface `after` method had to be further modified (on top of changes already provided in #5025), to allow to uniquely identify the original requests. HttpClients …
=> feat: generic HttpLoggingInterceptor

CHANGELOG.md, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkWebSocketImpl.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClientBuilder.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyWebSocket.java, httpclient-jetty/src/test/java/io/fabric8/kubernetes/client/jetty/JettyWebSocketTest.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpWebSocketImpl.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientBuilder.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxWebSocket.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocket.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListenerTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListenerTest.java
Addresses the additional concerns raised in #5036
This still needs to increase or allow setting the relevant limits in vertx and jetty.
cc @vietj 
=> fix #5036: addressing the handling of non-connection errors

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Client.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/NamespacedKubernetesClientAdapter.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ClientAdapter.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpRequest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestHttpResponse.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperationTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/DryRunTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/PatchTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/ClientIT.java, openshift-client/src/test/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsImplTest.java
Fix #5041 with very simple raw method. 
Some alternatives / additional work:
- additionally, or instead, provide non-blocking methods
- add more methods around the proxy url construction
Any scenario beyond this - requiring the manipulation of headers for example - we can direct the user to use HttpClient.
=> fix #5041: adding raw methods

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/InputStreamReadStream.java
fix: prevent runtime issues when running with Vert.x HTTP client in native mode
/cc @metacosm @geoand 
=> fix: prevent runtime issues when running with Vert.x HTTP client in native mode

httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClient.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyWebSocket.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpWebSocketImpl.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocketResponse.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/WebSocketUpgradeResponse.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpLoggingInterceptorTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java
Fix #5088
Changed a couple of test expectations to look for the last message first.
Also changed the WebSocketResponse to clearly be either the WebSocket or an exception.
=> fix #5088: adding a few more test timeouts

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/test/resources/test-kubeconfig-exec, kubernetes-client-api/src/test/resources/test-kubeconfig-exec-args-with-spaces, kubernetes-client-api/src/test/resources/test-kubeconfig-exec-args-with-spaces-windows, kubernetes-client-api/src/test/resources/test-kubeconfig-exec-null-args, kubernetes-client-api/src/test/resources/test-kubeconfig-exec-win, kubernetes-client-api/src/test/resources/test-kubeconfig-exec-win-null-args, kubernetes-client-api/src/test/resources/token-generator, kubernetes-client-api/src/test/resources/token-generator-win.bat
Fix #5035 
The initial version check doesn't seem necessary given that we're only trying to obtain the status token - and that schema is the same for all current version v1, v1beta1, v1alpha1.  Should a new/different schema come along, at worst we'll just report that the token is null.
=> fix #5035: removing initial execconfig version check

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestHttpResponse.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/DryRunTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/PatchTest.java, openshift-client/src/test/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsImplTest.java
Fix #5091 
Partially reverts #5064
We can't use `InputStream` yet for the parsing logic as thenApply will potentially use the io thread that needs to be free to deliver results.  We would need a non-blocking parser, or to first wait / return the operation to the calling thread before processing (but that doesn't quite line up to the current usage).
=> fix #5091 reverting to byte[] simple requests

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/HasMetadataOperation.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeploymentIT.java
Fixes the scale logic to be to wait on scale to 0.  Porting from the go implementation it wasn't obvious that the replica fields could be null as nil would be 0.
=> fix #5102: accounting for null replicas

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java
Fix #5100 
Not to beat a dead horse, but here's one more refinement.  Let me know if you would prefer the non-conflicting case at info instead.
=> fix #5100: lessening the level of the non-conflicting warning

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java
Fix #5095
After moving the retry logic, having the fail-safe enforcement of the requestTimeout above that does not make sense.  This moves the handling to the standard layer instead.
=> fix #5095: moving the enforcement to requestTimeout

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
fix: getHttpClientFactory LOGGER message is debug
The message describing the selected HttpClient.Factory should be visible only for debugging purposes.
=> fix: getHttpClientFactory LOGGER message is debug

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallback.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/apps/DeploymentConfigOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/impl/OpenShiftClientImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java, openshift-client/src/test/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsImplTest.java
Fixes #5121 
fix: RequestConfig is propagated to derived HttpClient instances
=> fix: RequestConfig is propagated to derived HttpClient instances

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpHeaders.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpHeaders.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/AsyncUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/AsyncUtilsTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
refactor: reduce StandardHttpClient retry complexity
- Abstracts the retryWithExponentialBackoff method so that it can be reused
- Provides specific testing for all scenarios
=> refactor: reduce StandardHttpClient retry complexity

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpHeaders.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestHttpResponse.java
refactor: don't expose StandardHttpHeaders internal Map
=> refactor: don't expose StandardHttpHeaders internal Map

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/test/resources/dummy-crd.yml, java-generator/it/src/it/escape-characters/src/test/java/io/fabric8/it/dummy/TestEscapeCharacters.java, java-generator/it/src/it/escape-characters/src/test/resources/dummy-crd.yml, java-generator/it/src/it/escape-characters/src/test/resources/sample.yaml
Fix https://github.com/fabric8io/kubernetes-client/issues/5164
=> [java-generator] handle more special characters in field names

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ServerSideApplicable.java
doc: adds Javadoc entry for ServerSideApplicable#serverSideApply
=> doc: adds Javadoc entry for ServerSideApplicable#serverSideApply

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/BufferUtil.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpLoggingInterceptor.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpLoggingInterceptorTest.java
Fix #5117 
Ensures the actual consumer is called, prevents decoding errors from logging the response, and showing the total bytes when truncated.
It is possible with the way we are doing decoding that multi-byte values could cross a single buffer, at which point we'll simply stop logging the response and consider it truncated.  We could improve upon that if needed.
=> fix #5117: correcting the call to the actual consumer, showing bytes

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientBuilder.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesSerialization.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/informers/cache/ReducedStateItemStoreTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/Handlers.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudWithCRDContextTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
A few naming refinements, cleanups, etc. mentioned on today's call.  While more verbose, we're more consistently using the the term KubernetesResource.
This also updates the constructor providing an objectmapper to elect to disable the classpath scanning via ServiceLoaders.  
I'm certainly open to refining this mechanism more once we be get more feedback on what's needed - in particular from Quarkus.
=> fix #4662: a few cleanups and exposing more control over the discovery

.github/workflows/release-snapshots.yaml, .github/workflows/release.yaml, pom.xml
Fixes #5168 
_Dirty_ workaround that allows the complete BOM (including Java11 modules) to be released.
CI workflows have been modified to manually deploy the generated BOMs. Note that since these project poms have no parent, the distribution management options must be provided as CLI arguments.
=> ci: release complete BOM

httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyWebSocket.java, httpclient-jetty/src/test/java/io/fabric8/kubernetes/client/jetty/JettyWebSocketTest.java
On more refinement to the Jetty handling
=> fix #5152: ensuring onClose can be called after channel closed

CHANGELOG.md, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientBuilderImpl.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClientBuilder.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClientFactory.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientBuilderImpl.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientFactory.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientFactoryTest.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientBuilder.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientFactory.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClientBuilder.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpHeaders.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java
Fix #5086
Fix #1335 
- Addresses #5086 by allowing socks proxy urls to be used.  A new config HttpClient.Builder property called proxyType was added for this.  Based upon the implementations I used an enum, but you could also consider using a just a string to capture support for things like socks5h.
- There was also a bug with the vertx client and proxy support - the auth header was not being applied for websocket requests. The common interceptor was refactored and applied to vertx as well
- Addresses #1335 / #5086 by ensuring that additionalConfig can be used consistently across the client types - and applied just before the final client is built so that its changes are not overriden.  The changes also try to infer when it's okay to default the proxy configuration to whatever is …
=> Various proxy changes

CHANGELOG.md, httpclient-jdk/src/test/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpConfiguredClientTest.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClient.java, httpclient-jetty/src/test/java/io/fabric8/kubernetes/client/jetty/JettyConfiguredClientTest.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpConfiguredClientTest.java, httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/VertxHttpConfiguredClientTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractConfiguredClientTest.java
Fix #5224 
Jetty needs to overwrite, rather than append headers because it sets the user-agent by default.
=> fix #5224: ensuring jetty sets the default user-agent

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
=> fix: crd-gen includes only enum values and discard enum fields

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/extensions/v1beta1/LegacyRollableScalableResourceOperation.java, kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/apps/DeploymentConfigOperationsImpl.java
Fix #5236
We can also consider turning the LegacyRollableScalableResourceOperation into just a utility, or just using that as the base scale logic if we suspect this will come up again.
=> fix #5236: using scale v1beta1 compatible logic for dc

CHANGELOG.md, doc/CHEATSHEET.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesSerialization.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/PatchUtilsTest.java
Resolves the discussion on #5214 - we'll treat the 6.6 / 6.7 behavior as a regression and switch to explicitly omitting nulls by default.
=> fix #5214: explicitly omitting nulls by default

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientBuilder.java
Fix #5235
Vert.x doesn't need to track derived HttpClients - prevents leakage
=> fix: vert.x doesn't need to track derived HttpClients - prevents leakage

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
=> fix #5238: Preserve folder structure again in PodUpload.upload()

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ContainerResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/CopyOrReadable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Execable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Loggable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/internal/PodOperationUtil.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/internal/PodOperationUtilTest.java, kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/apps/DeploymentConfigOperationsImpl.java, openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/build/BuildOperationsImpl.java
Fix #5229 
Addressing the timeout units and other exit conditions from the wait brought up on #5229
=> fix #5229: allowing for other exits from the readiness check

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpLoggingInterceptor.java
Some HttpClient implementations (OkHttpClientImpl) are sending downstream the originally received ByteBuffer(s).
This fix forces the interceptor to store a copy of the ByteBuffer so when the body is logged the buffer is not actually consumed
=> fix: HttpLoggingInterceptor uses response body ByteBuffer copy

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/NamespacedKubernetesClientAdapter.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ServiceAccountResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/TokenRequestable.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceAccountOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/KubernetesClientImpl.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceAccountOperationsImplTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceAccountTokenRequestIT.java, kubernetes-itests/src/test/resources/serviceaccounttokenrequest-it.yml, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceAccountTest.java
Fix #5133
+ Add new DSL method `tokenRequest()` in ServiceAccount DSL which will request apiserver for token for the given ServiceAccount.
+ Since this TokenRequest isn't any standard resource but subresource for ServiceAccount, add ServiceAccountResource in order to add new TokenRequestable interface for ServiceAccount
=> feat (kubernetes-client-api) : Support for using TokenRequest for existing ServiceAccount (#5133)

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Resource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Waitable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
Addresses #2718 by expanding the javadocs around readiness
=> fix #2718 minor changes related to readiness

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupportTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ErrorMessageTest.java
Fix #5166 
+ Remove opinionated status code to message mappings from Config
+ Deprecate Config.errorMessages field in favor of kubernetes status
+ Update OperationSupport to only rely on Kubernetes status for error messages
=> fix (kubernetes-client-api) : Remove opinionated messages from Config's `errorMessages` and deprecate it (#5166)

doc/CHEATSHEET.md
added a section demonstrating same context configuration by Resource Typed API vs. Resource Typeless API
=> Added example for Resource Typed API vs. Resource Typeless API to doc/CHEATSHEET.md

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/KubernetesClientImpl.java
This allows implementations to customize the default adapters and handlers being registered for a specific client
Just a minor refactoring in the `KubernetesClientImpl` moving the default registration of handlers and adapters in protected methods
=> chore(impl): Extract registration of adapters and handlers into protected methods

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/InternalSchemaSwaps.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/annotation/SchemaSwap.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/CollectionCyclicSchemaSwap.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/CyclicSchemaSwap.java, crd-generator/api/src/test/java/io/fabric8/crd/example/extraction/NestedSchemaSwap.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/keycloak/KeycloakRealm.java, doc/CRD-generator.md
Fix #5233 
Based upon https://github.com/keycloak/keycloak/issues/12725 it would be good to allow for configurable expansion depths.  Using the Any type as the terminal swap should also allow the content to be free-form under that.  I think this should eliminate the need for creating the intermidiate classes.
A couple of thoughts:
- there's still no default expansion depth, if a cycle is detected, then an exception will be thrown
- the cycle detection doesn't seem to work for non-collection properties, but at worst that just gives a stackoverflow so that could be addressed separately
- the naming or javadocs may need tweaked or examples added
cc @andreaTP 
=> fix #5233: allowing schemaswap to have a configurable level

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/WatchEventsListener.java
Fix #5293 
Deserialization may fail if resources are relying upon deserialization customization.  This is just a narrow change.  A broader one would be to remove the static use of Serialization and instead use a KubernetesDeserialization that performs no scanning / registration of classes - it will then naturally use GenericKubernetesResource for everything.
cc @metacosm 
=> fix #5293: removing all typed parsing

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
Fix #5221
+ Rather than directly deserializing `.kube/config` file content in `io.fabric8.kubernetes.api.model.Config`, do it only when `.kube/config` file content is non-blank.
+ Address cognitive complexity sonar warning in loadFromKubeconfig method
=> fix (kubernetes-client-api) : Check KubeConfig file contents if null/empty before deserialization (#5221)

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitiveNameAndType.java, java-generator/core/src/test/resources/crontab-crd.yml, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testCrontabCrd.approved.txt, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testCrontabExtraAnnotationsCrd.approved.txt, java-generator/it/src/it/default-values-instantiation/src/test/java/io/fabric8/it/certmanager/TestDefaultValues.java, java-generator/it/src/it/default-values-instantiation/src/test/resources/example.yaml, java-generator/it/src/it/enum-ser-deser/src/test/java/io/fabric8/it/certmanager/TestEnumSerialization.java, java-generator/it/src/it/enum-ser-deser/src/test/resources/cert-manager.crds.1.7.1.yaml, java-generator/it/src/it/enum-ser-deser/src/test/resources/sample1.yaml, java-generator/it/src/it/plugin/.gitignore
This PR adds native support for `date-time` format of fields of type `string`.
Please note that this is a breaking change, we should at least bump the minor version to introduce it.
`date-time` native parsing is very useful, especially in the standard `Conditions` in the `Status` stanza (e.g. https://maelvls.dev/kubernetes-conditions/ `lastTransitionTime`).
=> [java-generator] Add native support for date-time fields

httpclient-tests/src/test/java/io/fabric8/kubernetes/client/http/OkHttpClientTest.java
Fix #5260 
Removes a test with occasional failures likely due to reusing a test endpoint.
=> fix #5260: removing redundant flakey test

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/Reflector.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/ReflectorTest.java
Partially addresses: #5327
There are two parts to the issue:
- ensure that all async tasks terminate, which is what this commit does and is suitable for backport.  Prior to this fix I think that informers created by a client, but that are not explicitly closed, will leak a task (which has a reference to the full client) in the scheduler queue indefinitely.  After this fix they will eventually be expunged once the timeout is reached.
- a larger change is needed to perform proactive cleanup of scheduled tasks when the client is closed - only the executor is currently passed around and we don't have a completeablefuture or other callback mechanism for registering things that closable.  Most of the relevant timeouts are short and/or cleanup will be triggered by the failure of the httpclient. …
=> ensuring that the reconnect task terminates

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/task.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yml, .github/workflows/e2e-tests.yml, .github/workflows/gobuild.yml, .github/workflows/javadocs.yml, .github/workflows/sonar.yml, .github/workflows/style-checks.yml, .github/workflows/windows-build.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, doc/CHEATSHEET.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/CreateOrReplaceable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Replaceable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/cache/Indexer.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/SharedInformerFactoryImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/SharedProcessor.java
=> chore(ci): Change default branch to `main`

CHANGELOG.md, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClientFactory.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/behavior/RequestTimeoutTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/behavior/UploadTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceAccountOperationsImplTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java, openshift-client/src/test/java/io/fabric8/openshift/client/dsl/internal/build/BuildConfigOperationsTimeoutTest.java
Set bignumbermode when creating tar files for uploading to pod.
Bignumbermode is required to support large UIDs, which are commonly used on e.g. Openshift.
Integration tests already do the same thing:
https://github.com/fabric8io/kubernetes-client/blob/f6ea58c62e818a53f6c261a1c7a9549c138c8d88/kubernetes-itests/src/test/java/io/fabric8/openshift/BuildIT.java#L125
Bugfix, to avoid this type of error:
```
Caused by: java.lang.IllegalArgumentException: user id '1000990000' is too big ( > 2097151 ).
at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:406)
at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:400)
at org.apache.commons.compress.archivers.tar.TarArchiveOutputStr …
```
=> set bignumbermode when creating tar for upload to pod

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractCustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/CustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/CustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddAdditionPrinterColumnDecorator.java, crd-generator/api/src/test/java/io/fabric8/crd/example/joke/JokeRequestSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/ResourcesTest.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/zookeeper/ZookeeperCustomResourceTest.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/zookeeper/v1/ZookeeperStatus.java, doc/CRD-generator.md, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/PrinterColumn.java
=> feat: #5339 include priority field in the PrinterColumn

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/annotation/PrinterColumn.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AdditionalPrinterColumnDetector.java, crd-generator/api/src/test/java/io/fabric8/crd/example/joke/JokeRequestSpec.java, doc/CRD-generator.md
=> Deprecate PrinterColumn annotation to move it to the crd-generator module

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManagerTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperationTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/InformTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NodeMetricsTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodMetricsTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
Since we directly expose ListOptions, it's good to keep it up-to-date - to future-proof it logic was switched to serialization.  This accounts for several missing properties including includeInitialEvents and resourceVersionMatch.  
Closes #5368
=> adding support for new list options

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/it/src/it/escape-characters/src/test/java/io/fabric8/it/dummy/TestEscapeCharacters.java, java-generator/it/src/it/escape-characters/src/test/resources/dummy-crd.yml, java-generator/it/src/it/escape-characters/src/test/resources/sample.yaml
=> [java-generator] Avoid to emit Java Keywords as package names

CHANGELOG.md, pom.xml
=> removes the vertx-uri-template dependency

CHANGELOG.md, doc/FAQ.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/CreateOrReplaceable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/NonDeletingOperation.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ExtensibleResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ExtensibleResourceAdapter.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ResourceAdapter.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CreateOrTest.java
Covers one of the cases described in #5377 
As mentioned on https://github.com/fabric8io/kubernetes-client/issues/5337#issuecomment-1653494385 one path to createOrReplace replacement is offering alternative dsl.  It's a bit more work to do something like createIfNotFound - we'll need an additional context flag, and some new interfaces, so this shows what createOr method and unlock method would look like:
resource.createOrReplace() -> resource.unlock().createOr(NonDeletingOperation::upadate)
This means the user depending on the scenario may leave the operation as locked or use a json patch instead, for example:
resource.createOr(NonDeletingOperation::patch)
The thing that reads a little oddly is the use of the NonDeletingOperation - that is the first parent interface that knows about both …
=> operations to generalize createOrReplace

.github/workflows/e2e-chaos-tests.yml, chaos-tests/README.md, chaos-tests/pom.xml, chaos-tests/src/main/java/io/fabric8/it/CheckerCommand.java, chaos-tests/src/main/java/io/fabric8/it/ControlCommand.java, chaos-tests/src/test/java/ChaosIT.java
Simplified Chaos Tests configuration to allow for a single Maven execution.
=> test:refactor: Chaos tests require single Maven execution

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/ExpectationsTest.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
=> fix: OkHttpClientImpl supports setting request method for empty payload requests

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/ErrorStreamMessage.java, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/StatusStreamMessage.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/ErrorStreamMessageTest.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/OutputStreamMessageTest.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/StatusStreamMessageTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
=> Fix #5257: Add ErrorStreamMessage and StatusStreamMessage to ease mocking of pods/exec requests

CHANGELOG.md, doc/java-generation-from-CRD.md, java-generator/cli/src/main/java/io/fabric8/java/generator/cli/GenerateJavaSources.java, java-generator/core/src/main/java/io/fabric8/java/generator/Config.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/test/java/io/fabric8/java/generator/ConfigTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/gradle-plugin/src/main/java/io/fabric8/java/generator/gradle/plugin/JavaGeneratorPluginExtension.java, java-generator/it/src/it/crd-names/pom.xml, java-generator/it/src/it/datetime-fmt/pom.xml, java-generator/it/src/it/escape-characters/pom.xml, java-generator/it/src/it/preserve-unknown-objects-through-config/invoker.properties, java-generator/it/src/it/preserve-unknown-objects-through-config/pom.xml, java-generator/it/src/it/preserve-unknown-objects-through-config/src/test/java/io/fabric8/it/certmanager/TestPreserveUnkonwnUsabilityFromConfig.java, java-generator/it/src/it/preserve-unknown-objects-through-config/src/test/resources/dapr-components-crd.yaml, java-generator/it/src/it/preserve-unknown-objects-through-config/src/test/resources/sample.yaml, java-generator/it/src/it/preserve-unknown-objects/pom.xml, java-generator/it/src/it/preserve-unknown-serdeser/pom.xml, java-generator/it/src/it/ser-deser/pom.xml, java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java
=> [java-generator] Add the possibility to always emit `additionalProperties` on generated POJOs

.github/workflows/e2e-chaos-tests.yml
ci:fix: workflow concurrency id for chaos tests is unique
=> ci:fix: workflow concurrency id for chaos tests is unique

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Continuation of the previous fix that ensures informers stop when the client is closed.  This approach was easier than going back and adding a stateful scheduler - that should still be considered as it will ensure the purging of all tasks.
Also moving / tweaking the log of client closure
Closes #5327
=> Adds more proactive shutdown of informers

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java
Unexpected responses with creating a Status in OperationSupport are now causing exceptions to be thrown, we should just catch the exceptions instead.
Closes #5466
=> fix: OperationSupport should not fail trying to parse Status

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/Keywords.java, java-generator/core/src/test/java/io/fabric8/java/generator/CompilationTest.java, java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java, java-generator/core/src/test/resources/emissary-crds.yaml, java-generator/it/src/it/default-values-instantiation/src/test/java/io/fabric8/it/certmanager/TestDefaultValues.java, java-generator/it/src/it/default-values-instantiation/src/test/resources/example.yaml, java-generator/it/src/it/ser-deser/src/test/java/io/fabric8/it/certmanager/TestSerialization.java, java-generator/it/src/it/ser-deser/src/test/resources/cert-manager.crds.1.7.1.yaml, java-generator/it/src/it/ser-deser/src/test/resources/sample8.yaml
=> [java-generator] Correctly handle numeric enums

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java
Adds Config.onlyHttpWatches to control if WebSocket watches should be attempted.
There are a couple of considerations here:
1. Because detecting specifically a timeoutexception may be problematic across our client implementations, the code now for any non-handshake exception will try a http watch.
2. The standard retry logic will cause a 503 or timeout response to generally be retried - this will look instead like a long pause when attempting the websocket connection, which may then succeed as a regular http request.  This is captured at a debug level, but it could be something that we want more visible.
Closes #4624
=> adds a config property to control the use of http watches

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
Assuems that #5379 will be reopened.  Ensures that the futures will be notified when the client closes.
Closes #5379 
=> fix: making dsl waits aware of client close

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/V1AuthenticationAPIGroupDSL.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/V1beta1AdmissionRegistrationAPIGroupDSL.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/V1AuthenticationAPIGroupClient.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/V1beta1AdmissionRegistrationAPIGroupClient.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1SelfSubjectReviewTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1beta1ValidatingAdmissionPolicyBindingTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1beta1ValidatingAdmissionPolicyTest.java, kubernetes-tests/src/test/resources/test-v1beta1-validatingadmissionpolicy.yml, kubernetes-tests/src/test/resources/test-v1beta1-validatingadmissionpolicybinding.yml
Fix #5401
Follow up to #5472 
Add KubernetesClient DSL entrypoints for these resources:
- admissionregistration.k8s.io/v1beta1 ValidatingAdmissionPolicy `client.admissionRegistration().v1beta1().validatingAdmissionPolicies()`
- admissionregistration.k8s.io/v1beta1 ValidatingAdmissionPolicyBinding `client.admissionRegistration().v1beta1().validatingAdmissionPolicyBindings()`
- authentication.k8s.io/v1 SelfSubjectReview `client.authentication().v1().selfSubjectReviews()`
=> feat (kubernetes-client) : Add DSL entrypoints for Kubernetes 1.28.2 resources (#5401)

CHANGELOG.md, crd-generator/api/pom.xml, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java, crd-generator/test/pom.xml, crd-generator/test/src/test/java/io/fabric8/crd/generator/zookeeper/ZookeeperCustomResourceTest.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/zookeeper/v1/ZookeeperSpec.java
=> [crd-generator] Fix fallback value of `Default` annotation in presence of multiple accessors

crd-generator/apt/src/main/java/io/fabric8/crd/generator/apt/CustomResourceAnnotationProcessor.java
There are warnings that we're using an unsupported version when using annotation processors, this should address this problem, at least for the CRD generator.
```
[WARNING] No SupportedSourceVersion annotation found on io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor' less than -source '11'
```
=> fix: unsupported java version

doc/CHEATSHEET.md
Fix #5176
Update doc/CHEATSHEET.md to remove usages of createOrReplace methods since it's been deprecated. 
+ Use `create()` or `serverSideApply()` as alternatives wherever applicable.
+ Remove outdated reference to `createOrReplaceAnd()` DSL method
+ Replace `createOrReplace()` with outdated `deleteExisting()` DSL method with two separate calls.
=> doc : Replace `createOrReplace()` entries in CHEATSHEET with `create()` or `serverSideApply()` (#5176)

CHANGELOG.md, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/TypeInferenceTest.java, pom.xml
Fixes #5522
fix: type inference fixed by bumping Sundrio to 0.101.2
see https://github.com/sundrio/sundrio/pull/431
=> fix: type inference fixed by bumping Sundrio to 0.101.2

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/VisitorTest.java
test: adds test to verify visitables
Relates to https://github.com/sundrio/sundrio/issues/438
=> test: adds test to verify visitables

pom.xml
With the mock web server migrated into this repo zjsonpatch is now a production rather than test dependency.
The duplicate property definition has the potential to cause issues for tools which process the pom even if the `kubernetetes-client` build itself is un-affected (as both properties defined the same version).
=> Remove duplicate zjsonpatch version property declaration.

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpLoggingInterceptorTest.java
Fix #5251
Add a unit test in AbstractHttpLoggingInterceptor to verify response bytes are not consumed after they've been processed by HttpLoggingInterceptor.
I've verified that test fails when I revert https://github.com/fabric8io/kubernetes-client/pull/5250 in `httpclient-okhttp` and `httpclient-vertx` modules
=> test (kubernetes-client-api) : Add test in AbstractHttpLoggingInterceptor to not consume response bytes (#5251)

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AdditionalPrinterColumnDetector.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedPropertyPathDetector.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/LabelSelectorPathDetector.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/SpecReplicasPathDetector.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/StatusReplicasPathDetector.java, crd-generator/api/src/test/java/io/fabric8/crd/example/map/ContainingMaps.java
closes #5584
It doesn't seem like we need traversal below java. classes as we're only looking for our annotations.  Also we can switch to an iterative traversal, which should be less likely to blow out.
cc @andreaTP 
=> fix: adds filtering and switches to iterative traversal

README.md
The link doesn't work anymore.
=> [chore] Remove dangling link to platform

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java
**Context**: Trying to create KubeVirt model from CRDs. I am hitting an error as it seems that enum constants defined in the CRD are added twice.
This pull request changes JEnum to use Set instead of List to prevent any chance of having dublicate enum constants.
=> Fix duplicate enum constant in java generator

CHANGELOG.md, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientBuilderImpl.java, httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClient.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClientBuilder.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientBuilderImpl.java, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientBuilder.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClientBuilder.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
I completely missed the need for cleanup with the proactive closing of informers with #5327.  Unfortunately this affects both implicit and explicit usage of informers.  An alternative approach is to track if the client has been closed - I had initially avoided that because it's more work, as you can see from this pr.  This approach though doesn't have much risk other than some code complexity.
The only other possibility would be to track a set of informers on the BaseClient and close them using the completablefuture, but that will also require actively removing entires from the set once they've already been closed.
Fixes #5626
=> fix: prevents memory accumulation from informers

CHANGELOG.md, pom.xml
This is a PR to fix [CVE-2023-3635](https://nvd.nist.gov/vuln/detail/CVE-2023-3635)
The patch has been backported to branch 1.x thru https://github.com/square/okio/pull/1334 
fix #5485
=> Update `okio` to version 1.17.6

junit/mockwebserver/pom.xml, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerCrudTest.groovy, pom.xml
Part of #5632
Updates DefaultMockWebServerCrudTest to use Vert.x instead of OkHttp to perform the verifications.
This will allow to completely remove OkHttp in a future refactor of the `mockwebserver` module (#5613). Having the tests in  Vert.x will allow us to ensure that the functionality still works without modifying the tests.
=> refactor(mockwebserver): DefaultMockServerCrudTest uses Vert.x to perform verifications

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/crud/CrudDispatcherTest.groovy
Part of #5632
Updates CrudDispatcherTest to use Vert.x instead of OkHttp to perform the verifications.
This will allow to completely remove OkHttp in a future refactor of the `mockwebserver` module (#5613). Having the tests in  Vert.x will allow us to ensure that the functionality still works without modifying the tests.
=> refactor(mockwebserver): CrudDispatcherTest uses Vert.x to perform verifications

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerCrudTest.groovy
test: fix MockWebServer crud test concurrency issue
=> test: fix MockWebServer crud test concurrency issue

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerTest.groovy
Part of #5632
Updates DefaultMockServerTest to use Vert.x instead of OkHttp to perform the verifications.
This will allow to completely remove OkHttp in a future refactor of the `mockwebserver` module (#5613). Having the tests in  Vert.x will allow us to ensure that the functionality still works without modifying the tests.
=> refactor(mockwebserver): DefaultMockServerTest uses Vert.x to perform verifications

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerWebSocketTest.groovy
Part of #5632
Updates DefaultMockServerWebSocketTest to use Vert.x instead of OkHttp to perform the verifications.
This will allow to completely remove OkHttp in a future refactor of the `mockwebserver` module (#5613). Having the tests in  Vert.x will allow us to ensure that the functionality still works without modifying the tests.
=> refactor(mockwebserver): DefaultMockServerWebSocketTest uses Vert.x to perform verifications

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerAnyMethodTest.groovy
Part of #5632
test(mockwebserver): verify ANY method expectations
=> test(mockwebserver): verify ANY method expectations

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/behavior/UploadTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java
Fix #5527 
Using `/tmp` as upload directory can be problematic for scenarios where `/tmp` is read only. We can directly upload the intermediate upload tarball to the directory where we are uploading the content.
- In case of uploading a file to a Pod, temporary tarball would be uploaded in the parent directory of that file.
- In case of uploading a directory to a Pod, temporary tarball would be uploaded in the same directory that's specified for upload path.
Other minor changes:
- Replace deprecated `getNextTarEntry()` with `getNextEntry()` in UploadTest
- Refactor `getDirectoryFromFile` method to reuse logic for extracting directory from file path. For consistency we always add a trailing `/` at the end of file path.
=> fix (kubernetes-client) : Change Pod upload tarball location to target upload directory

junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/crud/Attribute.java, junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/crud/Key.java, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/crud/AttributeSetTest.groovy
Fixed the flaky test `when multiple attributes are specified it should examine all` inside the `AttributeSetTest` class
Detected flaky test `when setting an expectation as an object it should be serialized to json` inside the `DefaultMockServerTest` class.
Detected flaky tests `put /1, with missing item, should create item` `put /1, with existent item, should replace item` `get /1, with existent item, should return item` `get /, with one item, should return item` `get /, with multiple items, should return array` inside the `DefaultMockServerCrudTest` class.
All tests mentioned above have been reported as flaky when run with the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.
`when multiple attributes are specified it should examine all` inside the `AttributeSetTest` …
=> fix flaky test

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpClientProxyTest.java
Part of #5632
Make `AbstractHttpClientProxyTest` less reliant on OkHttp internals.
=> refactor: make AbstractHttpClientProxyTest less reliant on OkHttp internals

httpclient-tests/src/test/java/io/fabric8/kubernetes/client/http/OkHttpClientTest.java
Part of #5632
Make testWebsocketClientClose more reliable for async environments
=> test: make testWebsocketClientClose more reliable for async environments

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
Relates to https://github.com/quarkusio/quarkus/issues/37939
fix: ExecCredential doesn't fail with unsupported command output
=> fix: ExecCredential doesn't fail with unsupported command output

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/FlowControlAPIGroupDSL.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/V1FlowControlAPIGroupDSL.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/FlowControlAPIGroupClient.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/KubernetesClientImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/V1FlowControlAPIGroupClient.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1FlowSchemaTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1PriorityLevelConfigurationTest.java, kubernetes-tests/src/test/resources/v1-flowschema.yaml, kubernetes-tests/src/test/resources/v1-prioritylevelconfiguration.yaml
Related to #5643 
Add the following DSL entrypoints for KubernetesClient:
- `client.flowControl().v1().priorityLevelConfigurations()`
- `client.flowControl().v1().flowSchema()`
=> feat (kubernetes-client-api) : Add DSL for `flowcontrol.apiserver.k8s.io` `v1` apiVersion

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/EditReplacePatchable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/EphemeralContainersResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ItemWritableOperation.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/NonDeletingOperation.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/PodResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Replaceable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Updatable.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ExtensibleResource.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ExtensibleResourceAdapter.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ResourceAdapter.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodEphemeralContainersIT.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
also adding a general subresource method - to make this a little cleaner the existing status specific methods are moved off of what is obtained when you call subresource or ephemeralContainers
closes #5496
=> fix: adding PodResource.patchReadinessGateStatus

CHANGELOG.md, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/HasMetadataTest.java
Checks is owner references are correct in terms of scope and namespaces:
1. The referenced object should not be from different namespace (if both are namespaced objects)
2. Cluster scoped object should not reference namespace scoped object
=> feat: owner reference validity check regarding scope and namespace

CHANGELOG.md, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/BaseExtension.java, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/KubernetesExtension.java, junit/kubernetes-junit-jupiter/src/test/java/io/fabric8/junit/jupiter/api/KubernetesTestWithNestedTest.java
fix: JUnit5 Kubernetes Extension works with Nested tests
Partially addresses #3032 for the kubernetes-junit-jupiter extension.
The kubernetes-server-mock extension still needs to be fixed (maybe after #5632)
=> fix: JUnit5 Kubernetes Extension works with Nested tests

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerTest.groovy
Fix #5713
- Modifies the description to make it accurate
- Removes unneeded and misleading test implementation section
=> test: fix test for expectSentWebSocketMessage to match specification

kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorListenerTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/impl/cache/SharedProcessorTest.java
fix: replace deprecated junit assertTrue import
=> fix: replace deprecated junit assertTrue import

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/HasMetadataOperationsImpl.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/GenericResourceIT.java
closes #5729
There are two additional thoughts here:
1. we should not need to, but we could do this for types other than generic if we add setKind to HasMetadata.
2. the logic is currently only doing this for lists as other operations and events doen't seem to have the same problem - but we could of course move the logic into the updateApiVersion if needed.
=> fix: ensures kind is set for generic resource lists

CHANGELOG.md, extensions/open-virtual-networking/client/pom.xml, extensions/open-virtual-networking/client/src/main/java/io/fabric8/ovn/client/DefaultOpenVirtualNetworkingClient.java, extensions/open-virtual-networking/client/src/main/java/io/fabric8/ovn/client/GenericOpenVirtualNetworkingClient.java, extensions/open-virtual-networking/client/src/main/java/io/fabric8/ovn/client/NamespacedOpenVirtualNetworkingClient.java, extensions/open-virtual-networking/client/src/main/java/io/fabric8/ovn/client/OpenVirtualNetworkingClient.java, extensions/open-virtual-networking/client/src/main/java/io/fabric8/ovn/client/OpenVirtualNetworkingExtensionAdapter.java, extensions/open-virtual-networking/client/src/main/java/io/fabric8/ovn/client/V1OpenVirtualNetworkingAPIGroupClient.java, extensions/open-virtual-networking/client/src/main/java/io/fabric8/ovn/client/dsl/V1OpenVirtualNetworkingAPIGroupDSL.java, extensions/open-virtual-networking/client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.extension.ExtensionAdapter, extensions/open-virtual-networking/client/src/test/java/io/fabric8/ovn/client/OpenVirtualNetworkingClientAdaptTest.java, extensions/open-virtual-networking/client/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, extensions/open-virtual-networking/pom.xml, extensions/open-virtual-networking/tests/pom.xml, extensions/open-virtual-networking/tests/src/test/java/io/fabric8/ovn/client/mock/AdaptTest.java, extensions/open-virtual-networking/tests/src/test/java/io/fabric8/ovn/client/mock/AdminPolicyBasedExternalRouteTest.java, extensions/open-virtual-networking/tests/src/test/java/io/fabric8/ovn/client/mock/EgressFirewallTest.java, extensions/open-virtual-networking/tests/src/test/java/io/fabric8/ovn/client/mock/EgressIPTest.java, extensions/open-virtual-networking/tests/src/test/java/io/fabric8/ovn/client/mock/EgressQoSTest.java, extensions/open-virtual-networking/tests/src/test/java/io/fabric8/ovn/client/mock/EgressServiceTest.java, pom.xml
Fix #5636
Add OpenVirtualNetworkingClient with entrypoint `v1()` which will expose the following resources:
- `ovnClient.v1().egressIps()`
- `ovnClient.v1().egressQoses()`
- `ovnClient.v1().egressFirewalls()`
- `ovnClient.v1().egressServices()`
- `ovnClient.v1().adminPolicyBasedExternalRoutes()`
User would need to add this dependency in order to use this extension:
```xml
<dependency>
<groupId>io.fabric8</groupId>
<artifactId>open-virtual-networking-client</artifactId>
<version>${fabric8.version}</version>
</dependency>
```
Here is an example of sample usage:
```java
try (OpenVirtualNetworkingClient ovnClient = new KubernetesClientBuilder().build().adapt(OpenVirtualNetworkingClient.class)) {
EgressFirewall egressFirewall = new EgressFirewallBuilder()
.withNewMetadata() …
```
=> feat (extensions) : Add DSL for Open Virtual Networking `k8s.ovn.org` API group resources

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElectorTest.java
closes: #5635
This should clear up a couple of points of confusion brought up on that issue. We can treat a request to have the LeaderElector be reusable as a separate enhancement.
=> fix: refined leaderelector lifecylce and logging

chaos-tests/src/test/java/ChaosIT.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Scalable.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PersistentVolumeClaimExample.java
Related to https://github.com/fabric8io/kubernetes-client/pull/5483
After bulk update of license headers due to minor change in license header format, some files got license header duplicated due to wrong positioning of license header earlier.
=> chore : Cleanup duplicate license in files after license-maven-plugin `4.3` upgrade

crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/CustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/SetDeprecatedVersionDecorator.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/CustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/SetDeprecatedVersionDecorator.java, crd-generator/api/src/test/java/io/fabric8/crd/example/deprecated/v1/DeprecationExample.java, crd-generator/api/src/test/java/io/fabric8/crd/example/deprecated/v1/DeprecationExampleSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/example/deprecated/v1beta1/DeprecationExample.java, crd-generator/api/src/test/java/io/fabric8/crd/example/deprecated/v1beta1/DeprecationExampleSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/example/deprecated/v2/DeprecationExample.java, crd-generator/api/src/test/java/io/fabric8/crd/example/deprecated/v2/DeprecationExampleSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java, crd-generator/apt/src/main/java/io/fabric8/crd/generator/apt/CustomResourceAnnotationProcessor.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/CustomResource.java, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/Version.java
Add support for deprecation warnings in CRDGenerator.
=> feat(crd-generator): Deprecation warning for CRD versions

.gitignore
.DS_Store, short for Desktop Services Store, is a hidden file created by MacOS to store custom attributes of a folder, such as the positions of icons or the choice of a background image. Whenever you open a folder using Finder, MacOS generates this file to remember your view settings for that particular folder.
When developers work on MacOs, they may find those .DS_Store file are track by git.
It's best practice for us to ignore this file with git.
Close #5805
=> Ignore .DS_Store file with Git

CHANGELOG.md, extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/TaskRunCreate.java, junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/NamespaceExtension.java, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PostHandler.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpRequest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/UtilsTest.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/BindingExample.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/SecretExamples.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/StorageClassExamples.java, kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/WatchExample.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/LeaderIT.java, kubernetes-itests/src/test/java/io/fabric8/openshift/BuildIT.java
Fix #5735
+ Port Spring's `SimpleIdGenerator.generateId` utility method to `Utils.generateId`
+ Use `Utils.generateId` in place of `UUID.randomUUID` across codebase, the only place where it's still being used is [WebSocketSession](https://github.com/fabric8io/kubernetes-client/blob/main/junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/internal/WebSocketSession.java) which doesn't have kubernetes-client-api as dependency.
=> fix: replaced usages of `UUID.randomUUID()` with UUID created via AtomicLong

doc/CRD-generator.md, generator-annotations/src/main/java/io/fabric8/generator/annotation/Default.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Max.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Min.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Nullable.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Pattern.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Required.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesVersionFactory.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesVersionPriority.java
- Describe multi-version support in CRD Generator docs
- Describe ValidationRule in CRD Generator docs
Closes #5793, Depends on #5788
=> chore(docs): Describe multi-version support and ValidationRule in docs for CRD Generator

junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtension.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtensionCloseTest.java, junit/openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtension.java
In `KubernetesMockServerExtension`, a `KubernetesClient` created by `beforeAll()` and a `KubernetesClient` created by `beforeEach()` share the same member field.
Say we have a test code that has a non-staic client field. A `KubernetesClient` created by `beforeAll()` gets overridden by a client created by `beforeEach()`. As a result, we lose the former client's reference, resulting in a leak.
```java
@EnableKubernetesMockClient
class KubernetesMockServerTest {
private KubernetesClient client;
...
}
```
=> Fix a bug where a test client is not closed in `KubernetesMockServerExtension`

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/Resources.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/EnsureSingleStorageVersionDecorator.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/EnsureSingleStorageVersionDecorator.java, crd-generator/api/src/test/java/io/fabric8/crd/example/multiple/v1/Multiple.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorAssertions.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorExamplesTest.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/ParallelCRDGeneratorExamplesTest.java, crd-generator/api/src/test/resources/multiples.sample.fabric8.io-v1.yml, crd-generator/api/src/test/resources/multiples.sample.fabric8.io-v1beta1.yml, crd-generator/test/src/test/java/io/fabric8/crd/generator/multiple/MultipleVersionsCRDTest.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/multiple/v1/Multiple.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/multiple/v1/MultipleSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/multiple/v2/Multiple.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/multiple/v2/MultipleSpec.java
Fixes a bug where the CRDGenerator allows generating CRDs with multiple versions marked as stored. 
Additional changes:
- Extract some assertions to a seperate class (reusing is planned in the next PRs)
- Allow debugging decorator sequence by changing the log level to trace
(refer to [simplelogger.properties](https://github.com/fabric8io/kubernetes-client/blob/main/crd-generator/api/src/test/resources/simplelogger.properties#L22) during test runs)
Fixes #5845 
=> fix(crd-generator): Fail if multiple versions are marked as stored

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractInterceptorTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractSimultaneousConnectionsTest.java
In Armeria CI, we saw Netty leak reports from kubernetes-client CI tests. After investigating, I found out that some of the tests did not consume `HttpResponse`. As a result, `ByteBuf`s were not subscribed to and remained in the Publisher's internal buffer.
I fixed to call `AsyncBody.consume()` in tests where it was not called before.
=> Drain `HttpResponse` in tests

CHANGELOG.md, log4j/pom.xml, log4j/src/test/java/io/fabric8/kubernetes/log4j/lookup/it/KubernetesLookupIT.java
Fix #5847
Due to a misconfiguration of the Maven Bundle Plugin, the Log4j Core plugin descriptor:
```
META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat
```
file is missing in the generated JAR.
This PR fixes the Maven configuration and adds a simple integration test to prevent ensure that `PluginManager` is able to detect the Kubernetes Lookup.
=> Fix #5847: missing Log4j Core plugin descriptor

.github/workflows/build.yml, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/behavior/UploadTest.java, platforms/karaf/pom.xml, pom.xml
=> Run CI with Java 17 and 21

.github/workflows/windows-build.yml, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java
ci: update windows pipeline to run on Java 17
Requires updating #3245 (#3244 #3243)
=> ci: update windows pipeline to run on Java 17

.github/workflows/release-snapshots.yaml, .github/workflows/release.yaml
ci:fix: kube-api-test child modules released with Java 11
Relates to #5898 
=> ci:fix: kube-api-test child modules released with Java 11

kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/JsonUnwrappedDeserializer.java, kubernetes-model-generator/kubernetes-model-common/src/test/java/io/fabric8/kubernetes/model/jackson/JsonUnwrappedDeserializerTest.java
fix: JsonUnwrappedDeserializer works when serialized data is not provided
Relates to #5182
=> fix: JsonUnwrappedDeserializer works when serialized data is not provided

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
improves the error message when a cycle is detected
=> task: improve the cycle error message

pom.xml
Follow up to Update okio to version 1.17.6 #5587 
=> Followup to Update `okio` to version 1.17.6

CHANGELOG.md, doc/java-generation-from-CRD.md
=> Update documentation to include dependencies

CHANGELOG.md, crd-generator/api/pom.xml, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/types/TypeMappingsTest.java
Fixes #5866
Addresses issues from #5866
Relies upon jackson to resolve java. / javax. classes.
Does not yet change the default serialization for time stuff, nor does it address being able to pass in the objectmapper.
=> Address issues from #5866 - improve built-in resolving

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testCrontabCrd.approved.txt, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testCrontabExtraAnnotationsCrd.approved.txt
=> Use JsonFormat shape in crd-generator and java-generator

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/test/resources/k8svalidations.samples.fabric8.io-v1.yml, crd-generator/api/src/test/resources/k8svalidations.samples.fabric8.io-v1beta1.yml
Sort required properties to ensure deterministic output
See also #5949
Fixes partially #5951
=> fix(crd-generator): Sort required properties to ensure deterministic output

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java
Fix #5605
feat: proxy configs support proxy URLs without a scheme
=> feat: proxy configs support proxy URLs without a scheme

crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/inherited/BaseSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/inherited/BaseStatus.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/inherited/ChildSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/json/ContainingJsonSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/k8svalidation/K8sValidationSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/k8svalidation/K8sValidationStatus.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/map/ContainingMaps.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/map/ContainingMapsSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/multipleversions/v1/MultipleSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/multipleversions/v2/MultipleSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/nocyclic/NoCyclicSpec.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/nocyclic/NoCyclicStatus.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/nocyclic/Ref.java
Part of #5951 / #5948
test(crd-generator): approval tests use lombok for proper serialization
Relates to:
- #5948
- #5951
- #5850
- #5978
- #5980
- #5986
=> test(crd-generator): approval tests use lombok for proper serialization

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java, crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java
relates to: #5951
No changelog is needed as this just adjusts the recently added feature.
=> fix: serialization type remains string even if the shape is different

CHANGELOG.md, crd-generator/api/src/main/java/io/fabric8/crd/generator/CRDGenerator.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/CustomResourceHandler.java, crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/JsonSchema.java
closes: #5947
Another deprecation notice about the annotation processing crd generator can be added after the plugins are ready.
=> fix: adding a v1beta1 deprecation notice

CHANGELOG.md, extensions/service-catalog/client/pom.xml, extensions/service-catalog/client/src/main/java/io/fabric8/servicecatalog/client/DefaultServiceCatalogClient.java, extensions/service-catalog/client/src/main/java/io/fabric8/servicecatalog/client/GenericServiceCatalogClient.java, extensions/service-catalog/client/src/main/java/io/fabric8/servicecatalog/client/NamespacedServiceCatalogClient.java, extensions/service-catalog/client/src/main/java/io/fabric8/servicecatalog/client/ServiceCatalogClient.java, extensions/service-catalog/client/src/main/java/io/fabric8/servicecatalog/client/ServiceCatalogExtensionAdapter.java, extensions/service-catalog/model/pom.xml
fix: deprecate service catalog extension
Closes #5990 
=> fix: deprecate service catalog extension

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElectorTest.java
=> refactor: LeaderElector::canBecomeLeader for clarity

crd-generator/api-v2/src/test/java/io/fabric8/crdv2/example/complex/k8s/ServiceSpec.java
Making sure https://github.com/fabric8io/kubernetes-client/issues/5417 could not be reproduced with crd-generator-v2
In the tests
- Updated `ServiceSpec` to use `Collection` instead of `List` for `loadBalancerSourceRanges`.
- Modified getter and setter methods for `loadBalancerSourceRanges` to use `Collection`.
- Confirmed that CRD generation produces a field of type array when using `Collection`, ensuring compatibility and correct schema output.
=> test(crd-generator-v2): ensure Collection properties work like List in CRD generation

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java, kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/HasMetadataTest.java
=> feat: add factory methods to help with SSA

java-generator/gradle-plugin/src/main/java/io/fabric8/java/generator/gradle/plugin/JavaGeneratorPlugin.java, java-generator/gradle-plugin/src/main/java/io/fabric8/java/generator/gradle/plugin/JavaGeneratorPluginExtension.java, java-generator/gradle-plugin/src/test/java/io/fabric8/java/generator/gradle/plugin/JavaGeneratorPluginTest.java
In order to support Gradle's configuration cache, having the Project object in extensions/tasks is not allowed https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:disallowed_types. We can avoid that by injecting the ProjectLayout object directly which is legal.
> There are a number of types that task instances must not reference from their fields. 
> These types fall into some categories as follows:
> - Live JVM state types
> - Gradle model types
> - Dependency management types
>
> In all cases the reason these types are disallowed is that their state cannot easily be stored or recreated by the configuration cache.
Specifically
> Gradle model types (e.g. Gradle, Settings, Project, SourceSet, Configuration etc…​) are usually used to carry some task …
=> Remove project from task extension

CHANGELOG.md, doc/FAQ.md, junit/kube-api-test/core/pom.xml, junit/kubernetes-junit-jupiter/pom.xml, kubernetes-client-api/pom.xml, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/PKCS1Util.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/CertUtilsTest.java, kubernetes-client/pom.xml, kubernetes-itests/pom.xml, kubernetes-tests/pom.xml, pom.xml
Removes the bc optional dependency
closes: #6008
=> fix: remove bc optional dependency

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorStore.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/SharedProcessor.java
The handling to make the informer behavior deterministic allows for the cache call to happen after shutdown. The simplest thing to do is to just swallow the rejected execution exception.
closes: #6059
=> fix: swallow rejected execution after shutdown

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerExtensionTest.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/MockServerKubeconfigTest.java, junit/openshift-server-mock/pom.xml, junit/openshift-server-mock/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtensionStaticTests.java, junit/openshift-server-mock/src/test/java/io/fabric8/openshift/client/server/mock/OpenShiftMockServerExtensionTests.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java
Related to https://github.com/eclipse-jkube/jkube/pull/3142
Fix #6068 
+ Add currentContext and contexts arguments to Config constructor in order to pass them to child class OpenShiftConfig
+ Add values for username, oauthToken, and currentContext to Config created by the Kubernetes Mock Server for 
KubernetesClient used in tests
=> fix (kubernetes-server-mock) : Add opinionated current context to KubernetesMockServer's initConfig

kubernetes-model-generator/kubernetes-model-core/cmd/generate/generate.go, kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/APIVersions.java, kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/KubeSchema.java, kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/ValidationSchema.java, kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/kube-schema.json, kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/validation-schema.json, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/APIVersionsTest.java, kubernetes-model-generator/kubernetes-model-core/src/test/resources/valid-apiversions.json
Related to #6066 
Add [APIVersions](https://github.com/kubernetes/apimachinery/blob/65a3763a09c052972b3398cf85abd354bc09675f/pkg/apis/meta/v1/types.go#L1067) model type from Kubernetes APIMachinery
=> feat (kubernetes-model-generator) : Add model type APIVersions to Kubernetes Core Model

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Client.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ClientAdapter.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/impl/APIVersionsTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/APIVersionsIT.java
Fix #6066 
~:construction: Requires #6088 to be merged first~
Add DSL entrypoint `getAPIVersions()` in Client interface
=> feat (kubernetes-client-api) : Add support for `v1.APIVersions` in KubernetesClient

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigSourcePrecedenceTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java, kubernetes-client-api/src/test/resources/config-source-precedence/kube-config, kubernetes-client-api/src/test/resources/config-source-precedence/serviceaccount/ca.crt, kubernetes-client-api/src/test/resources/config-source-precedence/serviceaccount/namespace, kubernetes-client-api/src/test/resources/config-source-precedence/serviceaccount/token, kubernetes-client-api/src/test/resources/test-serviceaccount/ca.crt, kubernetes-client-api/src/test/resources/test-serviceaccount/token, kubernetes-itests/src/test/java/io/fabric8/kubernetes/DisableAutoConfigurationIT.java
Prerequisite to #6153
- Add unit test for `@Deprecated` Config constructor. We don't know whether this public constructor is being used by any user. Adding a test just in case to verify that it behaves as expected.
- Organize tests in `ConfigTest` to be grouped under various load sources 
- Use AssertJ throughout the test for assertions
- Group common tests sharing common initialization logic in `@Nested` classes
- Add new test `ConfigSourcePrecedenceTest` for verifying Config source load precedence
=> test : Add unit test for old deprecated Config constructor

kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/InlineModelResolver.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ModelGenerator.java
=> fix(openapi): tone down logging statements

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigDisableAutoConfigurationIT.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java, kubernetes-client-api/src/test/resources/config-disable-autoconfiguration/kube-config, kubernetes-client-api/src/test/resources/config-disable-autoconfiguration/serviceaccount/namespace, kubernetes-client-api/src/test/resources/config-disable-autoconfiguration/serviceaccount/token, kubernetes-client-api/src/test/resources/config-source-precedence/serviceaccount/ca.crt
Follow Up to https://github.com/fabric8io/kubernetes-client/pull/6157
- Remove `@Nested` class `BuilderConfigured` as it doesn’t have any common setup, teardown blocks
- Remove these tests as [ConfigSourcePrecedenceTest](https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigSourcePrecedenceTest.java) already covered them:
- `testOverrideViaSystemProperties`
- `testSystemPropertiesAndBuilderGetMorePrecedenceOverKubeconfig`
- Rename tests with legacy names starting with `testXXXX`
- Add `@DisplayName` annotation for tests wherever applicable
- Remove `assertConfig` method and inline assertions in tests wherever it was getting used
- Remove abstract test class introduced in #6157 `AutoConfiguredDisabledScenarios`, …
=> test (kubernetes-client-api) : Remove redundant methods and nested classes in ConfigTest

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListener.java
=> fix: prevent logging of RejectedExecutionException

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadTest.java
=> fix(client): improve reliability of file upload to pod (#6212)

CHANGELOG.md, httpclient-jdk/src/test/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientPostTest.java, httpclient-jdk/src/test/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientPutTest.java, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java, httpclient-jetty/src/test/java/io/fabric8/kubernetes/client/jetty/JettyHttpPostTest.java, httpclient-jetty/src/test/java/io/fabric8/kubernetes/client/jetty/JettyHttpPutTest.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpPostTest.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpPutTest.java, httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientPostTest.java, httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientPutTest.java, junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/internal/MockDispatcher.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpPostTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpPutTest.java
When fixing #6143 it was observed that the Jetty client was not handling failures well. This PR fails the appropriate futures when failures are encountered.
=> Fix jetty completion handling to forward failures

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/ConfigBuilder.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/ConfigFluent.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/SundrioConfig.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigConstructorTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigDisableAutoConfigurationTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/SundrioConfigBuilderTest.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/DisableAutoConfigurationIT.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java, openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Fix #6137 
`Config`'s autoConfigure field should behave as per expectations.
We need to make changes to ConfigBuilder and ConfigFluent in order to achieve this.
- Add a new Constructor with additional boolean arguments `autoConfigure` and   `shouldSetDefaultValues`
- Add a new package private class `SundrioConfig` that would extend `Config` for generating the Sundrio Builder for Config
- Move generated classes `ConfigBuilder` and `ConfigFluent` to `src/main/java`
- `ConfigBuilder` would extend generated SundrioConfigBuilder and override the `build()` method by calling `disableAutoConfig()` if `autoConfigure` is not provided by the user. Earlier `ConfigBuidler` was calling `new Config()` (this was enabling auto configuration)
- Make all fields in Config and ResourceConfig classes use boxed …
=> fix (kubernetes-client-api) : `Config`'s `autoConfigure` should disable auto configuration

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractInterceptorTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java
Expands the HTTP interceptor API to include a call back for failed connection attempts as discussed in #6143 
Fixes #6143
Depends on the definition of breaking change as it adds a new `default` method to an interface which could be seen as a breaking change for any implementation that already has that method defined but practically speaking this is backwards compatible.
=> Expands the HTTP interceptor API to include a call back for failed connection attempts

kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java
The Go client has added the ability to multiply a Quantity by a scalar value: kubernetes/kubernetes#117411. I think it would be useful to have this feature in the Java client as well.
=> feat: add functionality to multiply Quantity by a scalar value

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigProxySourceTest.java, kubernetes-client-api/src/test/resources/config-proxy-source/kubeconfig-with-proxy-url
Prerequisite before fixing #6150
Add tests to ensure that current precedence of loading proxy Urls from various sources is preserved:
- `proxy-url` in cluster of kubeconfig (not supported as reported in #6150)
- `all.proxy` System Property
- `http.proxy` System Property
- `configBuilder.withHttpProxy()` in ConfigBuilder
=> test (kubernetes-client-api) : Add test for loading proxy Urls in KubernetesClient Config

java-generator/it/src/it/cert-manager/verify.groovy, java-generator/it/src/it/plugin/gradle/existing-java-types/src/main/java/io/fabric8/test/ExistingJavaTypes.java, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerAnyMethodTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerCrudTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerHttpsTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerWebSocketTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/JsonResponseComposer.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/MockServerExceptionTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/User.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/UserAttributeExtractor.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/crud/AttributeSetTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/crud/AttributeTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/crud/CrudDispatcherTest.groovy, kubernetes-model-generator/openapi/maven-plugin/src/it/kubernetes-model-core/verify.groovy, pom.xml
This change increases the scope of the spotless configuration to apply rules on groovy files and java files below `src/it/**`.
The change was originally introduced and discussed in [PR#5979](https://github.com/fabric8io/kubernetes-client/pull/5979) ([Discussion](https://github.com/fabric8io/kubernetes-client/pull/5979#discussion_r1717062166)).
=> style(groovy,it): Apply spotless on groovy files and java files in src/it/

.github/workflows/e2e-tests.yml
ci: bump k8s legacy to v1.14.10 (EOL 2019-12-11)
Getting some trouble on some of the CI execution pipelines. It seems that the images might not be available in some of the container registry mirrors.
=> ci: bump k8s legacy to v1.14.10 (EOL 2019-12-11)

README.md
Fix #6280 
Since 6.x Watcher `onClose` has `WatcherException` argument not `KubernetesClientException`
=> doc : Update wrong exception type in Watcher `onClose` argument

junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesResponseComposerTest.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/crud/KubernetesCrudDispatcherGetTest.java
Related to #6220 
KubernetesResponseComposer should infer list type from list items instead
of returning a hardcoded `List` kind value. Added tests to provide
desired expectations.
=> test (kubernetes-server-mock) : Add disabled tests for handing Kubernetes list types

CHANGELOG.md, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/AbstractJsonSchema.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/example/annotated/AnnotatedSpec.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/example/person/Person.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/v1/JsonSchemaTest.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Max.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Min.java, generator-annotations/src/main/java/io/fabric8/generator/annotation/Pattern.java
Allows Pattern, Min, and Max to be specified on List or Map component types. This initial version looks specifically for List and Map types - this may be too restrictive, but it keeps the logic simplier. If there is a method as the annotatedmember, it will use the same simple logic as the validation rules to find the field.
I also commented out getting the minLength / maxLength from the string schema for the min / max - that is currently not used and it's not correct as minLength / maxLength are distinct and set specfically for strings.
cc @adriansuarez
closes: #6282
=> fix: allow limited use of type annotations

pom.xml
Bumps [com.approvaltests:approvaltests](https://github.com/approvals/ApprovalTests.Java) from 24.3.0 to 24.5.0.
Supersedes closes: #6255 
Relates to: https://github.com/approvals/ApprovalTests.Java/issues/546
=> chore(deps): bump com.approvaltests:approvaltests from 24.3.0 to 24.5.0

kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/model/TemplateContextTest.java
=> test(openapi): isNamespaced for resources with no metadata

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java
Uses authentication user info from proxy url. 
This support will make it much easier for keycloak to work with a proxy. @manusa will there be another 6.13 release?
cc @aboullos
closes: #6247
=> fix: Support for proxy authentication from proxy URL user info

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java
close: #6354
Moves the source close to the dispatcher thread.
=> fix: moving source close to the executor (just like doConsume)

CHANGELOG.md, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/SettableBeanPropertyDelegate.java, kubernetes-model-generator/kubernetes-model-common/src/test/java/io/fabric8/kubernetes/model/jackson/SettableBeanPropertyDelegateTest.java
Fixes: fabric8io/kubernetes-client#6342
Changes the delegation in `SettableBeanPropertyDelegate` from a custom implementation to the standard way of implementing a delegating property in jackson. This way, if some jackson module overrides methods that are not delegated explicitely here, they will continue to work.
=> fix(model): Use SettableBeanProperty.Delegating for jackson delegation

httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClientBuilder.java, httpclient-jetty/src/test/java/io/fabric8/kubernetes/client/jetty/JettyHttpClientProxyHttpsTest.java, httpclient-okhttp/src/test/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientProxyHttpsTest.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientBuilder.java, httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientProxyHttpsTest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpClientProxyHttpsTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpClientProxyTest.java
Precedes (or supersedes) #6352 
Fixes #6350
This is an adaptation of #6352 with no breaking changes.
We can go forward with the changes in the HttpClient interfaces for proxy authorization credentials once this one is merged.
Please @shawkins, check everything aligns with the expected fix.
/cc @cescoffier
=> fix: allowing the usage of authenticated http proxies for https

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/AsyncUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/StandardHttpClientTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/AsyncUtilsTest.java
Changes should retry to augment the long value, rather than return a boolean
closes: #6366
=> fix: use the Retry-After header value

.github/workflows/e2e-tests.yml, .github/workflows/sonar.yml, Makefile, kubernetes-model-generator/openapi/generator/cmd/openapi.go, kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen.go
Part of #6130
Explicit model generation is no longer needed
=> chore: updated makefile rules for schema generation

kubernetes-model-generator/openapi/generator/cmd/openapi.go, kubernetes-model-generator/openapi/generator/cmd/supported-apis.go, kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-json.go, kubernetes-model-generator/openapi/generator/pkg/parser/parser.go, kubernetes-model-generator/openapi/generator/tools/generator/openapi.go, kubernetes-model-generator/openshift-model-storageversionmigrator/pom.xml, kubernetes-model-generator/openshift-model-whereabouts/pom.xml, kubernetes-model-generator/pom.xml
=> refactor: misc refactors to the OpenAPI generator

.github/workflows/javadocs.yml, Makefile
ci: make javadoc with multiple threads
=> ci: make javadoc with multiple threads

CHANGELOG.md, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/AbstractCustomResourceHandler.java, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/AbstractJsonSchema.java, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/v1/CustomResourceHandler.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/example/joke/JokeRequest.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/CRDGeneratorTest.java, generator-annotations/src/main/java/io/fabric8/crd/generator/annotation/AdditionalPrinterColumn.java, generator-annotations/src/main/java/io/fabric8/crd/generator/annotation/AdditionalPrinterColumns.java
closes: #3069
I believe the is the most straight-foward appraoch to adding general additional printer columns.
Other thoughts:
- we could reuse the existing PrinterColumn annotation. However I didn't like about that is that it mixes the usage models, so the javadocs / validations would need to be more extensive.
- allow the annotation to appear in other places. I think we'd at least need to auto-prefix the paths with the current path within the structure - we do have that as we're navigating over the object model. This can be easily added later if needed.
- it's not being extensively validated. For example we could check that the path provided is valid / actually exists.
=> fix: adds an additional printer column annotation

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientImpl.java, platforms/karaf/features/src/main/resources/feature.xml, pom.xml
=> feat:deps: bumped OkHttp from 3.12.12 to 4.12.0

junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/ByteString.java, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerHttp2Test.groovy
Tests to ensure HTTP/2 is supported in the MockWebServer.
Closes #4193 
=> feat(mockwebserver): io.fabric8:mockwebserver has full support for HTTP/2

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java
=> fix: removed deprecated methods from IOHelpers class

kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/MixedCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/GroupTest.java, kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SubjectAccessReviewTest.java
test: remove unneeded KubernetesMockServer.createClient() calls
Relates to #6364
=> test: remove unneeded KubernetesMockServer.createClient() calls

CHANGELOG.md, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/BeanPropertyWriterDelegate.java, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/SettableBeanPropertyDelegating.java, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/UnmatchedFieldTypeModule.java, kubernetes-model-generator/kubernetes-model-common/src/test/java/io/fabric8/kubernetes/model/jackson/SettableBeanPropertyDelegatingTest.java
=> fix: renamed SettableBeanPropertyDelegate to SettableBeanPropertyDelegating

kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/ImportManager.java, kubernetes-model-generator/openshift-model-installer/src/generated/java/io/fabric8/openshift/api/model/installer/baremetal/v1/Platform.java, kubernetes-model-generator/openshift-model-installer/src/generated/java/io/fabric8/openshift/api/model/installer/v1/ClusterNetworkEntry.java, kubernetes-model-generator/openshift-model-installer/src/generated/java/io/fabric8/openshift/api/model/installer/v1/MachineNetworkEntry.java, kubernetes-model-generator/openshift-model-installer/src/generated/java/io/fabric8/openshift/api/model/installer/v1/Networking.java
fix(openapi): java.lang packaged classes aren't added as imports
=> fix(openapi): java.lang packaged classes aren't added as imports

kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java
fix(openapi): OpenAPI-generated class names don't have underscores
=> fix(openapi): OpenAPI-generated class names don't have underscores

extensions/knative/model/src/generated/java/io/fabric8/knative/pkg/apis/ConditionSet.java, extensions/knative/model/src/generated/java/io/fabric8/knative/pkg/apis/FieldError.java, extensions/tekton/model/src/generated/java/io/fabric8/tekton/triggers/v1alpha1/StatusError.java, extensions/tekton/model/src/generated/java/io/fabric8/tekton/triggers/v1beta1/StatusError.java, kubernetes-model-generator/openapi/generator/cmd/openapi.go, kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen.go, kubernetes-model-generator/openapi/generator/pkg/packages/packages.go, kubernetes-model-generator/openapi/generator/tools/generator/openapi.go, kubernetes-model-generator/openapi/schemas/dev.knative.json, kubernetes-model-generator/openapi/schemas/dev.tekton.json, kubernetes-model-generator/openshift-model-miscellaneous/src/generated/java/io/fabric8/openshift/api/model/miscellaneous/metal3/v1alpha1/SchemaSettingError.java, kubernetes-model-generator/openshift-model-monitoring/src/generated/java/io/fabric8/openshift/api/model/monitoring/v1/AuthorizationValidationError.java, kubernetes-model-generator/openshift-model-monitoring/src/generated/java/io/fabric8/openshift/api/model/monitoring/v1/OAuth2ValidationError.java, kubernetes-model-generator/openshift-model-monitoring/src/generated/java/io/fabric8/openshift/api/model/monitoring/v1/ProbeTargetsValidationError.java
fix(openapi): don't expose private fields in OpenAPI spec
=> fix(openapi): don't expose private fields in OpenAPI spec

.github/workflows/e2e-crc-okd-tests.yml, kubernetes-itests/src/test/java/io/fabric8/kubernetes/APIVersionsIT.java, kubernetes-itests/src/test/java/io/fabric8/kubernetes/PluralizeIT.java, kubernetes-itests/src/test/java/io/fabric8/openshift/ServiceToURLIT.java, kubernetes-itests/src/test/resources/service-to-url-it-network-v1-ingress.yml
Add workflow for OKD 4.14.0 for running Fabric8 Kubernetes Client E2E tests.
+ We create crc cluster with a custom okd preset, that creates a cluster based on [OpenShift Kubernetes Distribution](https://okd.io/)
+ CRC version is bound to OKD, for future upgrades we would need to bump CRC version.
+ I managed to get it working with CRC 2.32.0, I couldn't get it working with latest version of CRC, I've created https://github.com/crc-org/crc/issues/4382 on crc repository
+ Update existing tests for running on OpenShift Kubernetes Distribution 4.x:
- add support for handing `networking.k8s.io/v1` Ingress in ServiceToURLIT, replace deprecated methods
- Add an exception to PluralizeIT for `ResourceAccessReview` resource, OpenShift Aggregated Discovery API is returning `singularName` for this …
=> ci : Add github action workflow for okd 4.14.0 cluster with crc

kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen-processors.go, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ModelGenerator.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/TemplateContext.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java, kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model_fields.mustache, kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model_methods.mustache, kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/SchemaUtilsTest.java
=> feat(openapi): generation of JsonUnwrapped interface fields

kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen-processors.go, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ClassInformation.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/JsonSubTypes.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ModelGenerator.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/TemplateContext.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java, kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model_class_annotations.mustache, kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model_methods.mustache, kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/model/TemplateContextTest.java
feat(openapi): interfaces properly generated
=> feat(openapi): interfaces properly generated

kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen-processors.go, kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen.go, kubernetes-model-generator/openapi/maven-plugin/pom.xml
feat(openapi): generated classes implement interfaces
=> feat(openapi): generated classes implement interfaces

kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen-processors.go, kubernetes-model-generator/openshift-model/src/generated/java/io/fabric8/openshift/api/model/DockerImageReference.java
feat(openapi): protobuf tag name value considered for json serialization
=> feat(openapi): protobuf tag name value considered for json serialization

kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen-processors.go, kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen.go, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ClassInformation.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ModelGenerator.java, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java, kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model.mustache, kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model_methods.mustache
feat(openapi): support for Istio enums
=> feat(openapi): support for Istio enums

kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen-processors.go, kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ClassInformation.java, kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model.mustache, kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model_enum_body.mustache
feat(openapi): enum can be deserialized from int value (Istio)
=> feat(openapi): enum can be deserialized from int value (Istio)

Makefile, java-generator/it/src/main/java/io/fabric8/java/generator/testing/KubernetesResourceDiff.java, kubernetes-model-generator/kubernetes-model-apiextensions/src/test/java/io/fabric8/kubernetes/api/model/apiextensions/v1/ConversionReviewTest.java, kubernetes-model-generator/kubernetes-model-apiextensions/src/test/java/io/fabric8/kubernetes/api/model/apiextensions/v1/CustomResourceDefinitionTest.java, kubernetes-model-generator/kubernetes-model-apiextensions/src/test/java/io/fabric8/kubernetes/api/model/apiextensions/v1beta1/CustomResourceDefinitionTest.java, kubernetes-model-generator/kubernetes-model-apps/src/test/java/io/fabric8/kubernetes/api/model/apps/DeploymentTest.java, kubernetes-model-generator/kubernetes-model-core/pom.xml, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/ConfigMapTest.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/EventTest.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/KubernetesListTest.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/SecretTest.java, kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/ServiceTest.java, kubernetes-model-generator/kubernetes-model-discovery/src/test/java/io/fabric8/kubernetes/api/model/discovery/v1beta1/EndpointSliceTest.java, kubernetes-model-generator/kubernetes-model-rbac/src/test/java/io/fabric8/kubernetes/api/model/rbac/RoleBindingTest.java, kubernetes-model-generator/kubernetes-model-rbac/src/test/java/io/fabric8/kubernetes/api/model/rbac/RoleTest.java, kubernetes-model-generator/openshift-model-operator/src/test/java/io/fabric8/openshift/api/model/operator/network/v1/EgressRouterTest.java, kubernetes-model-generator/openshift-model/src/test/java/io/fabric8/kubernetes/api/model/BuildConfigTest.java, kubernetes-model-generator/openshift-model/src/test/java/io/fabric8/kubernetes/api/model/ImageStreamImportTest.java, kubernetes-model-generator/openshift-model/src/test/java/io/fabric8/kubernetes/api/model/ImageStreamTagTest.java, kubernetes-model-generator/openshift-model/src/test/java/io/fabric8/kubernetes/api/model/RouteTest.java, kubernetes-model-generator/openshift-model/src/test/java/io/fabric8/openshift/api/model/DeploymentConfigRollbackTest.java, kubernetes-model-generator/openshift-model/src/test/resources/valid-ist.json, kubernetes-model-generator/pom.xml, pom.xml
deps: remove unneeded net.javacrumbs.json-unit:json-unit-fluent dependency
=> deps: remove unneeded net.javacrumbs.json-unit:json-unit-fluent dependency

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
=> refactor(config): persistKubeConfigIntoFile uses File instead of String

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
=> refactor(config): refresh relies in non-deprecated method fromKubeconfig

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsMergeTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java, kubernetes-client-api/src/test/resources/internal/kube-config-utils-merge/config-1.yaml, kubernetes-client-api/src/test/resources/internal/kube-config-utils-merge/config-2.yaml, kubernetes-client-api/src/test/resources/internal/kube-config-utils-merge/config-3.yaml, kubernetes-client-api/src/test/resources/internal/kube-config-utils-merge/config-4.yaml, kubernetes-client-api/src/test/resources/internal/kube-config-utils-merge/config-empty.yaml
=> feat(config): KubeConfigUtils.merge supports merging multiple configs

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigAutoConfigureTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsMergeTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsTest.java, kubernetes-client-api/src/test/resources/config-auto-configure/config-1.yaml, kubernetes-client-api/src/test/resources/config-auto-configure/config-2.yaml, kubernetes-client-api/src/test/resources/config-auto-configure/config-3.yaml, kubernetes-client-api/src/test/resources/config-auto-configure/just-current-context.yaml, kubernetes-client-api/src/test/resources/internal/kube-config-utils-merge/just-current-context.yaml
=> feat(config): autoConfigure supports multiple kubeconfig file paths

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsBehaviorTest.java
=> refactor(config): OpenIDConnectionUtils.persistOAuthToken should not persist values that no longer exist

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigRefreshTest.java
Relates to:
- #6535
- #6558 
- #6516
=> test(config): ensure Config.refresh works with scattered kubeconfig files

Makefile
=> ci: streamline openapi-generate-java-classes Makefile target

kubernetes-model-generator/openapi/generator/go.mod
```
updater | 2024/11/15 05:01:25 INFO <job_917150770> Updating volcano.sh/apis from 1.10.0 to 1.19.6
updater | 2024/11/15 05:01:35 INFO <job_917150770> Handled error whilst updating volcano.sh/apis: dependency_file_not_resolvable {:message=>"go: volcano.sh/apis@v1.19.6: invalid version: unknown revision v1.19.6"}
```
```
updater | 2024/11/15 05:01:36 INFO <job_917150770> Updating github.com/stolostron/multiclusterhub-operator from 0.0.0-20240626140553-4f1ed6be3b84 to 1.0.1-2020-06-08-14-28-27
updater | 2024/11/15 05:01:38 INFO <job_917150770> Handled error whilst updating github.com/stolostron/multiclusterhub-operator: dependency_file_not_resolvable {:message=>"go: github.com/stolostron/multiclusterhub-operator@v1.0.1-2020-06-08-14-28-27: invalid version: unknown revision …
```
=> fix: dependabot issues with volcano and multicluster-observability-operator

.github/workflows/build.yml, .github/workflows/javadocs.yml, Makefile, java-generator/it/pom.xml, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerWebSocketTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/MockWebServerWebSocketTest.groovy, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractSimultaneousConnectionsTest.java
=> ci: make install

CHANGELOG.md, crd-generator/cli/README.md, crd-generator/cli/pom.xml, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/CRDGeneratorCLI.java, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/CRDGeneratorCliException.java, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/CRDGeneratorExecutionExceptionHandler.java, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/CRDGeneratorExitCode.java, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/CustomResourceClassNotFoundException.java, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/KubernetesClientVersionProvider.java, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/LoggingConfiguration.java, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/SourceParameter.java, crd-generator/cli/src/main/java/io/fabric8/crd/generator/cli/SourceParameterTypeConverter.java, crd-generator/cli/src/test/java/io/fabric8/crd/generator/cli/CRDGeneratorCLITest.java, crd-generator/cli/src/test/java/io/fabric8/crd/generator/cli/LoggingConfigurationTest.java, crd-generator/cli/src/test/java/io/fabric8/crd/generator/cli/SourceArgumentConverterTest.java, crd-generator/cli/src/test/java/io/fabric8/crd/generator/cli/examples/basic/Basic.java, crd-generator/cli/src/test/java/io/fabric8/crd/generator/cli/examples/basic/BasicSpec.java, crd-generator/cli/src/test/java/io/fabric8/crd/generator/cli/examples/basic/BasicStatus.java, crd-generator/collector/pom.xml, crd-generator/maven-plugin/pom.xml, crd-generator/pom.xml, java-generator/cli/pom.xml, pom.xml, uberjar/pom.xml
Fixes #5958
Relates to #5950
Add CRD-Generator CLI application (using api-v2).
Usage:
```
crd-gen [-hVv] [--force-index] [--force-scan] [--implicit-preserve-unknown-fields] [--no-parallel]
[-o=<outputDirectory>] [-cp=<classpathElement>]... [--exclude-package=<package>]...
[--include-package=<package>]... <source>...
Description:
Fabric8 CRD-Generator
Generate Custom Resource Definitions (CRD) for Kubernetes from Java classes.
Parameters:
<source>...     A directory or JAR file to scan for Custom Resource classes, or a full qualified Custom Resource
class name.
Options:
-o, --output-dir=<outputDirectory>
The output directory where the CRDs are emitted.
Default: .
-cp, --classpath=<classpathElement>
Additional classpath element, e.g. a dependency packaged as JAR file or a directory of class …
```
=> feat(crd-generator): Add CRD-Generator CLI

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Client.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extension/ClientAdapter.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/BaseClient.java, kubernetes-itests/src/test/java/io/fabric8/openshift/AdaptIT.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/KubernetesMockServerTest.java, kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/AdaptTest.java, openshift-client/src/main/java/io/fabric8/openshift/client/impl/URLFromOpenshiftRouteImpl.java, openshift-client/src/test/java/io/fabric8/openshift/client/dsl/AdaptTest.java
=> fix: removed deprecated `io.fabric8.kubernetes.client.Client.isAdaptable` method

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
Fixes #6626 
Removed unused deprecated methods from ManagedKubernetesClient
=> Remove deprecated bind/unbindResourceHandler methods from ManagedKubernetesClient

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java
Remove deprecated constructors and methods and ran the tests to ensure nothing is failing
Fixes #6629 
- [] Bug fix (non-breaking change which fixes an issue)
- [] Feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change
=> Remove deprecated methods from KubernetesClientException class #6629

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationContext.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/behavior/LogTest.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/internal/PodOperationUtilTest.java
=> fix: pod log request sinceTime param correctly encoded

.github/workflows/e2e-httpclient-tests.yml, CHANGELOG.md, chaos-tests/pom.xml, doc/FAQ.md, doc/MIGRATION-v7.md, kubernetes-client/pom.xml, kubernetes-itests/pom.xml, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java, log4j/src/main/java/io/fabric8/kubernetes/log4j/lookup/KubernetesLookup.java
=> feat: user Vert.x as the default HttpClient implementation

CHANGELOG.md, doc/MIGRATION-v7.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationContext.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
=> fix: withReadyWaitTimeout defaults to 0, which means no waiting

CHANGELOG.md, crd-generator/api-v2/pom.xml, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/AbstractJsonSchema.java, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/CRDUtils.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/v1/JsonSchemaDefaultValueTest.java, crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/annotated/AnnotatedSpec.java, crd-generator/test/src/test/resources/io/fabric8/crd/generator/approvaltests/CRDGeneratorApprovalTest.approvalTest.annotateds.samples.fabric8.io.v1.approved.yml, crd-generator/test/src/test/resources/io/fabric8/crd/generator/approvaltests/CRDGeneratorApprovalTest.approvalTest.annotateds.samples.fabric8.io.v1beta1.approved.yml
=> fix(crd-generator): default values for CRD fields can be numeric or boolean

crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/CustomResourceInfo.java, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/v1/CustomResourceHandler.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/example/joke/JokeRequest.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/CRDGeneratorTest.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/CustomResourceInfoTest.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/CustomResource.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/Custom.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/CustomResourceTest.java, kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/Categories.java
Adds a new annotation `@Categories` that enables users of the CRD generator to set categories in the generated CRD.
Closes #5795 
=> Enable configuring of categories in CRD generation

crd-generator/test/src/test/java/io/fabric8/crd/generator/approvaltests/annotated/AnnotatedSpec.java, crd-generator/test/src/test/resources/io/fabric8/crd/generator/approvaltests/CRDGeneratorApprovalTest.approvalTest.annotateds.samples.fabric8.io.v1.approved.yml, crd-generator/test/src/test/resources/io/fabric8/crd/generator/approvaltests/CRDGeneratorApprovalTest.approvalTest.annotateds.samples.fabric8.io.v1beta1.approved.yml
@andreaTP FYI and for your peace of mind ;)
Relates to:
- #6666 
- #6654
=> test(crd-generator): approval test for default double

crd-generator/apt/README.md, doc/CRD-generator-migration-v2.md, doc/CRD-generator.md, doc/MIGRATION-v7.md
Migration notes for users who want to switch to CRD Generator v2.
=> CRD-Generator v2 migration notes

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractSimultaneousConnectionsTest.java
=> test: set content length = 0 in abstract simultaneous connections test

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientFactory.java
Fixes #6709 
Initial proposal to fix the Vertx thread-leaking issue.
- Switched Vert.x to use daemon threads
- Refactored VertxHttpClientFactory to re-use the same Vertx instance
- VertxHttpClientFactory can optionally use a user-provided and user-managed Vertx instance
- Added shutdown hook to VertxHttpClientFactory to close the default provided Vertx instance
=> fix(vertx): VertxHttpClientFactory reuses the same Vertx instance for each VertxHttpClient instance

httpclient-jdk/pom.xml, httpclient-jdk/src/test/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientSimultaneousConnectionsTest.java, httpclient-jetty/pom.xml, httpclient-okhttp/pom.xml, httpclient-vertx/pom.xml, junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/MockWebServer.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractAsyncBodyTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractSimultaneousConnectionsTest.java
Relates to #6727
- test:refactor: AbstractSimultaneousConnectionsTest uses Vert.x as backend server
- ci: enable parallel build
=> test:refactor: AbstractSimultaneousConnectionsTest uses Vert.x as backend server

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
=> fix: catching rejected execution

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/HttpClientUtilsTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/IpAddressMatcherTest.java
ipv6 values are being excluded from no_proxy.
Also I don't see any reference for values starting with http(s), so we may want to remove that support.
closes: #6781
=> fix: allowing no_proxy to use ipv6 values

doc/CHEATSHEET.md
* Updated cheatsheet example for `serverSideApply()`.
=> Improved documentation for ServerSideApply

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollingUpdater.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
Change rolling restart/pause/resume to use rfc6902 JSON patch. 
Fixes #6658
Fixes #2516 
=> Change rolling restart/pause/resume to use rfc6902 JSON patch

CHANGELOG.md, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java, java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java, java-generator/core/src/test/java/io/fabric8/java/generator/ApprovalTest.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testRequireSpecAndStatusCrd.approved.txt, java-generator/core/src/test/resources/require-spec-and-status-crd.yml
Fixes #6802
Update Java generator to support generating required spec and status.
=> feat: java-generator support for required spec and status

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ItemReplacable.java
The originally deprecated method suggested using another method that has since been deprecated as well. This documentation update ensures the correct and final method to use is clearly specified, avoiding confusion and unnecessary intermediate steps.
=> docs: update deprecated method chain to use final recommended method

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/InputStreamReadStream.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClient.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientBuilder.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientFactory.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpRequest.java, httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientBuilderTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
Fixes #6792
A shared Vert.x instance can still be provided to the VertxHttpClientFactory.
This instance will be shared across the different VertxHttpClient instances.
It's responsibility of the user to handle the Vert.x shared instance lifecycle
/cc @shawkins 
=> fix(vertx): VertxHttpClient uses exclusive Vert.x instance by default

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketListener.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/ProcessorStore.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/cache/SharedProcessor.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/internal/SerialExecutor.java
throwing RejectedExecutionException was added to the SerialExecutor for consistency between the case when there was a local shutdown vs having the underlying executor shutdown. In every instance since then when this has come up we don't actually care about the work not being performed after shutdown - it's just a timing issue where we haven't check for shutdown prior to submitting the work. Rather than continue to change calling code, it seems better to just change the SerialExecutor contract and handle the rejections there.
closes: #6863
=> fix: fully encapsulating rejected execution handling

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollingUpdater.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentCrudTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java
=> fix: rolling().restart() doesn't remove preexistent pod template annotations

CHANGELOG.md, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/LogWatch.java, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallback.java, kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallbackTest.java
Fixes #6880
This feature implements a listener on the closing event of the LogWatch class. 
Currently, when a LogWatch is instantiated, and when the underlying stream is closed, the log processing stops and the underlying output stream received no more events without been inform that a dead end has been reach. 
With the onClose action I added, when the stream processing ends, (with an error or not), the information can be forwarded and a post processing can be easily started.
Due to some timeouts, I was loosing the log stream and could not reconnect in a smooth way. I did not see any easy way to be informed of this event and thus decided to implement it.
=> onClose callback for LogWatch

CHANGELOG.md, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpRequest.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpResponse.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpHeaders.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpHeaders.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpGetTest.java
Make vertx http request's header case insensitive to fix case related issues.
Fixes #6917
=> Make vertx request header case insensitive

CHANGELOG.md, junit/kube-api-test/core/src/main/java/io/fabric8/kubeapitest/process/ProcessReadinessChecker.java
In rare curcumstaces this it might occur that the readiness problem communcation
fails on SSL error.
Signed-off-by: Attila Mészáros <a_meszaros@apple.com>
=> fix: Kube API Test startup fails on readiness SSL check

CHANGELOG.md, junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java, junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServerTest.java, junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/DefaultMockServer.java, junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/MockWebServer.java, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerTest.groovy, junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/MockWebServerTest.groovy
=> fix(mockserver): KubernetesMockServer.reset resets lastRequest related variables

kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamTagIT.java
ImageStreamTag CRUD operations don't work in newer clusters
Users should rely on ImageStream resource operations for these purposes.
=> fix(e2e): ImageStreamTag CRUD operations don't work in newer clusters

CHANGELOG.md, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/example/annotated/AnnotatedSpec.java, crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java, java-generator/core/src/main/java/io/fabric8/java/generator/Config.java, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testCrontabCrd.approved.txt, java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testCrontabExtraAnnotationsCrd.approved.txt
fix: (java-generator) Use timezone format compatible with Kubernetes
Fixes #7116
Example error message:
```
Invalid value: "2025-05-30T23:04:44Zulu": startTime in body must be of type date-time
```
See also:
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
=> fix: (java-generator) Use timezone format compatible with Kubernetes

CHANGELOG.md, httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpWebSocketImpl.java
Follow-up to a potential okhttp issue - while we don't have a reproducer it's clear we are checking if the body can be null further down in the method so it should be done at the top instead of just calling response close (which is documented as just a body close).
close: #7087
=> fix: cannot call close if body is null

CHANGELOG.md, httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java, httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpRequest.java
closes: #7163
Checked each of the client's behavior when reading a stream with a proxy that is shutdown in the middle. Vertx did not notify correctly, and Jetty produced the wrong error.
@manusa at first glance I didn't see a way to induce this with the mockserver
=> fix: ensure that vertx streams notify when there is an error

CHANGELOG.md, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/CRDUtils.java, crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/CustomResourceInfo.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/example/annotated/AnnotationsAndLabels.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/CRDGeneratorTest.java, crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/CustomResourceInfoTest.java
This PR implements support for `@Annotations` and `@Labels` annotations in the CRD generator, addressing issue #7092.
Previously, when using `@Annotations` and `@Labels` annotations on CustomResource classes, these metadata were not included in the generated CRD files. This implementation ensures that annotations and labels specified via these annotations are properly included in the CRD metadata.
- https://github.com/fabric8io/kubernetes-client/blob/main/doc/CRD-generator.md#iofabric8crdgeneratorannotationannotations
- https://github.com/fabric8io/kubernetes-client/blob/main/doc/CRD-generator.md#iofabric8crdgeneratorannotationlabels
All tests pass successfully:
- `CustomResourceInfoTest#shouldIncludeAnnotationsAndLabelsInCustomResourceInfo` ✅
- …
=> feat(crd-generator): add support for @Annotations and @Labels in CRD generation

CHANGELOG.md, kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollingUpdater.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java, kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java
Reverts to the older style for rolling update, with a simplification of map creation.
Replaces and closes #7118 - @dkaukov I'd advocate for this approach to cut down on additional complexity / multiple requests
closes: #7072
=> fix: change rolling update logic to a json merge patch

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/ConfigBuilder.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/ConfigFluent.java, kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/SundrioConfig.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigConstructorTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java, kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/SundrioConfigBuilderTest.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftConfigBuilder.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftConfigFluent.java, openshift-client-api/src/main/java/io/fabric8/openshift/client/SundrioOpenShiftConfig.java
@manusa @rohanKanojia separated this from the pr dealing with watchLists. I realize that using just the swicth to use a static constructor is pretty narrow change. If possible I'd like to shoot for something bigger. The changes here get rid of all of our messiest constructors and hopely make adding new options more straight-forward.
- SundrioConfig -> goes from extending the Config to being a base class (could be renamed BaseConfig or something).  
- There are two reasons to do this:
- Creates a clean pojo from which to do sundrio generation.
- Creates a clean pojo from which to do delegated Json deserialization - see the Config(SundrioConfig config) constructor.
- Downsides:
- Probably needs to be public (https://github.com/fabric8io/kubernetes-client/issues/4724) - or maybe just the …
=> rationalizing Config constructors / building
