fabric8io/kubernetes-client

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/EditReplaceable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ReplicationControllerClientResource.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/RollingUpdateable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/HasMetadataOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SerializationUtils.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/examples/FullExample.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/MockReplicationController.java

Initial rolling update - image update only

---

kubernetes-client/pom.xml
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/BaseMockOperation.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/BuildConfigOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/TemplateOperationsImpl.java
pom.xml

Shade dependencies

---

pom.xml

update the model version

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PersistentVolumeClaimOperationsImpl.java

fixed typo

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/Utils.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftConfig.java

Request timeout config

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ServiceOperationsImpl.java

Correct service operations inheritance

---

pom.xml

This reverts commit 86c485be6789a9cb6fadf23f8d0256e1f30951ca.

Revert "Generate bom and bom with deps."

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftConfig.java

Add proxy configuration

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/HttpUtils.java
kubernetes-examples/pom.xml
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodLogExample.java

fixes #113 so that we can easily get a pods log

fixes #113 so that we can easily get a pods log

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Fixes fabric8io/fabric8#5178.
Review appreciated if you can @iocanel @stevemuk.

Support NO_PROXY env var

---

kubernetes-client/pom.xml
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/KubernetesMockClient.java
kubernetes-mock/src/test/java/io/fabric8/kubernetes/client/mock/KubernetesMockClientTest.java
openshift-client/pom.xml
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java
openshift-mock/src/main/java/io/fabric8/openshift/client/mock/OpenShiftMockClient.java

- increase mock coverage
- fix possible npes
- openshift client now supports username/password credentials (via authorize).
- fix usage bundle structure.

Misc changes

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/WatchExample.java

Fix watch single resource & close functionality

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
kubernetes-client/src/test/resources/test-pod.yml

Reflection ctor for load & cascading ops

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java

Validate name passed to withName

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java

Fix cross-platform file paths

---

kubernetes-client/pom.xml
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
pom.xml

Upgrade okhttp client to 2.6.0

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java

Fix exec with upgraded okhttp

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java

Handle non-base64 encoded cert data

---

platforms/karaf/pom.xml
pom.xml

@iocanel Any issues with these upgrades?

Dependency upgrades

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java

`onFailure` is sometimes called with a null `response`. When this happens,
we would throw a `NullPointException` that would mask the underlying error,
prevent `onClose` from being called, and therefore prevent reconnection.

WatchConnectionManager.onFailure: Handle null response

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java
openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java

Close response bodies

---

kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/KubernetesMockClient.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/MockComponentStatus.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/donable/MockDoneableComponentStatus.java

As committed to in https://github.com/fabric8io/kubernetes-client/pull/297 , I am committing the mocks for componentstatuses()
Kindly review.

Adding mocks for componentstatuses()

---

kubernetes-client/pom.xml
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ComponentStatusOperationsImpl.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/ComponentStatusTest.java
kubernetes-examples/pom.xml
kubernetes-mock/pom.xml
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/MockComponentStatus.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/donable/MockDoneableComponentStatus.java
openshift-client/pom.xml
openshift-mock/pom.xml
platforms/karaf/features/pom.xml
platforms/karaf/itests/pom.xml
platforms/karaf/pom.xml
platforms/pom.xml
pom.xml

Manually setting next development version.

prepare for next development iteration 1.3.68-SNAPSHOT

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java

Ensure rolling updater doesn't alter requested new RC

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java

* Connection pooling fixes
* Exception handling fix
* Rolling update better error handling

Various fixes:

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ConfigMapOperationsImpl.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/MockConfigMap.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/donable/MockDoneableConfigMap.java

Add ConfigMap support

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ThirdPartyResourceOperationsImpl.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/ExtensionsAPIGroupMockClient.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/MockThirdPartyResource.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/donable/MockDoneableThirdPartyResource.java

Fixes #310
/cc @jstrachan
There will be a follow up to easily create clients for third party resources.

Add third party resources with mocks

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/SecurityContextConstraintsOperationsImpl.java

Fix @Aftersuite exception after running Arquillian integration Tests. Someone should take a look and see if this overloaded constructor is the best way to fix this.

bug fix for @AfterSuite not running after Arquillian integration tests.

---

README.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java

@jimmidyson for #344 
It's not clear to me how to build this project, so this could be totally broken. Is there a getting started guide for developers?

Allow user to specify user-agent header for k8s requests

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/KubernetesDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ConfigMapOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/ExtensionsAPIGroupMockClient.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/KubernetesMockClient.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/MockConfigMap.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/donable/MockDoneableConfigMap.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
pom.xml

Also move ConfigMaps to v1 API.
Fixes #354

Upgrade model version to use strings for API versions

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java

Fix kubeconfig path on windows - thanks to @jmandawg

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java

Fix potential NPEs in Windows config

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java

Fix field selector query param

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/HorizontalPodAutoscalerOperationsImpl.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/ExtensionsAPIGroupMockClient.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/MockHorizontalPodAutoscaler.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/donable/MockDoneableHorizontalPodAutoscaler.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Fix for https://github.com/fabric8io/kubernetes-client/issues/377

Support for HorizontalPodAutoscaler

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java

@iocanel Can you think of a simpler way to do this? We don't know the builder type at this point sadly.
@jwendell This supercedes #391.

Ensure replace doesn't modify the original resource

---

kubernetes-client/pom.xml

Add jackson-core as explicit dependency

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/KubernetesListTest.java

Fix list deletes for cascadeable resources

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/ConfigMapHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/DaemonSetHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/DeploymentHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/HorizontalPodAutoscalerHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/IngressHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/JobHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/ReplicaSetHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/ReplicationControllerHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/ThirdPartyResourceHandler.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler

Add missing resource handlers

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java

Disable read timeout for log watching

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
pom.xml

See https://github.com/fabric8io/kubernetes-client/issues/418#issuecomment-221744856
@ravilr This should fix the deployment reaping to be consistent with kubectl.

Fix deployment reaping & upgrade model

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java

Fix deployment editing

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetRollingUpdater.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerRollingUpdater.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java

Fix rolling updates

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/DeploymentConfigTest.java

Tidy up constructors by reflection a bit to fix deploymentconfig bugs

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/handlers/BuildConfigHandler.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/KubernetesOperationTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/OpenShiftMockServerTestBase.java

Fixes #431
@dsimansk This will be fixed in next release.

Fix wrong config type detection when constructing via reflection

---

openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1351129

Add cascade for build config deletions

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
kubernetes-client/src/test/resources/test-kubeconfig

Resolve certificate files relative to the config file directory.

---

kubernetes-client/pom.xml
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
openshift-client/pom.xml
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/PropertiesOverrideTest.java

This should solve both #470 and #471 
@iocanel @jimmidyson can you have a look ?

Managed Kubernetes/Openshift Client does not respect environment varables #471

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/SecurityContextConstraintsOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/SecurityContextConstraintsTest.java

Enable editing of SCC

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock/KubernetesMockServer.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock/KubernetesServer.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock/MasterProtocolTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ComponentStatusTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ErrorMessageTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/HttpServerTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/IngressTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/KubernetesListTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NodeTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicationControllerTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/SecurityContextConstraintsTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/UntrustedCertTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/BuildConfigTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/DeploymentConfigTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/GroupTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/KubernetesOperationTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/OAuthClientTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/OpenShiftServer.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/ProjectRequestTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/ProjectTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/SubjectAccessReviewTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/TemplateTest.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/UserTest.java

Fixes fabric8io/fabric8#6261, fixes #498

Add test for cleartext API servers

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LimitRangeOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/LimitRangeHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/KubernetesMockClient.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/MockLimitRange.java
kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/impl/donable/MockDoneableLimitRange.java
kubernetes-mock/src/test/java/io/fabric8/kubernetes/client/mock/KubernetesMockClientTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

@jimmidyson @iocanel 
Can you please review this PR? Thanks!

#503 Support LimitRange resource type

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java

This handles reconnections is the server crashes & TCP connections are not properly closed.
@iocanel Would you mind reviewing please?

Use periodic websocket pings to check that server connection is still valid

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java

fix for re-assign trustCerts variable in Config()

fix for re-assign trustCerts variable

---

kubernetes-mock/src/main/java/io/fabric8/kubernetes/client/mock/BaseMockOperation.java

Added basic support for replace and patch operations in kubernetes-mock

---

openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/RoleBindingOperationsImpl.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/OpenShiftServer.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/RoleBindingTest.java

@rhuss @lburgazzoli This adds the enrichment to match the OS client logic - I don't like it being client side, but at least it's compatible...
Any review would be good, otherwise I'll merge later today & get a release out.

Enrich role bindings as required

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ResourceCompare.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/ResourceCompareTest.java

We aren't using the `right` param.
This causes equals to always return true.

Fix ResourceCompare.equals()

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-examples/pom.xml
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/WatchExample.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

@iocanel @jbguerraz As discussed on IRC. Would be great if you could try it out
and see if it works for you.

Add configurable websocket read timeout and ping intervals

---

openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/ClientDeployableScalableResource.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/Deployable.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/DeploymentConfigTest.java

Thanks to [openshift-restclient-java](https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/internal/restclient/capability/resources/DeployCapability.java#L55) where this implementation was lifted from.
Closes #572

Add deployment of latest DeploymentConfig version

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/PatchUtils.java

Conflicts:
openshift-client/src/test/java/io/fabric8/openshift/client/mock/RoleBindingTest.java

OSFUSE-453: Ignore empty arrays while creating a patch request

---

platforms/karaf/features/src/main/resources/feature.xml

(cherry picked from commit b65d1ba851b727b26b5e30947e25571bc784a1e9)

Cleanup karaf feature file #617

---

platforms/karaf/itests/pom.xml
platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/FeatureInstallationTest.java
platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/PropertiesOverrideTest.java
platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/ServiceTest.java
platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/TestBase.java
platforms/karaf/itests/src/test/resources/io/fabric8/kubernetes/karaf/itests/versions.properties
platforms/karaf/pom.xml

Align karaf version with JBoss Fuse 6.3.x

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java

4 small commits. Each has a small scope and its purpose is pretty obvious.

Bug fixes and improvements around resource and resourceList operations.

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClientTimeoutException.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/EndpointsOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/ReadinessWatcher.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java

Contains an NPE fix for DeploymentConfig isReady() method.
The timeout exception now provides more meaningfull information. (contains the resource that timed out).

Wait until ready improvements

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClientTimeoutException.java

Fix timeout exception constructor params order

---

openshift-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler

Would like to get this merged and released ASAP so we can fix up our iPaaS system tests.

Add missing RoleBinding handler

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
kubernetes-tests/pom.xml
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LoadAsTemplateTest.java
kubernetes-tests/src/test/resources/parameters.yml
kubernetes-tests/src/test/resources/template-with-params.yml
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/Processable.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java

An different approach to #664
This pretty much adds the ability to load() non-Template resource as Template using:
client.templates().load(is)

Template load

---

openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java
openshift-client/src/test/java/io/fabric8/openshift/client/mock/DeploymentConfigTest.java

#692 add check for NPE.

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java

fix inconsistency between Job api version in model and api path in client

---

openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java

This support is required when uploading data for binary OpenShift builds since this is used by OpenShift for validating a request before accepting the request upload stream.
For this to work, the latest, yet non-released version of OkHttp 3.6.0-SNAPSHOT is required. Support for this feature came in with https://github.com/square/okhttp/commit/a589b8170333476233d48476587a1d4363c90bd0
Since since OkHttp 3.5.0 the WebSocket handling has changed completely, this library needs to be updated for using this new WS scheme. Currently the tests are not running:
* fabric8/mockwebserver needs to be updated to use at least 3.5.0 as well since the tests are using a mixing fabric8/mockwebserver (depending on 3.4.x) and square/okhttp's MockServer (from 3.5.x) which doesn not mix at all.
Also the …

WIP: Support for `Expect: 100-continue` header

---

pom.xml
uberjar/pom.xml

Add an uberjar and an uberjar with versioned packages (majro / minor).

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NetworkPolicyOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/NetworkPolicyHandler.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler
pom.xml

The origin doesn't support "NetworkPolicy",so I add it for issue #739.
[PR#200](https://github.com/fabric8io/kubernetes-model/pull/200) of kubernetes-model is already submited.
PR #743 is abandoned.

Add support for NetworkPolicy

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/OperationInfo.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DefaultOperationInfo.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ServiceOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java

Fixes https://github.com/redhat-ipaas/ipaas-rest/issues/328. Well not exactly fixes, but it does provide a better error message.

edit() / getMandatory() now return a more meaningful error on 404

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java

The problem is simple. Our generated builder make use of the default constructor internally. By autoconfioguring Config as part of the default constructor we make it impossible to distinguish what's user provided and what's autoconfigured.
We **MUST** remove everything from the default constructor but first we need to warn people about it. So let's depracate for now and we remove as of 2.4.

Deprecate empty constructor of Config, so that we can remove its functionality in future releases

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallback.java

Naming shadowing..
This should fix https://github.com/fabric8io/fabric8-maven-plugin/issues/964

Fix the log watcher

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/StatefulSetHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler

This is improved version of https://github.com/fabric8io/kubernetes-client/pull/769 with readiness check for StatefulSet.
I need this in arquillian-cube to test our k8s deployments.
@jimmidyson @jstrachan could you please review?

StatefulSet handler and readiness check

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildConfigOperationsImpl.java

when using API Groups APIs and watches the events come in as Lists rather
than WatchEvent resources so lets handle that gracefully via a helper
method

fix watch handling when using API Groups

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/StatefulSetHandler.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler

Cannot perform e.g. delete without this.

Adding the missing statefulset handler

---

kubernetes-tests/pom.xml

lets disable failing test in release pipeline

---

openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java

By using the proper API version.
Closes #829.

Fix project creation for Openshift 3.6+

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java

This is not an alpha version anymore

Upgrade jobs to v1

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java

1. BaseOperation.isReady() return true when then resource object is null, I think it's a bug.
2. Add support for node when using isReady().
3. Fix conflicts in #792

fix null Object return true by using isReady() and add Node resource

---

kubernetes-examples/pom.xml
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExample.java
kubernetes-examples/src/main/resources/log4j2.yaml

- Add namespace to ExecExample
- Create profiles for PodLogExample and ExecExample
- Set log level to INFO, as TRACE may interfere with streaming

Improvements on kubernetes-examples

---

kubernetes-client/pom.xml
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/Dummy.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/DummySpec.java

ensuring any CRD resources are registered into the deserialiser

fix up watching of CRD based resources

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Loggable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildOperationsImpl.java

Extended Loggable Interface to return java.io.Reader

---

README.md

Fix a small mistake of config creation example in README.md.

Fix a mistake of config creation example in README.md

---

README.md

test compatability for kubernetes-client 1.3.92 & kubernetes-client 3.0.3 on Kubernetes 1.4.9&1.6.2&1.7.10

 add Compatability section to README.md

---

README.md

Fix README builder creation example

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ImpersonatorInterceptor.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java

I'm not very familiar with the code base, so I'm looking for comments if this is the correct way of implementing this feature and if it should be done differently.

Support setting Impersonate-User header to perform operations using user impersonation

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/EndpointsOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollableScalableResourceOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ServiceOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java

I'm submitting this only to discuss the approach I've taken. The code contains a couple of TODOs that need to be resolved first.
Also the PR doesn't contain any test; could you please advise how to approach testing this change? I'm not at all familiar with tests in this codebase.
Fixes #921.

waitUntilReady now first waits until resource exists

---

kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodSecurityPolicyIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/SecurityContexConstraintsIT.java

Update PodSecurityPolicyTest and SecurityContextConstraintsTest
to delete only the one created in Regression Test
#1002

Update PodSecurityPolicyTest and SecurityContextConstraintsTest

---

README.md

Added the links of CircleCI and Jenkins
Anyone can view the recent build logs

Update README.md to add the links to recent builds

---

kubernetes-itests/src/test/java/io/fabric8/kubernetes/NetworkPolicyIT.java
kubernetes-itests/src/test/resources/test-networkpolicy.yml
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NetworkPolicyCrudTest.java

Added CRUD Test and Regression Test for Network Policy
#996

Added CRUD test and regression test for NetworkPolicy

---

.circleci/config.yml
kubernetes-itests/pom.xml
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ConfigMapIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeploymentIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ReplicaSetIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ReplicationControllerIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/SecretIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceAccountIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/StatefulSetIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/BuildConfigIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/RouteIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/TemplateIT.java
pom.xml

kubernetes-api is fat and ugly, plus it introduces  a dependency cycle and
it can be a source of issues.

Remove kubernetes-api from kubernetes-itests.

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java

using `offer` instead of `add` for the blocking queue

Avoid queue is full exceptions

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ImpersonatorInterceptor.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java

This fixes an issue where the request config given in withRequestConfig is not applied.

Load request config when intercepting request

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java

Make max reconnect back off interval exponents configurable, keeping
default value to 32x of initial value.

Refactor WatchConnectionManager/WatchHttpManager

---

kubernetes-examples/src/main/java/io/fabric8/openshift/examples/ImageStreamExample.java
kubernetes-examples/src/main/java/io/fabric8/openshift/examples/ImageStreamTagExample.java

Added an Example for ImageStream

---

kubernetes-examples/src/main/java/io/fabric8/openshift/examples/ImageStreamTagExample.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamTagIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/SecurityContextConstraintsIT.java
kubernetes-itests/src/test/resources/test-ist.yml
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ImageStreamTagCrudTest.java

modified ImageStreamTagExample to work properly
Removed unused variable from test
#1046

Added ImageStreamTagTest both unit and regression

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java

Fix parsing openshift template throwing error

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java

fix(#1085): Propagate Impersonate attributes

---

CHANGELOG.md
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LimitRangeLoadTest.java
kubernetes-tests/src/test/resources/test-limitRange.yml

Fix missing LimitRangeHandler and StorageClassHandler

---

pom.xml

Improve regression test to only build the client and not run unit test
As we have another job for this, this will decrease the rt execution time

Improve regression test

---

CHANGELOG.md
kubernetes-itests/pom.xml
kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeploymentDelete.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeploymentIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeploymentReady.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodReady.java
pom.xml

Improved Pod Exec, Pod Log and Deployment wait Test

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RbacAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RbacAPIGroupExtensionAdapter.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/RbacAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/KubernetesRoleBindingOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/KubernetesRoleOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/KubernetesRoleBindingHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/KubernetesRoleHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler
kubernetes-itests/src/test/java/io/fabric8/kubernetes/KubernetesRoleBindingIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/KubernetesRoleIT.java
kubernetes-itests/src/test/resources/test-kubernetesrole.yml
kubernetes-itests/src/test/resources/test-kubernetesrolebinding.yml
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/KubernetesRoleBindingCrudTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/KubernetesRoleCrudTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Adds support for Kubernetes RBAC Role and Role Binding

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BatchAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/BatchAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CronJobOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/CronJobHandler.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CronJobExample.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/CronJobIT.java
kubernetes-itests/src/test/resources/test-cronjob.yml
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CronJobCrudTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CronJobTest.java
kubernetes-tests/src/test/resources/test-cronjob.yml

Fix #770: Added Support for CronJob

---

CHANGELOG.md
pom.xml

Chore #1168 : Upgrade to Java 8

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ImpersonatorInterceptor.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
kubernetes-itests/src/test/java/io/fabric8/openshift/UserImpersonationIT.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java

Fix #1179 : Impersonate-Extra keys may be specified multiple times

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
kubernetes-client/src/test/resources/test-kubeconfig-exec
kubernetes-client/src/test/resources/token-generator

Rudimentary implementation of #1200. Enough to get my authentication working at least; does not implement some parts of the documented spec.

#1200: Support client authenticator commands like aws-iam-authenticator

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/ReadinessWatcher.java

Signed-off-by: Laird Nelson <ljnelson@gmail.com>
This PR should fix issue #1201.  It deliberately does not fix #1199 as it is not immediately clear to me what the intent of that particular catch block was.

Fixes problems with swallowed InterruptedExceptions #1201

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceDefinitionOperationsImpl.java

It siffers from reflection issues.

fix: Broken withName() method  for CustomResourceDefinition.

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/PolicyAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/PolicyAPIGroupExtensionAdapter.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/PolicyAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodDisruptionBudgetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodDisruptionBudgetExample.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodDisruptionBudgetTest.java
kubernetes-tests/src/test/resources/test-pdb.yml
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Fix #866 : Add support for PodDisruptionBudget

---

.circleci/config.yml
kubernetes-model/kubernetes-model/pom.xml
kubernetes-model/pom.xml
pom.xml
release.sh
scripts/prepare-environment.sh
scripts/release.sh
scripts/utils.sh
utils.sh

Move client CD job to CircleCI

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Listable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ListExamples.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java

Fix #1142: Pagination Support

---

CHANGELOG.md
kubernetes-model/pom.xml
pom.xml

Contains fix : https://issues.apache.org/jira/browse/SUREFIRE-1588
which was causing problems like #1260

Chore: Upgrade to surefire 3.0.0-M1

---

.circleci/config.yml
CHANGELOG.md
kubernetes-itests/src/test/java/io/fabric8/kubernetes/KubernetesRoleBindingIT.java

Fix #1226: Extend and move integration tests

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SchedulingAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SchedulingAPIGroupExtensionAdapter.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/SchedulingAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PriorityClassOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodPriorityExample.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PriorityClassTest.java
kubernetes-tests/src/test/resources/test-priorityclass.yml
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Fix #1244 
Added support for resource type PriorityClass
(We can merge this after #1269 gets merged)

Fix #1244: PodPriority Support

---

.circleci/config.yml
CHANGELOG.md

Minor changes in CHANGELOG and circleci config

(Chore): Release preparation

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ReplicaSetTest.java

Fix #1271 
Extract apiGroup from HasMetadata just like apiVersion while initializing BaseOperation.

Fix #1271: Issue deploying ReplicaSet to extensions/v1beta1

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SettingsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SettingsAPIGroupExtensionAdapter.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/SettingsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodPresetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodPresetExamples.java
kubernetes-examples/src/main/resources/pod-preset-example.yml
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Added support for PodPreset in client

PodPreset Support

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterOperationsImpl.java

Fix slash missing when client config from  Config.loadFromKubeconfig

---

CHANGELOG.md
pom.xml

Update jackson dependency version.

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IpAddressMatcher.java

Fixing NPE while running the build

---

CHANGELOG.md
kubernetes-model/Gopkg.lock
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
kubernetes-model/pkg/schemagen/generate.go

This is resubmit of pull request already accepted in kubernetes-model: https://github.com/fabric8io/kubernetes-model/pull/340

Set generic type in classes implementing KubernetesResourceList

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/PortForward.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java

Fix #1362 store exceptions thrown in port forwarder websocket

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceNotFoundException.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Requirable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Resource.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java

Feature 213: Added require( ) method to Resource object class.

---

CHANGELOG.md
kubernetes-model/kubernetes-model-annotator/src/main/java/io/fabric8/kubernetes/annotator/KubernetesTypeAnnotator.java
kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/DeploymentTest.java
kubernetes-model/kubernetes-model/src/test/resources/valid-deployment.json

Fix #1361: Kubernetes was relax restrictions on environment variable names.

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AppsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/AppsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentRollingUpdater.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java

Fix #1064: Rollout Support for Deployment Object

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ValidatingWebhookConfigurationOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ValidatingWebhookConfigurationTest.java

Fix #1387: ValidatingWebhookConfigurationOperationsImpl should be a NonNamespaceOperation

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeploymentIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java

Fix get from server resource list (#807, #760)

Fix resource list fromServer().get()

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ServiceResource.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ServiceOperationsImpl.java

feat: First draft of exposing port-forward via service DSL.

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionAdapter.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java
kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java

I faced failures in build during release: 
https://circleci.com/gh/rohanKanojia/kubernetes-client/1082

Fix Javadoc issues

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java

Fix for issue [1297](https://github.com/fabric8io/kubernetes-client/issues/1297)

Encoding command in UTF-8

---

CHANGELOG.md
kubernetes-client/pom.xml
kubernetes-examples/pom.xml
kubernetes-itests/pom.xml
kubernetes-model/kubernetes-model-annotator/pom.xml
kubernetes-model/kubernetes-model-common/pom.xml
kubernetes-model/kubernetes-model/pom.xml
kubernetes-model/model-generator-app/pom.xml
kubernetes-model/pom.xml
kubernetes-server-mock/pom.xml
kubernetes-tests/pom.xml
openshift-client/pom.xml
openshift-server-mock/pom.xml
platforms/karaf/features/pom.xml
platforms/karaf/itests/pom.xml
platforms/karaf/pom.xml
platforms/pom.xml
pom.xml
uberjar/pom.xml

Chore: Update pom version to 4.2-SNAPSHOT

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Client.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionAdapter.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Deletable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExecListener.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Loadable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/PortForwardable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ApiVersionUtil.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReplaceValueStream.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecLoopExample.java

Chore #1470: Fix Javadoc issues

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Handlers.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/HandlersTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ResourceHandlerTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java

#1490: Fix from server resource loading

---

CHANGELOG.md
README.md

+ Updated CHANGELOG
+ Updated Compatibility matrix with latest client releases
Fixes #1376

Chore: Updated CHANGELOG after release

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java
kubernetes-examples/src/main/resources/prometheous-rule-cr.yml
kubernetes-examples/src/main/resources/prometheous-rule-crd.yml
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
kubernetes-tests/src/test/resources/test-hello-cr.yml

Minor improvements in RawCustomResourceOperationsImpl like `load()`, edit with Maps and an example

Add example for custom resource new dsl

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java

Fixes #1523
Added createOrReplace() method to dsl

Fix #1523: Can't apply CRD from raw resource more than one time

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/KubernetesListOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/KubernetesListHandler.java
kubernetes-client/src/main/resources/resource-handler.vm
openshift-client/src/main/resources/resource-handler.vm

Fix #758: Deleting Deployments with `.cascading(true)` creates a new Replica Set

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java

fix #1515 HasMetadataOperation.periodicWatchUntilReady is broken

---

CHANGELOG.md
README.md
kubernetes-client/pom.xml
kubernetes-examples/pom.xml
kubernetes-itests/pom.xml
kubernetes-model/kubernetes-model-annotator/pom.xml
kubernetes-model/kubernetes-model-common/pom.xml
kubernetes-model/kubernetes-model/pom.xml
kubernetes-model/model-generator-app/pom.xml
kubernetes-model/pom.xml
kubernetes-server-mock/pom.xml
kubernetes-tests/pom.xml
openshift-client/pom.xml
openshift-server-mock/pom.xml
platforms/karaf/features/pom.xml
platforms/karaf/itests/pom.xml
platforms/karaf/pom.xml
platforms/pom.xml
pom.xml
uberjar/pom.xml

+ Updated pom version to 4.3-SNAPSHOT
+ Updated compatibility matrix as per latest release
+ Updated CHANGELOG

Chore: Update pom and CHANGELOG after release

---

CHANGELOG.md
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/HorizontalPodAutoscalerExample.java
kubernetes-model/Gopkg.lock
kubernetes-model/cmd/generate/generate.go
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json

Fix #1589: Move HorizontalPodAutoscaler to autoscaling/v1

---

CHANGELOG.md
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodPresetTest.java
kubernetes-tests/src/test/resources/test-conflict-pod.yml
kubernetes-tests/src/test/resources/test-conflict-podpreset.yml
kubernetes-tests/src/test/resources/test-multiple1-podpreset.yml
kubernetes-tests/src/test/resources/test-multiple2-podpreset.yml
kubernetes-tests/src/test/resources/test-podpreset-pod.yml
kubernetes-tests/src/test/resources/test-podpreset.yml

Fixes #1381
Test coverage for PodPreset.

PodPresetTest added

---

CHANGELOG.md
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/EndpointsTest.java
kubernetes-tests/src/test/resources/test-endpoints.yml

Fixes #1381
Test coverage provided for Endpoints.

EndpointsTest added

---

kubernetes-model/cmd/generate/generate.go
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json

Chore: Add APIGroup to kubernetes model

---

kubernetes-itests/src/test/java/io/fabric8/kubernetes/ReplicaSetIT.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/AdaptTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/GroupTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/KubernetesOperationTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OpenshiftRoleTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/UserTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftAdapterSupport.java

Fix #1587: Refactor isOpenshift method in OpenshiftAdapterSupport in order to be compatible with Openshift 4

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/SubjectAccessReviewDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/SubjectAccessReviewDSLImpl.java
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-validation-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/CreateableSelfSubjectAccessReview.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/CreateableSelfSubjectRulesReview.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/SubjectAccessReviewOperation.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/SubjectAccessReviewOperationImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
openshift-client/src/main/resources/resource-handler.vm

Add support for SelfSubjectAccessReview & SelfSubjectRulesReview

---

CHANGELOG.md
openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java

Closes #1641
PS: Sorry about the formatting. I don't know which formatter is used

[ENTESB-10817] Openshift 4.1 + FMP: Unexpected response (403 Forbidden), to the authorization request. Missing header:[Location]!

---

CHANGELOG.md
kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java
kubernetes-itests/src/test/resources/kafka-cr.yml
kubernetes-itests/src/test/resources/kafka-crd.yml
kubernetes-model/Gopkg.lock
kubernetes-model/cmd/generate/generate.go
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
kubernetes-tests/src/test/resources/sparkapplication-crd.yml
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/CreateableSelfSubjectAccessReview.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/SubjectAccessReviewOperation.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/SubjectAccessReviewOperationImpl.java

Fix #1565: CRD's Enums are prefixed with "Raw: " keyword

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ResourceCompare.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftAdapterSupport.java

refactor: minimize creation of ObjectMapper objects

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java

feature(config): Introduced kubernetes.disable.autoConfig to disable auto configuration in Config constructor

---

kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java

This commit gets rid of some deprecated methods and avoids creating unecessary objects

chore: minor refactor to KubernetesDeserializer

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java

I believe unused code can be removed.

Remove unused argument and exceptions

---

CHANGELOG.md
extensions/service-catalog/client/pom.xml
extensions/service-catalog/model/pom.xml
extensions/service-catalog/pom.xml
kubernetes-model/Gopkg.lock
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
pom.xml

Fix #1730: Fix failing build on jdk11

---

CHANGELOG.md
kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
pom.xml

Added in kubernetes-server-mock (CRUD) the withoutLabel filter and respective tests...
Project mockwebserver was modified too, and PR was opened.

iss_1688 - Added the withoutLabel filter logic

---

CHANGELOG.md
extensions/knative/model/pom.xml
extensions/service-catalog/model/servicecatalog-model/pom.xml
extensions/tekton/model/pom.xml
kubernetes-model/kubernetes-model/pom.xml

This is meant to address: https://github.com/quarkusio/quarkus/issues/3593

fix: Remove @Valid annotation from generated classes fields.

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-itests/src/test/java/io/fabric8/openshift/UserImpersonationIT.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftAdapterSupport.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java

fix (#1759): Avoid closing the client on each openshift request.

---

CHANGELOG.md
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-validation-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/TemplateInstanceOperation.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/TemplateInstanceResource.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateInstanceOperationContext.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateInstanceOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Add support for TemplateInstance

---

CHANGELOG.md
kubernetes-model/cmd/generate/generate.go
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-validation-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json

Add support for ControllerRevision

---

kubernetes-model/kubernetes-model/src/main/resources/schema/kube-validation-schema.json

Fixed conflicts in kube-validation-schema.json due to TemplateInstance and ControllerRevision.

Fix conflict in kube-validation-schema.json

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/SharedProcessor.java

Fix #1782 
fixed my mistake, fixed lock typo in SharedProcessor

Fix #1782: Informer deadlock

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java

Fix #1724: createOrReplace function does not work properly for custom defined resources

---

CHANGELOG.md
extensions/tekton/generator/cmd/generate/generate.go
extensions/tekton/generator/go.mod
extensions/tekton/generator/go.sum
extensions/tekton/model/src/main/resources/schema/tekton-schema.json
extensions/tekton/model/src/main/resources/schema/validation-schema.json

Let's bump tekton to v0.7.0 so that we can address this: #1776

chore (#1776): Bump tekton to v0.7.0.

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceIT.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java

Fix #1789: Create or replace on operation seems broken

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/WaitUntilReadyIT.java

Fix #1607: WaitUntilReady for lists

---

CHANGELOG.md
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PortForwardExample.java
kubernetes-examples/src/main/resources/portforward-example-pod.yml

Fixes #1557
Example added for PortForward.

PortForwardExample Added

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BindingOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/BindingExample.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Fix #1816: Support for Binding in dsl

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/VersionInfo.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/VersionInfoTest.java

I'll update this in a sec with the changelog

fix: VersionInfo date parsing of year

---

CHANGELOG.md
extensions/knative/model/src/main/java/io/fabric8/knative/api/model/KnativeResourceMappingProvider.java

entries for messaging and eventing.

fix (#1838) Use correct apiGroup for knative serving and add missing

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ScalableResource.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StatefulSetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java

Fix #1188: Support for logs for Jobs

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedCustomResourceApiTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/DoneablePodSet.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/PodSet.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/PodSetList.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/PodSetSpec.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/PodSetStatus.java

Fix #1041: Support cascading delete on custom resources

---

README.md

Relates to https://github.com/fabric8io/kubernetes-client/issues/1879

Document kubeconfig property usage

---

CHANGELOG.md
extensions/tekton/client/src/main/java/io/fabric8/tekton/client/DefaultTektonClient.java
extensions/tekton/client/src/main/java/io/fabric8/tekton/client/TektonClient.java
extensions/tekton/generator/cmd/generate/generate.go
extensions/tekton/generator/go.mod
extensions/tekton/generator/go.sum
extensions/tekton/model/src/main/resources/schema/tekton-schema.json
extensions/tekton/model/src/main/resources/schema/validation-schema.json

AFAIK this is all that needs to be done to fix #1889

Update tekton from v0.7.0 to v0.9.0 #1889

---

kubernetes-examples/src/main/java/io/fabric8/openshift/examples/LoadExample.java

Nit: correct spelling

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReflectUtils.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/ReflectUtilsTest.java

[#1902]: Fix reflection

---

CHANGELOG.md
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/HorizontalPodAutoscalerExample.java
kubernetes-model/Gopkg.lock
kubernetes-model/cmd/generate/generate.go
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/HorizontalPodAutoscalerTest.java

Revert HorizontalPodAutoscaler resource to v2beta1.HorizontalPodAutoscaler
Fix #1707

Fix #1707: HorizontalPodAutoscalerSpecBuilder has no metric method

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/ResourceEventHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Cache.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OptionalDependencyWrapper.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java

Fix #1772: Add documentation for KubernetesClient interface

---

kubernetes-examples/pom.xml
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/WaitUntilReadyExample.java

fix: WaitUntilReadyExample works OK

---

.circleci/config.yml
pom.xml

+ Upgrade Sundrio to 0.20.0
+ Enable Integration tests

Chore: Upgrade Sundrio to 0.20.0

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Rollable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Scaleable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicaSetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollableScalableResourceOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StatefulSetOperationsImpl.java
kubernetes-model/Gopkg.lock
kubernetes-model/cmd/generate/generate.go
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java

Fix #417 
Adds support for Scale and DeploymentRollback in DSL
+ Changed extensions/Scale to autoscaling/Scale
+ Added tests

Fix #417: Support Subresources

---

CHANGELOG.md
kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java

@turchenkoalex pointed this out in https://github.com/fabric8io/kubernetes-client/commit/c370d2628aa5da6b7217486373e16a35d7013df2#commitcomment-36713112

Fix my mistake: Handle case for negative exponents while checking Quantity

---

platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/FeatureInstallationTest.java
platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/PropertiesOverrideTest.java
platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/ServiceTest.java

Fix #1957 
Changed url in Karaf tests to https

Fix #1957: Build Failing on CI Due to Central repository moving to HTTPS

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/DefaultKubernetesClientTest.java

Fix #1917: Allow user to add custom headers to client

Fix #1917 Allow user to add custom headers to client

---

CHANGELOG.md
pom.xml

PR to supersede https://github.com/fabric8io/kubernetes-client/pull/1970

Chore: Update Jackson bom to 2.10.2

---

CHANGELOG.md
kubernetes-client/pom.xml
openshift-client/pom.xml

fix: remove useless resource-*.vm from jar packages

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/DefaultKubernetesClientTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
kubernetes-client/src/test/resources/test-list.yml

Added tests verifying reported misbehavior in #1874.
All tests pass, #1874 is probably caused by something else. Additional feedback is required from @nbn for viable fix.

test: tests verifying CRLF works + refactored failing and disabled activated tests

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/PolicyAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/PolicyAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodSecurityPolicyOperationsImpl.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodSecurityPolicyExample.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodSecurityPolicyIT.java
kubernetes-model/Gopkg.lock
kubernetes-model/cmd/generate/generate.go
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodSecurityPolicyCrudTest.java

Closes #1968 #1969 
Updated client classes but also entrypoint in client (added deprecation notice in former entrypoint too)

feat: Updated PodSecurityPolicy api version to be compatible with k8s 1.17

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
kubernetes-client/src/test/resources/test-kubeconfig

Fix #703: Fix NullPointerException in Config.tryKubeConfig

---

CHANGELOG.md
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/TopExample.java
kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Duration.java
kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/DurationTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/MetricsTest.java

Refactor Duration for fully compatibility with `github.com/go-openapi/strfmt.Duration`
Closes: #1964

refactor: Duration is fully compatible with client-go implementation

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodSecurityPolicyOperationsImpl.java

I fixed another line with the wrong api version.
Please integrate it
thx.

new api version for PodSecurityPolicies. #1968

---

README.md
kubernetes-model/Gopkg.lock
kubernetes-model/Gopkg.toml
kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json
kubernetes-model/kubernetes-model/src/main/resources/schema/validation-schema.json

Updated Openshift model to latest revisions. There were not any tags
pushed since v4.1.0 so I just updated the revision

Chore: Update Openshift model to latest version

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BatchAPIGroupExtensionAdapter.java

Added OSGi metadata to BatchAPIGroupExtensionAdapter

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java

Allow the ManagedKubernetesClient to reference an available OAuthTokenProvider.class

---

.github/workflows/sonar.yml
pom.xml

Sonar scanner enabled and run from a GitHub Action Workflow
Closes: #1981 
Sonar scanner results can be checked here https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client

ci: Enable Sonar Analysis

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExampleWithTerminalSize.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java

Fix #1247: URL parameters are not escaped.

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/UtilsTest.java

Fix #2017: Incorrect plural form for Endpoints kind in SharedInformers

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/readiness/ReadinessTest.java

Fix #2047: Made Readiness#isReady more reliable for StatefulSets

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListener.java

https://gitter.im/fabric8io/kubernetes-client?at=5e68c96ca2ccef3232e785f8

fix : NullPointerException with upload() websocket failures

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/UtilsTest.java
kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LabelTest.java

Fix #2009: Regression `withoutLabel()` stopped to work

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StatefulSetOperationsImpl.java

fixes #2078 watchLog for Deployment and StatefulSet

---

README.md
pom.xml

ci: Change Sonar Cloud project under Fabric8io organization

---

CHANGELOG.md
kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
kubernetes-model/kubernetes-model/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java

Fix #2034: Quantity.equals mishandles fractions

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java

Fix #1586: Replace of Job should add extra selector property to the resource

---

CHANGELOG.md
extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/PipelineResourceCreate.java
extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/TaskCreate.java
extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/TaskRunCreate.java
extensions/tekton/generator/go.mod
extensions/tekton/generator/go.sum
extensions/tekton/model/src/main/resources/schema/validation-schema.json
pom.xml

Fix #1987 
+ Added TaskRunCreate and TaskCreate example
+ Updated Tekton model to v0.11.0

Fix #1987: Added example of Task and TaskRun in tekton with updated model

---

doc/CHEATSHEET.md

There are still a lot of things to add. But I think we can start with this much.

Doc: Added a document for common operations using Fabric8 Kubernetes Client

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java

Fix #2124: Raw Watch on CustomResource does not work if name specified

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1APIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1APIGroupExtensionAdapter.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1APIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTemplateTest.java
kubernetes-tests/src/test/resources/test-podtemplate.yml
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Fix #2002 
DSL support for `PodTemplate` resource

Fix #2002: Add DSL support for PodTemplate

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java

Fix #2163: kubernetes client support cert chain

---

CHANGELOG.md
pom.xml

Fix #2145: Updated OkHttp to v3.12.11

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Listable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/SubjectAccessReviewDSLImpl.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ListExamples.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/SubjectAccessReviewAuthTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/SubjectAccessReviewOperationImpl.java

Fix #2165: list() should also be able to handle ListOptions

---

kubernetes-model/kubernetes-model-core/pom.xml
kubernetes-model/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
kubernetes-model/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/internal/KubernetesDeserializerTest.java

KubernetesDeserialier lazy loads mappings via current thread (#2109)

---

doc/CHEATSHEET.md

It's not much... but I guess better than nothing :)

[tekton] CHEATSHEET.md updated

---

CHANGELOG.md
kubernetes-model/kubernetes-model-annotator/pom.xml
kubernetes-model/pom.xml
pom.xml

Fix #2195: Annotation processors and build time dependencies transitive

---

CHANGELOG.md
README.md
kubernetes-server-mock/pom.xml
kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/WatchEventsListener.java
kubernetes-tests/pom.xml
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java

Added Watch support on MockServer in Crud mode

---

CHANGELOG.md
kubernetes-client/pom.xml
openshift-client/pom.xml

Fix #1760: The bundle version of kubernetes-client is missing ServiceLoader files

---

CHANGELOG.md
doc/CHEATSHEET.md
extensions/knative/client/src/main/resources/resource-handler.vm
extensions/service-catalog/client/src/main/resources/resource-handler.vm
extensions/tekton/client/src/main/resources/resource-handler.vm
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Watchable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawWatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/KubernetesListHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
kubernetes-client/src/main/resources/resource-handler.vm
kubernetes-client/src/main/resources/resource-operation.vm
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java
openshift-client/src/main/resources/resource-handler.vm
openshift-client/src/main/resources/resource-operation.vm

Fix #1821: ListOptions now supported when watching a Kubernetes Resource

---

CHANGELOG.md
kubernetes-model/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/util/Helper.java
kubernetes-model/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/LoadTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NetworkingV1beta1IngressTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1HorizontalPodAutoscalerTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V2beta2HorizontalPodAutoscalerTest.java
kubernetes-tests/src/test/resources/test-networkpolicy.yml
kubernetes-tests/src/test/resources/test-v1beta1-ingress.yml
kubernetes-tests/src/test/resources/test-v2beta2-hpa.yml

Fix #2251: Modify KubernetesDeserializer for checking classes with same name but different apiVersions

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/URLFromClusterIPImpl.java
kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ServiceToURLProvider
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceTest.java

Fix #2233: Added getUrl() implementation for fetching URL from Service of type ClusterIP

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/ListVisitFromServerGetDeleteRecreateWaitApplicable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Resource.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/VisitFromServerGetWatchDeleteRecreateWaitApplicable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollableScalableResourceOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/BindingOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

- Added type parameters for KubernetesList in KubernetesClient
- Test verifying waitUntilCondition **always** retrieves resource from server (since 4.10.2)

fix: Code clean up + testing

---

CHANGELOG.md
openshift-client/src/main/java/io/fabric8/openshift/client/handlers/ProjectRequestHandler.java
openshift-client/src/main/resources/resource-handler-services.vm

Resuscitate ProjectRequestHandler in openshift-client

---

CHANGELOG.md
README.md
kubernetes-model-generator/README.md
kubernetes-model-generator/kubernetes-model-admissionregistration/src/main/java/io/fabric8/kubernetes/api/model/admission/AdmissionRequest.java
kubernetes-model-generator/kubernetes-model-core/cmd/generate/generate.go
kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/kube-schema.json
kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/validation-schema.json
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/AdmissionReviewTest.java
kubernetes-tests/src/test/resources/admissionreview-withconnectexec.json

Fix #2332 
Adds PodExecOptions model.
(Also fixes small typos in a couple of READMEs).
Let me know if I've missed something...

Add PodExecOptions #2332

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallback.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/SharedProcessor.java

Fix #2299: Improve error handling of RejectedExecutionException from ExecutorService

---

README.md
kubernetes-model-generator/README.md

Update javadoc links for update Kubernetes Model

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/ReplicaSetOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StatefulSetTest.java

Fix #2342: Fix getLog(), watchLog() methods for Job and Deployment

---

kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java

Closing watch used in tests after using it

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java

Add appendResourceVersionInObject for CRD objects

---

kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NetworkingV1beta1IngressTest.java

I missed adding a `@Test` annotation over `testCreateOrReplaceWhenAnnotationUpdated()`, I
noticed it when I was commenting on the issue

Chore: Add missing @Test annotation

---

kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceIT.java

Fix failing ResourceIT list createOrReplace()

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java

Replace hardcoded character sets in projects with StandardCharsets static constants

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java

@GQH1993 said:
> My modifications are on lines 714-716.
> Fixed the total deletion caused when a deleted resource was null.
This is a reopen PR from #2383, commits authored by @GQH1993

Fixed the total deletion caused when a deleted resource was null 

---

README.md

chore: fix build status README badges

chore: fix build status README badges

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java

expose path to kubeconfig file that was used (#2411)

---

kubernetes-itests/src/test/java/io/fabric8/kubernetes/CreateOrReplaceIT.java

Added an integration test for CreateOrReplace

Added an integration test for CreateOrReplace

---

CHANGELOG.md
doc/CHEATSHEET.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/BytesLimitable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Containerable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Prettyable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Tailable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Terminateable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Timeable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Timestampable.java

Fix #2408
Added documentation for all existing log options

Fix #2408: Add documentation for Pod log options

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OIDCTokenRefreshInterceptor.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java
kubernetes-client/src/test/resources/test-kubeconfig-oidc

Fix #2111: Add Support for OIDC token refresh
- Added OIDCTokenRefreshInterceptor which would try to refresh token
in case 401 is received.
- OpenIDConnectionUtils would refresh token using two HTTP requests
- first client tries to get OpenID provider discovery document at
[[.issuer-url]]/.well-known/openid-configuration and gets token_endpoint
- Then client does a POST request to token_endpoint with all the required
parameters(refresh_token, client_id, client_secret etc)

Fix #2111: Add Support for OIDC token refresh

---

CHANGELOG.md
kubernetes-itests/src/test/java/io/fabric8/kubernetes/JobIT.java

Fix #2507: Add a test for creating a Job with generateName

---

CHANGELOG.md
kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentCrudTest.java

Fix #2517: Replace does not work in CRUD mockwebserver

---

kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceIT.java

This PR addresses review comments added in #2472 which were added after PR actually
got merged

Chore: follow-up PR for https://github.com/fabric8io/kubernetes-client/pull/2472

---

CHANGELOG.md
README.md

+ latest Kubernetes Versions should be shown first followed by older versions
+ Added column for 1.16.0 as discussed in #2509
+ Added column for OpenShift 4.5.14(after running integration tests on `crc`)

Chore: Fix order of Kubernetes versions in Compatibility matrix

---

kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/FullExample.java

Fix rolling update error in FullExample according to PR-2272 (#2555)

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/PodStatusUtil.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/PodMockUtils.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/PodStatusUtilTest.java

PodStatusUtil#isRunning & #isInitializing (#2293)

---

CHANGELOG.md
kubernetes-model-generator/kubernetes-model-core/cmd/generate/generate.go
kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/kube-schema.json
kubernetes-model-generator/kubernetes-model-core/src/main/resources/schema/validation-schema.json

Fixes #2574
Add supports for Condition type that was added in https://github.com/kubernetes/apimachinery/commit/d8315376cf5ef3f6105fd76c1f867b921c59923a

feat: add support for metav1.Condition

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java

Fixes the issue #2300 . Removes job extensions/v1beta1 from backward compatibility interceptor. As job has been removed from extensions/v1beta1 .

remove job extensions/v1beta1 from backward compatibility

---

kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java
kubernetes-examples/src/main/java/io/fabric8/openshift/examples/AdaptClient.java

Changed KubernetesClient usage to try-with-resources in LoadMultipleDocumentsFromFileExample & AdaptClient
Related to #2444 

Fixing some code smells by closing the kubernetes client

---

extensions/knative/tests/src/test/java/io/fabric8/knative/test/AdaptTest.java
extensions/knative/tests/src/test/java/io/fabric8/knative/test/crud/ServiceCrudTest.java
extensions/service-catalog/tests/src/test/java/io/fabric8/servicecatalog/test/AdaptTest.java
extensions/service-catalog/tests/src/test/java/io/fabric8/servicecatalog/test/crud/ClusterServiceBrokerTest.java
extensions/service-catalog/tests/src/test/java/io/fabric8/servicecatalog/test/crud/ClusterServiceClassTest.java
extensions/service-catalog/tests/src/test/java/io/fabric8/servicecatalog/test/crud/ClusterServicePlanTest.java
extensions/service-catalog/tests/src/test/java/io/fabric8/servicecatalog/test/crud/ServiceBindingTest.java
extensions/service-catalog/tests/src/test/java/io/fabric8/servicecatalog/test/crud/ServiceInstanceTest.java
extensions/tekton/tests/src/test/java/io/fabric8/tekton/test/AdaptTest.java
extensions/tekton/tests/src/test/java/io/fabric8/tekton/test/crud/PipelineCrudTest.java
extensions/tekton/tests/src/test/java/io/fabric8/tekton/test/crud/V1alpha1PipelineCrudTest.java

refactor tests to remove public modifier

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AppsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BatchAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/MetricAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/NetworkAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RbacAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SchedulingAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SettingsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/StorageAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java

refactor to remove thrown KubernetesClientException

---

CHANGELOG.md
extensions/knative/model/src/test/java/io/fabric8/knative/ModelTest.java
extensions/tekton/model-v1beta1/src/test/java/io/fabric8/tekton/ModelTest.java
model-annotator/src/main/java/io/fabric8/kubernetes/ModelAnnotator.java

fix(#2596) Add buildable ref for container, port and volume

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Pluralize.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudWithCRDContextTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Provide a customResources alternative that only accepts resourceType as an argument

---

kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ListCustomResourceDefinitions.java
kubernetes-examples/src/main/java/io/fabric8/openshift/examples/BuildConfigExamples.java
kubernetes-examples/src/main/java/io/fabric8/openshift/examples/DeploymentConfigExamples.java
kubernetes-examples/src/main/java/io/fabric8/openshift/examples/LoadExample.java

Fix #2444 Use try with resources in kubernetes-examples

---

kubernetes-examples/pom.xml
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecuteCommandOnPodExample.java

Example of executing commands on a pod with cleaning all the resources after the execution.

Execute command on pod example

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java

doc: Add deprecation notice fo customResourceDefinitions() DSL method.
As reported by @jonathanvila.

doc: Add deprecation notice fo customResourceDefinitions() DSL method

---

CHANGELOG.md
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java
kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/HasMetadataTest.java

fix: add `isFinalizerValid` to encapsulate validation logic

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesVersionFactory.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesVersionPriority.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/KubernetesVersionFactoryTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/KubernetesVersionPriorityTest.java

Allow to pick the CustomResourceDefinitionVersion with the highest priority (#2599)

---

.github/workflows/build.yml

Add Github Action Workflow for Java 11 build

---

kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrud1109Test.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/FooBar.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/crd/FooBarList.java

test: Added specific verification for issue #1109
Relates to #2658 

test: Added specific verification for issue #1109

---

CHANGELOG.md
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java
kubernetes-examples/src/main/resources/multiple-document-template.yml

Fix #2642 
Update `kubernetes-examples/../multiple-document-template.yml` to use apps/v1
Deployment rather than extensions/v1beta1

Fix #2642: Update kubernetes-examples to use apps/v1 Deployment rather than extensions/v1beta1

---

.github/workflows/e2e-tests.yml

ci: Upgrade manusa/actions-setup-minikube to v2.2.0

ci: Upgrade manusa/actions-setup-minikube to v2.2.0

---

README.md
doc/KubernetesOperatorsInJavaWrittenUsingFabric8.md

I think having a list of already existing examples would be a nice addition. Users can get an idea of where to start by looking at these examples.
I checked Github Depends By section and added entries that seemed okay. Feel free to suggest more projects if you know.

Doc: Add a Section for Kubernetes Java Operators written using Fabric8

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java

fix: spec and status don't need to be KubernetesResources

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperationRequestBuilder.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawRequestBuilder.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawWatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WebSocketClientRunner.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManagerTest.java

Refactor watcher code so that more code is shared between implementations.

Refactor watchers

---

README.md

fixed example code for editing resources

---

doc/CHEATSHEET.md

chore: typo compilcated -> complicated

---

kubernetes-model-generator/pom.xml
pom.xml

I broke
https://github.com/fabric8io/kubernetes-client/pull/2604
when updating the branch

make build near reproducible (jandex index is not)

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java

Update log level to warn to avoid error logs during stopAllRegisteredInformers#2753

---

kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CustomResourceV1Example.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/Dummy.java

We added support for automatically instantiating Spec and Status in https://github.com/fabric8io/kubernetes-client/pull/2739 but somehow missed updating our examples, due to that I was facing status instantiation errors like these:
```
Caused by: java.lang.IllegalArgumentException: Cannot instantiate Status, consider overriding initStatus: Cannot instantiate interface/abstract type io.fabric8.kubernetes.api.model.KubernetesResource
at io.fabric8.kubernetes.client.CustomResource.genericInit(CustomResource.java:342)
```

Chore: Fix Status initialization errors in kubernetes-examples/

---

CHANGELOG.md
kubernetes-client/pom.xml
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java

fix: use proper classloader

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CustomResourceInformerExample.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CustomResourceV1Example.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/CustomResourceCreateDemo.java
kubernetes-itests/src/test/java/io/fabric8/commons/DeleteEntity.java
kubernetes-itests/src/test/java/io/fabric8/commons/ReadyEntity.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudWithCRDContextTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PropagationPolicyTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedClusterScopeCustomResourceApiTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedCustomResourceApiTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Fix #2694 
Removing the following deprecated methods from KubernetesClient DSL:
- `client.customResourceDefinitions()`
- `client.events()`
- `client.customResources(CustomResourceDefinitionContext crd, Class<T>
resourceType, Class<L> listClass)`
- `client.customResources(CustomResourceDefinition crd, Class<T>
resourceType, Class<L> listClass)`
- `client.customResource(CustomResourceDefinition crd, Class<T>
resourceType, Class<L> listClass)`

Fix #2694: Remove deprecated methods from KubernetesClient DSL

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java

resyncPeriodMillis is analyzed and never used inside addEventHandlerWithResyncPeriod method.
Most probably there is a typo on line 115:
ProcessorListener<T> listener = new ProcessorListener(handler, determineResyncPeriod(resyncCheckPeriodMillis, this.resyncCheckPeriodMillis));
one of the parameters should be resyncPeriodMillis that is provided to the method, so this fix corrects this bug

addEventHandlerWithResyncPeriod  fix

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java

Fix (partially) #2766 
Replace occurrences of Function<T, T> with UnaryOperator<T>. Imports are also reorganized in the touched class.

Issue-2766: Replace occurrences of Function<T, T> with UnaryOperator<T>

---

kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/KubernetesListTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ClusterRoleTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CronJobTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/VersionInfoTest.java

Fix #2804 
- Swap assertion arguments so they are in the correct order (expected value, actual value)
- Minor: Imports reorganized in few classes
- Minor: Anonymous new Visitor() replaced with lambda 

Issue-2804: Swap assertion arguments so they are in the correct order (expected value, actual value)

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java

spec/ status
-------
Resolves: #2827

fix (#2827) Use crd classloader and fallback to tccl when initalizing

---

CHANGELOG.md
kubernetes-examples/src/main/java/io/fabric8/openshift/examples/LoginExample.java
kubernetes-itests/src/test/java/io/fabric8/commons/ClusterEntity.java
kubernetes-itests/src/test/java/io/fabric8/openshift/AdaptIT.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/AdaptTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftAdapterSupport.java

Related to https://github.com/eclipse/jkube/issues/566
OpenshiftAdapterSupport hits `/apis` endpoint for getting list of
available APIGroups. This fails for OpenShift 4 since OpenShift 4 gives
403. Modify OpenShiftAdapterSupport.isOpenShiftAPIGroups to use
OkHttpClient instance with added `OpenShiftOAuthInterceptor`

Fix client.adapt behavior for OpenShiftClient on OpenShift 4

---

extensions/service-catalog/client/src/main/java/io/fabric8/servicecatalog/client/internal/ClusterServiceClassOperationsImpl.java

- Removed assignment to local variable "p"
- Removed unused local variable "p"
Fixes #2826 

Fix #2826: Removed unused local variable

---

.github/workflows/e2e-tests.yml
kubernetes-itests/src/test/java/io/fabric8/kubernetes/CreateOrReplaceIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ServiceIT.java

Chore: Add Kubernetes v1.20.1 to Github Action minikube workflow matrix

---

crd-generator/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java

- Define a constant instead of duplicating literals "string" and "number"
- Changed member access modifier to "protected"
- Reduce the total number of break and continue statements in loop to use at most one
Fixes #2823 

Fix #2823: Reduced number of duplicate literals and continue statements

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/CustomResourceTest.java

fix!: remove automatic instantiation of spec and status

---

crd-generator/pom.xml

This would allow consumers of the generator to retrieve it transitively,
making it easier to use the generator.
Fixes #2840

feat: include common model dependency

---

CHANGELOG.md

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

fix: fix typo in changelog

---

kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java

Change from Guava/Apache API to pure JDK Files API in the PodIT test

test: Use JDK Files API in PodIT tests

---

CHANGELOG.md
crd-generator/src/main/java/io/fabric8/crd/generator/apt/CustomResourceInfo.java
crd-generator/src/main/java/io/fabric8/crd/generator/v1/CustomResourceHandler.java
crd-generator/src/main/java/io/fabric8/crd/generator/v1beta1/CustomResourceHandler.java
crd-generator/src/main/java/io/fabric8/crd/generator/visitor/AdditionalPrinterColumnDetector.java
crd-generator/src/main/java/io/fabric8/crd/generator/visitor/LabelSelectorPathDetector.java
crd-generator/src/main/java/io/fabric8/crd/generator/visitor/SpecReplicasPathDetector.java
crd-generator/src/main/java/io/fabric8/crd/generator/visitor/StatusReplicasPathDetector.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
kubernetes-itests/src/test/java/io/fabric8/crd/zookeeper/ZookeeperCustomResourceIT.java
kubernetes-itests/src/test/java/io/fabric8/crd/zookeeper/v1/ZookeeperSpec.java
kubernetes-itests/src/test/java/io/fabric8/crd/zookeeper/v1/ZookeeperStatus.java
kubernetes-itests/src/test/java/io/fabric8/crd/zookeeper/v1alpha1/ZookeeperSpec.java
kubernetes-itests/src/test/java/io/fabric8/crd/zookeeper/v1alpha1/ZookeeperStatus.java
kubernetes-model-generator/kubernetes-model-common/pom.xml
kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/Scope.java
kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/LabelSelector.java
kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/PrinterColumn.java
kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/SpecReplicas.java
kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/annotation/StatusReplicas.java

Move CRD annotations to kubernetes-model-common

---

CHANGELOG.md
crd-generator/api/src/main/java/io/fabric8/crd/generator/CRDGenerator.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java
crd-generator/apt/src/main/java/io/fabric8/crd/generator/apt/CustomResourceAnnotationProcessor.java
kubernetes-itests/pom.xml
kubernetes-itests/src/test/java/io/fabric8/crd/Base.java
kubernetes-itests/src/test/java/io/fabric8/crd/BaseSpec.java
kubernetes-itests/src/test/java/io/fabric8/crd/BaseStatus.java
kubernetes-itests/src/test/java/io/fabric8/crd/Foo.java
kubernetes-itests/src/test/java/io/fabric8/crd/FooCRDIT.java
kubernetes-itests/src/test/java/io/fabric8/crd/FooSpec.java
kubernetes-itests/src/test/java/io/fabric8/crd/FooStatus.java
kubernetes-itests/src/test/java/io/fabric8/crd/zookeeper/ZookeeperCustomResourceIT.java
pom.xml

feat: improve handling of complex CR hierarchies

---

extensions/chaosmesh/client/pom.xml
extensions/chaosmesh/model/pom.xml
extensions/service-catalog/client/pom.xml
extensions/service-catalog/model/pom.xml
extensions/tekton/client/pom.xml
extensions/tekton/model-v1alpha1/pom.xml
extensions/tekton/model-v1beta1/pom.xml

Chore: Remove references to jackson-module-jaxb-annotations from repository

---

CHANGELOG.md
crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedPropertyPathDetector.java

fix: crd path detectors skip enums

---

CHANGELOG.md
extensions/tekton/client/src/main/java/io/fabric8/tekton/client/V1alpha1APIGroupClient.java
extensions/tekton/client/src/main/java/io/fabric8/tekton/client/dsl/V1alpha1APIGroupDSL.java
extensions/tekton/generator-triggers/cmd/generate/generate.go
extensions/tekton/model-triggers/src/main/resources/schema/tekton-schema-triggers.json

Makes it possible to create and manage Tekton Triggers
directly and not via EventListener only.
Fixes #2938

feat(tekton): expose Tekton Triggers trigger API

---

.github/workflows/build.yml
.github/workflows/e2e-tests.yml
.github/workflows/javadocs.yml
.github/workflows/license.yml
.github/workflows/sonar.yml

Add options to workflow CI:
-B,--batch-mode
-C,--strict-checksums
-V,--show-version
-ntp,--no-transfer-progress

Add additionals maven options to CI

---

CHANGELOG.md
kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/WatchEventsListener.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java

When a watch is added it should provide events for existing resources.
There don't seem to be any tests covering mock watches.

adding an added event when the watch is added

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java

copy to/from pods: fixed error message; removed debug output

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractCustomResourceHandler.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/CustomResourceHandler.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/CustomResourceHandler.java
crd-generator/apt/src/main/java/io/fabric8/crd/generator/apt/CustomResourceAnnotationProcessor.java

Simplify crd generator code

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/CustomResourceInfo.java
crd-generator/api/src/test/java/io/fabric8/crd/generator/CustomResourceInfoTest.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java

CRD generator API fixes 

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AppsAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/AppsAPIGroupDSL.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ControllerRevisionTest.java
kubernetes-tests/src/test/resources/test-controllerrevision.yml

+ Add `controllerRevisions()` DSL entrypoint in `client.apps()`. Although, ControllerRevision is primarily intended for internal use by controllers; let's keep it for sake of completeness. You can also create a plain ControllerRevision using `kubectl create -f`
Related to https://github.com/fabric8io/kubernetes-client/issues/2912

Add DSL Support for `apps/v1#ControllerRevision` resource

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/StorageAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/StorageAPIGroupDSL.java
kubernetes-model-generator/kubernetes-model-storageclass/cmd/generate/generate.go
kubernetes-model-generator/kubernetes-model-storageclass/src/main/resources/schema/kube-schema.json
kubernetes-model-generator/kubernetes-model-storageclass/src/main/resources/schema/validation-schema.json
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CSIStorageCapacityTest.java
kubernetes-tests/src/test/resources/test-csistoragecapacity.yml

I noticed this when I upgraded my minikube to v1.21.0 and noticed there is an additional resource in `storage.k8s.io/v1beta1`
This should fix #2912 

Fix #2912: Add DSL Support for storage.k8s.io/v1beta1 CSIStorageCapacity

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java

fix: do not output null values on CustomResources

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ControllerTest.java

Fix #3014 
Cancel resync future and shutdown executor while stopping informer

Cancel resync future and shutdown executor while stopping informer

---

CHANGELOG.md
pom.xml

-------
Bump sundrio to 0.30.6 which deals with StackOverflow bug

chore: bump sundrio to 0.30.6

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImplTest.java

set resourceVersion for before replacing RawCustomResource

---

CHANGELOG.md
crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/Annotated.java
crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java

feat: account for JsonProperty annotation to compute properties name

---

CHANGELOG.md
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/CustomResourceHandler.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/SortPrinterColumnsDecorator.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/CustomResourceHandler.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/SortPrinterColumnsDecorator.java
crd-generator/api/src/test/java/io/fabric8/crd/example/joke/JokeRequestSpec.java
crd-generator/api/src/test/java/io/fabric8/crd/example/person/Address.java
crd-generator/api/src/test/java/io/fabric8/crd/example/person/Person.java
crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java

fix: order printer columns by json path for consistent ordering

---

CHANGELOG.md
crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/JsonSchema.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/JsonSchema.java
crd-generator/api/src/test/java/io/fabric8/crd/example/inherited/ChildSpec.java
crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java

fix: properly output additionalProperties field for map-like fields

---

doc/CHEATSHEET.md

Fixed misnamed variable in example code

---

CHANGELOG.md
kubernetes-model-generator/openshift-model/cmd/generate/generate.go
kubernetes-model-generator/openshift-model/src/generated/java/io/fabric8/kubernetes/api/model/KubeSchema.java
kubernetes-model-generator/openshift-model/src/generated/java/io/fabric8/openshift/api/model/ResourceAccessReviewResponse.java
kubernetes-model-generator/openshift-model/src/generated/java/io/fabric8/openshift/api/model/RoleBindingRestrictionList.java
kubernetes-model-generator/openshift-model/src/main/resources/schema/kube-schema.json
kubernetes-model-generator/openshift-model/src/main/resources/schema/validation-schema.json
kubernetes-model-generator/pkg/schemagen/generate.go
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ClusterRoleTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/RoleBindingRestrictionTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SubjectAccessReviewTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftLocalSubjectAccessReviewOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftSubjectAccessReviewOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Add DSL support for the following resources:
- ResourceAccessReview : `client.resourceAccessReviews()`
- LocalSubjectAccessReview : `client.localSubjectAccessReviews()`
- ClusterRole : `client.clusterRoles()`
- LocalResourceAccessReview : `client.localResourceAccessReviews()`
- SubjectRulesReview : `client.subjectRulesReviews()`
- SelfSubjectRulesReview : `client.selfSubjectRulesReviews()`
- RoleBindingRestrictions: `client.roleBindingRestrictions()`
Related to https://github.com/fabric8io/kubernetes-client/issues/2949

Add missing OpenShift Resources in `authorization.openshift.io` apiGroup in OpenShiftClient DSL

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java

Fixed typo oicd -> oidc
https://github.com/fabric8io/kubernetes-client/pull/3105#discussion_r643024114

Fixed typo oicd -> oidc

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/v1/decorator/AddAdditionPrinterColumnDecorator.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/v1beta1/decorator/AddAdditionPrinterColumnDecorator.java

Fix part of the Sonar issues reported in #3162 

Replaced anonymous inner classes with lambdas

---

kubernetes-model-generator/openshift-model/cmd/generate/generate.go
kubernetes-model-generator/openshift-model/src/generated/java/io/fabric8/kubernetes/api/model/KubeSchema.java
kubernetes-model-generator/openshift-model/src/main/resources/schema/kube-schema.json
kubernetes-model-generator/openshift-model/src/main/resources/schema/validation-schema.json
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ImageSignatureTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ImageStreamImageTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ImageStreamImportTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ImageStreamMappingTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftCreateOnlyResourceOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/image/ImageSignatureOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/image/ImageStreamImageOperationsImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java

Add support for the following resources in OpenShiftClient DSL
- ImageStreamImport `openShiftClient.imageStreamImports()`
- ImageStreamImage `openShiftClient.imageStreamImages()`
- ImageStreamMapping `openShiftClient.imageStreamMappings()`
- ImageSignature `openShiftClient.imageSignatures()`
Related to #2949

Add missing resources in `image.openshift.io` apiGroup to OpenShiftClient DSL

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/utils/Generics.java
extensions/camel-k/client/src/main/java/io/fabric8/camelk/client/DefaultCamelKClient.java
extensions/camel-k/mock/src/main/java/io/fabric8/camelk/mock/CamelKServer.java
extensions/camel-k/model-v1/src/main/java/io/fabric8/camelk/v1/TraitConfiguration.java
extensions/knative/client/src/main/java/io/fabric8/knative/client/DefaultKnativeClient.java
extensions/knative/client/src/main/java/io/fabric8/knative/client/serving/v1/DefaultServingV1Client.java
extensions/knative/mock/src/main/java/io/fabric8/knative/mock/KnativeServer.java
extensions/service-catalog/mock/src/main/java/io/fabric8/servicecatalog/server/mock/ServiceCatalogServer.java
extensions/tekton/client/src/main/java/io/fabric8/tekton/client/DefaultTektonClient.java
extensions/tekton/mock/src/main/java/io/fabric8/tekton/mock/TektonServer.java
extensions/tekton/model-v1beta1/src/main/java/io/fabric8/tekton/pipeline/v1beta1/ArrayOrString.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Lister.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStore.java
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/IntOrString.java
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/WatchEvent.java
kubernetes-model-generator/openshift-model-monitoring/src/main/java/io/fabric8/openshift/api/model/monitoring/v1alpha1/PagerDutyConfig.java
kubernetes-model-generator/openshift-model/src/main/java/io/fabric8/openshift/api/model/Template.java
openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock/OpenShiftServer.java

Use diamond operator (<>) wherever possible

---

CHANGELOG.md
README.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListener.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java

Configuration for pod upload connection and request timeout. 
https://github.com/fabric8io/kubernetes-client/issues/3202

iss_32020 PodUpload timeouts

---

.github/workflows/windows-build.yml
uberjar/src/test/java/io/fabric8/kubernetes/clnt/UberJarTest.java

Windows tests were supposedly fixed in #3244, let's add a GitHub action
workflow for windows builds so that we don't break tests on windows
again

Add Github Action workflow for Windows build

---

README.md

Added Boomerang Flow to the list of communities using Fabric8. Boomerang Flow is a cloud-native workflow automation tool that uses the Fabric8 Kubernetes Client and Fabric8 Tekton Client under the covers.

Added Boomerang Flow to the list of communities

---

CHANGELOG.md
extensions/tekton/generator-v1beta1/go.mod
extensions/tekton/generator-v1beta1/go.sum
extensions/tekton/model-v1beta1/src/main/resources/schema/tekton-schema-v1beta1.json

This PR updates the model of tekton pipelines to 0.25.0

[tekton] update model to v0.25.0

---

kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/BindingExample.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ConfigMapExample.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/EndpointsExample.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExample.java

add lots of annotate

---

extensions/camel-k/client/src/main/resources/resource-handler.vm
extensions/certmanager/client/src/main/resources/resource-handler.vm
extensions/chaosmesh/client/src/main/resources/resource-handler.vm
extensions/knative/client/src/main/resources/resource-handler.vm
extensions/service-catalog/client/src/main/resources/resource-handler.vm
extensions/tekton/client/src/main/resources/resource-handler.vm
extensions/volumesnapshot/client/src/main/resources/resource-handler.vm
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ResourceHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/KubernetesListHandler.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/CreateOrReplaceHelper.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/DeleteAndCreateHelper.java
kubernetes-client/src/main/resources/resource-handler.vm
openshift-client/src/main/java/io/fabric8/openshift/client/handlers/ProjectRequestHandler.java
openshift-client/src/main/java/io/fabric8/openshift/client/handlers/imageregistry/operator/ConfigHandler.java
openshift-client/src/main/java/io/fabric8/openshift/client/handlers/operator/ConfigHandler.java
openshift-client/src/main/resources/resource-handler.vm

Chore to move implementation logic from the templates to the ResourceHandler interface.

chore: minimizing methods in handler templates

---

kubernetes-client/pom.xml
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java

Fix #2887 
Added utility method for secret creation.

Fix #2887: create secret of docker-registry

---

CHANGELOG.md
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java

fix: OpenShiftConfig missing some configurations from provided Config

fix: OpenShiftConfig missing some configurations from provided Config

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/utils/Generics.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/utils/Metadata.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/utils/Types.java
extensions/camel-k/client/src/main/java/io/fabric8/camelk/client/util/ApiVersionUtil.java
extensions/certmanager/examples/src/main/java/io/fabric8/certmanager/examples/ClientFactory.java
extensions/knative/client/src/main/java/io/fabric8/knative/client/util/ApiVersionUtil.java
extensions/knative/examples/src/main/java/io/fabric8/knative/api/examples/ClientFactory.java
extensions/knative/model/src/main/java/io/fabric8/knative/api/model/Constants.java
extensions/service-catalog/client/src/main/java/io/fabric8/servicecatalog/client/util/ApiVersionUtil.java
extensions/service-catalog/examples/src/main/java/io/fabric8/servicecatalog/examples/ClientFactory.java
extensions/service-catalog/model/src/main/java/io/fabric8/servicecatalog/api/model/Constants.java
extensions/tekton/client/src/main/java/io/fabric8/tekton/client/util/ApiVersionUtil.java
extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/ClientFactory.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfigHolder.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SerializationUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ApiVersionUtil.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReflectUtils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLFromServiceUtil.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java
kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/util/Helper.java
openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftAPIGroups.java

Added private constructor in utility classes to hide implicit constructor

---

README.md

Add Apache Flink to the list of Fabric8 users. We've been using the client for quite a while now, and our K8s user-base is constantly growing.

Add Flink to the list of fabric8 users

---

crd-generator/README.md

Fixes the right path where the CRD files are generated.

Fix path where CRD files are generated

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/URLFromEnvVarsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/URLFromNodePortImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLFromServiceUtil.java

I have fixed 3 vulnerabilities referenced sin [Sonarcloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client)

Fix 3 Sonalcloud Vulnerabilities on logger definitions

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java

feat: add equals and hashCode implementations for CustomResource

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractCustomResourceHandler.java

Fix #3401
I have updated the lambda function in AbstractCustomResourceHandler for better readability.
#3401

replace lambda with a method reference for better readability

---

CHANGELOG.md
crd-generator/api/pom.xml
crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java
crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java

fix: enum values should honor JsonProperty annotations

---

CHANGELOG.md
kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java

https://github.com/fabric8io/kubernetes-client/pull/3432

fix ConcurrentModificationException in KubernetesCrudDispatcher --> was #3432

---

extensions/camel-k/tests/pom.xml
extensions/certmanager/tests/pom.xml
extensions/chaosmesh/tests/pom.xml
extensions/knative/tests/pom.xml
extensions/service-catalog/tests/pom.xml
extensions/tekton/tests/pom.xml
extensions/volumesnapshot/tests/pom.xml
kubernetes-client/pom.xml
kubernetes-server-mock/pom.xml
kubernetes-tests/pom.xml
openshift-client/pom.xml
pom.xml

fix: Fix mockwebserver dependency in modules and main pom.xml

fix: Fix mockwebserver dependency in modules and main pom.xml

---

CHANGELOG.md
pom.xml

Revert "chore(deps): bump jandex from 2.3.1.Final to 2.4.0.Final"
This reverts commit 5b2b0987d729ec5433e7ff5ccdea8e5a520903ae.
Relates to: quarkusio/quarkus#19831

Revert "chore(deps): bump jandex from 2.3.1.Final to 2.4.0.Final"

---

CHANGELOG.md
crd-generator/README.md

dependencies have change from one (io.fabric8:crd-generator) to two (io.fabric8:crd-generator-api & io.fabric8:crd-generator-apt)

Update the crd-generator/README.md file

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Scaleable.java

Adding a java doc about the wait parameter to resolve #3398

fix #3398 adding a javadoc about wait

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java

fix: sanitizeName now truncate names to be less than 63 chars

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Filterable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/FilterNestedImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/OperationContextTest.java

Improve selectors support in `OperationContext`

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java

This check  should be removed because "null" can appear in a valid URL. https://github.com/fabric8io/kubernetes-client/blob/d1740ffeaa624bd63b6d929b25d764a477c1c17e/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java#L151

fix #3548: Removed url.contains("null") check

---

kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/GenericKubernetesResource.java
kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/GenericKubernetesResourceTest.java

Add `@Buildable` annotation to GenericKubernetesResource class in order
to generate a builder class

Add GenericKubernetesResourceBuilder to Kubernetes Model Core

---

.github/ISSUE_TEMPLATE/bug_report.yml

style: id field has same name causing issue in bug report

---

kubernetes-model-generator/generateModel.sh

chore: Add missing extensions to model generation scripts
These scripts are used by CI validation pipelines for models.

chore: Add missing extensions to model generation scripts

---

CHANGELOG.md
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java
kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/HasMetadataTest.java

feat: add owner reference support to HasMetadata

---

kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/base/BaseOperationTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/informers/cache/ReflectorTest.java

Replace JUnit4 Assertions with Junit5 Jupiter Assertions

---

CHANGELOG.md
kubernetes-client/pom.xml
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Base64.java
kubernetes-examples/pom.xml
pom.xml

Fix #3672
Alternative to #3673
Using [Robert Harder's Base64 class](http://iharder.sourceforge.net/current/java/base64/).
Extracted from [Keycloak's repo](https://github.com/keycloak/keycloak/blob/422ae0b3dbc1fb99f939860c78f5631fe2d83805/common/src/main/java/org/keycloak/common/util/Base64.java) since it was already trimmed off of unneeded methods.
/cc @geoand 

deps: Remove commons-codec dependency (trouble with GraalVM)

---

doc/CHEATSHEET.md

Fix #3655
Add the usage document content of clusterrole
#3655

Doc:Update CHEATSHEET.md by ClusterRole usage

---

crd-generator/api/src/test/java/io/fabric8/crd/example/annotated/AnnotatedSpec.java
crd-generator/api/src/test/java/io/fabric8/crd/generator/v1/JsonSchemaTest.java

Follow up for the requested test:
https://github.com/fabric8io/kubernetes-client/pull/3687#issuecomment-1000662416
cc. @manusa 

Add a test for JsonIgnore on methods

---

kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationYamlTest.java

Closes #3653
Verification for `Security issue in kubernetes-client` #3653 fix

test: Verification for `Security issue in kubernetes-client` #3653 fix

---

crd-generator/api/src/test/java/io/fabric8/crd/example/person/AddressList.java
pom.xml

Bump `sundrio` to latest patch that fix #3716 
Included a minimal variation on a test to act as regression test.

[chore] Bump sundrio to latest patch

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java

Fix #3769 
It's completely out of my understanding how I can have a different type coming from `sundrio` there running outside this codebase.
Since I cannot reproduce locally you can use the repro: https://github.com/andreaTP/schemafrom-classref-repro to validate the fix, maybe @iocanel or @metacosm can shed a light on how to reproduce locally in the test-suite.

Fix for ClassCastException from SchemaFrom

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/PortForwardable.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocketTest.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PortForwardExample.java

Fix #3234 #3704 
Add additional `portForward(int port, InetAddress localInetAddress, int localPort)` method to PortForward Interface

Fix #3234: Allow specifying specific localhost while port-forwarding

---

extensions/camel-k/generator-v1/go.mod
extensions/camel-k/generator-v1/go.sum
extensions/camel-k/generator-v1alpha1/go.mod
extensions/camel-k/generator-v1alpha1/go.sum
extensions/camel-k/model-v1/src/main/resources/schema/camel-k-schema-v1.json

chore(camel k): Update Fabric8 CamelK Extension model to v1.8.0

---

CHANGELOG.md

Added missing changelog for camel-k-1.8.0

---

CHANGELOG.md
extensions/verticalpodautoscaler/generator-v1/cmd/generate/generate.go
extensions/verticalpodautoscaler/model-v1/src/main/resources/schema/verticalpodautoscaler-schema.json
extensions/verticalpodautoscaler/tests/src/test/java/io/fabric8/verticalpodautoscaler/test/crud/V1VerticalPodAutoscalerCrudTest.java

Failing test case for V1VerticalPodAutoscalerCrudTest

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUploadWebSocketListener.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/serialization/BeanPropertyWriterDelegate.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/PluralizeIT.java

chore: clean up smells after fixes

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java

This relates to issue #3509 - it broadens it to be for all of the out streams.  Do we want a separate issue / changelog / tests for this, or is this sufficient?

related to #3509 all outputs should be flushed

---

.github/workflows/e2e-tests.yml

Update K8s versions to the latest patch release.
Update Minikube to 1.25.1

Update E2E tests Kubernetes matrix

---

java-generator/cli/pom.xml

chore: attach generated java-gen cli as artifact
/cc @andreaTP 

chore: attach generated java-gen cli as artifact

---

kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/SecretExamples.java

add kubernetes-client example for secret
#3677

add kubernetes-client example for secret

---

java-generator/core/pom.xml
java-generator/it/pom.xml
java-generator/it/src/it/cert-manager/expected/AuthSpec.java
java-generator/it/src/it/cert-manager/invoker.properties
java-generator/it/src/it/cert-manager/pom.xml
java-generator/it/src/it/cert-manager/src/main/resources/cert-manager.crds.1.7.1.yaml
java-generator/it/src/it/cert-manager/verify.groovy
java-generator/it/src/it/settings.xml
java-generator/maven-plugin/pom.xml
java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java
java-generator/pom.xml
pom.xml

- Spiked a Maven Plugin to invoke the generator.
- Created an integration test infrastructure based on the plugin
- TODO: Test generated sources compared to our actual extensions (the end goal would be to be able to replace our current code generation with this --> Configuration options should be added for package, additionalProperties generation, etc.)
- TODO: Create a proper verification infrastructure
Other comments:
- Current implementation is slow. We can probably improve the performance by running the generation in multiple threads for each individual CRD.
- CRD Generator only admits passing in a File. We could support reading complete directories (makes a lot of sense for the Maven Plugin workflow)
/cc @andreaTP 

[java-gen] feat: Maven Plugin + Integration test infrastructure

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java

This is useful because in a lot of cases the YAML mapper
is only need at application startup when the client
is created, so there is no reason to keep the very heavy
(in terms of memory) mapper around indefinitely.

Allow applications to clear out YAML ObjectMapper

---

CHANGELOG.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java

Fix #1883
Fix #3832
This is a bit of a corner case, but I don't want to construct a client instance just for this check - it is done without a reference to the HttpClient.Factory, which is a problem if it's possible to pass one in from a higher level. 
What is proposed here is to just use an HttpsURLConnection - that also addresses #1883 because all it's checking for is a successful handshake.  This assumes that you'll of course still use the Config to setup your https related properties.
Another direction to take would be to have the HttpClient.Factory available here - such as setting it on the Config.
And the last option is to as much as possible not allow for the programmatic association of an HttpClient.Factory / HttpClient, so that all calls use what will be the service loader.
test, …

fix #3832 #1883 simplifying the isHttpsAvailable check

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java

Fix #3889 : remove piped stream for file download

---

.github/workflows/build.yml
.github/workflows/style-checks.yml

ci: Spotless checks run on dedicated pipeline (with License check)

ci: Spotless checks run on dedicated pipeline (with License check)

---

java-generator/cli/src/main/java/io/fabric8/java/generator/cli/GenerateJavaSources.java
java-generator/cli/src/main/java/io/fabric8/java/generator/cli/KubernetesClientVersionProvider.java
java-generator/core/src/main/java/io/fabric8/java/generator/CRGeneratorRunner.java
java-generator/core/src/main/java/io/fabric8/java/generator/Config.java
java-generator/core/src/main/java/io/fabric8/java/generator/WritableCRCompilationUnit.java
java-generator/core/src/main/java/io/fabric8/java/generator/exceptions/JavaGeneratorException.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/GeneratorResult.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JArray.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JArrayNameAndType.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnumNameAndType.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JMap.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JMapNameAndType.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObjectNameAndType.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitive.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitiveNameAndType.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JavaNameAndType.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JavaType.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/Keywords.java
java-generator/core/src/test/java/io/fabric8/java/generator/ApprovalTest.java
java-generator/core/src/test/java/io/fabric8/java/generator/CompilationTest.java
java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java
java-generator/core/src/test/java/io/fabric8/java/generator/PackageSettings.java
java-generator/core/src/test/java/io/fabric8/java/generator/StringSanitizationTest.java
java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java

Bulk formatting of the `java-generator` module.

[java-gen] Bulk format of the java-generator module

---

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObjectExtraAnnotations.java

Follow up from:
https://github.com/fabric8io/kubernetes-client/pull/3918#discussion_r818009082

[java-gen] Apply sundrio annotations to the CustomResource class

---

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java
java-generator/it/src/it/cert-manager/expected/Auth.expected

remove Redundant specification of type arguments

---

CHANGELOG.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Itemable.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/NonNamespaceOperation.java

A cleanup related to the resource changes.  Went ahead and added an interface and a changelog entry.

fix #3407: adding a changelog and an Itemable interface

---

.github/workflows/e2e-httpclient-tests.yml
.github/workflows/release-snapshots.yaml
kubernetes-itests/pom.xml

ci: Pipeline to run E2E tests for each httpclient implementation
Runs the tests based on the latest available SNAPSHOT builds.

ci: Pipeline to run E2E tests for each httpclient implementation

---

.github/workflows/build.yml
.github/workflows/e2e-httpclient-tests.yml
.github/workflows/e2e-tests.yml
.github/workflows/javadocs.yml
.github/workflows/release-snapshots.yaml
.github/workflows/release.yaml
.github/workflows/sonar.yml
.github/workflows/style-checks.yml
.github/workflows/windows-build.yml
.gitignore
.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd
pom.xml

chore: added Maven wrapper (predictable Maven version)

chore: added Maven wrapper (predictable Maven version)

---

pom.xml

chore: bump to sundrio 0.90.0

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/NonNamespaceOperation.java

fix: re-add missing interfaces

---

pom.xml

chore: bump sundrio to 0.90.3

---

java-generator/it/pom.xml
java-generator/it/src/it/enum-ser-deser/src/test/java/io/fabric8/it/certmanager/TestEnumSerialization.java
java-generator/it/src/it/extensions/invoker.properties
java-generator/it/src/it/extensions/pom.xml
java-generator/it/src/it/extensions/src/test/java/io/fabric8/it/extensions/TestExtensionsWireCompat.java
java-generator/it/src/it/extensions/src/test/java/io/fabric8/it/extensions/camelk/JavaGeneratedCamelK.java
java-generator/it/src/it/extensions/src/test/resources/camel-k.crds.1.8.1.yaml
java-generator/it/src/it/extensions/src/test/resources/camel-k/kustomization.yaml
java-generator/it/src/main/java/io/fabric8/java/generator/testing/KubernetesResourceDiff.java
java-generator/it/src/main/java/io/fabric8/java/generator/testing/extensions/camlek/ExtensionCamelK.java

Revamped this branch to follow up on the discussion we had here:
https://github.com/fabric8io/kubernetes-client/pull/3932
This should be ready for review 🙂  cc. @manusa 
E2E tests to compare the output of the "curated" extensions with the output of the code generated using the `java-gen` tool.
Sharing to discuss about a few interesting facts:
- @manusa this is a starting implementation of what we discussed, but those tests are slightly hard to write and slow to execute 😞 
- writing the code to use the java generated code is painful (e.g. slow, I do it in another project and copy-paste the result ...) as the IDE doesn't help in the Maven integration tests and we are relying on generated code + sundrio annotations, maybe @manusa knows some tricks that can be used in this case?
- now the …

[java-gen] Generate Builder pattern for CustomResource

---

.github/workflows/e2e-httpclient-tests.yml
.github/workflows/e2e-tests.yml
CONTRIBUTING.md
kubernetes-itests/src/test/java/io/fabric8/jupiter/KubernetesNamespacedTestExtension.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/JobIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/ResourceQuotaIT.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/RoleBindingIT.java

ci: OpenShift E2E test pipeline includes those for K8s
Based on https://github.com/fabric8io/kubernetes-client/pull/4054#discussion_r847418727
Kubernetes specific tests are still filtered of the Minikube pipeline. This is not strictly necessary but allows us to quickly check if tests were ignored during the execution. Since there are 60+ OpenShift specific tests, those ignores might hide some other ignored but required tests.

ci: OpenShift E2E test pipeline includes those tests specific to K8s

---

CHANGELOG.md
extensions/camel-k/client/src/main/java/io/fabric8/camelk/client/V1alpha1APIGroupClient.java
extensions/camel-k/client/src/main/java/io/fabric8/camelk/client/dsl/V1alpha1APIGroupDSL.java
extensions/camel-k/generator-v1alpha1/cmd/generate/generate.go
extensions/camel-k/generator-v1alpha1/go.mod
extensions/camel-k/model-v1alpha1/src/main/resources/schema/camel-k-schema-v1alpha1.json
extensions/camel-k/tests/pom.xml
extensions/camel-k/tests/src/test/java/io/fabric8/camelk/test/KameletBindingTest.java
extensions/camel-k/tests/src/test/resources/test-kameletbinding.yml

Fix #3854
+ KameletBinding resource was available in CamelK v1alpha1 model but it
wasn't exposed in `v1alpha1()` DSL of CamelKClient. Adding missing DSL
method to CamelKClient interface.
+ Added manual typemapping for [EndpointProperties](https://github.com/apache/camel-k/blob/main/pkg/apis/camel/v1alpha1/kamelet_binding_types.go#L90) to a string map

feat (camel-k) : Add Missing DSL method for manipulating KameletBindings (#3854)

---

CHANGELOG.md
extensions/camel-k/generator-v1alpha1/cmd/generate/generate.go
extensions/camel-k/model-v1alpha1/pom.xml
extensions/camel-k/model-v1alpha1/src/main/resources/schema/camel-k-schema-v1alpha1.json
extensions/camel-k/model-v1alpha1/src/test/java/io/fabric8/camelk/KameletModelTest.java
extensions/camel-k/model-v1alpha1/src/test/resources/valid-kamelet-x-descriptors.json

Fix #3852
+ Kamelet resource seems to be using `JSONSchemaProps`. However, this `JSONSchemaProps` is not coming from Apiextensions. Camel repository seems to have its own version of JSONSchemaProps. It contains some additional
fields like `x-descriptors`. We've currently added a manual type mapping of JSONSchemaProps to `io.fabric8.kubernetes.api.model.apiextensions.v1.JSONSchemaProps`. This works for most cases but doesn't work when some camel specific fields are used in Kamelet (like in the case of #3852, #3182).
+ While writing test using user provided YAML, I also faced an issue with `JSON` type in camelk model (it's copied along with other JSON* structs from apiextensions). Added a manual type mapping  for `v1alpha1.JSON` like we have in …

fix (camel-k) : Deserializing Kamelet fails with UnrecognizedPropertyException (#3852)

---

.github/workflows/e2e-httpclient-tests.yml
.github/workflows/e2e-tests.yml
junit/kubernetes-junit-jupiter/src/main/java/io/fabric8/junit/jupiter/KubernetesNamespacedTestExtension.java

Run tests on K8s v1.24

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedMultiPropertyPathDetector.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/visitor/AnnotatedPropertyPathDetector.java
crd-generator/api/src/test/java/io/fabric8/crd/example/basic/BasicSpec.java

Resolves #4092 
Unfortunately, this StackOverflow is caused by some "pre-processing", here I'm specifically skipping the path for the issue reported, I'm open to listening for a more generic/better approach. cc. @metacosm 

Avoid StackOverflow Exception skipping JsonIgnored properties

---

CHANGELOG.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/PodResource.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/PortForwardable.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ServiceResource.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java

fix #4149: several cleanups related to port forwarding

fix #4149: several cleanups related to port forwarding

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java

in this PR (#3321), createDockerRegistrySecret() makes a secret named "harbor-secret"
I think the name of secret should be "docker-registry-secret"
++ 
now createDockerRegistrySecret() makes a secret named "container-image-registry-secret"
also we can create docker-registry-secret with secretName param

fix : change the docker-registry secret's name to be configurable.

---

README.md

Fix Eleastic to be Elastic in README.md

docs: Fix Eleastic to be Elastic in README.md

---

README.md

Fix #4196 .
Change ENV `kubernetes_websocket_ping_interval` to uppercase in README.md

chore #4196: change ENV kubernetes_websocket_ping_interval to uppercase in README.md

---

pom.xml

chore: bump sundrio to 0.92.0

---

pom.xml

chore: bump to sundrio 0.92.1

---

doc/FAQ.md

 docs: Added FAQ for BouncyCastle optional dependency (#3949)

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java

Backport fix 4250: ensuring nullable polymorphic unwrapped works

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationAdditionalPropertiesTest.java

test: Verify Serialization.clone works with UnmatchedFieldTypeModule
Relates to #4292 #4109

test: Verify Serialization.clone works with UnmatchedFieldTypeModule

---

extensions/istio/generator-v1alpha3/cmd/generate/generate.go
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/ExecHealthCheckConfig.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/HTTPHeader.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/HTTPHealthCheckConfig.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/IsReadinessProbeHealthCheckMethod.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/ReadinessProbe.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/ReadinessProbeExec.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/ReadinessProbeHttpGet.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/ReadinessProbeTcpSocket.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/TCPHealthCheckConfig.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/WorkloadGroup.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/WorkloadGroupList.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/WorkloadGroupObjectMeta.java
extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/WorkloadGroupSpec.java
extensions/istio/model-v1alpha3/src/main/resources/schema/istio-schema.json

Fix #4287: add WorkloadGroup for istio v1alpha3 generator

---

CHANGELOG.md
extensions/camel-k/mock/pom.xml
extensions/certmanager/mock/pom.xml
extensions/chaosmesh/mock/pom.xml
extensions/istio/mock/pom.xml
extensions/knative/mock/pom.xml
extensions/open-cluster-management/mock/pom.xml
extensions/service-catalog/mock/pom.xml
extensions/tekton/mock/pom.xml
extensions/verticalpodautoscaler/mock/pom.xml
extensions/volcano/mock/pom.xml
extensions/volumesnapshot/mock/pom.xml
junit/kubernetes-junit-jupiter/pom.xml
junit/kubernetes-server-mock/pom.xml
junit/openshift-server-mock/pom.xml
pom.xml

fix: Configure dependency scope for junit dependencies at parent

fix: Configure dependency scope for junit dependencies at parent

---

platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/KubernetesDeserializerTest.java
platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/TestBase.java

test: refactor karaf deserialization tests to ensure GenericKuberentesResource errors

test: refactor karaf deserialization tests to ensure GenericKuberentesResource errors

---

CHANGELOG.md
pom.xml

* Fix #4383: bump snakeyaml from 1.30 to 1.31

chore(deps): bump snakeyaml from 1.30 to 1.31

---

CHANGELOG.md

Follow up for #4382 to add changelog and note about breaking change.

chore : Update changelog regarding tekton model upgrade and trigger changes (#4243)

---

CHANGELOG.md
kubernetes-model-generator/openshift-model-monitoring/pom.xml
kubernetes-model-generator/openshift-model-monitoring/src/generated/java/io/fabric8/openshift/api/model/monitoring/v1alpha1/PagerDutyConfig.java

Fix #4359 
Remove manual model class PagerDutyConfig from OpenShift Model
Monitoring. Rest of the classes should be removed in https://github.com/fabric8io/kubernetes-client/pull/4361

fix (kubernetes-model-generator/openshift-model-monitoring) : Remove manual model classes with fields name class (#4359)

---

pom.xml

Thanks to @iocanel that have fixed #4357 🙂  with this release!

[chore] Bump sundrio to 0.93.0

---

kubernetes-model-generator/pom.xml

Fix #4380
as it breaks Reproducible Builds: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/fabric8/kubernetes-client/README.md
when activating Reproducible Builds mode, this type of value has to be avoided

drop Java-Version prop in MANIFEST.MF

---

CHANGELOG.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptorTest.java

Fix #4401 
This pull-request is related to refactoring to 'TokenRefreshInterceptor'. :) 
* Code improvements points

refactor: refactoring `TokenRefreshInterceptor` for code readability (#4401)

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java

fix: issues/4400 add support for cronJob batch/v1

---

kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java

Split tests implemented in #4417, and ensure exception assertions are verified

refactor: test: terminal tests split

---

CHANGELOG.md
pom.xml

Back-port of #4387 and #4415
Relates to #4383 
chore(deps): bump snakeyaml from 1.28 to 1.32

chore(deps): bump snakeyaml from 1.28 to 1.32

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
kubernetes-client/src/test/resources/test-kubeconfig-exec-null-args
kubernetes-client/src/test/resources/test-kubeconfig-exec-win-null-args
kubernetes-client/src/test/resources/token-generator-win.bat

Backport of #4381

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptorTest.java
kubernetes-client/src/test/resources/token-refresh-interceptor/kubeconfig
kubernetes-client/src/test/resources/token-refresh-interceptor/kubeconfig.new

backport: #4264 - Refresh token every minute

backport: #4264 - Refresh token every minute

---

CHANGELOG.md
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/DryRunTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java

Backport of #4263

---

kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java

Very narrow fix of a timing issue with the PodCrudTest - https://github.com/fabric8io/kubernetes-client/actions/runs/3158671057/jobs/5140968779#step:4:31568
The onOpenAction callback to deliver the initial add events happens asynchronously from the onOpen call on the client side, so  there's no guarantee that after the Watch call we've already processed that.  If the delete/create happens before the server side gets to the onOpenAction, then there will just be a single add event seen by the Watcher.  This is how the logic always functioned (prior to the async logic), so this must be a pretty narrow timing issue.

fix to address timing issue

---

doc/KubernetesOperatorsInJavaWrittenUsingFabric8.md

Adding "Locust k8s operator" to the list of example operators that where written with the help of `fabric8io/kubernetes-client`

Add Locust k8s operator to the list of operators

---

README.md
doc/FAQ.md

Closes #4503 adding more dependency related information into the faq.

Fix #4503: updating dependency and readme

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/SerializationTest.java

Fixes https://github.com/fabric8io/kubernetes-client/issues/4484

Fixed failing unit test testSerializeYamlWithAlias.

---

kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java

I have updated the job creation code according to the version 6 and above.
Related to https://stackoverflow.com/questions/74148689

JobExample doesn't use deprecated methods

---

httpclient-jdk/src/main/java/io/fabric8/kubernetes/client/jdkhttp/JdkHttpClientImpl.java
httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java
httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyHttpClient.java
httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyWebSocketBuilder.java
httpclient-jetty/src/test/java/io/fabric8/kubernetes/client/jetty/JettyWebSocketBuilderTest.java
httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientBuilderImpl.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/Interceptor.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractAsyncBodyTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractInterceptorTest.java

test: additional HTTP client tests

---

crd-generator/test/pom.xml
crd-generator/test/src/test/java/io/fabric8/crd/generator/keycloak/KeycloakRealm.java
crd-generator/test/src/test/java/io/fabric8/crd/generator/keycloak/KeycloakRealmCRDTest.java

And generate crd from it to verify that it can be done without StackOverwlows and other errors. No other verifications are performed.

Chore: Add Keycloak model as a dependency to crd-generator tests

---

java-generator/core/src/main/java/io/fabric8/java/generator/CRGeneratorRunner.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java
java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java
java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testAkkaMicroservicesCrd.approved.txt
java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testCrontabCrd.approved.txt
java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testCrontabExtraAnnotationsCrd.approved.txt
java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testJokeCrd.approved.txt
java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testKeycloakCrd.approved.txt
java-generator/it/src/it/crd-names/invoker.properties
java-generator/it/src/it/crd-names/pom.xml
java-generator/it/src/it/crd-names/src/test/java/io/fabric8/it/names/TestCRDNames.java
java-generator/it/src/it/crd-names/src/test/resources/artemis-crd.yml

[java-generator] Fix incosistent CRD names

---

httpclient-jetty/src/main/java/io/fabric8/kubernetes/client/jetty/JettyAsyncResponseListener.java

Simplification of the Jetty Async Listener blocking mechanism.
Content consumption is blocked before Jetty actually processes the response.
Instead of blocking the content processing, we block the onContent callback. See related [Javadoc](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/client/api/Response.DemandedContentListener.html#onBeforeContent(org.eclipse.jetty.client.api.Response,java.util.function.LongConsumer)):
> Callback method invoked before response content events. The demand object should be used to demand content, otherwise the demand remains at zero (no demand) and `onContent(Response, LongConsumer, ByteBuffer, Callback)` will not be invoked even if content has been received and parsed.

fix(jetty): simple async response listener blocking mechanism

---

doc/CHEATSHEET.md

Job creation code has been updated.

Updated CHEATSHEET

---

.github/CODEOWNERS

With the purpose of automating the reviewer request for PRs (as per repository traditions PRs should only be merged if they have at least 2 approvals), I bootstrapped a [`.github/CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file to automate the task.
I've included @andreaTP, @metacosm, @oscerd, @rohanKanojia, @shawkins, @sunix with the entries I think might apply given how we've worked until now. Please feel free to change/suggest additional people, or to remove or add yourself from the code locations you'd like to review or not to review (if necessary we can make it more granular) :)

chore: bootstrapped CODEOWNERS file

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractSimultaneousConnectionsTest.java

test: deflake http1 simultaneous connection test

test: deflake http1 simultaneous connection test

---

httpclient-vertx/pom.xml
httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/InputStreamReadStream.java
httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientFactory.java
httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpRequest.java
httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/HttpBodyStreamTest.java
httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/SslTest.java
httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientNewWebSocketBuilderTest.java
httpclient-vertx/src/test/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientPostTest.java
pom.xml

Implements some missing features
- proxy authorization
- InputStream async body
- WebSocket handshake failure
- SSLContext handling
- upgrade to Vert.x 4.3.7

Vertx client

---

CHANGELOG.md
extensions/certmanager/generator-v1/cmd/generate/generate.go
extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/acme/v1/Challenge.java
extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/acme/v1/ChallengeList.java
extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/acme/v1/Order.java
extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/acme/v1/OrderList.java
extensions/certmanager/model-v1/src/main/resources/schema/certmanager-schema.json
extensions/certmanager/model-v1/src/test/java/io/fabric8/certmanager/test/model/V1ChallengeTest.java
extensions/certmanager/model-v1/src/test/java/io/fabric8/certmanager/test/model/V1OrderTest.java

fix #4668: use acme.cert-manager.io ApiGroup for Orders and Challenges

---

doc/java-generation-from-CRD.md

[java-generator] Update documentation

---

java-generator/core/src/main/java/io/fabric8/java/generator/URLJavaGenerator.java

The target download folder is still slightly off 😓 
This should fix it, cc. @manusa 

[java-generator] Fix the download directory creation steps

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java
kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java
kubernetes-itests/src/test/resources/pod-it.yml

Closes: #4839 
test: PodIT misc refinements

test: PodIT misc refinements

---

.github/workflows/e2e-httpclient-tests.yml
.github/workflows/e2e-tests.yml

Related to https://github.com/fabric8io/kubernetes-client/pull/4842#issuecomment-1422879472

ci: isolate Kubernetes 1.26 E2E test

---

CHANGELOG.md
junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java
junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PatchHandler.java
junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PostHandler.java
junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PutHandler.java
junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/crud/KubernetesCrudDispatcherFinalizerTest.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java

Fix #3805
Hello there :wave:  I tried my hand on fixing this issue: https://github.com/fabric8io/kubernetes-client/issues/3805
I'm not sure why the `io.fabric8.kubernetes.client.server.mock.MasterProtocolTest::testWithSSL` fails, but I think that I didn't introduce this error.

Fix #3805: Implement support for finalizers and `deletionTimestamp`s

---

CHANGELOG.md
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java
java-generator/core/src/test/java/io/fabric8/java/generator/CompilationTest.java
java-generator/core/src/test/resources/dummy-crd.yml
java-generator/it/src/it/escape-characters/invoker.properties
java-generator/it/src/it/escape-characters/pom.xml
java-generator/it/src/it/escape-characters/src/test/java/io/fabric8/it/dummy/TestEscapeCharacters.java
java-generator/it/src/it/escape-characters/src/test/resources/dummy-crd.yml
java-generator/it/src/it/escape-characters/src/test/resources/sample.yaml

[java-generator] handle special characters in field names

---

kubernetes-examples/pom.xml
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java

Fix #4904 
In order for Slf4j to work, it needs to be in compile scope. Otherwise we're getting failure in resolving StaticLoggerBinder errors while running samples in kubernetes-examples

fix (kubernetes-examples) : Update Slf4j Simple dependency scope to runtime (#4904)

---

java-generator/maven-plugin/pom.xml

Fix for those warnings:
Noticed on another project, this will probably also sort out this one: https://github.com/fabric8io/kubernetes-client/pull/4835

[java-generator] Mark Maven dependencies as provided in the Maven plugin

---

CHANGELOG.md
doc/java-generation-from-CRD.md
java-generator/cli/src/main/java/io/fabric8/java/generator/cli/GenerateJavaSources.java
java-generator/core/src/main/java/io/fabric8/java/generator/Config.java
java-generator/maven-plugin/src/main/java/io/fabric8/java/generator/maven/plugin/JavaGeneratorMojo.java

The initial phase to roll #4875 plan

[java-generator] Deprecate configuration options identified for removal

---

crd-generator/api/pom.xml

fix: CRD generator doesn't need full kubernetes-client access

---

CHANGELOG.md
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java

Related to #4993
+ Add `@JsonIgnore` on Quantity additionalProperties parameter
+ Clean up QuantityTest to replace with parameterized tests wherever
applicable
+ Add test to verify additionalProperties field is ignored during
serialiation and deserialization

fix (kubernetes-model-core) : Add `@JsonIgnore` on Quantity additionalProperties parameter (#4993)

---

README.md

Apache Kyuubi uses this library to access K8s cluster to operate the Application deployed in K8s.
https://github.com/apache/kyuubi/blob/master/kyuubi-server/src/main/scala/org/apache/kyuubi/engine/KubernetesApplicationOperation.scala

doc: Add Apache Kyuubi to user list

---

doc/CHEATSHEET.md

Add the missed API example for deleting clusterRoleBindings

Add the missed API example

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/CreateOrReplaceable.java

typo: correct the typo use in Javadoc

---

kubernetes-model-generator/pom.xml

chore: remove invalid Maven profiles

chore: remove invalid Maven profiles

---

doc/CHEATSHEET.md

`SerializationUtils` was removed after kubernetes-client 6.x.x, and add code snippet for the replacement of using `PatchUtils`.

append Serializing to yaml via PatchUtils

---

CHANGELOG.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/informers/cache/Cache.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/ReflectUtils.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/ReplaceValueStream.java

@manusa here's the changelog missing from the larger pr with a couple of additional deprecations.

fix #4662: adding a changelog and additional deprecations

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java

Fix #5184 
Correcting the leader election debug messages

fix #5184: correcting leader election debug

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesSerialization.java
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java

The changes mentioned in https://github.com/fabric8io/kubernetes-client/pull/5200#issuecomment-1573668627

follow up to Marc's change - removing the legacy confusion

---

kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java
kubernetes-itests/src/test/resources/deploymentconfig-it.yml

test: DeploymentConfigIT has dedicated resource for scale test

test: DeploymentConfigIT has dedicated resource for scale test

---

kubernetes-model-generator/kubernetes-model-admissionregistration/cmd/generate/generate.go
kubernetes-model-generator/kubernetes-model-admissionregistration/src/generated/java/io/fabric8/kubernetes/api/model/KubeSchema.java
kubernetes-model-generator/kubernetes-model-admissionregistration/src/generated/java/io/fabric8/kubernetes/api/model/ValidationSchema.java
kubernetes-model-generator/kubernetes-model-admissionregistration/src/generated/java/io/fabric8/kubernetes/api/model/authentication/BoundObjectReference.java
kubernetes-model-generator/kubernetes-model-admissionregistration/src/generated/java/io/fabric8/kubernetes/api/model/authentication/TokenRequest.java
kubernetes-model-generator/kubernetes-model-admissionregistration/src/generated/java/io/fabric8/kubernetes/api/model/authentication/TokenRequestSpec.java
kubernetes-model-generator/kubernetes-model-admissionregistration/src/generated/java/io/fabric8/kubernetes/api/model/authentication/TokenRequestStatus.java
kubernetes-model-generator/kubernetes-model-admissionregistration/src/main/resources/schema/kube-schema.json
kubernetes-model-generator/kubernetes-model-admissionregistration/src/main/resources/schema/validation-schema.json
kubernetes-model-generator/kubernetes-model-admissionregistration/src/test/java/io/fabric8/kubernetes/api/model/authentication/TokenRequestTest.java
kubernetes-model-generator/kubernetes-model-admissionregistration/src/test/resources/valid-tokenrequest.json

Related to #5133
Add a model for type [TokenRequest](https://github.com/kubernetes/api/blob/master/authentication/v1/types.go#L136) to `kubernetes-model-admissionregistration` in `io.fabric8.kubernetes.api.model.authentication` package.
Note: This PR only adds the model type, I'll add DSL to kubernetes-client in a follow up PR.

feat (kubernetes-model-generator) : Add TokenRequest to authentication v1 model (#5133)

---

kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java

test: PodIT don't rely on PodResource.file.read to verify the contents of the upload test

PodIT don't rely on PodResource.file.read to verify the contents of the upload test

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/ExtensionsAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/ExtensionsAPIGroupClient.java

doc: deprecation notices for extensions/v1beta1

doc: deprecation notices for extensions/v1beta1

---

.gitignore
java-generator/it/pom.xml
java-generator/pom.xml

Fix #5299
+ Not sure why it's getting used. Even if I remove this all java generator
tests seem to pass
+ Everytime we run java generator gradle integration test, I see an
untracked file `.gradle` in git index. Add an entry to git ignore file for that

chore (java-generator) : Remove `com.google.guava:guava` dependency from pom (#5299)

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/V1Alpha1NetworkAPIGroupDSL.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/AuthenticationAPIGroupDSL.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/CertificatesAPIGroupDSL.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/NetworkAPIGroupDSL.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/V1Alpha1CertificatesAPIGroupDSL.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/V1Beta1AuthenticationAPIGroupDSL.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/KubernetesClientImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/NetworkAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/V1Alpha1CertificatesAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/V1Alpha1NetworkAPIGroupClient.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/V1Beta1AuthenticationAPIGroupClient.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ClusterCIDRTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ClusterTrustBundleTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/IPAddressTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/StorageVersionTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1Beta1SelfSubjectReviewTest.java

Related to #5056 
Should be merged after #5270
Add DSL support and mock tests for the following Kubernetes resources to KubernetesClient:
- `networking.k8s.io/v1alpha1` IPAddress
- `networking.k8s.io/v1alpha1` ClusterCIDR
- `certificates.k8s.io/v1alpha1` ClusterTrustBundle
- `authentication.k8s.io/v1beta1` SelfSubjectReview

feat (kubernetes-client-api) : Add DSL support for new resources in Kubernetes v1.27.3

---

README.md

doc: remove misleading compatibility matrix
Relates to:
- #5132 
- #4790
- #3185

doc: remove misleading compatibility matrix

---

kubernetes-client/src/test/java/io/fabric8/kubernetes/client/behavior/UploadTest.java

test: behavioral test for InputStream uploads

test: behavioral test for InputStream uploads

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesSerialization.java

It looks like there may not be much needed to close the issue.
Closes #5274

small change to allow for more type refinement

---

CHANGELOG.md
java-generator/gradle-plugin/pom.xml
java-generator/it/pom.xml
java-generator/it/src/main/java-templates/io/fabric8/java/generator/testing/GradleProperties.java
java-generator/it/src/test/java/io/fabric8/java/generator/gradle/plugin/SimpleIT.java
java-generator/pom.xml
kubernetes-model-generator/pom.xml
pom.xml

feat: Gradle base API based on v8.2.1

feat: gradle base API based on v8.2.1

---

junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/ExpectationsTest.java

test: scenarios to verify post expectations

---

doc/MIGRATION-v5.md
doc/MIGRATION-v6.md

Fix #5389 
/cc @metacosm @rolfedh

doc: invite users to report issues with a specific document

---

.github/workflows/e2e-tests.yml

ci: bump actions-setup-minikube to v2.8.0
https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster?version=v2.8.0

ci: bump actions-setup-minikube to v2.8.0

---

.github/workflows/e2e-tests.yml

ci: bump actions-setup-minikube to v2.9.0 (e2e)

ci: bump actions-setup-minikube to v2.9.0 (e2e)

---

.github/workflows/e2e-chaos-tests.yml
.github/workflows/e2e-httpclient-tests.yml

ci: bump actions-setup-minikube to v2.9.0

ci: bump actions-setup-minikube to v2.9.0

---

CHANGELOG.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtilTest.java

refinements and clarifications to the validation of names

---

extensions/volcano/examples/src/main/java/io/fabric8/volcano/examples/Utils.java
extensions/volcano/tests/src/test/java/io/fabric8/volcano/test/crud/VolcanoTest.java

Required by https://github.com/sundrio/sundrio/pull/416 downstream checks so that the unnecessary validation related constructors can be removed.
Relates to #5409

removing usage of validation parameter

---

.github/workflows/e2e-tests.yml

Relates to #5444 
ci: free up space for OpenShift execution

ci: free up space for OpenShift execution

---

kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ControlPlaneMachineSetTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ImageDigestMirrorSetTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ImageTagMirrorSetTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/Metal3RemediationTemplateTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/Metal3RemediationTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OLMConfigTest.java
kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ProjectHelmChartRepositoryTest.java
openshift-client-api/src/main/java/io/fabric8/openshift/client/NamespacedOpenShiftClientAdapter.java
openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
openshift-client-api/src/main/java/io/fabric8/openshift/client/dsl/OpenShiftConfigAPIGroupDSL.java
openshift-client-api/src/main/java/io/fabric8/openshift/client/dsl/OpenShiftMachineAPIGroupDSL.java
openshift-client-api/src/main/java/io/fabric8/openshift/client/dsl/OpenShiftOperatorHubAPIGroupDSL.java
openshift-client/src/main/java/io/fabric8/openshift/client/impl/OpenShiftClientImpl.java
openshift-client/src/main/java/io/fabric8/openshift/client/impl/OpenShiftConfigAPIGroupClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/impl/OpenShiftMachineAPIGroupClient.java
openshift-client/src/main/java/io/fabric8/openshift/client/impl/OpenShiftOperatorHubAPIGroupClient.java

Add DSL support for the following endpoints:
- `openShiftClient.metal3RemediationTemplates()`
- `openShiftClient.metal3Remediations()`
- `openShiftClient.projectHelmChartRepositories()`
- `openShiftClient.operatorHub().olmConfigs()`
- `openShiftClient.config().imageTagMirrorSets()`
- `openShiftClient.config().imageDigestMirrorSets()`
- `openShiftClient.machine().controlPlaneMachineSets()`

feat (openshift-client-api) : Add DSL for new OpenShift 4.13.12 resources to OpenShiftClient (#5286)

---

kubernetes-model-generator/kubernetes-model-core/pom.xml

fix: should not export the builder package

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/TypeInferenceTest.java

Relates to #5522 
Should fail unless disabled

Type inference tests

---

pom.xml

deps: bump com.marcnuri.plugins:gradle-api-maven-plugin to v0.0.5

deps: bump com.marcnuri.plugins:gradle-api-maven-plugin to v0.0.5

---

CHANGELOG.md
pom.xml

Add lombok and sundrio dependencies to the generated bom

---

CHANGELOG.md
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java
java-generator/it/src/it/default-values-instantiation/src/test/java/io/fabric8/it/certmanager/TestDefaultValues.java
java-generator/it/src/it/default-values-instantiation/src/test/resources/example.yaml

[java-generator] Correctly handle defaults for IntOrString types

---

doc/FAQ.md

Fix a small typo on documentation of FAQ

docs: fix small typo

---

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerTest.groovy

test(mockwebserver): fix concurrency issues with DefaultMockServerTest

test(mockwebserver): fix concurrency isues with DefaultMockServerTest

---

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerTest.groovy

test:fix: vert.x instantiation on setup only

test:fix: vert.x instantiation on setup only

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/UploadProcessor.java

refactor: misc fixes for the PodUpload class
Related to https://github.com/quarkusio/quarkus/issues/38098

refactor: misc fixes for the PodUpload class

---

.github/workflows/sonar.yml
httpclient-vertx/pom.xml

ci: sonar uses Java 17

---

CHANGELOG.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientBuilder.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/KubernetesClientBuilderTest.java
kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java
kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/QuantityTest.java

Put these in the same pr as separate commits because they are quite small. On the quantity methods I went for immutabilty, but we can just as easily make them modify the current object like go does.

Minor enhancements for additional client builder and quantity methods

---

crd-generator/test/pom.xml
httpclient-jdk/pom.xml
httpclient-jetty/pom.xml
httpclient-okhttp/pom.xml
httpclient-tests/pom.xml
httpclient-vertx/pom.xml
kubernetes-examples/pom.xml
kubernetes-tests/pom.xml
pom.xml

chore: exec maven plugin defined at main pom.xml

chore: exec maven plugin defined at main pom.xml

---

CHANGELOG.md
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java
java-generator/core/src/test/java/io/fabric8/java/generator/CompilationTest.java
java-generator/core/src/test/resources/colliding-enums-crd.yml
java-generator/it/src/it/ser-deser/src/test/java/io/fabric8/it/certmanager/TestSerialization.java
java-generator/it/src/it/ser-deser/src/test/resources/cert-manager.crds.1.7.1.yaml
java-generator/it/src/it/ser-deser/src/test/resources/sample1.yaml

[java-gen] Handle multiple colliding enums

---

.github/workflows/e2e-httpclient-tests.yml
.github/workflows/e2e-tests.yml
kubernetes-itests/src/test/java/io/fabric8/openshift/AdaptIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/BuildConfigIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/BuildConfigWatchIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamTagIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/K8sAuthorizationOnOpenShiftIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/OpenShiftAuthorizationIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ProjectIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ProjectRequestIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/RouteIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/SecurityContextConstraintsIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/SelfSubjectAccessReviewIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ServiceToURLIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/SubjectAccessReviewIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/TemplateIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/UserImpersonationIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/VersionIT.java
kubernetes-itests/src/test/resources/imagestreamtag-it.yml

ci: initial fixes to run OpenShift specific pipelines
Relates to #5545

ci: initial fixes to run OpenShift specific pipelines

---

.github/workflows/e2e-osci-tests.yml
kubernetes-itests/src/test/java/io/fabric8/openshift/AdaptIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/BuildConfigIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/BuildConfigWatchIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/BuildIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/DeploymentConfigIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/ImageStreamTagIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/K8sAuthorizationOnOpenShiftIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/OpenShiftAuthorizationIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/RouteIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/SelfSubjectAccessReviewIT.java
kubernetes-itests/src/test/java/io/fabric8/openshift/VersionIT.java
kubernetes-itests/src/test/resources/buildconfig-it.yml
kubernetes-itests/src/test/resources/deploymentconfig-it.yml
kubernetes-itests/src/test/resources/imagestream-it.yml
kubernetes-itests/src/test/resources/route-it.yml
kubernetes-itests/src/test/resources/template-it.yml

Relates to https://github.com/fabric8io/kubernetes-client/issues/5545

ci: OpenShift 4 pipeline running on OSPO OSCI

---

.github/workflows/e2e-chaos-tests.yml
.github/workflows/e2e-httpclient-tests.yml
.github/workflows/e2e-osci-tests.yml
kubernetes-itests/pom.xml

ci: enable snapshots on E2E specific tests

---

.github/workflows/release-snapshots.yaml
.github/workflows/release.yaml

ci:fix: kube-api-test module released with Java 11

---

kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/jackson/JsonUnwrappedDeserializer.java
kubernetes-model-generator/kubernetes-model-common/src/test/java/io/fabric8/kubernetes/model/jackson/JsonUnwrappedDeserializerTest.java

feat: JsonUnwrappedDeserializer supports multiple polymorphic unwrapped fields
Relates to #5182

feat: JsonUnwrappedDeserializer supports multiple polymorphic unwrapped fields

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClientBuilder.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClientFactory.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java

test: initial refactor of OpenIDConnectionUtils tests

test: initial refactor of OpenIDConnectionUtils tests

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClient.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClientBuilder.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsBehaviorTest.java

test: complete behavioral test suite for OpenIDConnectionUtils

test: complete behavioral test suite for OpenIDConnectionUtils

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClient.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsBehaviorTest.java

test(openid-connection): ensure token refresh request contains required attributes

test(openid-connection): ensure token refresh request contains required attributes

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsBehaviorTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java
openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java

Refactor OpenID Connection Utils
- Decouple internal methods
- Provide some level of isolation from OpenShiftInterceptor
- Add more test cases

Refactor OpenID Connection Utils

---

crd-generator/pom.xml
crd-generator/test/pom.xml
crd-generator/test/src/test/java/io/fabric8/crd/generator/types/TypeMappings.java
crd-generator/test/src/test/java/io/fabric8/crd/generator/types/TypeMappingsSpec.java
crd-generator/test/src/test/java/io/fabric8/crd/generator/types/TypeMappingsTest.java

test(crd-generator): ensure type mappings Java to OpenAPIV3Schema
Prerequisite for #5877
/cc @shawkins @andreaTP 

test(crd-generator): ensure type mappings Java to OpenAPIV3Schema

---

CHANGELOG.md

chore: fix changelog entry for #5878

---

CHANGELOG.md
crd-generator/test/src/test/java/io/fabric8/crd/generator/types/TypeMappingsTest.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesSerialization.java

fix: updating the kubernetesserializer handling of time types

---

.github/workflows/gobuild.yml
Makefile

ci: run Kubernetes Model Generator Check in macos
This should decrease the pipeline's execution time

ci: run Kubernetes Model Generator Check in macos

---

.github/workflows/sonar.yml
Makefile

ci: sonar pipeline uses make

---

crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/AbstractJsonSchema.java
crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/v1/JsonSchemaTest.java

closes: #5997
No changelog entry is needed because there hasn't been a release yet.

fix: remove the usage of JsonFormat pattern

---

kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java

Trivial PR to fix a typo on an error message.

Fixed typo on error message

---

.github/CODEOWNERS

config: fix CODEOWNERS file

---

openshift-client/src/test/java/io/fabric8/openshift/client/dsl/internal/core/ExpressionValueGeneratorTest.java

test:fix: use JUnit Jupiter import

---

kubernetes-model-generator/openapi/generator/main.go

fix: add support for MicroTime in openapi generator

fix: add support for MicroTime in openapi generator

---

kubernetes-model-generator/openapi/generator/main.go

fix: add support for request options in openapi generator

---

kubernetes-model-generator/openapi/generator/main.go

fix: add temp support for TypeMeta in openapi generator

---

kubernetes-model-generator/openapi/generator/README.md
kubernetes-model-generator/openapi/generator/main.go

fix: add support for AdmissionRequest in openapi generator

---

kubernetes-model-generator/openapi/generator/main.go

fix: add support for JSONSchemaProps in openapi generator

---

kubernetes-model-generator/openapi/generator/README.md

feat: initial go-openapi generator is complete

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

chore: Update Maven Wrapper to 3.2.2

---

.github/workflows/generate-model.yml
Makefile

ci: OpenAPI model generated files checked in pipeline

---

kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/GeneratorSettings.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ModelGenerator.java

fix(openapi): misc fixes to OpenAPI generator

---

kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/GeneratorSettings.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/GeneratorUtils.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ModelGenerator.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/TemplateContext.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/InlineModelResolver.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java
kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/SchemaUtilsTest.java

refactor: reorganized schema utils

---

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerWebSocketTest.groovy

test: improve reliability of mockwebserver websocket test

---

java-generator/it/src/it/datetime-fmt/src/test/java/io/fabric8/it/datetime/TestDateTimeSerDeser.java
java-generator/it/src/it/default-values-instantiation/src/test/java/io/fabric8/it/certmanager/TestDefaultValues.java
java-generator/it/src/it/escape-characters/src/test/java/io/fabric8/it/dummy/TestEscapeCharacters.java
java-generator/it/src/it/preserve-unknown-objects-through-config/src/test/java/io/fabric8/it/certmanager/TestPreserveUnkonwnUsabilityFromConfig.java
java-generator/it/src/it/preserve-unknown-objects/src/test/java/io/fabric8/it/certmanager/TestPreserveUnkonwnUsability.java
java-generator/it/src/it/preserve-unknown-serdeser/src/test/java/io/fabric8/it/certmanager/TestPreserveUnkonwnSerDeser.java
java-generator/it/src/it/ser-deser/src/test/java/io/fabric8/it/certmanager/TestSerialization.java
pom.xml

Follow up from #6301
Apply the formatter also to the tests.

[chore] Run spotless on the it/test folders

---

kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/GeneratorSettings.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaFlattener.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java
kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/SchemaUtilsTest.java

feat(openapi): configurable java type mappings to OpenAPI refs

---

kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/GeneratorSettings.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/GeneratorUtils.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/CrdParser.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java

feat(openapi): openapi generation from CRD definitions

---

kubernetes-model-generator/openapi/maven-plugin/pom.xml
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/CrdParser.java
kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/schema/CrdParserTest.java
kubernetes-model-generator/openapi/maven-plugin/src/test/resources/crd-parser/multiple-documents.yaml
kubernetes-model-generator/openapi/maven-plugin/src/test/resources/crd-parser/single-document.yaml
kubernetes-model-generator/openshift-model-autoscaling/pom.xml
kubernetes-model-generator/pom.xml

Fixes #6263 
Second attempt as follow-up of #6362 
Preserves names and type references

refactor: openshift-model-autoscaling generated from OpenAPI schemas

---

kubernetes-model-generator/openapi/generator/cmd/openapi.go
kubernetes-model-generator/openapi/generator/go.mod
kubernetes-model-generator/openapi/generator/go.sum
kubernetes-model-generator/openapi/generator/pkg/openshift/openshift.go
kubernetes-model-generator/openapi/generator/tools/generator/openapi.go

feat(openapi): add schemas for misc types

---

kubernetes-model-generator/pom.xml

refactor: remove unneeded OpenShift 4.17.0 OpenAPI schema file

---

.github/workflows/build.yml
.github/workflows/e2e-tests.yml
.github/workflows/javadocs.yml
.github/workflows/release-snapshots.yaml
.github/workflows/release.yaml
CHANGELOG.md
doc/MIGRATION-v7.md
httpclient-jdk/pom.xml
httpclient-jetty/pom.xml
httpclient-tests/pom.xml
junit/kube-api-test/pom.xml
kubernetes-model-generator/pom.xml
pom.xml

feat: move Java baseline from 8 (1.8) to 11

---

junit/mockwebserver/pom.xml
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/Buffer.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/ByteString.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/Dispatcher.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/Headers.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/HttpUrl.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/MediaType.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/MockResponse.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/QueueDispatcher.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/RecordedRequest.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/Response.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/WebSocket.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/WebSocketListener.java
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/BufferTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/ByteStringTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/HeadersTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/HttpUrlTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/MediaTypeTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/MockResponseTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/QueueDispatcherTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/RecordedRequestTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/WebSocketListenerTest.groovy

feat(mockwebserver): support and OkHttp compatibility classes for HTTP

---

junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/WebSocket.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/vertx/HttpServerRequestHandler.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/vertx/Protocol.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/vertx/ServerWebSocketHandler.java
junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/vertx/VertxMockWebSocket.java
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/vertx/ProtocolTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/vertx/VertxMockWebSocketTest.groovy
kubernetes-model-generator/openapi/maven-plugin/pom.xml
zjsonpatch/pom.xml

feat(mockwebserver): vert.x implementation bridge classes

---

junit/mockwebserver/src/main/java/io/fabric8/mockwebserver/http/MockResponse.java
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/http/MockResponseTest.groovy

refactor(mockwebserver): removed hardcoded values in MockResponse

---

junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerAnyMethodTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerCrudTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerTest.groovy
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/DefaultMockServerWebSocketTest.groovy

refactor(mockwebserver):test: use PollingConditions to make tests more reliable on Windows

---

CHANGELOG.md
doc/MIGRATION-v7.md
junit/mockwebserver/src/test/groovy/io/fabric8/mockwebserver/MockWebServerWebSocketTest.groovy

chore(mockwebserver): migration guide entry

---

.github/workflows/generate-model.yml

ci: remove go version from generate-model pipeline

---

kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen-processors.go
kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen.go

Istio/Protobuf specific handling

feat(openapi): add component extensions for interfaces and implementations

---

kubernetes-model-generator/openapi/generator/pkg/openapi/openapi-gen-processors.go
kubernetes-model-generator/openapi/generator/pkg/packages/packages.go
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/ModelGenerator.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/model/TemplateContext.java
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java
kubernetes-model-generator/openapi/maven-plugin/src/main/resources/templates/model.mustache
kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/SchemaUtilsTest.java

feat(openapi): initial support for interfaces in Maven Plugin

---

kubernetes-model-generator/openapi/maven-plugin/pom.xml
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/expected/IsEnvoyFilterEnvoyConfigObjectMatchObjectTypes.expected
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/expected/IsLoadBalancerSettingsLbPolicy.expected
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/expected/LoadBalancerSettings.expected
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/expected/LoadBalancerSettingsConsistentHash.expected
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/expected/LoadBalancerSettingsSimple.expected
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/expected/LoadBalancerSettingsSimpleLB.expected
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/invoker.properties
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/pom.xml
kubernetes-model-generator/openapi/maven-plugin/src/it/istio/verify.groovy
kubernetes-model-generator/openapi/maven-plugin/src/main/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtils.java
kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/model/ClassInformationTest.java
kubernetes-model-generator/openapi/maven-plugin/src/test/java/io/fabric8/kubernetes/schema/generator/schema/SchemaUtilsTest.java

test(openapi): comprehensive tests for openapi-model-generator-maven-plugin

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestHttpResponse.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/TestStandardHttpClientFactory.java
openshift-client/src/test/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptorTest.java

test: refactored OpenShiftOAuthInterceptorTest to not rely on mocks

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java

refactor: OpenIDConnectionUtils public static constants are now private

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java

refactor: removed Config.impersonateGroup

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigFromKubeconfigTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsBehaviorTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java
kubernetes-client-api/src/test/resources/config-from-kubeconfig/single-context-config.yaml
openshift-client/src/test/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptorTest.java

feat:refactor: added convenience Config.fromKubeconfig(File) method(s)

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/ConfigBuilder.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/SundrioConfig.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigConstructorTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java

refactor: removed deprecated constructors from Config

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsBehaviorTest.java

fix(config): removed setFile setter (internal)

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java

fix(config): removed setAutoConfigure setter (internal)

---

doc/MIGRATION-v7.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/ConfigListUsers.java
kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/ConfigViewEquivalent.java

refactor(config): changed getKubeconfigFilename to getKubeconfigFilenames (multiple file support)

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/ConfigBuilder.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/ConfigFluent.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/SundrioConfig.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigConstructorTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/SundrioConfigBuilderTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsBehaviorTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsTest.java
kubernetes-client-api/src/test/resources/internal/kube-config-utils-parse/config-1.yaml
openshift-client-api/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java

refactor(config): getFile inferred from Config.currentContext NamedContext

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/KubeConfigUtils.java
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigAutoConfigureTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsMergeTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/internal/KubeConfigUtilsTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtilsBehaviorTest.java
kubernetes-client-api/src/test/resources/config-auto-configure/scattered-cluster.yaml
kubernetes-client-api/src/test/resources/config-auto-configure/scattered-context.yaml
kubernetes-client-api/src/test/resources/config-auto-configure/scattered-user.yaml
kubernetes-client-api/src/test/resources/config-auto-configure/scattered.yaml

feat(config): support for scattered kubeconfig files

---

extensions/chaosmesh/pom.xml
extensions/open-cluster-management/pom.xml
extensions/pom.xml
pom.xml

refactor(openapi): remove jsonschema2pojo remaining unnecessary configs

---

kubernetes-model-generator/openapi/generator/go.mod

fix: dependabot issues with stolostron/multiclusterhub-operator

fix: dependabot issues with stolostron/multiclusterhub-operator

---

crd-generator/api/src/main/java/io/fabric8/crd/generator/CRDInfo.java

Remove depricated getVersion() method from CRDInfo
Fixes #6609
I tested changes by building the project
Also ran test for `crd-generator`

Remove depricated getVersion() method from CRDInfo

---

java-generator/cli/pom.xml

config(java-generator): remove unneeded version tag from pom.xml

config(java-generator): remove unneeded version tag from pom.xml

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/CustomResource.java

Fixes #6627 
Removed deprecated methods from CustomResource class

chore: Remove deprecated methods from CustomResource

---

CHANGELOG.md
kubernetes-model-generator/openapi/validator/pom.xml
kubernetes-model-generator/openapi/validator/src/main/java/io/fabric8/kubernetes/schema/validator/ValidationMessage.java
kubernetes-model-generator/openapi/validator/src/main/java/io/fabric8/kubernetes/schema/validator/ValidationReport.java
kubernetes-model-generator/openapi/validator/src/main/java/io/fabric8/kubernetes/schema/validator/Validator.java
kubernetes-model-generator/openapi/validator/src/test/java/io/fabric8/kubernetes/schema/validator/ValidatorTest.java
kubernetes-model-generator/openapi/validator/src/test/resources/custom-resource-not-in-schema.yml
kubernetes-model-generator/openapi/validator/src/test/resources/invalid-deployment-config.yml
kubernetes-model-generator/openapi/validator/src/test/resources/invalid-deployment.yml
kubernetes-model-generator/openapi/validator/src/test/resources/invalid-pod.yml
kubernetes-model-generator/openapi/validator/src/test/resources/valid-deployment-config.yml
kubernetes-model-generator/openapi/validator/src/test/resources/valid-deployment.yml
kubernetes-model-generator/openapi/validator/src/test/resources/valid-pod.yml
kubernetes-model-generator/pom.xml
pom.xml

fix(openapi): introduced io.fabric8:kubernetes-model-validator module to validate Kubernetes resources

---

README.md

Small PR - Commit 6ee1e5df44b12bd5271dce5574d76aa61936a9de moved the `OpenShiftClient.java` file. This PR adjusts sources to changes.

doc: update `OpenShiftExtensionAdapter.java` reference

---

kubernetes-model-generator/README.md

doc: model generation process readme

---

CHANGELOG.md
crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/AbstractCustomResourceHandler.java
crd-generator/api-v2/src/test/java/io/fabric8/crdv2/example/joke/JokeRequestSpec.java
crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/CRDGeneratorTest.java
crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractCustomResourceHandler.java
crd-generator/api/src/test/java/io/fabric8/crd/example/joke/JokeRequestSpec.java
crd-generator/api/src/test/java/io/fabric8/crd/generator/AbstractCustomResourceHandlerTest.java
crd-generator/api/src/test/java/io/fabric8/crd/generator/CRDGeneratorTest.java
crd-generator/test-apt/src/test/java/io/fabric8/crd/generator/zookeeper/ZookeeperCustomResourceTest.java
crd-generator/test-apt/src/test/java/io/fabric8/crd/generator/zookeeper/v1/ZookeeperStatus.java
generator-annotations/src/main/java/io/fabric8/crd/generator/annotation/AdditionalPrinterColumn.java
generator-annotations/src/main/java/io/fabric8/crd/generator/annotation/PrinterColumn.java
generator-annotations/src/main/java/io/fabric8/crd/generator/annotation/PrinterColumnFormat.java

feat(crd-generator): Change format in `@PrinterColumn` to enum

---

CHANGELOG.md
crd-generator/api/src/main/java/io/fabric8/crd/generator/CRDGenerator.java
crd-generator/apt/src/main/java/io/fabric8/crd/generator/apt/CustomResourceAnnotationProcessor.java
doc/CRD-generator.md
doc/MIGRATION-v7.md

refactor(crd-generator): deprecation of CRD Generator v1

---

kubernetes-model-generator/openapi/validator/src/main/java/io/fabric8/kubernetes/schema/validator/Validator.java

fix(openapi-validator): OpenAPI schema can be loaded from a jar

---

kubernetes-model-generator/openapi/generator/pkg/packages/packages.go

fix(openapi): include IntOrString in openshift-generated.json

---

kubernetes-model-generator/openapi/generator/pkg/packages/packages.go

fix(openapi): include Quantity in openshift-generated.json

---

doc/MIGRATION-v7.md

Add mention of v2 CRD generator API

---

CHANGELOG.md
pom.xml

Removes the integration tests, tests and examples from the BOM

chore(bom): Exclude tests and examples from BOM

---

java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java

test(java-generator): use assertJ assertions

---

doc/MIGRATION-v7.md

doc(migration): OpenShift Template objects type

---

crd-generator/apt/README.md
doc/CRD-generator.md
doc/MIGRATION-v7.md

Add migration notes for CRD Generator and create README for crd-generator-apt.

CRDGenerator annotation processor v7 migration notes

---

kubernetes-model-generator/openapi/generator/go.mod
kubernetes-model-generator/openapi/generator/go.sum

deps(generator): update overridden chaos-mesh dependency to latest fork branch

---

crd-generator/README.md
crd-generator/gradle/README.md
doc/CRD-generator.md

Add CRD-Generator usage description for gradle users
Example project can be found [here](https://github.com/baloo42/crd-generator-gradle-example)

chore(crd-generator): Add usage description for Gradle users

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpClientNewWebSocketBuilderTest.java

test: improve async reliability of AbstractHttpClientNewWebSocketBuilderTest

---

.github/workflows/build.yml
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractSimultaneousConnectionsTest.java

test: close exchange on AbstractSimultaneousConnectionsTest

---

kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpPostTest.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractHttpPutTest.java

test: improve http client failure test performance (disable retry)

---

httpclient-jdk/pom.xml
httpclient-jetty/pom.xml
httpclient-okhttp/pom.xml
httpclient-vertx/pom.xml
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/http/AbstractSimultaneousConnectionsTest.java
platforms/karaf/itests/pom.xml
pom.xml

test: improve reliability of concurrently run tests

---

doc/FAQ.md

Improve documentation of Server Side Apply

---

.github/workflows/e2e-chaos-tests.yml
.github/workflows/e2e-httpclient-tests.yml
.github/workflows/e2e-tests.yml

ci: bump kubernetes versions to latest v1.32.0

---

pom.xml

deps: bump gradle-api-maven-plugin from 0.0.5 to 0.0.7

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientBuilder.java
kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/KubernetesClientBuilderTest.java
kubernetes-client/src/test/java/io/fabric8/kubernetes/client/behavior/KubernetesClientBuilderTest.java

test: KubernetesClientBuilder withConfig tests

---

CHANGELOG.md
crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/CRDGenerator.java
crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/CRDPostProcessor.java
crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/CRDGeneratorTest.java

review(crd-generator): process generated CRDs before they are written out

---

CHANGELOG.md
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java
java-generator/core/src/main/java/io/fabric8/java/generator/nodes/Keywords.java
java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java
java-generator/it/src/it/ser-deser/src/test/java/io/fabric8/it/certmanager/TestSerialization.java
java-generator/it/src/it/ser-deser/src/test/resources/cert-manager.crds.1.7.1.yaml
java-generator/it/src/it/ser-deser/src/test/resources/sample9.yaml

[java-generator] boolean enum support

---

extensions/volcano/model/src/generated/java/io/fabric8/volcano/api/model/flow/v1alpha1/JobFlowStatus.java
kubernetes-model-generator/openapi/generator/go.mod
kubernetes-model-generator/openapi/generator/go.sum
kubernetes-model-generator/openapi/schemas/sh.volcano.json

chore(deps): bump volcano.sh/apis from 1.10.0 to 1.11.0

---

kubernetes-model-generator/openapi/generator/go.mod
kubernetes-model-generator/openapi/generator/go.sum
kubernetes-model-generator/openshift-model-config/src/generated/java/io/fabric8/openshift/api/model/config/v1/AWSPlatformStatus.java
kubernetes-model-generator/openshift-model-config/src/generated/java/io/fabric8/openshift/api/model/config/v1/NodeSpec.java
kubernetes-model-generator/openshift-model-config/src/generated/java/io/fabric8/openshift/api/model/config/v1/NutanixFailureDomain.java
kubernetes-model-generator/openshift-model-config/src/generated/java/io/fabric8/openshift/api/model/config/v1/Release.java
kubernetes-model-generator/openshift-model-console/src/generated/java/io/fabric8/openshift/api/model/console/v1/ConsolePluginCSP.java
kubernetes-model-generator/openshift-model-console/src/generated/java/io/fabric8/openshift/api/model/console/v1/ConsolePluginSpec.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/IngressControllerSpec.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/NodeStatus.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/OLM.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/OLMList.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/OLMSpec.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/OLMStatus.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/OpenStackLoadBalancerParameters.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/OperatorCondition.java
kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/ProviderLoadBalancerParameters.java

chore(deps): bump github.com/openshift/api from 20240930 to 20250305

---

kubernetes-model-generator/openapi/generator/go.mod
kubernetes-model-generator/openapi/generator/go.sum

chore(deps): bump github.com/chaos-mesh/chaos-mesh to latest master

---

kubernetes-model-generator/openapi/generator/go.mod
kubernetes-model-generator/openapi/generator/go.sum
kubernetes-model-generator/openshift-model-miscellaneous/src/generated/java/io/fabric8/openshift/api/model/miscellaneous/metal3/v1alpha1/BareMetalHostSpec.java
kubernetes-model-generator/openshift-model-miscellaneous/src/generated/java/io/fabric8/openshift/api/model/miscellaneous/metal3/v1alpha1/BareMetalHostStatus.java
kubernetes-model-generator/openshift-model-miscellaneous/src/generated/java/io/fabric8/openshift/api/model/miscellaneous/metal3/v1alpha1/ProvisionStatus.java
kubernetes-model-generator/openshift-model-miscellaneous/src/generated/java/io/fabric8/openshift/api/model/miscellaneous/metal3/v1alpha1/RAIDConfig.java

chore(deps): bump github.com/metal3-io/baremetal-operator/apis from v0.4.0 to v0.9.0

---

kubernetes-model-generator/openapi/generator/go.mod
kubernetes-model-generator/openapi/generator/go.sum

chore(deps): bump k8s.io/autoscaler/vertical-pod-autoscaler from v1.2.1 to v1.3.0

---

README.md

doc: update Kubernetes Mock Server documentation

---

pom.xml

fix: remove `com.squareup` entry from bom configuration

---

java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java
java-generator/core/src/test/java/io/fabric8/java/generator/CompilationTest.java
java-generator/core/src/test/resources/gateway.envoyproxy.io_backendtrafficpolicies.yaml

[java-generator] Suffix Double default values with d

---

kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Deletable.java

doc: improved documentation for Deletable.delete

---

CHANGELOG.md
kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/VersionInfo.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/MixedCrudTest.java
kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/VersionInfoTest.java

fix: getKubernetesVersion works in Kubernetes v1.33.0

---

.github/workflows/e2e-chaos-tests.yml
.github/workflows/e2e-httpclient-tests.yml
.github/workflows/e2e-tests.yml

ci: run tests in Kubernetes v1.33

---

CHANGELOG.md
crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/CRDGenerator.java
crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/CRDGeneratorTest.java

fix: avoid NPE if CRDPostProcessor is set to null

---

.github/workflows/release-snapshots.yaml
pom.xml

feat(ci): publish snapshots to Maven Central
Part of #7088

feat(ci): publish snapshots to Maven Central

---

chaos-tests/pom.xml
kubernetes-client-deps-compatibility-tests/pom.xml
kubernetes-itests/pom.xml

feat(ci): use central-portal snapshots repository in e2e

---

.github/workflows/build.yml

Increased number of files (threads) process limits

chore(ci): build pipelines can customize os

---

.gitattributes
.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

Update maven wrapper and scripts. Used `mvn wrapper:wrapper -Dmaven=3.9.9` command to regenerate the wrapper scripts.
Maven command not working as expected on windows and MacOS due to this bug: https://issues.apache.org/jira/browse/MWRAPPER-111

Update maven wrapper and scripts
